### ISSUE TITLE
[TBC] Karazhan Chess Event

### ISSUE THREAD

**Issue by BillytheOrc** [cmangos/issues#1650] opened 2018-07-14 13:26 UTC
**Current behavior**: 
When you talk to king, or
When use .aura 30019, the chess pieces run to you and don't move even when on chess squares.

**Expected behavior**: 
There should be a gossip option to take control of the initial king, then you should take control.
Even when forcing control, the king should not run to the player's location. Possible charm issue?

**Steps to reproduce**:

1. Speak to King. Nothing. .cast/.aura 30019 on the king to kickstart fight. 
2. Movement CD triggers, but no movement.

**Client version**: 
2.4.3 Build 8606
**Commit hash**: 
f1aad0db6555be21bbbe8d9a51937b94300fa729
**Database version**: 
Most recent as of 2018/07/14
**Operating system**: 
Win10

**Comment by BillytheOrc** [comment] 2018-07-28 09:54
https://www.bountysource.com/issues/60881261-karazhan-chess-event-tbc

I placed a 15 USD bounty on this.

**Comment by jimmybrancaccio** [comment] 2018-11-17 08:14
Closing as a duplicate of #827.

**Closed by jimmybrancaccio** 2018-11-17 08:14 UTC
Labels: Version-TBC
