### ISSUE TITLE
[CLASSIC][TBC][WOTLK] Core Bug with Logging Into an Already Logged in Account Causes Multiple Problems

### ISSUE THREAD

**Issue by Warlockbugs** [cmangos/issues#1177] opened 2016-11-30 15:06 UTC
**Current behavior**: 
a) Logging in into an already logged account doesn't remove character from world.
b) Logging in into an already logged account can roll back character if it wasn't automatically saved by a global interval.
**Expected behavior**: 
Disconnect is a disconnect and should save the character and remove from world.
**Steps to reproduce**:
This must be performed quickly within global character save interval.
1. Log in into an account.
2. Enter world with a character.
3. Change character state: teleport to another location, add some items, etc. 
4. Log in into the same account from another client instance and enter world with a different character.
5. First client instance is disconnected.
6. Teleport to first instance's character location.
7. Note that the character first instance was logged in with, remains standing online in the world, you can perform basic interaction with it: ask for duel, etc.
8. Log out and disconnect your second client instance.
9. Log in again and enter world with first character.
10. Character state is rolled back to state in step 2. None of items acquired are saved, etc.

**Client version**: 
2.4.3.8606
**Commit hash**: 
https://github.com/cmangos/mangos-tbc/commit/d8ebcfce73f1ab6d15b39f251006d14d5c75b53d
**Database version**: 
Latest.
**Operating system**: 
Server: Linux Mint 18 (host).
Client: Windows 10 (virtual guest).

[//]: # (If this is a crash report, include the crashlog from a debug build with https://gist.github.com/)

**Comment by ulfgebhardt** [comment] 2016-12-09 14:59
Rollback also happens when disconnected on latest mangos-tbc.

**Comment by Rapth** [comment] 2017-01-19 08:18
is that problem solved?

**Comment by ulfgebhardt** [comment] 2017-01-23 13:23
Problem is not solves.

Steps to reproduce:

1. Log Character
2. Kill Mob & Loot item from corpse
3. Login second account
4. (Sometimes both Clients get disconnected - reconnect)
5. Item Lost

**Comment by ulfgebhardt** [comment] 2017-02-18 15:20
I have digged into that Problem a bit more and can now tell a save way to detect and reproduce the problem. I have no solution yet tho.

**Steps to reproduce**

1. Log Character
2. a. Log the same Account again
2. b. Disconnect by removing your Network Connection
2. c. Kill the Client with the Taskmanager(Alt+F4 is not sufficient)

**Resulting Behaviour**

- Character Table contains online=1 for Character in question
- Logging the Character again and logging out results in a temporary online=0 in the Database, till the next Worldsave Cycle, then the Character is back to online=1 in the Database.
- This causes Dataloss(position, items, etc..) on the Character.
- The Problem can be solved only by restarting the Server for the affected Characters.

**What causes this?**
Here you can find all instances of LogoutPlayer
https://github.com/cmangos/mangos-tbc/search?utf8=%E2%9C%93&q=LogoutPlayer&type=Code

It seems like this function is not executed correctly when losing the Connection unexpected.

https://github.com/cmangos/mangos-tbc/blob/13079fec97e64a73cc6cb2a62f3861901daae958/src/game/WorldSession.cpp#L293
```
// check if we are safe to proceed with logout
    // logout procedure should happen only in World::UpdateSessions() method!!!
    if (updater.ProcessLogout())
    {
        ///- If necessary, log the player out
        const time_t currTime = time(nullptr);

        if (m_Socket->IsClosed() || (ShouldLogOut(currTime) && !m_playerLoading))
            LogoutPlayer(true);

        // finalize the session if disconnected.
        if (m_Socket->IsClosed())
            return false;
    }

    return true;
```
Here it is Possible that "updater.ProcessLogout()" returns false and causes the Problem.
Or m_Socket->IsClosed() does not return the correct value.

https://github.com/cmangos/mangos-tbc/blob/13079fec97e64a73cc6cb2a62f3861901daae958/src/game/WorldSession.cpp#L95

```
/// WorldSession destructor
WorldSession::~WorldSession()
{
    ///- unload player if not unloaded
    if (_player)
        LogoutPlayer(true);

    // marks this session as finalized in the socket which references (BUT DOES NOT OWN) it.
    // this lets the socket handling code know that the socket can be safely deleted
    m_Socket->FinalizeSession();
}
```

If the Session is not terminated correctly it fails to call LogoutPlayer

Hope this helps ;-) im Quite eager to solve this Problem since its major.

**Comment by kotishe** [comment] 2017-03-05 15:58
Fix don't work.

**Comment by SilvioDoMine** [comment] 2017-05-13 07:26
Nothing about?

**Comment by SilvioDoMine** [comment] 2017-05-15 21:07
@ulfgebhardt any commit related to fix this?

**Comment by zmmmspy** [comment] 2017-05-19 06:59
None.

**Comment by ulfgebhardt** [comment] 2017-05-21 14:10
Soory, i have not looked into this any further, my commit seems not to work - even tho it seemed to work when i tested it.
The problem remains and still is major ;-)

**Comment by Razfury** [comment] 2017-06-25 22:11
I've 2 lines to my WorldSession::KickPlayer() and it I don't seem to be having any issues so far now, can anyone else confirm, I'm 100% sure this is a hack but it works for right now until the devs figure it out.

void WorldSession::KickPlayer()
{
	_player->SaveToDB(); // Save character information
	_player->SaveInventoryAndGoldToDB(); // Save Inventory & gold
    if (m_Socket && !m_Socket->IsClosed())
        m_Socket->Close();
}

**Comment by KwazarFr** [comment] 2017-07-04 16:26
The problem remains and still is major ;-)

**Comment by KwazarFr** [comment] 2017-08-26 22:51
Still not fixed?  there is a PR concerning this major bug ?

thx

**Comment by ulfgebhardt** [comment] 2017-08-26 22:56
The PR worked only for a short period of time - your best bet is to try what @Razfury suggested.
I'm not up to date with this project - can you confirm that it is still a problem/is fixed?

Grüße Ulf
<3

**Comment by SilvioDoMine** [comment] 2017-08-27 01:55
@kamenblackrx

**Comment by Ve1vet** [comment] 2017-11-14 04:48
@namreeb this bug related to your work with world sessioin & socket. Somwhere you did mistake & session doesn't close properly.

**Comment by namreeb** [comment] 2017-11-14 18:38
@Ve1vet I've been putting off thinking about this because it is a smaller part of a larger question, which is whether there would be any down-side to removing the implementation of Nagle's algorithm buffering within the socket code.  I will try and answer that question sooner rather than later.

**Comment by rmzV** [comment] 2018-01-05 21:15
hmm.. probably related to 
https://github.com/cmangos/wotlk-db/issues/182
i thought it was after "backport from tbc issue".. but probably quest log was corrupted

**Comment by keyshuwen** [comment] 2018-02-12 13:54
I thought it was the only thing I met. It turned out that everyone had met.  :(
Double client login is the same player data exception. The problem can only be solved by restarting the Core.

**Comment by ulfgebhardt** [comment] 2018-02-12 20:57
This is an intentional bug. Don't expect it to be fixed soon.

**Comment by keyshuwen** [comment] 2018-02-13 01:23
Is there a temporary solution? Thanks.

**Comment by Thema89** [comment] 2018-03-20 16:20
Actually, there's a cleaner "one-line way" to definitely handle this problem. Based upon my tests, this is simply related to a memleak inside _World::AddSession\_(WorldSession* s)_. We should destroy session's pointer when client disconnects but, don't ask me why, that delete has been removed from CMaNGOS somewhen, (maybe as a quick hackfix for a minor problem?) Every other project based upon original MaNGOS code simply handle session pointers that way without problems. I've tested this solution, and it flawlessly resolves every bug here reported. Still, there's still a problem related to @namreeb's work, (#1319 as maybe the most critical problem) but that's not related to this one as some of us thought.
I'll open a pull request for this if you want this bug handled this way.

**Comment by killerwife** [comment] 2018-03-20 16:21
@Thema89 ask @namreeb how to solve the issue, and resolve it based on his liking. The bug needs to be resolved once and for all, and afaik he mentioned removing nagles algo impl in cmangos.

**Comment by SilvioDoMine** [comment] 2018-03-21 06:20
@Thema89 could you please send me this hackfix to this, so I can continue using the cMangos meanwhile?

**Comment by SilvioDoMine** [comment] 2018-03-21 06:20
`Actually, there's a cleaner "one-line way" to definitely handle this problem. Based upon my tests, this is simply related to a memleak inside World::AddSession_(WorldSession* s). We should destroy session's pointer when client disconnects but, don't ask me why, that delete has been removed from CMaNGOS somewhen, (maybe as a quick hackfix for a minor problem?) Every other project based upon original MaNGOS code simply handle session pointers that way without problems. I've tested this solution, and it flawlessly resolves every bug here reported. Still, there's still a problem related to @namreeb's work, (#1319 as maybe the most critical problem) but that's not related to this one as some of us thought.
I'll open a pull request for this if you want this bug handled this way.`

@Thema89 could you please send me this hackfix to this, so I can continue using the cMangos meanwhile?

**Comment by Thema89** [comment] 2018-03-21 20:46
@SilvioDoMine actually it isn't an hackfix, it's the good way to go, but it will not prevent CMaNGOS to suffer for #1359 even worse. I've opened a pull request here: https://github.com/cmangos/mangos-tbc/pull/225.
It completely resolves this bug and #1347 aswell, but expect #1359 to occur when that multiple connection attempts are made by a client which loose its connection unexpectedly (e.g. by turning wi-fi off and on again or unplugging the eth cable while logged in): so no more duplicates, but socket-related problems and crashes will remain, and you'll notice that even more until fixed.

**Comment by jimmybrancaccio** [comment] 2018-11-19 23:12
I've gotten word in our Discord chat this issue is resolved. Would you be able to speak to that @cyberium or @killerwife? Much appreciated on your input.

> Levi, The Snek [𓆙]Today at 5:04 PM
> 1177 was fixed by Defrag a long time ago, already.(edited)
> SilvioToday at 5:04 PM
> Yes
> I worked on 1359
> astuffedtigerToday at 5:05 PM
> Hrmm, 1177 still not closed.
> SilvioToday at 5:05 PM
> Should be, is not an issue for ages

**Comment by Fix1234** [comment] 2019-04-14 22:57
Hello guys,
Here is a fix for this issue. Tested on WOTLK for about 4 months.

Add after this line:
https://github.com/cmangos/mangos-tbc/blob/13079fec97e64a73cc6cb2a62f3861901daae958/src/game/World.cpp#L212
`WorldSessionFilter updater(old->second);`
`// if WorldSession::Update fails, the session is no longer used. We need to delete it.`
`if (!old->second->Update(updater))`
`{`
`                              m_sessions.erase(old);`
`                              WorldSession* pSessionm = old->second;`
`                              delete pSessionm;`
`}`

**Comment by Yatzii93** [comment] 2019-04-17 02:09
old is undeclared. Wheres the variable getting it's data?

**Comment by Ve1vet** [comment] 2019-04-17 02:15
@Yatzii93 parhaps he made mistake in line number.
**old** is declared in local scope at line 203. As i can see from code. So this code should start at line 211 as i understand. Before local scope is closed.

**Comment by Yatzii93** [comment] 2019-04-20 06:46
Well it's a quick way to crash the core if so :P

**Comment by BenDol** [comment] 2019-05-31 01:27
Is this resolved with https://github.com/cmangos/issues/issues/1359 ? If not what are the differences seen here?

**Comment by jimmybrancaccio** [comment] 2019-06-08 23:47
Assigning to @cyberium for feedback on whether or not this is resolved. If anyone else can confirm this is resolved please let me know!

**Comment by cyberium** [comment] 2019-06-13 09:36
On my side we can close this. No matter what i do i can't reproduce any crash on my setup. But idea was to let it open to be sure no one else (with an updated core) can experience it.
So let say keep it open one more month if no more feedback.

**Comment by jimmybrancaccio** [comment] 2019-06-13 15:06
Sounds good, thanks @cyberium!

**Comment by al3xc1985** [comment] 2020-02-25 11:30
@killerwife this should be closed

**Closed** 2020-02-25 11:34 UTC
Labels: Info: Needs Feedback, System: Miscellaneous, Version: Classic, Version: TBC, Version: WotLK
