### ISSUE TITLE
Touch of Zanzil

### ISSUE THREAD

**Issue by TheTrueAnimal** [cmangos/issues#491] opened 2014-11-02 09:51 UTC
Touch of Zanzil can be removed by getting in stealth. 
http://www.wowhead.com/spell=9991

Content Version: Classic DB version 1.4.1 'Toward the Fiery Heart'. For CMaNGOS z2525 and Scriptdev2 z2703 (update 0786_quest_template applied to mangos db)
Creature AI: ACID 1.12.x (Classic) for CMaNGOS-CLASSIC (1.12.X Client)

**Comment by brotalnia** [comment] 2017-06-18 00:34
I don't know if this has been already fixed, but the problem is that the spell has the wrong effect.

Here's a fix from Elysium - https://github.com/elysium-project/server/pull/363/files

Since you don't have the `spell_effect_mod` table to allow editing spell effects in the database, you'd have to do it in the core when loading the spell. Here's what has to be changed to make the spell function as described on the tooltip.

Change these for Effect 1:
EffectImplicitTargetA = TARGET_SELF (1)
EffectApplyAuraName = SPELL_AURA_DISPEL_IMMUNITY (41)
EffectMiscValue = DISPEL_STEALTH (5)

With the default effect from the DBC files, the buff is considered as stealth, and it is removed when you take damage or interact with something.

**Comment by killerwife** [comment] 2017-06-18 05:36
That's a horrible hack. Adding effect alters the amount of packets that are sent to client. All that this spell needs to apply is AURASTATE_FAERIE_FIRE which prevents stealth from being used.

Also, we do allow editing of everything in the database. Look in spell_template table. You do no need additional tables if you have one where you can edit everything.

**Comment by brotalnia** [comment] 2017-06-18 06:09
It's not adding an additional effect, it's replacing the existing one. This is how Fearie Fire prevents stealth actually. I looked at the Faerie Fire spell to see if the effect was different there, since it successfully prevents stealth, and compared it to Touch of Zanzil. I then replaced the Effect1 of the Touch of Zanzil spell with that of Faerie Fire and that made it function as you would expect from reading the tooltip of the spell.

If you were to leave the original Effect1 of Touch of Zanzil, you'd have to do more hacks in the core to prevent it from being removed when taking damage, attacking, using objects, looting, etc. The default effect is Apply Aura #16: Mod Stealth so everything that breaks stealth removes the debuff.

**Comment by killerwife** [comment] 2017-06-18 06:16
What are you basing this on? The spell has different effect/tooltip from TBC on. I would be inclined to say that it has wrong effect, but only if the one number was wrong. (like in case of one wotlk spell where I actually edited effect ID) In this case the effect has the effect values validly filled out for stealth aura, which means it is not a simple mistake when exporting DBC to client. I suggest you find a vanilla video to seek out the true meaning of Touch of Zanzil during Vanilla to verify what is going on. IF you find a video that shows that the player doesnt look like stealthing, I will be inclined to seek out a solution for this. (and make sure that video isnt from elysium, feenix or whatnot)

I know this might be almost impossible, but altering Effects of a spell is the biggest bad thing causing malfunctions to the client. It expects spelllog of a specific structure, and if it gets a different from what it expects, it can do literally anything. The effects I swapped in Wotlk were both auras and as such the packet sent is 100% the same.

**Comment by brotalnia** [comment] 2017-06-18 06:37
Hmm, seems like it is really supposed to be different in vanilla. Older comments on wowhead are saying it does not prevent stealth. I didn't realize that.

> While i had this debuff, i could stealth. But mobs detected me from very far away, so only cheap shot was possible to use as stealth opener

> This make your agility 15x lover and reduce stealth level for 50 (like if you were 10 levers lover then you are).

I guess then you have to change how the effect is handled. It actually has a negative value (-50) whereas normal stealth spells have a positive one.

**Comment by killerwife** [comment] 2017-06-18 06:41
Plot thickens, which means the following: It should stack with stealth, but it should completely neutralize "stealth level" due to the -50 value. Ok, @WarlockBugs see what I am writing?

**Comment by Warlockbugs** [comment] 2017-06-18 12:34
Yes, i see exactly what needs to be done. I already prospected dispel type relation to stacking mechanism for other auras (namely stats), this fits into this category as well. However, this should be incorporated into the new future aura system in a more clever way, because existing solution keeps growing like cancer with very similar, but slightly different code for many auras.
The change required to fix it properly noted, but current aura stacking system for classic and TBC despite being a relatively new one, still is kind of a practical research material and scheduled to be replaced with a better solution ASAP for all cores at once after research is complete. I'll see if there is enough worthy material to update it in CMaNGOS one more time before i start working on a new one.

**Comment by Warlockbugs** [comment] 2017-06-18 13:21
I've checked and its already no longer removed by getting into stealth within current system. However, there is a different problem with stealth, unrelated to stacking. Ots the lack of proper AuraInterruptFlags handling for stealth. We remove all stealth auras on attack and other actions instead of abiding AIF.

**Comment by AnonXS** [comment] 2018-03-14 13:29
thats why stealth is not removed when the unit gets sapped by player.
dk what happens in player case currently.

**Comment by AnonXS** [comment] 2019-01-28 16:33
![unbenannt](https://user-images.githubusercontent.com/19734826/51850800-cf94b380-2322-11e9-9587-a56685af4937.PNG)

**Closed by AnonXS** 2019-01-28 16:33 UTC
Labels: System: Spells, Version: Classic
