### ISSUE TITLE
If you use the spell crash 1.12.1

### ISSUE THREAD

**Issue by DescCore** [cmangos/issues#1085] opened 2016-09-16 14:48 UTC
If you use the spell taming pet hunter crash occurs
Testing 10 minutes ago, Hunter orc

**Comment by mangostaters** [comment] 2016-09-16 17:16
Unable to reproduce as a level 60 orc hunter (GM command to attain the level) taming a Dire Mottled Boar south of Razor Hill. Also unable to reproduce as a Nelf hunter on a Webwood Venomfang in Teldrassil; however, I was unable to tame the Venomfang (a spider) at all. 

Assuming the GM commands wouldn't override whatever is making it crash, you may want to make sure your databases are in order and up-to-date.

**Comment by Phatcat** [comment] 2016-09-18 12:07
Unable to reproduce, I am able to tame just fine without any explosions, also you seem to be able to as well you would not even get to this stage; https://github.com/cmangos/issues/issues/1086 - closing this for now.

**Closed by Phatcat** 2016-09-18 12:07 UTC
