### ISSUE TITLE
Scorched Debuff Stops Applying to Target

### ISSUE THREAD

**Issue by yatzi888** [cmangos/issues#1832] opened 2019-01-13 17:12 UTC
**Current behavior**:  Using the talent Improved Scorch as a Fire mage [https://vanilla-twinhead.twinstar.cz/?spell=11095] a player is able to put a 5 stack debuff on a target to increase it's fire damage taken. Currently that debuff stops applying when the player iceblocks, and other random events which are hard to replicate.

(video showing the bug - https://youtu.be/EpybIJWPFwk?t=23)

**Expected behavior**: Scorch should apply debuff at all times [https://tbc-twinhead.twinstar.cz/?spell=22959]

**Steps to reproduce**:

1. Roll mage, talent in Improved Scorch [https://vanilla-twinhead.twinstar.cz/?spell=11095]
2. Use iceblock
3. Use Scorch [https://tbc-twinhead.twinstar.cz/?spell=27074] and observe the debuff not appearing on target

Relogging fixes the problem temporarily.

Client version: 2.4.3

Commit hash: c559b36d4e99345002f59987161bb87591bc30d4

Database version: 8de43372a43d824a3f9e5688d1f6609ab71cb775

Operating system: Windows Server 2012 R2

[//]: # (If this is a crash report, include the crashlog from a debug build with https://gist.github.com/)

**Comment by yatzi888** [comment] 2019-01-13 17:31
https://imgur.com/sCuC2m0 - when its working 
Noting appears when it doesnt.

**Comment by killerwife** [comment] 2019-01-13 17:34
I have seen this bug before, and I thought it was eliminated. I inspected code on death and currently that should not be possible, but I am used to being proven wrong. I will try to look into this soon, because its definitely in my area of expertise.

**Comment by yatzi888** [comment] 2019-01-13 17:38
If it helps in anyway it seems to be recent, it was brought up when I jump from a mid December core where the pet trainer was working then the latest once it was resolved. I can't confirm anything but there was no word until I did the update and now its spotted a fair bit.

**Comment by yatzi888** [comment] 2019-01-13 17:43
I'll do some core rollbacks in the test envirument when I'm a bit more free, maybe I can pinpoint a rought time on commits to where the bug appeared.

**Comment by yatzi888** [comment] 2019-01-13 18:33
Been testing older cores and I've narrowed it down to a change between the 28/12/2018 and the 9th of Jan. Don't have the exact core date right now. But coming up recently to the first iteration of the pet trainer fix caused it to appear my end.

**Comment by killerwife** [comment] 2019-01-13 19:06
Reproduced. Will be fixed.

**Comment by MagPurify** [comment] 2019-01-25 15:57
This issue looks a regression from recent commits, because it was working around 1 month ago.

**Comment by killerwife** [comment] 2019-01-25 16:01
Confirm fix. https://github.com/cmangos/mangos-tbc/commit/7dce71e65c909690c254563f2d023f1cb98fe3a3

**Comment by yatzi888** [comment] 2019-01-27 04:18
Comfirmed fixed

**Commit hash**: 4589c7b22866e86bfd29eb0ecd3c85aff45d42d1
**Database version**: c3ac98f8838b4318c3819485e3bae40f8e645052

**Closed** 2019-01-27 04:19 UTC
Labels: System: Spells, Version: TBC
