### ISSUE TITLE
 the server goes down

### ISSUE THREAD

**Issue by k4s1pro** [cmangos/issues#2314] opened 2020-11-15 17:00 UTC
when fighting Shirrak the Dead the server crashes

![crashserver](https://user-images.githubusercontent.com/74503380/99191325-5ae76f00-276c-11eb-939a-c381cc64ba03.jpg)

**Comment by jimmybrancaccio** [comment] 2020-11-16 00:52
This is a duplicate of #2192. @k4s1pro In the future please search through issues before creating your own as well as utilize the bug reporting template. Closing this.

**Closed by jimmybrancaccio** 2020-11-16 00:52 UTC
Labels: Version: TBC
