### ISSUE TITLE
Bug in the WoW API

### ISSUE THREAD

**Issue by Muehe** [cmangos/issues#1244] opened 2017-01-18 16:02 UTC
**Current behavior**: 
When you loot the **first quest item** the quest progress isn't shown in the following [QUEST_LOG_UPDATE](http://wowprogramming.com/docs/events/QUEST_LOG_UPDATE). It is for kill quests and all other quest items though. Also the [UNIT_QUEST_LOG_CHANGED](http://wowprogramming.com/docs/events/UNIT_QUEST_LOG_CHANGED) event only triggers on kill quests.

**Expected behavior**: 
Receive a [QUEST_WATCH_UPDATE](http://wowprogramming.com/docs/events/QUEST_WATCH_UPDATE) (<- this is working) and have updated quest information in the following QUEST_LOG_UPDATE event. Also receive an UNIT_QUEST_LOG_CHANGED event (with updated data I think, but not sure).

**Steps to reproduce**:

1. Monitor the three events and their payload using an addon.
2. Monitor the quest status in the event handling function.
3. Acquire a quest which needs items to be completed.
4. Collect the first item. There is no UNIT_QUEST_LOG_CHANGED event and during the QUEST_LOG_UPDATE the quest log still shows 0/X items.
5. Collect the second item. Still no UNIT_QUEST_LOG_CHANGED event but the QUEST_WATCH_UPDATE shows 1/X items and the QUEST_LOG_UPDATE shows 2/X items.

**Client version**: 
**Commit hash**: 
**Database version**: 
Current classic.

**Operating system**: 
Xubuntu 16.04

**Screenshot**:
(ignore the WORLD_MAP_UPDATE, used them to separate kills)
![screenshot_events](https://cloud.githubusercontent.com/assets/8838573/22071517/aff10652-dd9f-11e6-80b4-108e1897fb6f.jpg)

**Comment by ulfgebhardt** [comment] 2017-01-23 13:57
Is this a Client or Server Issue?

**Comment by Warlockbugs** [comment] 2017-01-23 14:01
Almost guaranteed it's server issue. I'll take a look at this sometime later.

**Comment by Muehe** [comment] 2017-01-23 18:18
Think it's a server issue as well, that's why I posted here. I also tried to investigate but due to lack of C++ and mangos knowledge I got stuck at investigating how opcodes are sent in the WorldSession.cpp.

I think this function in Player.cpp is involved in the bug: [void Player::ItemAddedQuestCheck(uint32 entry, uint32 count)](https://github.com/cmangos/mangos-classic/blob/master/src/game/Player.cpp#L12531). It calls [void Player::SendQuestUpdateAddItem(Quest const* pQuest, uint32 item_idx, uint32 count) const](https://github.com/cmangos/mangos-classic/blob/master/src/game/Player.cpp#L13024) in the same file. The functions handling kill objectives are next to these two (for comparison, like I said they send a `UNIT_QUEST_LOG_CHANGED` event).

**Comment by Warlockbugs** [comment] 2017-02-28 07:19
An unrelated client-side bug in vanilla client was found during investigation:
![Screenshot](https://i.imgur.com/z4Ql9Es.jpg?1)
Quest watcher does not save tracked quests during UI reloading procedure. After each UI reload, it adds another duplicate entry on first quest progress update to the list, until the list is full (up to a 5 reloads/duplicates). This issue was fixed in newer versions.
This can only be fixed via an addon. Since the issue is quite specific, a client-side workaround will be provided only on demand.

**Comment by Warlockbugs** [comment] 2017-02-28 15:46
Should be fixed in:
https://github.com/cmangos/mangos-classic/commit/360c3865080c696cfeb51cb0e62d80df4d9b20dd
https://github.com/cmangos/mangos-tbc/commit/d13617ed1bfa680a5396956cb65c07e1191998e4
https://github.com/cmangos/mangos-wotlk/commit/ff3b2cff6fda4e7e9fddbb5fc8366011dffe129f

**Closed by Warlockbugs** 2017-02-28 15:46 UTC
Labels: Version-Classic, Version-TBC, Version-WotLK
