### ISSUE TITLE
Classic: Warrior Rage mechanics

### ISSUE THREAD

**Issue by Kelzior** [cmangos/issues#607] opened 2015-02-12 18:11 UTC
Core: Lastest

Warrior should lose all his rage bar on stance change.
You can reduce the penalty up to saving 25 rage on stance change with a talent.
 
so warriors do not lose any rage on stance dance and can freely switch in between them...

**Comment by TheTrueAnimal** [comment] 2015-02-19 19:26
On classic the bug seems to be fixed. Without the talent you loose all your rage when changing stances.

**Comment by krullgor** [comment] 2015-03-18 14:48
Rage loss seems working as intended in core version 2644, so i'm closing this issue.

**Closed by krullgor** 2015-03-18 14:48 UTC
