### ISSUE TITLE
[CLASSIC] CC's in PvP Last Too Long

### ISSUE THREAD

**Issue by dazidkk** [cmangos/issues#1013] opened 2016-07-30 18:05 UTC
CC's in pvp last too long. 
Spells such as sap,polymorph,enta roots, freezeing traps have their full pve duration against other players.

The hamstring limit duration code for PvP in SpellMgr.cpp seems to be broken aswell,
not resulting in the desired 10secs.

**Comment by Phatcat** [comment] 2016-07-30 20:39
Not only that, but mostly all CC's suffer from diminishing returns in pvp as well, no?

**Comment by dazidkk** [comment] 2016-07-30 21:15
Diminishing returns seems to work fine in pvp, by reducing the duration of the second cast by 50%. Only problem is the first duration being like 50sec's.

**Comment by Phatcat** [comment] 2016-07-30 21:23
Well, unless we are going to have to hardcore in exceptions then a scalar (or several, depending if penality varies with cc effect) has to be found.

**Comment by Phatcat** [comment] 2016-07-30 21:28
Also, does the diminishing returns work properly?

Do they reduce duration by 50% off of PvE duration? because that might not be correct considering PvP durations are different and that diminishing returns should probably scale off of that, and not the PvE duration.

**Comment by dazidkk** [comment] 2016-07-30 22:08
Yeah thats true atm, they diminsh at 50% of the PvE time. I cant seem to find the code regarding how it scales the diminish being a set value or a set %.

The supposed to duration for cc's in pvp should be 10sec, Then 50% second cast then 75% third cast with a window of 18sec to reset.

**Comment by Phatcat** [comment] 2016-07-30 22:14
So that's just a hardcoded 10 seconds for all cc's in pvp (not considering DR)?
Do we have any sources on that?

**Comment by Phatcat** [comment] 2016-07-30 22:15
Also, does that also go for pets using cc's, and cc's used on player's pets? do they also suffer from diminishing returns?

**Comment by dazidkk** [comment] 2016-07-30 22:27
http://vanilla-wow.wikia.com/wiki/Sap
http://vanilla-wow.wikia.com/wiki/Polymorph
http://vanilla-wow.wikia.com/wiki/Freezing_Trap
http://vanilla-wow.wikia.com/wiki/Fear
http://vanilla-wow.wikia.com/wiki/Entangling_Roots

Seems like charm effects are 15sec in pvp tho, such as seduction i would assume
http://vanilla-wow.wikia.com/wiki/Charm

And when i said 18sec before it was wrong, seems to be 15sec in the earlier patches.
http://vanilla-wow.wikia.com/wiki/Patch_1.4.0

Im not sure regarding cc on pets since i cant find a source on it.

**Comment by Phatcat** [comment] 2016-09-09 01:03
@Warlockbugs Hey man, if your work in any way also touches on the durations of cc's then this issue may be worth noting. 

Now I've tagged you at least since this seems to be just your sort of thing =)

**Comment by Warlockbugs** [comment] 2016-09-09 01:14
I did not touch diminishing returns in any way yet.

**Comment by Lillecarl** [comment] 2016-11-28 18:16
The duration should be determined by Heartbeat resist, @Laizerox knows some about this.

**Comment by AnonXS** [comment] 2019-01-30 11:52
Not sure about classic diminishing returns system, but i guess this is resolved?

**Comment by Lillecarl** [comment] 2019-01-31 04:02
This is not solved at all, there's no work done to implement this properly yet. And it seems no one knows how it should work either.

**Comment by killerwife** [comment] 2019-01-31 08:02
Diminishing returns support in core is there. The problem is that 1. someone has to review all groups and tweak them and 2. after that figure out the issues that are unsolvable atm. Its not a hard job, I did it for TBC. (but even those are not perfect)

**Comment by Ve1vet** [comment] 2019-01-31 11:51
1. https://wowwiki.fandom.com/wiki/Diminishing_returns?oldid=491006 this is for vanilla. As i remember( not shure for 100% ), the groups of DR was introduced only in TBC.
2. http://vanilla-wow.wikia.com links show wrong inormation absolutely for DR or shure.
3. Max PvP duration for CC spells in classic was 15 seconds. In TBC was down to 8 seconds & added DR groups.
4. The thing that wasn't work erlier, maybe fixed now. DR timer was updated on spell hit, not at that point when CC spell removed from the target. 
So for example, when you cast polymorph 3rd time on the same target, it start duration of DR for 15( at this point immune to this spell/group ). The target will be in poly for 2 seconds & then you can cast poly on this target again after 13 seconds aftar poly removed from the target. Should be 15.
5. In case you need info for TBC: https://wowwiki.fandom.com/wiki/Diminishing_returns?oldid=1663771. There should be Disarm also( from 2.3.0 ).

**Comment by Lillecarl** [comment] 2019-02-01 11:34
@ve1vet https://github.com/cmangos/mangos-wotlk/pull/159

This is what made CCs break in reasonable times in vanilla mate, they had the 50+ seconds on the timer, but never lasted the full duration. This is a critical PR that'd be great if someone (@warlockbugs loves the spell system) to check it out 😁

**Comment by Tobschinski** [comment] 2019-02-01 15:10
No DR categories in vanilla? That must be incorrect, the patch notes are filled with information about it. (1.9 being the most interesting here)

**Comment by Lillecarl** [comment] 2019-02-02 00:51
@Ve1vet My information here is that the game won't be built on the 1.12.1 server nor the 1.12.1 client, they'll be using the new client with all new cool gfx and such. It'll be a mix between what's today and what was back in the days so to speak. We'll see if all spells and talents behave as they did in 1.12.1 👍

**Comment by AnonXS** [comment] 2022-04-13 23:08
The Initial Claim that CC spells in Classic also had limited duration of max 10secs has been debunked.

<https://youtu.be/5BH5pbxPb34?t=71>

Patch 2.2.0 introduced DIMINISHING_LIMITONLY (10secs rule for all? spells)

https://wowwiki-archive.fandom.com/wiki/Patch_2.2.0

```
[Hibernate](https://wowwiki-archive.fandom.com/wiki/Hibernate) and Entangling Roots duration against PvP targets has been reduced to 10 seconds.
[Freezing Trap](https://wowwiki-archive.fandom.com/wiki/Freezing_Trap) and [Scare Beast](https://wowwiki-archive.fandom.com/wiki/Scare_Beast) duration against PvP targets has been reduced to 10 seconds.
[Polymorph](https://wowwiki-archive.fandom.com/wiki/Polymorph) duration against PvP targets has been reduced to 10 seconds.
[Mind Control](https://wowwiki-archive.fandom.com/wiki/Mind_Control) duration against PvP targets has been reduced to 10 seconds.
[Sap](https://wowwiki-archive.fandom.com/wiki/Sap) duration against PvP targets has been reduced to 10 seconds.
[Banish](https://wowwiki-archive.fandom.com/wiki/Banish), [Seduction](https://wowwiki-archive.fandom.com/wiki/Seduction), [Enslave Demon](https://wowwiki-archive.fandom.com/wiki/Enslave_Demon) and [Fear](https://wowwiki-archive.fandom.com/wiki/Fear) duration against PvP targets has been reduced to 10 seconds.
```

**Closed by AnonXS** 2022-04-13 23:08 UTC
Labels: System: Spells, Version: Classic (1.12), Info: Needs Replication

**Comment by Nytanath** [comment] 2022-04-14 09:22
Maybe only marginally related, but I believe that the heartbeat resist chance seems too low compared to retail. When I was testing Mind Control on retail it broke very often (level 70 player vs level 60-63 creatures), so much that I never really managed to have it last for the full minute of duration. Usually the break happens sometime after the 20-second mark.

I guess that the more the CC is active, the higher chance it has to break, but I don't have enough data to be sure.
