### ISSUE TITLE
Players Under Immunity Effects Like Ice Block or Divine Shield are not Targeted by Mass Dispel

### ISSUE THREAD

**Issue by MagPurify** [cmangos/issues#1855] opened 2019-01-28 12:30 UTC
**Current behavior**: 
Mass Dispel is not removing undispellable Magic effects such as  [Ice Block] and  [Divine Shield].
**Expected behavior**: 
Mass Dispel is able to remove normally undispellable Magic effects such as  [Ice Block] and  [Divine Shield].

Tested on Duel, Arena and against enemy faction.

**Steps to reproduce**:

1. .learn 32375 on Character A
2. .learn 36911 , learn 1020 on Character B
3. Fight, make Character B immune using either spell, Character A uses mass dispel.

**Client version**: 
2.4.3 
**Commit hash**: 
d54c4e869f6e638deb9382853ea1945c4fd240fe
**Database version**: 
2f888027f01c1f149dc060f43c83d3e5bdb625db

**Comment by Levitanious** [comment] 2019-01-28 12:33
Actually, you're not doing it right.

**Comment by Levitanious** [comment] 2019-01-28 12:34
Let me explain:

Mass dispell isn't supposed to proc at each cast of _Mass Dispell_, but it's supposed to be checked against each new _instance of the shield_ you're casting it against.

**Comment by AnonXS** [comment] 2019-01-28 12:51
When Immunity Effects are dispelled it should display "Immune Message" but the immunity aura is removed:

https://wow.gamepedia.com/index.php?title=Mass_Dispel&oldid=1437397

```
As of Patch 2.0.10 Mass Dispel has been changed to always pick immunity granting effects as its target. Note that even if Ice Block, Divine Shield, Divine Protection or Banish are dispelled by Mass Dispel, you'll still get the immune message even though it has been removed. 
```

**Comment by Ve1vet** [comment] 2019-01-28 13:02
@Levitanious what are you talking about?
Mass dispell should dispel Divine Shirld(Paladin)/ Ice Block(Mage), and those two spells have the highest priority(blizzlike) to be dispelled from dispell list.

@AnonXS the second link is 2009 -> WoLK, where palas have talent with dispell resistanse. Third link the same 2010. In TBC neither paladin, nor mage don't have dispell resistance at all.

The only way paladin or mage can resist mass dispell -> spell miss( 1% miss blizzlike minimum ) based in level diff & spell hit.
But if mass dipell not dispell bubble & ice block at all, than this is 100% bug.

**Comment by AnonXS** [comment] 2019-01-28 13:06
https://wowwiki.fandom.com/wiki/Patch_2.2.0
```
Mass Dispel: The portion of this spell that removes immunity effects (Blessing of Protection, Ice Block, etc.)
Now has a chance to be resisted, and will display correctly to the combat log.
It will no longer cause Rogues and Druids in Cat Form to lose stealth. 
```

**Comment by Ve1vet** [comment] 2019-01-28 13:18
@AnonXS you read it wrong.
For example priest in discipline have talent "Silent Resolve", that "reduce the chance that priest spells will be dispelled by 4/8/12/16/20%". Before patch 2.2.0 Mass Dispel ignores that talent, but not after.

Spell Penetration was in TBC also. Mechanic was the same, as a spell hit mechanic too. 

There is no other reason except 1% & spell hit, that Divine Shield & Ice Block can resist mass dispell. Other way you break all mechanics.

**Comment by AnonXS** [comment] 2019-01-28 13:32
![unbenannt](https://user-images.githubusercontent.com/19734826/51839307-2bead980-2309-11e9-8df0-686be27d6717.PNG)

Silent Resolve does not affect Mass Dispell.

---

Focused Power does affect Mass Dispell in TBC.

![unbenannt](https://user-images.githubusercontent.com/19734826/51839374-5ccb0e80-2309-11e9-923b-bb8e174667f1.PNG)

https://dwarfpriest.wordpress.com/2008/01/07/spell-hit-spell-penetration-and-resistances/
```
The talent Focused Power (from the Discipline talent tree) can increase your chance to hit
with Mind Blast, Smite, and Mass Dispel by 2% per rank (2 ranks, max of 4%).
```

https://www.ownedcore.com/forums/world-of-warcraft/world-of-warcraft-guides/114860-few-shadowpriest-arena-pvp-tips.html

04-22-2008
2.2k rated shadow priest
```
13) Paladin Shield - this isn't quite as simple as it seems. Paladins have a very high resistance against mass dispel, but 4/5 times it will go down on your first dispel.
```

20% chance to resist, doesnt quite match the 1% rule.

**Comment by Ve1vet** [comment] 2019-01-28 14:18
@AnonXS,  sorry. orgot about paladin talent "Stoicism"( https://wowwiki.fandom.com/wiki/Stoicism?oldid=1634267 ). Gives 30%.
Plus 96% spell hit chance to player the same level( https://wowwiki.fandom.com/wiki/Spell_hit?oldid=1601050 ). 1% doesn't work if spell hit chance <= 99%.
So we getting already about ~34% to dispel resist( 30% dispel resist + 4% spell miss chance ) w/o bonus spell hit & spell penetration in items.
Also shadow priset can't get to Focused Power ever. because 20/0/41. So that 2,2k noob have too big chance with mass dispel 4/5. Should have 2/3 🤣 He is lucky.
This discussion have matter if Mass Dispel dispels Ice Block & Divine Shield ever. If not, than we talk about nothing now. 
I can't test, i don't have client & server.

**Comment by Ve1vet** [comment] 2019-01-28 14:30
And Silent Resolve does affect to mass dispell, because:
Id: 38 (SPELL_EFFECT_DISPEL) for all dispell spells( Dispel/Mass Dispel/Purge etc. )
And Silent Resolve applies aura:
Aura Id 107 (SPELL_AURA_ADD_FLAT_MODIFIER), value = 20, misc = 28 (SPELLMOD_RESIST_DISPEL_CHANCE), miscB = 0, periodic = 0
Same as paladins Stoicism. Druid have such talent as i remember and someone else.

**Comment by MagPurify** [comment] 2019-01-29 18:09
As researching a little bit more, it looks like 
https://github.com/cmangos/mangos-tbc/blob/master/src/game/Spells/Spell.cpp#L977-L980
It's returning SPELL_MISS_IMMUNE as a MissCondition returned from this piece of code:
https://github.com/cmangos/mangos-tbc/blob/master/src/game/Entities/Unit.cpp#L2788-L2793

I see a note about `// All positive spells can`t miss`, what should be considered positive spell ? 
@Warlockbugs you worked on that recently right ?

**Comment by Ve1vet** [comment] 2019-01-29 19:01
@MagPurify positive spell, for example all healing/buff spells, self casting spells( not all ), etc. They can't miss, but they can be resisted. For example when druid tries to clean poison & poison have SPELLMOD_RESIST_DISPEL_CHANCE. So spell hits the target but its effect can be resisted.
Mass Dispel not a positive spell, because it dispels positive spells(buffs) from the enemy, but have positive effect when apply on self or friendly unit( spell_miss_immune, tells the client, that spell can't miss, as you can see from code in your links, but for enemies Mass Dispel effect shouldn't pass this checks, move on and return MagicSpellHitResult(pVictim, spell, schoolMask); from line 2834 ).
I apologize for not expressing my thoughts well.

**Comment by MagPurify** [comment] 2019-01-29 19:42
Okay,  @Ve1vet  so narrowed down to this block 
https://github.com/cmangos/mangos-tbc/blob/master/src/game/Entities/Unit.cpp#L7378-L7385

The if inside the block 
```
if (!(itr.aura && IsPositiveEffectMask(itr.aura->GetSpellProto(), itr.aura->GetEffIndex()) && isPositive && !itr.aura->GetSpellProto()->HasAttribute(SPELL_ATTR_EX_UNAFFECTED_BY_SCHOOL_IMMUNE)) &&
                    (itr.type & GetSpellSchoolMask(spellInfo)))
                    return true;
```
For example, IceBlock, this effect returns true. 
```
Effect #3 | Apply Aura: Immune School (126)
```

Will study a little bit more to understand why.

**Comment by Gelori** [comment] 2019-02-15 15:09
Bug report is totally wrong for TBC!

_Expected behavior:
Mass Dispel is able to remove normally undispellable Magic effects such as [Ice Block] and [Divine Shield].
Tested on Duel, Arena and against enemy faction._

This was added only in Wotlk! Doesn't apply to TBC in any way!

**Comment by LevelOneX** [comment] 2019-02-15 15:17
@Gelori Follow the information on the link `Mass Dispel is a new level 70 priest spell in Burning Crusade available from a trainer. It can remove Paladin  [Divine Shield] and Mage  [Ice Block] abilities, as well as other normally undispellable Magic effects like the Banish some mobs use.` 
https://wow.gamepedia.com/index.php?title=Mass_Dispel&oldid=1437397

**Comment by LevelOneX** [comment] 2019-02-15 15:19
@MagPurify It's getting the immune return type because of the school mask.
`(itr.type & GetSpellSchoolMask(spellInfo)` This line here will always be true for 126 spells: 
Immune School (126). Now I am not sure if the spell school needs to change, or statement in the if.

**Comment by killerwife** [comment] 2019-02-15 15:58
I just want to tell everyone to stop looking. The proper solution is more complicated than it seems. It will be fixed whenever I export my targeting rework to cmangos. The current plan is March, but my IRL is a bit unstable.

**Comment by berserkingyadis** [comment] 2020-03-09 10:40
Was this targeting rework exported?

**Comment by killerwife** [comment] 2021-12-09 23:22
Should be resolved some long time ago :D

**Closed by killerwife** 2021-12-09 23:22 UTC
Labels: System: Spell, Version: TBC (2.4.3), Info: Will Be Fixed in Export to CMaNGOS
