### ISSUE TITLE
[Classic] Warrior's Last Stand cause player can't release spirit

### ISSUE THREAD

**Issue by wowmui** [cmangos/issues#1238] opened 2017-01-16 03:35 UTC
**Current behavior**: 
When warrior died in the Last Stand buff. They can't do anything include release spirits.
![image](https://cloud.githubusercontent.com/assets/12601614/21970251/81fe15d0-dbdf-11e6-8a11-0d82ff7be06f.png)

**Expected behavior**: 
They should display [release spirit] option.
**Steps to reproduce**:

1. player a warrior,learn Last stand
2. cast last stand 
3. died in last stand.

**Client version**: 
1.12.1
**Commit hash**: 
fea8e7bd4be36b50f05eeadb33e6a5a74b88595d
**Database version**: 
z2693_01
**Operating system**: 
WIN 10

[//]: # (If this is a crash report, include the crashlog from a debug build with https://gist.github.com/)

**Comment by evil-at-wow** [comment] 2017-01-17 20:25
Ah, the famous "1 hp" bug. This is a duplicate of #462.

**Closed** 2017-01-25 15:22 UTC
