### ISSUE TITLE
🐛 [Bug Report] "Improved Sap" doesn't work

### ISSUE THREAD

**Issue by yyhhrr** [cmangos/issues#3577] opened 2023-10-06 08:12 UTC
### Bug Details

The talent "Improved Sap" doesn't work.
ID spell
Rank 1 = 14076
Rank 2 = 14094
Rank 3 = 14095
when rogue use sap spell with improved sap talent,if target is player,it worked.But if target is mob ,target won't be sapped.

### Steps to Reproduce

1.
2.
3.
4.

### Core SHA1 Commit Hash

330c0e33c0ceae42745874c61cf8db98e948ac6b

### Database SHA1 Commit Hash

58976c2fc01028dcd64efbaf6fd54c46db437dac

### Operating System

win 10

### Client Version

1.12.1 (Classic)

**Comment by yyhhrr** [comment] 2023-10-06 08:16
![image](https://github.com/cmangos/issues/assets/3608322/2b15dde2-fd03-42b1-b415-3a3b95bc0e7f)

**Comment by insunaa** [comment] 2023-10-06 09:42
duplicate of https://github.com/cmangos/issues/issues/3073

**Closed as not planned** 2023-10-06 09:44 UTC
Labels: Info: Needs Replication
