### ISSUE TITLE
[CLASSIC] Garr Does Not Cast his Antimagic Pulse

### ISSUE THREAD

**Issue by terassiel** [cmangos/issues#1326] opened 2017-03-06 15:59 UTC
**Current behavior**: NPC 12057(Garr) does not cast his spell 19492 (Antimagic Pulse)
While a player can cast this spell to its full effect any npc who was given this spell id will not cast it. The code for garr seems ok though as he will cast any other ID.

**Expected behavior**: Garr should cast the dispel on a timer.

**Steps to reproduce**: Go to Molten Core, start the Garr fight, wait.

**Client version**: 1.12.1 (5875), Core and DB on the latest updates

**Comment by cala** [comment] 2017-03-27 09:53
Greetings,

I tested this encounter several times for the last weeks and the antimagic pulse worked as intented.
If you can provide more data on how reproduce this, I'll gladly read this. Unless, I'll close this issue soon.
Thanks.

**Comment by terassiel** [comment] 2017-03-27 20:32
What kind of data do you need? I am using a unmodified version of the classis core and db

**Comment by cala** [comment] 2017-04-20 07:42
I'm sorry, I tested again this encounter yesterday and the debuffs were removed for every player in the raid.
Can you check in your server and SD2 logs for data about spell 19492?

**Comment by terassiel** [comment] 2017-04-20 13:39
SD2 Logs are clean, Server only contains following errors during loading : 
Loading CreatureEventAI Scripts...
ERROR CreatureEventAI: Creature 7307 has nonexistent SpellID(26865) defined in event 730710.
ERROR CreatureEventAI: Creature 7307 has EFLAG_REPEATABLE set. Event can never be repeatable. Removing flag for event 730711.
ERROR CreatureEventAI: Creature 7308 has nonexistent SpellID(26867) defined in event 730807.
ERROR CreatureEventAI: Creature 7308 has EFLAG_REPEATABLE set. Event can never be repeatable. Removing flag for event 730808.
ERROR CreatureEventAI: Creature 7310 has nonexistent SpellID(27441) defined in event 731007.

So nothing related to Molten Core. During the encounter no additional error logs are created.
My DB entry for the spell is as followos : 
'19492', '0', '0', '0', '0', '16', '136', '4', '0', '0', '0', '0', '0', '0', '0', '0', '0', '1', '0', '0', '0', '0', '0', '0', '101', '0', '0', '62', '62', '0', '0', '0', '0', '0', '0', '1', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '-1', '0', '0', '38', '0', '0', '1', '0', '0', '1', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '22', '0', '0', '15', '0', '0', '11', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '1', '0', '0', '0', '0', '0', '0', '0', '0', '5306', '74', '0', '0', 'Antimagic Pulse', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '0', '0', '0', '0', '0', '0', '0', '1', '1', '1', '0', '0', '0'
My Boss_Garr.cpp : 
[boss_garr.txt](https://github.com/cmangos/issues/files/943230/boss_garr.txt)

**Comment by terassiel** [comment] 2017-04-20 13:41
For me not a single NPC that I gave this spell ID would cast it - A GM on the other hand could cast it to its full effect.

**Comment by cala** [comment] 2017-08-30 07:28
Ok, I think I finally got this one. By any chance, did you perform your tests with a single player (I mean: solo) ? If so, this is due to the spell mechanics to pick a target. With at least two players, the ability works as intended. I tested these two cases and got the expected results (no dispell with a single target, periodic dispell with two targets).

**Comment by terassiel** [comment] 2017-08-30 12:55
No, I did it with as many as 5 characters, both in one party and spread over the raid. I did use only one pc though if that makes any difference.

**Comment by al3xc1985** [comment] 2020-03-07 06:12
@cala i believe that it can't be replicate and it is invalid. We can close it

**Comment by cala** [comment] 2020-04-20 11:28
Tested today and no longer replicable. Closing this.

**Closed by cala** 2020-04-20 11:28 UTC
Labels: Info: Needs Development, Info: Replicated, System: Spells, Version: Classic
