### ISSUE TITLE
How can I verify that ScriptDev2 is actually loading and running scripts properly

### ISSUE THREAD

**Issue by Gacnt** [cmangos/issues#1251] opened 2017-01-21 23:22 UTC
I can't seem to get a certain NPC to work properly though the supplied ScriptDev2 script seems to be fine, so I tried adding some random `DoScriptText` calls and random `std::cout << "HELLOOOO"` but it doesn't seem to call anything. The NPC says nothing and the `cout` never appears

How can I verify that ScriptDev2 is launching

**Comment by BeerfishWoW** [comment] 2017-01-21 23:44
This isn't a bug you're reporting, but rather a question you may ask on the forums or on IRC. You can check if SD2 runs, when you launch your server. It should output something like:

```
Initializing Scripting Library...

 MMM  MMM    MM
M  MM M  M  M  M
MM    M   M   M
 MMM  M   M  M
   MM M   M MMMM
MM  M M  M 
 MMM  MMM  http://www.scriptdev2.com

SD2: Using configuration file ../etc/mangosd.conf

MySQL client library: 5.5.53
MySQL server ver: 5.5.53-0+deb8u1 
MySQL client library: 5.5.53
MySQL server ver: 5.5.53-0+deb8u1 
SD2: ScriptDev2 database initialized.

SD2: Loading Script Texts...
Loading texts from script_texts, with additional data
>> Loaded 4301 text templates from script_texts

SD2: Loading Custom Texts...
Loading texts from custom_texts, with additional data

>> Loaded 0 string templates. DB table `custom_texts` is empty.
SD2: Loading Gossip Texts...
Loading texts from gossip_texts
>> Loaded 134 string templates from gossip_texts

SD2: Loading Script Waypoints for 109 creature(s)...

>> Loaded 3407 Script Waypoint nodes.
SD2: Loading C++ scripts
```

**Comment by Gacnt** [comment] 2017-01-22 02:37
```       _____     __  __       _   _  _____  ____   _____ 
      / ____|   |  \/  |     | \ | |/ ____|/ __ \ / ____|
     | |        | \  / |     |  \| | |  __  |  | | (___  
     | |ontinued| |\/| | __ _| . ` | | |_ | |  | |\___ \ 
     | |____    | |  | |/ _` | |\  | |__| | |__| |____) |
      \_____|   |_|  |_| (_| |_| \_|\_____|\____/ \____/ 
      http://cmangos.net\__,_|     Doing things right!


Using configuration file mangosd.conf.
World Database total connections: 2
MySQL client library: 5.7.17
MySQL server ver: 5.7.17 
MySQL client library: 5.7.17
MySQL server ver: 5.7.17 
Character Database total connections: 2
MySQL client library: 5.7.17
MySQL server ver: 5.7.17 
MySQL client library: 5.7.17
MySQL server ver: 5.7.17 
Login Database total connections: 2
MySQL client library: 5.7.17
MySQL server ver: 5.5.5-10.1.20-MariaDB 
MySQL client library: 5.7.17
MySQL server ver: 5.5.5-10.1.20-MariaDB 

Realm running as realm ID 1

Using World DB: Classic DB version 1.8 "Lunar Festival". For core Classic z2692.
Using creature EventAI: ACID 1.12.x (Classic) for CMaNGOS-CLASSIC (1.12.X Client)

Using DataDir ./
WORLD: VMap support included. LineOfSight:1, getHeight:1, indoorCheck:1
WORLD: VMap data directory is: ./vmaps
WORLD: MMap pathfinding enabled

Loading MaNGOS strings...
Loading texts from mangos_string
>> Loaded 817 MaNGOS strings from table mangos_string

Loading spell_template...
>> Loaded 22357 spell_dbc records

Initialize DBC data stores...
>> Initialized 50 data stores

Using enUS DBC Locale as default. All available DBC locales: enUS 

Loading Script Names...
>> Loaded 333 Script Names

Loading WorldTemplate...
>> Loaded 2 World Template definitions

Loading InstanceTemplate...
>> Loaded 26 Instance Template definitions

Loading SkillLineAbilityMultiMap Data...
>> Loaded 5072 SkillLineAbility MultiMap Data

Loading SkillRaceClassInfoMultiMap Data...
>> Loaded 148 SkillRaceClassInfo MultiMap Data

Cleaning up instances...
>> Instances cleaned up

Packing instances...
>> Instance numbers remapped, next instance id is 1

Packing groups...
>> Group Ids remapped, next group id is 2


Loading Page Texts...
>> Loaded 1431 page texts

Loading Game Object Templates...
>> Loaded 10548 game object templates

Loading GameObject models...

Loading Spell Chain Data...
>> Loaded 2845 spell chain records (1786 from DBC data with 2 req field updates, and 1059 loaded from table)

Loading Spell Elixir types...
>> Loaded 60 spell elixir definitions

Loading Spell Facing Flags...

>> Loaded 971 facing caster flags
Loading Spell Learn Skills...
>> Loaded 58 Spell Learn Skills from DBC

Loading Spell Learn Spells...
>> Loaded 9 spell learn spells + 4735 found in DBC

Loading Spell Proc Event conditions...
>> Loaded 151 extra spell proc event conditions +10 custom proc (inc. +8 custom ranks)

Loading Spell Bonus Data...
>> Loaded 100 extra spell bonus data

Loading Spell Proc Item Enchant...
>> Loaded 4 proc item enchant definitions

Loading Aggro Spells Definitions...
>> Loaded 73 spell threat entries

Loading NPC Texts...
>> Loaded 4815 npc texts

Loading Item Random Enchantments Table...
>> Loaded 27892 Item Enchantment definitions

Loading Item Templates...
>> Loaded 14879 item prototypes

Loading Item Texts...

>> Loaded 0 item pages
Loading Creature Model Based Info Data...
>> Loaded 10534 creature model based info

Loading Equipment templates...
>> Loaded 4898 equipment template

Loading Creature Stats...
>> Found 189 creature stats definitions.

Loading Creature templates...
>> Loaded 9114 creature definitions

Loading Creature template spells...
>> Loaded 2430 creature_template_spells definitions

Loading SpellsScriptTarget...
>> Loaded 497 spell_script_target definitions

Loading ItemRequiredTarget...
>> Loaded 41 Item required targets

Loading Reputation Reward Rates...
>> Loaded 3 reputation_reward_rate

Loading Creature Reputation OnKill Data...
>> Loaded 441 creature award reputation definitions

Loading Reputation Spillover Data...
>> Loaded 12 reputation_spillover_template

Loading Points Of Interest Data...
>> Loaded 244 Points of Interest definitions

Loading Pet Create Spells...

>> Loaded 7 pet create spells from table and 301 from DBC
Loading Creature Data...
>> Loaded 63113 creatures

Loading Creature Addon Data...
>> Loaded 7463 creature template addons
>> Loaded 2097 creature addons
>>> Creature Addon Data loaded

Loading Gameobject Data...
>> Loaded 51794 gameobjects

Loading CreatureLinking Data...
> Loading table `creature_linking_template`
`creature_linking_template` has FLAG_FOLLOW, but no master, (entry: 17647, map: 0, master: 17635)
`creature_linking_template` has FLAG_FOLLOW, but no master, (entry: 17996, map: 0, master: 17995)
>> Loaded creature linking for 117 creature-entries

> Loading table `creature_linking`
>> Loaded creature linking for 547 creature-Guids

Loading Objects Pooling Data...

>> Loaded 5513 objects pools

>> Loaded 357 creatures in pools from `pool_creature`

>> Loaded 734 creatures in pools from `pool_creature_template`

>> Loaded 27451 gameobject in pools from `pool_gameobject`

>> Loaded 198 gameobject in pools from `pool_gameobject_template`

>> Loaded 3412 pools in mother pools

Loading Weather Data...
>> Loaded 33 weather definitions

Loading Quests...
>> Loaded 4243 quests definitions

Loading Quests Relations...

>> Loaded 245 quest relations from gameobject_questrelation

>> Loaded 208 quest relations from gameobject_involvedrelation

>> Loaded 3820 quest relations from creature_questrelation

>> Loaded 3976 quest relations from creature_involvedrelation
>>> Quests Relations loaded

Loading Game Event Data...

>> Loaded 34 game events

>> Loaded 584 creatures in game events

>> Loaded 9619 gameobjects in game events

>> Loaded 80 creature reactions at game events

>> Loaded 54 quest additions in game events

>> Loaded 0 start/end game event mails
>>> Game Event Data loaded

Loading Conditions...
Condition (31) reserved for later versions, skipped
ObjectMgr::LoadConditions: invalid condition_entry 717, skip
Condition (31) reserved for later versions, skipped
ObjectMgr::LoadConditions: invalid condition_entry 718, skip
>> Loaded 630 Condition definitions

Creating map persistent states for non-instanceable maps...

Loading Creature Respawn Data...
>> Loaded 0 creature respawn time.

Loading Gameobject Respawn Data...
>> Loaded 0 gameobject respawn time.

Loading SpellArea Data...
>> Loaded 1 spell area requirements

Loading AreaTrigger definitions...
>> Loaded 100 area trigger teleport definitions

Loading Quest Area Triggers...
>> Loaded 30 quest trigger points

Loading Tavern Area Triggers...
>> Loaded 42 tavern triggers

Loading AreaTrigger script names...
>> Loaded 41 areatrigger scripts

Loading event id script names...
>> Loaded 22 scripted event id

Loading Graveyard-zone links...
>> Loaded 171 graveyard-zone links

Loading spell target destination coordinates...
>> Loaded 313 spell target destination coordinates

Loading SpellAffect definitions...

>> Loaded 250 spell affect definitions
Loading spell pet auras...
>> Loaded 24 spell pet auras

Loading Player Create Info & Level Stats...

>> Loaded 40 player create definitions

>> Loaded 0 custom player create items

>> Loaded 1497 player create spells

>> Loaded 215 player create actions

>> Loaded 540 level health/mana definitions

>> Loaded 2400 level stats definitions

>> Loaded 60 xp for level definitions
>>> Player Create Info & Level Stats loaded

Loading Exploration BaseXP Data...
>> Loaded 61 BaseXP definitions

Loading Pet Name Parts...
>> Loaded 260 pet name parts

Cleaning character database...

Loading the max pet number...
>> Loaded the max pet number: 1859

Loading pet level stats...
>> Loaded 1560 level pet stats definitions

Loading Player Corpses...
>> Loaded 1 corpses

Loading Loot Tables...
>> Loaded 234648 loot definitions (4396 templates) from table creature_loot_template

>> Loaded 90 loot definitions (70 templates) from table fishing_loot_template

>> Loaded 15529 loot definitions (568 templates) from table gameobject_loot_template

>> Loaded 4096 loot definitions (178 templates) from table item_loot_template

>> Loaded 61 loot definitions (61 templates) from table mail_loot_template

>> Loaded 6909 loot definitions (1560 templates) from table pickpocketing_loot_template

>> Loaded 2819 loot definitions (780 templates) from table skinning_loot_template

>> Loaded 80 loot definitions (37 templates) from table disenchant_loot_template

>> Loaded 4601 loot definitions (204 templates) from table reference_loot_template

>>> Loot Tables loaded

Loading Skill Fishing base level requirements...
>> Loaded 57 areas for fishing base skill level

Loading Npc Text Id...
>> Loaded 80 NpcTextId

Loading Gossip scripts...
>> Loaded 258 script definitions from table dbscripts_on_gossip

(Re)Loading Gossip menus...
Table gossip_menu for menu 6644, text-id 8702 has condition_id 718 that does not exist in `conditions`, ignoring
>> Loaded 3267 gossip_menu entries

(Re)Loading Gossip menu options...
Table gossip_menu_option for menu 6644, id 0 has condition_id 717 that does not exist in `conditions`, ignoring
Table gossip_menu_option for menu 6644, id 1 has condition_id 718 that does not exist in `conditions`, ignoring
>> Loaded 2167 gossip_menu_option entries

Loading Vendors...
>> Loaded `npc_vendor_template`, table is empty!

>> Loaded 12504 vendor items

Loading Trainers...
Table `npc_trainer_template` for trainer (Entry: 20) has non-learning spell 21084, ignore
  ... possible must be used spell 21085 instead
Table `npc_trainer_template` for trainer (Entry: 21) has non-learning spell 21084, ignore
  ... possible must be used spell 21085 instead
>> Loaded 0 trainer template spells

>> Loaded 27308 trainer spells

Loading Waypoint scripts...
>> Loaded 1119 script definitions from table dbscripts_on_creature_movement

Loading Waypoints...
>> Loaded 2061 paths, 44334 nodes and 109 behaviors from waypoints

>> Loaded 235 path templates with 7990 nodes and 4 behaviors from waypoint templates

Loading ReservedNames...
>> Loaded 0 reserved player names

Loading GameObjects for quests...
>> Loaded 667 GameObjects for quests

Loading BattleMasters...
>> Loaded 24 battlemaster entries

Loading BattleGround event indexes...
>> Loaded 1144 battleground eventindexes

Loading GameTeleports...
>> Loaded 221 GameTeleports

Loading Localization strings...
>> Loaded 0 creature locale strings. DB table `locales_creature` is empty.
>> Loaded 0 gameobject locale strings. DB table `locales_gameobject` is empty.
>> Loaded 0 Item locale strings. DB table `locales_item` is empty.
>> Loaded 0 Quest locale strings. DB table `locales_quest` is empty.
>> Loaded 0 Quest locale strings. DB table `locales_npc_text` is empty.
>> Loaded 0 PageText locale strings. DB table `locales_page_text` is empty.
>> Loaded 0 gossip_menu_option locale strings. DB table `locales_gossip_menu_option` is empty.
>> Loaded 0 points_of_interest locale strings. DB table `locales_points_of_interest` is empty.
>>> Localization strings loaded

Loading Auctions...
>> Loaded 0 auction items
>> Loaded 0 auctions. DB table `auction` is empty.
>>> Auctions loaded

Loading Guilds...
>> Loaded 0 guild definitions

Loading Groups...
>> Loaded 1 group definitions

>> Loaded 0 group-instance binds total

>> Loaded 0 group members total

Returning old mails...
>> Only expired mails (need to be return or delete) or DB table `mail` is empty.

Loading GM tickets...
>> Loaded 1 GM tickets

Loading DB-Scripts Engine...
>> Loaded 347 script definitions from table dbscripts_on_quest_start

>> Loaded 572 script definitions from table dbscripts_on_quest_end

>> Loaded 13 script definitions from table dbscripts_on_spell

>> Loaded 80 script definitions from table dbscripts_on_go_use

>> Loaded 122 script definitions from table dbscripts_on_go_template_use

>> Loaded 552 script definitions from table dbscripts_on_event

>> Loaded 13 script definitions from table dbscripts_on_creature_death

>>> Scripts loaded

Loading Scripts text locales...
Loading texts from db_script_string, with additional data
>> Loaded 635 text templates from db_script_string

Loading CreatureEventAI Texts...
Loading texts from creature_ai_texts, with additional data
>> Loaded 414 text templates from creature_ai_texts

Loading CreatureEventAI Summons...
>> Loaded 18 CreatureEventAI summon definitions

Loading CreatureEventAI Scripts...
>> Loaded 12649 CreatureEventAI scripts

Initializing Scripting Library...
Scripting library not found or not accessible.

Initialize game time and timers
Starting Map System

Starting BattleGround System
>> Loaded 3 battlegrounds

Starting Outdoor PvP System
>> Loaded 2 Outdoor PvP zones

Loading Transports...
>> Loaded 8 transports

Deleting expired bans...

Starting server Maintenance system...
Loading Honor Standing list...

>> Loaded 0 Horde and 0 Ally honor standing definitions
Starting Game Event system...
GameEvent 3 "Pyrewood Village - Worgen Curse" started.
GameEvent 16 "Gurubashi Arena Booty Run" started.
GameEvent 20 "Call to Arms: Arathi Basin!" started.
GameEvent 27 "Nights" started.
GameEvent 30 "Edge of Madness, Hazza'rah" started.
GameEvent 32 "Edge of Madness, Wushoolay" started.
GameEvent 35 "Winter Season Fishing" started.
GameEvent 61 "Stormwind City - Stockades Jail Break" started.
Next game event check in 188 seconds.
Game Event system initialized.

Loading grids for active creatures or transports...

Player::DeleteOldChars: Deleting all characters which have been deleted 30 days before...

Initialize AuctionHouseBot...
AHBOT is Disabled. Unable to open configuration file(../etc/ahbot.conf). 

---------------------------------------
      CMANGOS: World initialized       
---------------------------------------

SERVER STARTUP TIME: 0 minutes 3 seconds

```

This is my startup log, I don't see anything referencing ScriptDev2, any ideas?

**Comment by kartoffelsup** [comment] 2017-01-22 08:00
> Initializing Scripting Library...
Scripting library not found or not accessible.

There it is.

**Comment by devmaximus** [comment] 2017-01-22 08:02
was resolved :) wrong mangosd.config location

**Comment by devmaximus** [comment] 2017-01-22 08:07
@Gacnt  looks like you can close this ticket :) based on our discussion 

[20:57:30] 20<maximus>30 2017-01-21 23:05:50 <SD2 ERROR>: Unable to open configuration file. Database will be unaccessible. Configuration values will use default. <--
[20:57:41] 20<maximus>30 thats states it all that it even failed to find mangosd.config
[20:57:47] 18<Gacnt18> :O
[21:00:39] 18<Gacnt18> weird, moving it into /etc/mangosd.conf works
[21:00:48] 18<Gacnt18> but calling -c on where ever it is doesnt
[21:00:52] 18<Gacnt18> Even though it conncets to everything else
[21:01:09] 18<Gacnt18> works now though
[21:12:05] 19<Gacnt> @maximus Thanks for your help, I think everything is running as intended now
[21:12:12] 18<Gacnt18> I'm sure I'll be back.
[21:25:53] 20<maximus>30 np

**Closed** 2017-01-22 08:10 UTC
