### ISSUE TITLE
🐛 [Bug Report] q.1193 A Broken Trap doesn't work

### ISSUE THREAD

**Issue by yyhhrr** [cmangos/issues#3630] opened 2023-12-14 10:00 UTC
### Bug Details

q.1193 A Broken Trap doesn't work

### Steps to Reproduce

1.
2.
3.
4.
q.1193 A Broken Trap doesn't work

### Core SHA1 Commit Hash

468c62bd774af33e3270d63f77b4c3cceb735cd9

### Database SHA1 Commit Hash

364f84ad5e9f6bb986afa6cb39a5bb4902613118

### Operating System

win 10

### Client Version

1.12.1 (Classic)

**Comment by evil-at-wow** [comment] 2023-12-14 14:40
This is also an issue in the WotLK core/database (see cmangos/wotlk-db#1139) and TBC core/database.

I haven't checked in Classic but the issue is likely the same in all databases. Could you test in Classic with the changes from my TBC pull request https://github.com/cmangos/tbc-db/pull/1173 applied?

**Closed as completed** 2023-12-14 20:51 UTC
Labels: Info: Needs Replication

**Comment by yyhhrr** [comment] 2023-12-15 13:19
Yes,it works.But you can only complete q.1193 once.So I think q.1193 should set repeatable(specialflag=1)
