### ISSUE TITLE
DK - Mind Freeze + Endless Winter Talent

### ISSUE THREAD

**Issue by tarwyn** [cmangos/issues#177] opened 2013-04-01 12:33 UTC
http://www.hotwow.com/spell-47528.html

With Endless Winter r2 (http://www.hotwow.com/spell-49657.html) seems to lock your runepower until a new runepower gain is achieved. This problem does not occur when used without Endless Winter, thus penalizing Frost-DKs.

**Comment by killerwife** [comment] 2022-02-03 18:45
I cannot reproduce this issue and as such I am closing it.

**Closed by killerwife** 2022-02-03 18:45 UTC
Labels: System: Spells, Version: WotLK (3.3.5), Info: Needs Replication, Class: Death Knight
