### ISSUE TITLE
[TBC][WOTLK] Script of the Quest City of Light (id 10211) Does Not Work

### ISSUE THREAD

**Issue by Rapth** [cmangos/issues#1218] opened 2017-01-09 18:10 UTC
**Current behavior**: script did not work，npc say nothing just walk，quest cant complete！

**Expected behavior**: 

**Steps to reproduce**:

1. 
2. 
3. 

**Client version**: 
2.4.3
**Commit hash**: 

**Database version**: 
1.4.3
**Operating system**: 

windows 10
[//]: # (If this is a crash report, include the crashlog from a debug build with https://gist.github.com/)

**Comment by killerwife** [comment] 2017-01-09 18:11
@cala @cyberium toldya :D

**Comment by cyberium** [comment] 2017-01-09 18:14
Worst comment ever...
Refresh our memories instead! :)

**Comment by killerwife** [comment] 2017-01-09 18:19
JustRespawned is being called inside AIM_Initialize, causing EscortAI to not function properly, because it has 2 different events, on constructor init and on JustRespawned. This is the way the AI is structured, because before moving JustRespawned to AIM_Init, we only called JustRespawned on initial object construction for EAI.

Either:
A) Add event JustAIInit
B) Rewrite EscortAI to behave correctly for this scenario

This quest has a TemporarySummon creature with EscortAI, not a pre-spawned creature like most. If I recall correctly, similar quest is in Caverns of Time during the attunement on the beginning.

**Comment by cyberium** [comment] 2017-01-09 18:40
Well, you partialy right at one point.
Before moving justrespawned to AI_Init() it was called in the constructor. But with a result of a call to an AI method being constructed. So not fully constructed or initialized.

So for me all of this resulting only about the naming of that method and the different interpretation we can have for it.
Yes the best is to rename it and define correctly its role.

JustSpawned.
JustAddedToTheMap.
AiReset

and probably other need to be added to fit actual use of JustRespawned.

Someone told me that a certain @killerwife have perfect knowledge to do this properly.

**Comment by Rapth** [comment] 2017-01-10 01:50
@killerwife  but cavern of time just works fine！

**Comment by Rapth** [comment] 2017-01-10 07:07
@cyberium  I found that this quest can be done on CMaNGOS TBC/0.12.3  !

**Comment by Rapth** [comment] 2017-01-10 08:03
@killerwife could you show me some more details to fix this?

**Comment by killerwife** [comment] 2017-01-10 15:13
Essentially look at EscortAI and rewrite it so that instead of utilizing constructor you use JustRespawned event. Disregard naming problems right now.

**Comment by Rapth** [comment] 2017-01-11 05:01
ok thank u

**Comment by jimmybrancaccio** [comment] 2018-11-20 19:52
This was resolved for WotLK (#1019). Closing as a duplicate of #1019.

**Closed by jimmybrancaccio** 2018-11-20 19:52 UTC
Labels: System-Quests, Version-TBC, Version-WotLK
