### ISSUE TITLE
wotlk magisters terrace client freeze on entering selin fireheart area🐛 [Bug Report] 

### ISSUE THREAD

**Issue by Eriumango** [cmangos/issues#2949] opened 2022-05-17 21:25 UTC
### Bug Details

when doing magisters terrace in wotlk and heading into selin firehearts area the client will freeze (tested by a couple of people on the discord channel)

### Steps to Reproduce

1. go to magister terrace, approach selin fieheart ( from the entrance go past the first courtyard and into the next area,
2. your client and pc will freeze so dont have anything important unsaved
3. you can sign out on windows and back in to get control back on your pc
4. 
6.
7.

### Expected behavior

no client freeze

### Core SHA1 Commit Hash

 1090e42745b4d0b86a1f7bd4aa3757420c6ccca9

### Database SHA1 Commit Hash

16026f79f5509a6cdc1b15ad32a1f7e786479bb7

### Operating System

ubuntu 20.04

### Client Version

3.3.5a (Wrath of the Lich King)

**Comment by killerwife** [comment] 2022-05-17 21:50
Tomorrow I will prioritize this.

**Comment by jokerlfm** [comment] 2022-05-18 11:51
Confirmed. I tried other cores. It can enter the area which cmangos will freeze the client. So it should be the server issue.
And the command .teleport will crash the client.

**Comment by killerwife** [comment] 2022-05-18 15:18
Narrowed it down to being caused by NPC 24722. Will continue more today. Likely related to [2] Movement Flags: 134220033 (Forward, Walking, Root, SplineEnabled)

**Comment by killerwife** [comment] 2022-05-18 16:42
Fixed in https://github.com/cmangos/mangos-wotlk/commit/418d7a12eb6a0ece58490117fc8d24153b7849fb

**Closed by killerwife** 2022-05-18 16:42 UTC
Labels: Info: Needs Replication
