### ISSUE TITLE
[CLASSIC] escort quest "Bodyguard for Hire" - not attacked

### ISSUE THREAD

**Issue by RichardGe2** [cmangos/issues#1693] opened 2018-09-01 23:10 UTC
During quest 5821 :  Bodyguard for Hire ,
the spawned creatures rarely attack the caravan.  
Both caravan NPCs vs attackers NPCs seem to ignore themselves.
( However, my character is attacked - but if I'm far enough, the caravan can travel without any attack)
I assume this is a simple issue related to faction assignment... but I don't know how to fix that. 

My source and database are several months old... but I don't see recent fixes related to this issue, so I assume the bug still exists.

To reproduce:  start the server and go to Desolace. you have to wait ~15 minutes before  Cork Gizelton moves the caravan and asks for escort help. As soon as he asks help, you can take and start the quest

**Comment by cala** [comment] 2018-09-04 09:18
The ambushing NPCs were attacking the caravan when I released the script (I tested it) and the factions were not changed. So I assume some intermediate change broke the relations between the NPCs.

**Comment by killerwife** [comment] 2018-09-04 10:13
90% of these issues are due to UNIT_FLAG_IMMUNE_TO_NPC not being removed correctly in script.

**Comment by cala** [comment] 2018-09-04 14:11
I think you meant:
> 90% of these issues are due to UNIT_FLAG_IMMUNE_TO_NPC ~not being~ *that now needs to be manually* removed in script *because the behaviour was changed in core*.

because this script, like the Stitches one and many others were working even if the behaviour core-side was incorrect (bad handling of the flag though we did not know it). The flag was changed in core (I agree the change is correct) but not only the documentation was not fully updated leading to misunderstanding, the change broke many scripts and quests. This change happened months if not a year ago and we are still seeing fixes/issues related to it almost every week.

We are in a concentric ecosystem: the core is a tool for DB devs/scripters to do their job and they cannot always see all the side effects of a core change, especially DB devs as they have even fewer ways of scripting compared to SD2 devs. For example, you will understand that DB devs like Grz3s or myself cannot review the thousands of commits we made over the years every time a big change occurs in the core.

In the present case, if I had not seen by chance the Stitches script fail or if this report was not made, I would have never known that the scripts were no longer working correctly because they have been previously reworked and I would have no reason to look at them again. How many other scripts/quests are in the same state?

I'm probably not the first one to tell this but you have a tendency to think that because your changes are valid (at least in your point of view) this is for other people to handle the consequences of these changes.

We cannot ask of a full backward compatibility of course, but it would have been better to have a way to spot things affected by this change or at the very least new errors reported in logs so we can easily find what's wrong/needs to be updated. I remember that when Schmoozerd did changes that affects DBs, he provided tools and often scripts to help DB devs to handle the changes. It was very helpful and helped to roll out changes more efficiently.

**Comment by killerwife** [comment] 2018-09-04 14:28
Well, if you looked in tbc-db, you would know that we fixed more than 70 issues like this, possibly even more, and even in core I ported many to cmangos that fix this exact issue. I understand that it might have been badly communicated by you, but me, WB spammed it a lot on discord, and Grz3s knew about it.

There was no way to do backwards compatibility on this, it simply broke quests. The upside is that you can mimic sniffs 1:1 now and it works. The way it was spotted on our end was to launch it on voa. There is no other possible sane way of finding these issues other than rigorously testing all old scripts. Proof we are fixing these issues even for vanilla in tbc-db: https://github.com/cmangos/tbc-db/commit/c7a159feba7d2652e13ccc2f298eea12a02178ad

**Comment by killerwife** [comment] 2018-09-04 15:32
Well I am not able to make any such system that wouldn't have 10x more false positives. The problem is also how we (understand my team) are tackling this issue. We tackle it by looking it up in sniffs, and this process is mostly a 2-3 per day. Again, this is not meant to say how many we fixed, just that its time consuming, and why it is what it is.

When it comes to wiki, tell me whats not updated and I will sort it out with my team. (just disregard EAI please for now)

I know you can't pay attention to discord, neither does cyberium, or grz3s, but at this point even I am not paying attention to it enough. I have like 5 people messaging me who filter through stuff and how it gets to me. If there is a format which is feasible to update to pass these changes along, then someone needs to show it to me because I do not know how. I tend to ping everyone on critical commits and so far noone usually responds for weeks. Same can be true for @Saltgurka cos he complained to me that noone replies to him either. So clearly all of us are doing smth wrong.

**Comment by Saltgurka** [comment] 2018-09-04 15:51
I just want to pitch in that the quest was fixed in this commit 6 days ago: https://github.com/cmangos/tbc-db/commit/49dc8f97fce183728a4475eabf30d98448a6ebde

The problem was not the UnitFlag itself but that the TEMPFACTION flags were wrong (UnitFlags were restored upon leaving combat)

As for the whole discussion in this thread, I won't get into it too much. In my opinion what we must strive for is to have a core that allows us to follow sniffs 100%, and the update to TEMPFACTION_TOGGLE_IMMUNE_TO_NPC was one huge and important step in that direction. Every big change will always cause regressions and to be fair this one only affects scripts that was not scripted correctly to begin with. 

As for communications, we all know we got an issue there and I'm still not sure what our official main communication channel is. Discord? IRC? Github? My vote would be on Discord simply because I use it daily and if we set it up properly we could have a "News" channel where all major changes like this could be announced.

**Comment by cyberium** [comment] 2018-09-04 17:15
Core devs/Scripters and DB devs are different things with different objectives. But we have one main goal. Improve our project and make it better. So we all have to be patient. As a core dev we have to listen content devs and vice versa. Its not always easy. 

About the communication @cala is correct, we lack clearly on a more reliable way to discuss about some specific dev project. Iam open for some suggestion, do we need to reopen a forum? A disqus? Something that can let us the chance to talk about what we think its important. Wiki, discord and github are not for that. (well there is some new feature in github that i have to explore though)

**Comment by RichardGe2** [comment] 2018-09-04 18:28
@Saltgurka - good to know it's fixed. however your fix seems to be targeting TBC only ? I don't know how you guys manage deployment on all the other wow versions - but I assume this fix should be copied to Vanilla.

**Comment by Grz3s** [comment] 2018-09-04 18:30
Everyone will agree, that is not nice to find out ... that script u worked on (few days on one script etc) ... after few years .. just stops working .. and you have to spend more time to find out what happened...
Massive change for 0x100 and 0x200 ... is a good example of that... even xfurry complained that this change will dmg. lots of sd2 scripts...

From other side ... We all know that Core is not perfect and devs slowly step by step making it better.
Sometimes this will brake stuff ... but we all know about it. As a good example: when Schmoo.. added new buddy system i started to making tons of new script using it ... and few months later he change whole logic (buddy - other buddy) - I had to redo 100+ maybe more... scripts one by one... (it wasnt nice - but i knew its right way). The only diff ..was that he told me whats commig, so i had a time to prepare all.

Sometimes would be nice .. when some big change commig (that core dev knows it will brake smth)...just let everyone know (we do have nice tool on discord for that) ..

**Comment by RichardGe2** [comment] 2018-09-04 19:05
I tested the fix pointed by @Saltgurka on my Classic server - I confirm it's solving the issue. 
not perfect, because sometime Cork Gizelton continues to walk even if the caravan is under attack - I assume he should come to help. but this is another issue  - and more minor.

**Comment by RichardGe2** [comment] 2018-09-04 20:10
also another issue - if  Cork Gizelton reaches the finish point alone - we validate the quest - even if all the caravan has been killed - 
main fix for that would be to force Cork Gizelton to come help us during fights, instead of continue his way

**Comment by cala** [comment] 2018-09-06 13:05
@RichardGe2 Yes, the fix will be ported. I have technical issues preventing me from pushing right now, but I intend to port recent changes from TBC and WotLK DBs to Classic DB. I will also handle a few PR currently pending.
Regarding the quest failure, it is not properly handled at the moment, I have to look in the commit history why I did not add it, but I remember leaving a note there on that purpose for later.

@ everyone: thank you for the feedbacks and suggestions. We are going somewhere.
Regarding the communication between us, before looking for what tools, we should clarify our needs:
- for small specific points like issues or commits, I think GitHub is doing a great job
- for global and reference documentation, we have our wiki. IMHO, it has one big quality and two flaws (one major):
    - the wiki is very oriented and quite complete regarding database structures, which is a plus
    - the wiki is not always updated on par with the core, leading to some inconsistencies and we should motivate ourself to do so every time something is changed (and I include myself here as I dislike spending time on documentation)
    - the wiki is poorly documented about core systems (what are the main ones, what they do, how they interact) or SD2. We will never be able to have a fully documented core and full text research in code will always be the easiest way to find something. Yet it would be interesting to have a basic structure that is updated with core changes and is linked with the existing DB articles
- for basic and exploratory discussions, I think that discord is fine and it could probably be better used (I did not play with everything yet). I do not read all messages when there are lots of them, but I scroll to notifications, for examples I read @killerwife ping about spell cone targets though I did not took the time to respond but I'm definitely interested by more info on the subject
- for technical discussions about big subject that are about to be made or major changes (I mean those that are enough developed to be close to a PR/release) I don't think we have a suitable medium and we probably need to fill this gap

I can discuss with the guy in charge of code quality and documentation at work to see if he has some advices, because we had similar concerns in the past.
I also propose to write myself drafts in the wiki regarding the core systems, so we can build upon it and everyone here could correct/enhance them.

**Closed** 2018-11-22 15:51 UTC
Labels: Regression, System-Miscellaneous, Version-Classic
