### ISSUE TITLE
Issues in code

### ISSUE THREAD

**Issue by bdebaere** [cmangos/issues#1926] opened 2019-04-11 18:27 UTC
https://github.com/cmangos/mangos-classic/commit/77bf53850ea8cc31a17fe55598ff9aaa7e239278

Lines 947-954 contain an unconditional break within a loop.

```cpp
    for (SkillLineAbilityMap::const_iterator _spell_idx = bounds.first; _spell_idx != bounds.second; ++_spell_idx)
    {
        if (!_spell_idx->second->reqtrainpoints)
            return 0;

        basetrainp = _spell_idx->second->reqtrainpoints;
        break;
    }
```

**Comment by cala** [comment] 2020-04-23 20:04
I have edited the original report to remove element that are no longer present in the current version of the code.

**Comment by cala** [comment] 2020-04-23 20:09
Tagging @cyberium for the unreachable code in `LootMrg.cpp` because I believe this is for consistency with WotLK (and TBC) core loot code?

However, I'm unsure who to tag for the pet code.

I think the unreachable code for warlock pets should be dropped.

Regarding the unconditional break in the third report, I don't know the expected behaviour so I'm unsure if we are missing a check here or if the for-loop should be refactored in another way because it should be iterate only once to return either 0 or `_spell_idx->second->reqtrainpoints`

**Comment by cala** [comment] 2021-01-19 22:58
Edited first post to remove now fixed reports. @cyberium do you have a word to say regarding the last remaining point?

**Comment by killerwife** [comment] 2022-01-30 14:36
Tbh i dont know what the code is supposed to do and it still seems to have a purpose :D I am not dealing with this one :D

**Closed** 2022-02-01 22:10 UTC
Labels: Version: Classic (1.12)
