### ISSUE TITLE
Hunter Pets Not Gaining Health From Pet Training

### ISSUE THREAD

**Issue by Patrick-Barry** [cmangos/issues#1896] opened 2019-03-04 17:25 UTC
Hunter pets aren't getting health from the extra stamina granted from scrolls or the pet training "Great Stamina".

Expected behavior: Pet maximum health should increase.

Client Version:  "1.12.1" (CLASSIC)

CMaNGOS Repo & Commit Hash:  cmangos-classic 7fa4124748e2f378e209c82bd7d0dea448482f02

Database Repo & Commit Hash: classic-db  c02a5131930c04e7b0a0fa2fca6ad726c025cac9

Operating System: Win 10

### Steps to reproduce
1. Learn "Great Stamina" at any rank. The pets stamina will go up, but maximum health is not increased.

**Comment by bdebaere** [comment] 2019-03-10 15:35
Commit bbcbd50eb13ca0148dfbd6d34070db1e9224f3ad by @killerwife changed the calculation for health to the lines below. The commit changed the line marked in bold. You will notice that for some reason stamina increases below a set value of 20 have 0 effect whatsoever. This feels wrong to me at least since the first 6 ranks of Great Stamina now have no net effect on health i.e. the health is not increased for the first 6 ranks of Great Stamina because they do not cross the 20 stamina threshold.

@killerwife You also changed the UpdateMaxPower in the same commit, maybe that needs to be double checked too.

```
void Pet::UpdateMaxHealth()
{
    UnitMods unitMod = UNIT_MOD_HEALTH;
    float stamina = GetStat(STAT_STAMINA) - GetCreateStat(STAT_STAMINA);

    float value = GetModifierValue(unitMod, BASE_VALUE) + GetCreateHealth();
    value *= GetModifierValue(unitMod, BASE_PCT);
    **value += GetModifierValue(unitMod, TOTAL_VALUE) + std::max((stamina - 20) * 10 + 20, 0.f);**
    value *= GetModifierValue(unitMod, TOTAL_PCT);

    SetMaxHealth((uint32)value);
}
```

**Comment by killerwife** [comment] 2022-01-30 12:22
Closing this as I cannot reproduce this.

**Closed by killerwife** 2022-01-30 12:22 UTC
Labels: System: Player Controlled Units, Version: Classic (1.12), Info: Needs Replication, Class: Hunter

**Comment by MilkmanMHOC** [comment] 2023-07-13 01:52
Can this be looked at again?  My hunters are reporting that the great stamina is not giving more health to their pets.
