### ISSUE TITLE
🐛 [Bug Report] Wandering dead rabbits

### ISSUE THREAD

**Issue by katz1** [cmangos/issues#3711] opened 2024-05-12 15:33 UTC
### Bug Details

I have seen a lot of dead rabbits in Elwynn Forest that wander around.
Their body slides around the floor, see the video:

https://github.com/cmangos/issues/assets/18726138/aa92d2fd-35cc-4557-b141-5e0139babe4f

I don't think the rabbits are killed by wolves and keep wandering. I think they spawn like this, because I haven't seen a living rabbit yet.

### Steps to Reproduce

1. Make a human character
2. Find a rabbit near the start zone

### Core SHA1 Commit Hash

0e32ab652f9b44868bdadf99638002faca426c9d

### Database SHA1 Commit Hash

6885b120d8ef9338359ddf462239d8de27e679ee

### Operating System

Windows 10

### Client Version

1.12.1 (Classic)

**Comment by insunaa** [comment] 2024-05-12 15:44
duplicate of https://github.com/cmangos/issues/issues/3708

**Closed as not planned by insunaa** 2024-05-12 15:44 UTC
Labels: Info: Needs Replication
