### ISSUE TITLE
🐛 [Bug Report] server Crash from Spell Checkcast 

### ISSUE THREAD

**Issue by cbcs** [cmangos/issues#2926] opened 2022-04-24 03:42 UTC
### Bug Details

teleport to Instance if the ObjectSpawn and cast the spell .the server crash.

### Steps to Reproduce

just teleport to this local
 .go 89.4339 -279.589 91.4462 229

### Crash Log

Spell.app

m_trueCaster->GetZoneAndAreaId(zone, area);
GetTerrain -> m_currMap is Nullptr

### Core SHA1 Commit Hash

bb48d3144b3c603d307b3eada4ad893765422d24

### Database SHA1 Commit Hash

Last DB

### Operating System

Win10

### Client Version

1.1.12 (Classic)

**Comment by insunaa** [comment] 2022-07-23 08:42
This issue contains no actionable information.

Please update the issue to be more specific.

**Comment by evil-at-wow** [comment] 2023-07-30 20:55
The coordinates mentioned go to an egg in LBRS, so I'm going to guess this is a duplicate of #3267.

If it's not the same issue and you can still reproduce the issue with a recently updated server, please open a new issue _with proper details_ so we can investigate.

**Closed by evil-at-wow** 2023-07-30 20:55 UTC
Labels: Info: Needs Replication
