### ISSUE TITLE
tbc-db Error installing world database via ./InstallFullDB.sh

### ISSUE THREAD

**Issue by freeman00725** [cmangos/issues#1704] opened 2018-09-17 00:55 UTC
When I try to install the world database, it gets past processing the db, installing the updates, then gets to installing the dbc sql and crashes with an error.

  CORE UPDATE PROCESSED: 0
  CORE UPDATE FOUND BUT ALREADY IN DB: 47

> Trying to apply /c/CMaNGOS TBC/mangos-tbc/sql/base/dbc/original_data ...
    Appending DBC file update CMaNGOS to database tbcmangos
./InstallFullDB.sh: line 284: $f: ambiguous redirect
ERROR: cannot apply /c/CMaNGOS TBC/mangos-tbc/sql/base/dbc/original_data/DungeonEncounter.sql

**Comment by jimmybrancaccio** [comment] 2018-11-17 07:48
Closing this out as Cannot Reproduce. I've just fetched a fresh copy of tbc-db (cmangos/tbc-db@a231e74) today and run the installation script without error.

```
$ ./InstallFullDB.sh 

Welcome to the TBC-DB helper InstallFullDB.sh

ATTENTION: Your database tbcmangos will be reset to TBC-DB!
Please bring your repositories up-to-date!
Press CTRL+C to exit
...........
> Processing TBC database v1.7 'A New Hope' ...
  v1.7 'A New Hope' is applied!
[...]
You have now a clean and recent TBC-DB database loaded into tbcmangos
Enjoy using TBC-DB
```

If you're still experiencing any issues please don't hesitate to connect with us on Discord. We'd be happy to help.

**Closed by jimmybrancaccio** 2018-11-17 07:48 UTC
