### ISSUE TITLE
🐛 [Bug Report] [WoTLK] [Gomeregan] Matrix Punchograph 3005-B causes server to crash.

### ISSUE THREAD

**Issue by adellaci** [cmangos/issues#3388] opened 2023-04-30 13:03 UTC
### Bug Details

Enter Gnomeregan completed Matrix Punchograph 3005-A and got the Yellow Punch Card. Descended down to The Dormitory and accessed Matrix Punchograph 3005-B. As soon as i select 'Access Higher Level Card' the server crashes with this fault;
2023-04-30 12:45:35 ERROR:Attempt get value from nonexistent value field: 59 (count: 18) for object typeid: 5 type mask: 33

I have repeated it 3 times

### Steps to Reproduce

1. Enter Gomeregan
2. Access Matrix Punchograph 3005-A
3. Get Yellow Punch Card
4. Access Matrix Punchograph 3005-B
5. Select Access Higher Level Card
6. Server crash

### Expected behavior

Should receive Blue Punch Card without server crashing 

### Suggested Workaround

N/A

### Crash Log

2023-04-30 12:45:35 ERROR:Attempt get value from nonexistent value field: 59 (count: 18) for object typeid: 5 type mask: 33

### Core SHA1 Commit Hash

f7aec4af7c95914227d8fa7888379e5240e5c1fc

### Database SHA1 Commit Hash

39bcb0d0ac9ebb22e049973bf79e14aab9ade189

### Operating System

Ubuntu 20.04 LTS Server, Ubuntu 20.04 LTS Desktop Client

### Client Version

3.3.5a (Wrath of the Lich King)

**Comment by evil-at-wow** [comment] 2023-05-17 22:08
Allow me to close this as a duplicate of cmangos/issues#3314.

**Closed as completed by evil-at-wow** 2023-05-17 22:08 UTC
Labels: Info: Needs Replication
