### ISSUE TITLE
🐛 [Bug Report] Shadow Labyrinth Boss blackheart bug

### ISSUE THREAD

**Issue by yukozh** [cmangos/issues#2060] opened 2019-11-05 03:18 UTC
TBC 2.4.3

After the boss casted `INCITE_CHAOS`, the each party member will get the buff that they were controlled by boss, however, when the control expired, boss will stop combat and disappeared. The expected behavior should be the boss continue combat with party members.

**Comment by jimmybrancaccio** [comment] 2020-01-20 21:54
@yukozh Please provide **all** of the information quested in the bug report.

**Comment by cala** [comment] 2020-02-25 08:17
Thanks for this report.
However, closing as duplicate of https://github.com/cmangos/issues/issues/1908

**Closed by cala** 2020-02-25 08:17 UTC
Labels: Info: Incomplete Information, Info: Needs Replication
