### ISSUE TITLE
Shadow of Akama in the Dark Temple Cannot Be Killed Properly

### ISSUE THREAD

**Issue by yuanf225** [cmangos/issues#1814] opened 2018-12-28 09:49 UTC
Current behavior: akama NPCS cannot talk, akama shadow cannot attack
Expected behavior: akama NPCS talk normally, then akama's shadow walks up to akama and triggers the attack

Client version: 2.4.3 Client

Core Hash:

2d420a4c40ab47d5679959b0f1eba4a30f34b152

Database Hash:

1ad105e926393dd3bd2c632ee4ca4e6932028dcf

Database version: mariadb10.3.10
Operating system: Windows 10

**Comment by yuanf225** [comment] 2019-01-04 08:10
I don't know how to view the hash value, but I just update the DB and core, keep to the latest status, and then I recorded this BOSS video: https://youtu.be/on66Vhh5E-Y

**Comment by killerwife** [comment] 2019-01-04 17:49
Yes, I can confirm the script is in shambles. It will not be addressed soon, but my team is working on Black Temple.

**Comment by Muehe** [comment] 2019-01-07 15:02
@yuanf225 You can get the currently checked out commit hash of any git repo by opening a console at its location and entering `git rev-parse HEAD`. This will print one line containing the full hash.

**Comment by yuanf225** [comment] 2019-01-09 04:03
core:2d420a4c40ab47d5679959b0f1eba4a30f34b152
DB:1ad105e926393dd3bd2c632ee4ca4e6932028dcf

**Comment by yuanf225** [comment] 2019-01-09 04:05
@Muehe 
core：2d420a4c40ab47d5679959b0f1eba4a30f34b152
DB:1ad105e926393dd3bd2c632ee4ca4e6932028dcf

**Comment by Ve1vet** [comment] 2019-01-09 07:10
@killerwife the script is fully working. The only thing need to change is flag for Akama on channel pharse. Change UNIT_FLAG_NON_ATTACKABLE to UNIT_FLAG_DISABLE_HELP to not let raid heal Akama.
Everithing else is DB issues, not script.
I tried to find my fixes for DB, but they are gone :(

**Comment by Ve1vet** [comment] 2019-01-09 07:54
If any, I can dump all info related to Shade of Akama encounter from Database. NPC, Spells etc.
Shade of Akama encounter worked as it should.

**Comment by yuanf225** [comment] 2019-02-19 13:21
May I ask, when can this problem be fixed? @killerwife

**Comment by killerwife** [comment] 2019-02-19 14:20
No ETA. I am doing other things at the moment. If someone wants to submit a temporary patch go ahead.

**Comment by Zettoo** [comment] 2019-04-06 03:09
I have tried everything possible, I have changed the flags of both akama and the shadow of Akama, I have changed the faction of Akama, I have changed flags of the NPC's around and the same thing is happening: Akama can not be attack and the CHANNEL PHASE does not pass. It is a problem of the script that leaves it stagnant in that phase, also does not diminish the counter of the spell cast by the channelers on the Shadow of Akama.
If someone can help me or say that I have to change in the source code please I need to know:
- How to make Akama attackable, in which part of the source code is left stagnant in NON_ATTACKABLE.
- There are 6 channelers and a sorcerer, in total the counter of the spell on the Shadow of Akama reaches 7, How do I make that for each channeler that is eliminated that counter is reduced by 1 and when it reaches 0 the instance changes phase, the shadow comes close to Akama and start hitting? Thank you.

**Comment by 5man999** [comment] 2019-04-09 18:52
Without looking, which I will at some point. Maybe using Magtheridon as a reference would help.

**Comment by yuanf225** [comment] 2019-04-10 01:31
Looking forward to your repair

**Comment by 5man999** [comment] 2019-04-11 14:17
> Looking forward to your repair

**anxiety intensifies** Wheres the gods Killerwife or Warlockbugs when you need them ;)

**Comment by Yatzii93** [comment] 2019-04-18 00:40
Ok had a quick look - Seems 
https://github.com/Yatzii93/mangos-tbc/blob/master/src/game/AI/ScriptDevAI/scripts/outland/black_temple/boss_shade_of_akama.cpp#L618
Isn't triggering. 

Adding a breakpoint at     if (Creature* pAkama = m_pInstance->GetSingleCreatureFromStorage(NPC_AKAMA_SHADE)) - it hits.

  pAkama->AI()->KilledUnit(m_creature); - doesn not.

I suspect it's a problem with the if. Without some acknowlodgement that the channelers have died, it's not suprising that the script fails to progress concerning the Akuma shade.

**Comment by Yatzii93** [comment] 2019-04-18 02:01
https://github.com/Yatzii93/mangos-tbc/blob/master/src/game/AI/ScriptDevAI/scripts/outland/black_temple/black_temple.h#L25

Change to :
`     NPC_AKAMA_SHADE                 = 23191,`
Not sure why 22990 is there, no wonder nothing happened. 22990 is just a dummy akama that isn't in the instance, thus why that query fails. How did it end up like this? Why is there a random duplicate akama with no data and how did it end up in the script info. Very werid. 

All that needs to be done after this is to change the Akama (friendly version) flag so creatures can attack it. The script works perfect after that.

**Comment by MantisLord** [comment] 2019-04-18 02:14
Hopefully I can shed a little light. You are 100% correct - the current script references the wrong entry for Shade. 23191 is the correct one as you discovered. The reason it ended up like this is we're ahead on DB exports and behind on core exports.

So that means the spawn was already switched to 23191, but the C++ change to update the script and several other things in this encounter has yet to be applied.

It was my mistake to export the database change to fix the entry before the C++ changes were applied. We'll hopefully have this peculiar situation addressed soon when core changes are exported.

**Comment by Yatzii93** [comment] 2019-04-18 03:11
Gotcha, thanks for the info. Shame it wasn't picked up sooner.

**Comment by Yatzii93** [comment] 2019-04-18 04:09
I was wrong, it wasn't the case of making the boss attackable with flags. This is already handled in the script. It's the faction thats incompatible.

Faction 1812 works for me - UPDATE creature_template Set Faction = 1812 WHERE Entry = 23191;

**Comment by Zettoo** [comment] 2019-04-18 05:06
Thank you very much with your contributions, I will continue working with the following parts of the instance (it seems to me that illidan never attacks the players, I have to review it, but it has been an error when updating the database first and not changing the entries in c ++ also, I will review the entries of the constants in case it is the same problem, there are more instances with the same problem, if I manage to solve them all I comment the changes that I have been making

**Comment by Yatzii93** [comment] 2019-04-18 11:04
@MantisLord Could you perhaps shed some light on the other examples script inconsistencies with creature entries? Are we talking about just BT or could this be something affecting other raids?

**Comment by AnonXS** [comment] 2019-04-18 11:04
it was pretty much only akama

**Comment by Yatzii93** [comment] 2019-04-18 11:05
Ah ok cool. Thanks for the deets

**Comment by AnonXS** [comment] 2019-04-18 11:06
All other stuff like scripts and spells are currently only disfunctional due to missing relations exports from voa and or can be fixed up by adjusting some "unitflag" removals in cpp or by setting correct faction/unitflags to the npcs in db.

**Comment by Yatzii93** [comment] 2019-04-18 11:10
Are we talking about BT or just in general. I'm a bit of a nutcase in terms of how much time I spend on this project. For instance are a lot of the tier set bonuses that arent working just pending voa exports?

**Comment by AnonXS** [comment] 2019-04-18 11:14
we havnt fixed much item / class spell related stuff, so if you find that some setbonus/talents are nonfunctional, these are fixes that are welcome as we are currently only focusing on getting content out and subsystems rewritten so stuff can be properly fixed at some point.

Database up to and including T5 content is fully released in cmangos, Core commit related to T5 is probably only exported like 20%, T6 is missing nearly all updates from db and core in cmangos.
Only the Instance Files are nearly in complete Sync with cmangos as these are a well rounded feature we want to keep in Sync as much as possible with open source.

---

Fazit: Fixing Class Spell/Mechanics is a thing we dearly need support.

**Comment by Yatzii93** [comment] 2019-04-18 13:25
I understand, I guess it arguable whether a hack fix that is clearly contained to it's specific function is better than nothing for months or years. Maybe the best place to things that may be considered a hackfix is better contained in an issue.

**Comment by nullpointer010** [comment] 2019-04-18 22:35
I've been looking at the script code and @Yatzii93 is 100% right, the entry reference is wrong for Akama.
Also akama is not attackable, but the update isn't a solution because it is possible that he could be attacked by mobs before the encounter starts, so the solution is to add:
`m_creature->SetFactionTemporary(1868, TEMPFACTION_RESTORE_RESPAWN);`

In the line:
https://github.com/cmangos/mangos-tbc/blob/master/src/game/AI/ScriptDevAI/scripts/outland/black_temple/boss_shade_of_akama.cpp#L290
(The faction id need to be added in enums)

After adding that, the script work well the only thing is when Akama start to talk and spawn the Ashtongue Broken his faction don't change, so if you stay close they will start attacking you. 
So like Akama, the solution is simple, just add 
`pBroken->setFaction(1820);`
Before the line:  https://github.com/cmangos/mangos-tbc/blob/master/src/game/AI/ScriptDevAI/scripts/outland/black_temple/boss_shade_of_akama.cpp#L329 

But there is another problem, if you stay close to them when they are walking they will attack you. So a flag update is needed.
`UPDATE creature_template SET UnitFlags=33536, ExtraFlags=2048 WHERE Entry=23319;`

And with this little changes the script is fully working.

**Comment by Yatzii93** [comment] 2019-04-18 22:54
Love it, will give it a spin tomorrow.

**Comment by killerwife** [comment] 2022-01-28 21:05
Resolved since script got completely nuked and reworked.

**Closed by killerwife** 2022-01-28 21:05 UTC
Labels: Version: TBC (2.4.3), Info: Needs Testing, System: Creatures, Info: Needs Development
