### ISSUE TITLE
[TBC] Rogue Gouge

### ISSUE THREAD

**Issue by Mymaqn** [cmangos/issues#1094] opened 2016-09-19 05:26 UTC
**Current behavior**: 
Rogue's ability Gouge is only usable from behind

**Expected behavior**: 
Gouge should be usable only from the front

**Steps to reproduce**:

1. Create a rogue
2. Learn gouge
3. Stand in front of NPC and try to use it

**Client version**: 
2.4.3

**Commit hash**: 
?

**Database version**: 
TBCDB_1.5.0_cmangos-tbc
and update up until
s2331_01_mangos_event_linkedto

**Operating system**: 
Windows 10

NOTE: Currently haven't found a temporary fix for this
[//]: # (If this is a crash report, include the crashlog from a debug build with https://gist.github.com/)

**Comment by Phatcat** [comment] 2016-09-21 18:27
If you want to look into this yourself since you've shown such interest, I would recommend looking in spell::checkcast

**Comment by alanman** [comment] 2016-09-22 00:44
I can confirm that mine was working fine in s2330 running the same db.  I just updated last night, so I will test to see if it is broken now when I get home.

**Comment by alanman** [comment] 2016-09-22 02:30
Confirmed broken in s2332_01_mangos_more_spell_data.
 Game claims you are not in front of target when you are.  

![wowscrnshot_092116_200122](https://cloud.githubusercontent.com/assets/4338585/18734979/eec36710-8036-11e6-9153-22144e286e4a.jpg)

And confirmed Gouge works when behind target.
![wowscrnshot_092116_200908](https://cloud.githubusercontent.com/assets/4338585/18735100/6d28bcee-8038-11e6-8fae-01c915ed6f71.jpg)

**Comment by alanman** [comment] 2016-09-22 04:09
I think I found it!
in Object.cpp, line 1263, we're missing a '!'
We're checking to see if target is not looking at caster, but we have:
if (target->HasInArc(arc, this))
        return false;
...which looks to me like it says "If target has caster in line of sight, then target is NOT looking at caster"
Changing this line, adding ! to it:
if (!target->HasInArc(arc, this))
        return false;
...appears to resolve the issue. Attacking from the front, I attack successfully.  Attacking from the rear is denied.

**Comment by alanman** [comment] 2016-09-26 03:22
I'd like to close this and submit the fix in git, but I'm not permitted.  I'm sure I'm not going through the proper channels though.  I'm just overly excited because I feel like I'm finally contributing to the cause with my first bug fix, so I'm extra eager to see this issue get closed and implemented. ;)

**Comment by devmaximus** [comment] 2016-09-26 03:53
i think you are miss understanding these methods. your code change suggestion would break the purpose of these methods.

you are referring to code here:
https://github.com/cmangos/mangos-tbc/blob/master/src/game/Object.cpp#L1263

if you read the comments i added it should be clear the logic of this method:
` 
//the perspective is from the player to target
bool WorldObject::IsFacingTargetsFront(const WorldObject* target, float arc /*= M_PI_F*/) const
{
/
    if (!target)
        return false;
//in this case if the target is not facing us then we are NOT facing him for sure!
    //if target is not facing the current object then we know its not possible that the current object would be facing the targets front
    if (target->HasInArc(arc, this))
        return false;

// in this case if we are not facing the target that definitly we know that we cant hit him.
    //if current object is not facing the target then we know the current object is not facing the target at all
    if (!this->HasInArc(arc, target))
        return false;

    return true;
}
`


what you are experiencing is a server/client orientation out of sync situation. that requires more root issue investigation.

**Comment by Phatcat** [comment] 2016-09-26 09:49
No, Maximus, what you're pointing at is still a logical error.

think about it.

    //if target is not facing the current object then we know its not possible that the current object would be facing the targets front
    if (target->HasInArc(arc, this))
return false;

the comment is contradictory to what actually happens.

**Comment by Phatcat** [comment] 2016-09-26 09:52
It's also the opposite logic of what is done right beneath; https://github.com/cmangos/mangos-tbc/blob/master/src/game/Object.cpp#L1267

    //if current object is not facing the target then we know the current object is not facing the target at all
    if (!this->HasInArc(arc, target))
        return false;

**Comment by alanman** [comment] 2016-09-26 11:57
Yes it does look opposite, but isn't it supposed to be? In checking facing
target's front we need to confirm not only target is in our line of sight,
but to that we are in its line of sight as well. Currently it returns false
when target is looking at you. Pretty sure it's just a typo.

On Sep 26, 2016 3:52 AM, "Thorbjørn H.H. Sindrup" <notifications@github.com>
wrote:

>

> It's also the opposite logic of what is done right beneath;
https://github.com/cmangos/mangos-tbc/blob/master/src/game/Object.cpp#L1267
>
> //if current object is not facing the target then we know the current
object is not facing the target at all if (!this->HasInArc(arc, target))
return false;
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
<https://github.com/cmangos/issues/issues/1094#issuecomment-249527347>, or
mute the thread

**Comment by Phatcat** [comment] 2016-09-26 13:08
> Currently it returns false when target is looking at you. Pretty sure it's just a typo.

This is the logical error... I am agreeing with you. Maximus is the one saying you're wrong and that your change will break the logic, my comments is directed at him, not you.

**Comment by alanman** [comment] 2016-09-26 14:02
Yeah, I saw that. That was my direction as well. Sorry for the confusion. :)

**Comment by alanman** [comment] 2016-09-26 14:19
Ok I'm the one confused. But yes, we're in agreement. :)

**Comment by Phatcat** [comment] 2016-09-26 14:25
You should check in with me on IRC sometime, I can help you with the process of setting up a Pull Request.

**Comment by alanman** [comment] 2016-09-26 16:16
Ah, IRC. It's been a while since I've used that. Sure thing, thanks! Where
can I get server info for where to log in?

**Comment by devmaximus** [comment] 2016-09-26 16:17
@Phatcat  i went through numerous tests for this method. there is no logical issue here except that you are still misunderstanding the logic's purpose.

i used drawings before to explain this before to vegeancewow team but i guess i can bring it up here as well, so first scenario:

here we have target and caster facing each other... so both hasinarc will be true (assuming has in harc handle is 180 degrees which is default value. so IsFacingTargetsFront will be TRUE. 

![image](https://cloud.githubusercontent.com/assets/1082629/18842206/29a6a33e-83c9-11e6-8376-eb51b6bd00d0.png)

    //if target is not facing the current object then we know its not possible that the current object would be facing the targets front
    if (!target->HasInArc(this, arc)) <-- this will be skiped because hasinarc will return true
        return false;

    //if current object is not facing the target then we know the current object is not facing the target at all
    if (!this->HasInArc(target, arc)) <-- this will be skiped because hasinarc will return true
        return false; 

 this will indicate that isfacingtargetsfront is TRUE.

second scenario:

![image](https://cloud.githubusercontent.com/assets/1082629/18842441/df546996-83c9-11e6-8a5a-c6b7dfc6b8ba.png)


    //if target is not facing the current object then we know its not possible that the current object would be facing the targets front
    if (!target->HasInArc(this, arc)) <-- this condition will be MET because hasinarc will return false
        return false; <-- therefore will return false

    //if current object is not facing the target then we know the current object is not facing the target at all
    if (!this->HasInArc(target, arc)) <-- it will never reach this condition
        return false; 

 this will indicate that isfacingtargetsfront is FALSE.

**Comment by Phatcat** [comment] 2016-09-26 16:20
you are still not seeing it?

the code isn't
`if (!target->HasInArc(this, arc))`

its 

`if (target->HasInArc(this, arc))`

this is the whole issue....

**Comment by devmaximus** [comment] 2016-09-26 16:21
OHH LOL wait, i am looking at vengeancewow code. @killerwife didn't port it properly ^^.

**Closed** 2016-09-26 16:45 UTC

**Comment by Phatcat** [comment] 2016-09-27 13:42
> Ah, IRC. It's been a while since I've used that. Sure thing, thanks! Where
can I get server info for where to log in?

Didn't see that comment, sorry, we're on the Rizon network, channel name is 'cmangos'.

**Comment by devmaximus** [comment] 2016-09-27 16:22
@Phatcat this exposes issue with facing targets back now... the methods where in fact incorrectly flipped here.. yes this fixes the facing targets front... yet the back portion now is identical to the front logic :) we need to remove the ! from the back method.


the two methods should be like so:

	bool WorldObject::IsFacingTargetsBack(const WorldObject* target, float arc) const
	{
	    if (!target)
	        return false;

	    //if target is facing the current object then we know its not possible that the current object would be facing the targets back
	    if (target->HasInArc(this, arc))
	        return false;

	    //if current object is not facing the target then we know the current object is not facing the target at all
	    if (!this->HasInArc(target, arc))
	        return false;

	    return true;
	}

	bool WorldObject::IsFacingTargetsFront(const WorldObject* target, float arc) const
	{
	    if (!target)
	        return false;

	    //if target is not facing the current object then we know its not possible that the current object would be facing the targets front
	    if (!target->HasInArc(this, arc))
	        return false;

	    //if current object is not facing the target then we know the current object is not facing the target at all
	    if (!this->HasInArc(target, arc))
	        return false;

	    return true;
	}

**Comment by Phatcat** [comment] 2016-09-27 16:23
Ah, I see!
I will do that now.

**Comment by Phatcat** [comment] 2016-09-27 16:26
That is actually how it already looks at least in classic. checking tbc and wrath now.

**Comment by Phatcat** [comment] 2016-09-27 16:27
TBC and WotLK looking good as well already.

**Comment by devmaximus** [comment] 2016-09-27 16:54
great thanks
