### ISSUE TITLE
[WOTLK] Protection Paladin Talent Skills Not Working

### ISSUE THREAD

**Issue by Coldfriction** [cmangos/issues#1504] opened 2017-11-11 15:45 UTC
**Current behavior**: 
Casting Avenger's Shield does nothing.
Glyphing Avenger's Shield to hit only 1 target causes it to function as expected with the glyph.

Caster Hammer of Righteousness does nothing.

**Expected behavior**: 
Avenger's Shield should cast and hit primary target then bounce to secondary targets.
Hammer of Righteousness should cast and hit multiple targets.

**Steps to reproduce**:

1.   Spec into required talent skill as protection Paladin.
2.  Try to use Avenger's Shield or Hammer of Righteousness.

**Client version**: 
3.3.5a

**Commit hash**: 
CMaNGOS/0.18 (2017-11-07) 19:12:08 - 11a2123009c8e51fcef145b8e7573b747f0d3e10

**Database version**: 
WoTLKDB v1.1 'The Warsong' for CMaNGOS-WOTLK 13965
commit a3f2ecbe8f8ef558dd772456b1f1fd7768cedc76

**Operating system**: 
Windows 10 64 bit.

[//]: # (If this is a crash report, include the crashlog from a debug build with https://gist.github.com/)

**Comment by evil-at-wow** [comment] 2017-12-20 18:42
I can confirm that Avenger's Shield is currently broken in TBC as well (I tested with the latest code, which at the time of writing is https://github.com/cmangos/mangos-tbc/commit/f0d02ebca423a88c1659e6135ca5066b0fa46659 + https://github.com/cmangos/tbc-db/commit/bf3489cadacc7a136da1c9560486b3d8fb3f2448).

I have done some debugging with the TBC core, and it was apparently broken by @killerwife in https://github.com/cmangos/mangos-tbc/commit/238e3190b89c7956c3eda6088a4afd8c58eadf3f. Let me explain in some more detail what I think is going on.

The current problem starts in ``` void Spell::SetTargetMap(SpellEffectIndex effIndex, uint32 targetMode, UnitList& targetUnitMap)```. In at least TBC, Avenger's Shield has EffectImplicitTargetA = {6, 6, 0}, with 6 = TARGET_CHAIN_DAMAGE, so we get in this block of code:
```
...
case TARGET_CHAIN_DAMAGE:
{
    Unit* pUnitTarget = m_targets.getUnitTarget();

    if (!pUnitTarget)
        break;
    ...
    WorldObject* originalCaster = GetAffectiveCasterObject();
    ...
    UnitList tempTargetUnitMap;
    {
        MaNGOS::AnyAoEVisibleTargetUnitInObjectRangeCheck u_check(pUnitTarget, originalCaster, max_range);
        MaNGOS::UnitListSearcher<MaNGOS::AnyAoEVisibleTargetUnitInObjectRangeCheck> searcher(tempTargetUnitMap, u_check);
        Cell::VisitAllObjects(m_caster, searcher, max_range);
    }
    ...
}
...
```
The problem is that Cell::VisitAllObjects isn't adding anything, so we end up without targets for Avenger's Shield. It is worth noting that in this code pUnitTarget is the mob I'm targeting when casting Avenger's Shield, and originalCaster is me, the player.

After some more debugging, the reason why nothing gets added is in our check:
```
class AnyAoEVisibleTargetUnitInObjectRangeCheck
{
    public:
        AnyAoEVisibleTargetUnitInObjectRangeCheck(WorldObject const* obj, WorldObject const* originalCaster, float range)
            : i_obj(obj), i_originalCaster(originalCaster), i_range(range)
        {
            i_targetForUnit = i_originalCaster->isType(TYPEMASK_UNIT);
            i_targetForPlayer = (i_originalCaster->GetTypeId() == TYPEID_PLAYER);
        }

        bool operator()(Unit* u)
        {
            // Check contains checks for: live, non-selectable, non-attackable flags, flight check and GM check, ignore totems
            if (!i_obj->CanAttackSpell(u))  // this check used to be !u->isTargetableForAttack()
                return false;
            ...
        }
        ....
};
```
As you can see, i_obj is initialized with the first parameter of the constructor, which is the creature I was targeting. The Unit u passed to the check is another unit in the world - remember we're searching a part of the map for targets. In the current code, CanAttackSpell() typically returns false because the creature you are targeting is friendly with Unit u passed to the check, which is normal because these are typically similar creatures (for example a group of trash in an instance). When CanAttackSpell() above returns false, the check also immediately returns false, and eventually nothing gets selected.

Before killerwife's change I mentioned above, this first check was different (although perhaps not making more sense). This was the code for isTargetableForAttack() before it was removed:
```
bool Unit::isTargetableForAttack(bool inverseAlive) const
{ 
  if (GetTypeId() == TYPEID_PLAYER && ((Player*)this)->isGameMaster()) 
    return false;
  
  if (HasFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_NON_ATTACKABLE | UNIT_FLAG_NOT_SELECTABLE)) 
    return false; 
  
  // This check should be done only for players or players controlled creature 
  if (GetBeneficiaryPlayer() && HasFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_IMMUNE_TO_PLAYER)) 
    return false; 
  
  // inversealive is needed for some spells which need to be casted at dead targets (aoe) 
  if (isAlive() == inverseAlive) 
    return false; 
  
  return IsInWorld() && !hasUnitState(UNIT_STAT_FEIGN_DEATH) && !IsTaxiFlying(); 
}
```
When called with the Unit u, the result is typically true here: the creature is not a player, let alone a GM, a typical creature is selectable and attackable by players, etc. Basically merely being alive and in the world was almost enough to return true here, which then resulted in the first test in AnyAoEVisibleTargetUnitInObjectRangeCheck to be skipped, and the whole check became a matter of the rest of the tests (visible, in range, friendly/hostile etc), so the check returned true for some Unit u values and targets for Avenger's Shield were selected. Note that more gridnotifiers were changed, so it's possible that killerwife's change had other (unintentional) effects, although I'm not aware of any others yet.

We can of course bring the old code back - that "fixes" Avenger's Shield for me - but that doesn't sound like the best way to resolve this. But I'm not sure yet what a proper fix would be...

**Comment by killerwife** [comment] 2017-12-20 18:43
Dont worry about avengers shield. I have it handled. I just have an insane workload outside of wow atm.

**Comment by al3xc1985** [comment] 2020-03-07 06:50
It is fixed in tbc tgrough exports. I beliwve it ia fixed innwotlk 2 @killerwife  we can close it

**Comment by killerwife** [comment] 2022-02-22 13:08
Can confirm this is working perfectly fine now.

**Closed by killerwife** 2022-02-22 13:08 UTC
Labels: Version: WotLK (3.3.5), Info: Needs Development, Class: Paladin
