### ISSUE TITLE
".gobject near" crashes the Server

### ISSUE THREAD

**Issue by D3thw0lf** [cmangos/issues#1805] opened 2018-12-12 19:12 UTC
**Current behavior**: 
Crashes the Server if the given distance is higher than 1 and is not outputting a List with Gameobjects near the Character.

**Expected behavior**: 
Should output a List with guids (Gameobjects) near the player in a given distance (default = 10)

**Steps to reproduce**:

1. Login
2. Be a GM Rank 2 or higher
3. Use .gobject near (optional with 1-10 ex. .gobject near 1)

**Client version**: 
TBC 2.4.3 (8606)

**Commit hash**: 
290b39e53fbdad161dd3a6ec60fadcb2a11621a5

**Database version**: 
7acaa3054854b480b48df3baadb068eb3e099309

**Operating system**: 
Debian 9

**Additional Information:**
I'm using vmaps & mmaps and also set that all mmaps should load on server startup. I also do not unload the grids and I've set that the Pathfinder should normalize Z. I really don't know if any of this information is helpful for you but I guess it's good to know about the maps stuff ^^'

[//]: # (If this is a crash report, include the crashlog from a debug build with https://gist.github.com/)

**Comment by bdebaere** [comment] 2019-01-13 16:10
Couldn't reproduce on classic (Code 0c4900f5dd8388ce9b4124ee281e3693b133cdce, DB 6412c603a03b5d9b0e9d734e418ece4ce5cc7d49).

**Comment by AnonXS** [comment] 2019-01-28 08:50
can someone please check for tbc so we can close this?

**Comment by Phatcat** [comment] 2019-01-28 09:07
Can't reproduce, but I am not running my server under Debian, I am running it under Win10.

I can do all the .gobject near in the world without any issues, tried with

.gobject near
.gobject near 1
.gobject near 10
.gobject near 100

then I settled with being unable to reproduce, at least without any further conditions than the ones specified.

If you can still reproduce this @D3thw0lf , could you perhaps build and run the server in debug mode and provide the associated crash dump along with the issue?

**Comment by D3thw0lf** [comment] 2019-01-28 09:08
Re-tested on Core (d54c4e869f6e638deb9382853ea1945c4fd240fe) and DB (2f888027f01c1f149dc060f43c83d3e5bdb625db) same issue.

Also tried with and without translation in mangos_string but same behavior.

Console says:
`Delayed Zone Update: Client send invalid zoneId for X,Y & Map Coordinates. zoneId: 12 Expected 33, Coords: -14384.200195 389.851013 23.081900`

Weird is that I've teleported to an offline char and tried that command. After that the Server crashed. If you use .tele bootybay (which is where I've tested this, again) and use .gobject near there it seems like it at least do not crash. But the list is still empty so even without that crash it still is not working as expected. :3 

![image](https://user-images.githubusercontent.com/895448/51825164-79a11b00-22e4-11e9-9e80-6312b0494917.png)

I'll build in debug and try to get any crashlog for you guys. Thanks in advance for helping. ^w^

**Comment by D3thw0lf** [comment] 2019-01-28 09:40
Yip always starting with a clean cache. You can do ".go Playername" if they're offline but that worked since ages (as I remember right). 

I'm currently waiting for cmake to finish with the debug build and then I'll try to get as much data as possible that hopefully helps to resolve this darn issue. :)

**Comment by Levitanious** [comment] 2019-02-03 19:52
So, as it turns out -- the debug build stops the crashing in normal conditions, but will crash when a value above maximum described will be used?

**Comment by AnonXS** [comment] 2019-02-03 21:38
crashes related to text commands, appearing in normal build, not appearing in debug build, sounds familiar.

**Comment by Lankytim** [comment] 2019-02-09 07:35
I tested on my Debian 9 64bit system.  mangosd compiled with gcc.  Release build.

mangos-tbc 2508cbb76849b9a3501b2f0cbcd281edcf1b00c8
mangos-classic 45f9fb5afe5b58c18be191b197ea4822a1abd524

In both cases, I was not able to reproduce it.  I tried numerous `.gobject near` commands in the orc starting area - with and without the distance parameter, with and without any near objects returned.

**Comment by Baynar** [comment] 2019-02-14 09:18
I cannot reproduce this, but i can confirm i has happened to me quite a few times and that is not only with .gameobject near

Server will sometimes crash when: .gobject near / .gobject target / .gobject delete / . object spawn

If you want to reproduce this:
Go in-game spawn and depawn game objects untill the server crashes.

Note: Server might not crash if you do it really slow, but if your spawn and despawn object fast it will 100% crash.

**Comment by Phatcat** [comment] 2019-02-14 09:20
Would you happen to have a crashdump from one of thoe crashes you could make available?

**Comment by Levitanious** [comment] 2019-02-14 09:22
And @D3thw0lf should bring some of those too `:D` it would clear a lot of theories out there.

**Comment by Baynar** [comment] 2019-02-14 09:24
> Would you happen to have a crashdump from one of thoe crashes you could make available?

I will see if i have not deleted them once i get home.

**Comment by ulfgebhardt** [comment] 2019-02-14 12:35
If this is related to `.gobject add` - back in 2017 there was a Problem with an mysql index pointer.

1. Spawn many object
2. Exhaust mysql insert index (~100 objects back then)
3. no more inserts/core crash etc

I am not sure this is related to this issue - or even still happening - but might be worthwhile inspecting.
Runtime spawned Objects might use the same pointer.

Maybe create an NPC which spawns objects with an AI script to test this.

**Comment by al3xc1985** [comment] 2020-03-19 20:30
@killerwife this crash report is not replicable...I believe it can be closed

**Comment by diluh** [comment] 2021-03-16 18:55
The same problem happened on my server, not only `.gob near` close in a few moments `.gob add`  also makes Crash

**Comment by killerwife** [comment] 2022-01-28 19:39
Should be resolved now.

**Closed by killerwife** 2022-01-28 19:39 UTC
Labels: Version: TBC (2.4.3), Info: Needs Replication, Type: Client / Core Crash
