### ISSUE TITLE
Classic - rouge abillity "sprint"

### ISSUE THREAD

**Issue by Primus11** [cmangos/issues#891] opened 2016-04-11 09:27 UTC
The rouge class spell "sprint"  don´t increase the speed (sound and cooldown work).

(spell id for rank3: 11305)

**Client version**:  1.21.1

**Database version**:   11/4/16 classicdb  (https://github.com/classicdb/database)
                                     11/4/16 Cmangos + Scripdev2 + Acid 

**Operating system**:  Windows 10

**Comment by cala** [comment] 2016-04-16 09:40
Thank you for your report. Actually, I think that this is the Improve Sprint ability that is broken, not the Sprint itself.
Could you check that without Improve Sprint, the rogue sprint properly, please ?

**Comment by Primus11** [comment] 2016-04-16 15:40
Thank you for contributing/developing this nice classic project!
Yes you´re right. After i´ve reseted the talents, the basic sprint abillity works fine.
So the problem is due to the talent skill.

**Comment by TarasHots** [comment] 2016-04-17 11:17
Confirmed this with 'Improved Sprint' as well. Morover, there is probably another bug with only '1/2 Improved Sprint'. Currently we have support for 30918 spell, but seems that we don't distinguish 1/2 and 2/2 cases

1/2 is spell 13743
and
2/2 is 13875

**Comment by cala** [comment] 2016-04-18 09:21
Thanks for confirming this. As I thought, this issue is a duplicate of: https://github.com/cmangos/mangos-classic/pull/31 so I'm closing this one. Thank you.

**Closed by cala** 2016-04-18 09:21 UTC
