### ISSUE TITLE
🐛 [Bug Report] SendNextWayPointPath() crash on empty m_currentWaypointNode

### ISSUE THREAD

**Issue by Valkirie** [cmangos/issues#2289] opened 2020-10-10 16:23 UTC
## 🐛 Bugreport
Server will crash when SendNextWayPointPath() is called with a null m_currentWaypointNode (???).

### Expected behavior
Get nextNode value and keep up.

### Version & Environment

- Client Version: "2.4.3" (TBC)
- CMaNGOS Repo & Commit Hash: https://github.com/cmangos/mangos-tbc/tree/27c44a2c57f0a0a6ca873995b30093a6da8429c6
- Database Repo & Commit Hash: https://github.com/cmangos/tbc-db/tree/4c839e5d5ec5791aa26e9030dd3ce676cd0d88dc
- Operating System: Windows 10

### Steps to reproduce
1. Return quest https://www.wowhead.com/quest=9180/journey-to-undercity.
2. Wait for crash after Highborns (21628) are summoned.

### Crashlog
```
 	std::_Tree_const_iterator<std::_Tree_val<std::_Tree_simple_types<std::pair<unsigned int const ,WaypointNode>>>>::operator*() Ligne 181	C++
 	std::_Tree_const_iterator<std::_Tree_val<std::_Tree_simple_types<std::pair<unsigned int const ,WaypointNode>>>>::operator->() Ligne 189	C++
>	WaypointMovementGenerator<Creature>::SendNextWayPointPath(Creature & creature) Ligne 399	C++
 	WaypointMovementGenerator<Creature>::Reset(Creature & creature) Ligne 156	C++
 	MovementGeneratorMedium<Creature,WaypointMovementGenerator<Creature>>::Reset(Unit & u) Ligne 90	C++
 	MotionMaster::DirectExpire(bool reset) Ligne 199	C++
```

**Comment by AnonXS** [comment] 2020-10-10 20:30
```
.quest add 9180
.go c id 10181
```

**Comment by Grz3s** [comment] 2020-10-10 20:44
all you need is to backport wotlk fixes for path = 0 .. and errors like this will disapear

**Comment by AnonXS** [comment] 2020-10-10 20:53
so it didnt crash for me, he says its crashing for him, should be investigated then.

**Comment by Valkirie** [comment] 2020-10-11 07:12
> all you need is to backport wotlk fixes for path = 0 .. and errors like this will disapear
> [2855]
> [2856] for this one - [cmangos/wotlk-db@85aa46f](https://github.com/cmangos/wotlk-db/commit/85aa46fad40afbe4d3a4b5bf661c009b7459934e)

This:
`UPDATE creature_template SET MovementType = 0 WHERE entry = 21628;`
Plus:
`summon->GetMotionMaster()->MovePoint(1, fX, fY, fZ + 5.0f);`

Fixed it.

**Comment by Lillecarl** [comment] 2020-10-26 14:14
"Duplicate" of #2244 (Same crash)

**Comment by jimmybrancaccio** [comment] 2020-11-16 00:43
Closing as duplicate of #2244.

**Closed by jimmybrancaccio** 2020-11-16 00:43 UTC
Labels: Info: Needs Replication, System: Miscellaneous, Type: Core Crash, Version: TBC
