### ISSUE TITLE
Q974 Finding the Source autocomplete

### ISSUE THREAD

**Issue by bdebaere** [cmangos/issues#1405] opened 2017-06-21 18:53 UTC
**Current behavior**: 
This could be a broader issue than just this one quest. Maybe to do with the message that is sent from the server. When accepting quest 974 it is marked as completed in the quest log. Handing it in however is not possible. Relogging fixes this issue.
**Expected behavior**: 
Accepting the quest 974 the objective should not be marked as completed.
**Steps to reproduce**:

1. .quest add 974
2. Open quest log
3. See objective completed

**Client version**: 
1.12.1
**Commit hash**: 

**Database version**: 
Classic DB version 1.8.5 "Below Blackrock Mountain". For core Classic z2697.
**Operating system**: 
Windows 10

[//]: # (If this is a crash report, include the crashlog from a debug build with https://gist.github.com/)

**Comment by hlarsen** [comment] 2017-06-28 06:24
this appears to be caused by Player::SendQuestUpdateAddItem() calling SetQuestSlotCounter() - commenting out that call has the quest properly added and can be completed. not sure of the overall effects of that, though...

looking at some other projects i see Player::SendQuestUpdateAddCreatureOrGo( ) calling SetQuestSlotCounter(), but not SendQuestUpdateAddItem() as it is here.

@Warlockbugs thoughts? looks like you were the one who added the SetQuestSlotCounter() calls.

**Comment by Warlockbugs** [comment] 2017-06-28 12:47
The issue that was closed with this change is: https://github.com/cmangos/issues/issues/1244

Currently quest counters for some reason use 6 bit unsigned integer portions of single 32bit field and share same field as quest status. This is a very old change (https://github.com/cmangos/mangos-classic/commit/80523937f47972c234c42149f58b28a155aebc1b#diff-017f80bef23acf4b9632d91e43180252R1145) and i was not able to find out what really is going on with this field client-side myself, so I don't have a middle ground solution for this yet. I am keeping my eyes on  this and other side effects caused by it.

**Comment by cala** [comment] 2018-04-17 10:00
I tried right now to pick that quest and: it did not autocomplete and was completable as expected.

Could you please retry it? As this issue seems to be related to client and as I have a Mac client, it is possible that I can't have that issue. So let's be sure of it.

**Comment by killerwife** [comment] 2018-04-17 10:11
@cala I know the reason. Give me 5 min to confirm.

**Comment by killerwife** [comment] 2018-04-17 10:17
We have following quest_template columns. ReqItemId1-4, ReqCreatureOrGOId1-4. In client these columns are not separate. They are exclusive. There are 4 fields, which house both reqitem and reqcreature. Which means in quest_template Id1 should never be set for both ReqItem and ReqCreature.

This means fix should be along the lines of:
UPDATE quest_template SET ReqCreatureId2=ReqCreatureId1, ReqCreatureId1=0, (same for count) WHERE Id IN(945);

But it gets trickier. 95% of the time where I encountered this issue, ReqItemId1 was completely wrong based on sniffs or research on the web. For some reason the devs back in the day added the items which were received as item on accepting quest to this field. My theory is so that the q item is taken from them on completing quest. But this is also complicated, because from several quests one has to manually remove quest item from inventory when quest ends, be it by blizz bug or fluke in design, I don't know at this moment.

As a result the fix most likely is(I dont have this q sniffed, so i dont know for sure):
UPDATE quest_template SET ReqItemId1=0, ReqItemCount1=0 WHERE Id IN(945);

Hopefully this explanation is sufficient, @Grz3s already knew about this, so did @MantisLord and the rest of my team.

**Comment by cala** [comment] 2018-04-17 11:09
> This means fix should be along the lines of:
UPDATE quest_template SET ReqCreatureId2=ReqCreatureId1, ReqCreatureId1=0, (same for count) WHERE Id IN(945);

Then this is already fixed in Classic DB and we can close this issue. Thanks.

**Closed by cala** 2018-04-17 11:09 UTC

**Comment by Grz3s** [comment] 2018-04-17 18:41
@cala @killerwife ... sory for offtopic... but i know how difficult was to fix this quest back in the day...
Because of the same object id ..we never coud make it work correctly... so every object used was giving credit (check if it still does on Classic or TBC) ... 
I made fix using cyberiums search for pool... and it does its job here...
Only top object will give credit...
more info here:
https://github.com/cmangos/wotlk-db/commit/f5cd21dcc40e9567d89b700092a12e536bcaa489
