### ISSUE TITLE
🐛 [Bug Report] Gnomergan - Yellow Punch card crash

### ISSUE THREAD

**Issue by rfox33837** [cmangos/issues#3507] opened 2023-07-30 04:15 UTC
### Bug Details

When submitting a yellow punch card: https://www.wowhead.com/classic/item=9280/yellow-punch-card

to the Matrix Punchograph 3005-B: https://www.wowhead.com/classic/object=142475/matrix-punchograph-3005-b

The server crashes.

### Steps to Reproduce

1. .additem 9280 1
2. go to the object: 142475
3. Interact and submit the punch card
4. Crash

### Expected behavior

Should punch the card

### Suggested Workaround

None that I know of.

### Core SHA1 Commit Hash

989f52c90686662d824453d36b0d3ce7093f21cf

### Database SHA1 Commit Hash

e73a057823da24cb854be01a70b64eb7b7a6b6b8

### Operating System

Windows 11 Pro

### Client Version

3.3.5a (Wrath of the Lich King)

**Comment by insunaa** [comment] 2023-07-30 05:45
Duplicate of https://github.com/cmangos/issues/issues/3507

**Closed as not planned by insunaa** 2023-07-30 05:45 UTC
Labels: Info: Needs Replication

**Comment by celguar** [comment] 2023-07-30 06:34
but this is #3507

**Comment by AnonXS** [comment] 2023-07-30 13:52
https://github.com/cmangos/issues/issues/3314
