### ISSUE TITLE
[Cata] No NPCs or Creatures with UDB-4.3.4

### ISSUE THREAD

**Issue by RHOPKINS13** [cmangos/issues#628] opened 2015-03-11 21:47 UTC
Took a fresh build and loaded UDB-4.3.4. When I login I can't see any creatures or NPCs. Log files below.

DBErrors.log: https://www.dropbox.com/s/dlrgl9y505gz29h/DBErrors.log?dl=1
SD2Errors.log: https://www.dropbox.com/s/nn00vafpbghvwzw/SD2Errors.log?dl=1
Server.log: https://www.dropbox.com/s/infavae17i0vw9d/Server.log?dl=1

**Comment by xfurry** [comment] 2015-03-12 17:11
Well, the problem is that I'm not sure if UDB 434 is still developed.
Poke @X-Savior for this.

**Comment by Ulduar** [comment] 2015-03-13 22:38
/Summon @X-Savior.
JustSummonedCollaborato(pCollaborator)
SendAIEvent(pCollaborator)
XD

**Comment by jimmybrancaccio** [comment] 2018-11-24 00:14
Closing this out as it appears to be an issue with UDB and not CMaNGOS. Please create a new issue if you're still experiencing any problems. Thanks.

**Closed by jimmybrancaccio** 2018-11-24 00:14 UTC
