### ISSUE TITLE
🐛 [Bug Report] (TBC) Hunter Pets not gaining loyalty levels when their level is equal to the hunters

### ISSUE THREAD

**Issue by Patrick-Barry** [cmangos/issues#2444] opened 2021-04-01 06:43 UTC
## 🐛 Bugreport
Hunter's pets will not gain loyalty when they have the same level as the hunter. This means max level hunters that tame new pets will never get loyal pets.

### Expected behavior
Hunter pets should gain loyalty even when the same level as the hunter.

### Version & Environment

Client Version: 2.4.3 TBC
CMaNGOS Repo & Commit Hash:  TBC  8853d361c64445e6c67fc04e253d30dd4f128003
Database Repo & Commit Hash:  TBC  8af8ce15f60fb7b68a3d98d49cd49ff7f1cd5263

Operating System:  Windows 10

### Steps to reproduce
1. Take a level 70 hunter.
2. Tame a new Pet.
3. Gain the required combat xp the pet requires as well as the time needed having the pet out for each loyalty level.
4. Pet never reaches next loyalty level.
5. Profit

Looking through the source code I think I identified the issue.   In Pet.cpp in the function  void Pet::GivePetXP(uint32 xp)  (Line 1106)   The code checks to see if the pet is the same level as the hunter or higher before awarding it any xp. If it is it returns from the function. This is correct. However the amount of xp needed to reach the next loyalty level is updated at the end of the function so if this condition is ever true the pet will never get its loyalty value updated.

**Comment by MilkmanMHOC** [comment] 2021-04-01 14:16
Just a comment, i had a report of "pets disappearing" by the only hunter on the new classic server updated last week.  Is this issue present in all the versions? Im thinking this is likely the cause of their lost pet?

**Comment by insunaa** [comment] 2021-04-01 20:13
How do you mean "disappear"? Do you mean the regular "running away" pets do when they don't get fed etc.?

**Comment by MilkmanMHOC** [comment] 2021-04-01 20:29
I wish i had better information to share.  The pet(s) were following them around town and then they were gone.  Happened multiple times im told.  I checked the pet table and they were not in there.  No DB errors or log errors related that i could see.  It just was reported to me last night, didn't know what to make of it then saw the above report.  My thoughts were perhaps they were getting the pet, but were unable to get any loyalty so while running around the pet left on its own and they didn't know what happened. User is also new to the game, so no understanding or experience with how it should work.   Hence my question if this code applys to classic-core as well because it would be a logical explanation for the problem reported to me.  If they are lvl 11 and getting their first lvl 11 pet they would with the above issue also not gain in loyalty and likely to loose said pet because of it i would think.  I hate to assume when troubleshooting but seems too coincidental of timing to not be possibly related.

**Comment by al3xc1985** [comment] 2021-04-07 20:03
It might happend if pet is loyality 0

**Comment by cyberium** [comment] 2021-04-07 20:05
Should be fixed by https://github.com/cmangos/mangos-tbc/commit/74e1f760faa91fadfb15fa19ba76f21d60e10c89

Sorry forgot to close this.

**Closed by cyberium** 2021-04-07 20:05 UTC
Labels: Info: Needs Replication
