### ISSUE TITLE
Classic: Quest: The Last Barov

### ISSUE THREAD

**Issue by Kelzior** [cmangos/issues#604] opened 2015-02-12 18:06 UTC
Core: Lastest
http://db.vanillagaming.org/?quest=5344

as killing the NpC assigned has not yielded the expected results, specifically
acquiring the Quest Item, his head of course can't even slit a throat properly...

**Comment by TarasHots** [comment] 2016-05-09 15:21
Not sure if still needed, but [cannot reproduce anymore](https://imgur.com/a/85tJ4)

**Comment by cala** [comment] 2016-05-09 15:47
I sucessfully did this quest a month or two ago. So, I will close this issue soon unless someone still has the issue.

**Comment by Phatcat** [comment] 2016-09-23 21:07
since it's been several months and no news on this I'm gonna go ahead and do it for you, cala =)

**Closed by Phatcat** 2016-09-23 21:07 UTC
