### ISSUE TITLE
🐛 [Bug Report] Eating Animation isnt showing

### ISSUE THREAD

**Issue by banehammer** [cmangos/issues#2503] opened 2021-07-25 13:25 UTC
## 🐛 Bugreport

The Eating animation wont show. Drinking animation is showing fine though.

### Expected behavior

You should see your character eating :)

### Version & Environment

Client Version: 3.3.5a WOTLK

CMaNGOS Repo & Commit Hash: 

https://github.com/cmangos/mangos-wotlk/commit/bb422625030607ad39bc3ed2b528f400d93de246

Database Repo & Commit Hash: 

https://github.com/cmangos/wotlk-db/commit/0a84eadcd5f14a1bf211ed44c0f821cf97b5aebc

Operating System: 

### Steps to reproduce
1. Buy Eat Stuff
2. Eat
3. You wont see the character eating
4. ...
5. Profit

### Crashlog

- None

**Comment by banehammer** [comment] 2021-07-25 13:29
Tried to find a way of fixing it myself but I cant. I am way too dumb :)

**Comment by MantisLord** [comment] 2021-07-25 18:34
Duplicate of https://github.com/cmangos/issues/issues/2253

**Closed by MantisLord** 2021-07-25 18:34 UTC
Labels: Info: Needs Replication
