### ISSUE TITLE
Classic latest verision Core Crash

### ISSUE THREAD

**Issue by kuramajssken001** [cmangos/issues#974] opened 2016-06-23 12:13 UTC
**Current behavior**: 
Revision: 2016-06-22 14:08:26 ad250a3bcba14c8461da0411b9b76125f0d5f36d
Date 23:6:2016. Time 20:4 
//=====================================================
*** Hardware ***
Processor: Intel(R) Xeon(R) CPU           E5530  @ 2.40GHz
Number Of Processors: 16
Physical Memory: 8379176 KB (Available: 5235400 KB)
Commit Charge Limit: 16756492 KB

*** Operation System ***
Windows 7 Service Pack 1 (Version 6.1, Build 7601)

//=====================================================
Exception code: C0000005 ACCESS_VIOLATION
Fault address:  000000014027F969 01:000000000027E969 D:\Server\mangosd.exe

(...)

https://gist.github.com/Phatcat/3aba59e4068a01157bac68b776d4e0d3

**Comment by Lillecarl** [comment] 2016-06-23 13:08
Please use https://gist.github.com for posting such data.

**Comment by Phatcat** [comment] 2016-06-23 13:42
Thank you for your crash report, I hope you don't mind that I cleaned it a bit.

Could you please provide the details on what you were doing on this server if you were in game when this crash happened, if anything at all?

**Comment by Phatcat** [comment] 2016-06-26 16:25
@kuramajssken001

We are going to need the steps here you used to produce this crash or we will not be able to help you since you did not provide a debug crash log..

**Comment by Phatcat** [comment] 2016-08-11 03:57
Cannot reproduce this with nothing to go by so going to have to close this as you are not responding.

**Closed by Phatcat** 2016-08-11 03:57 UTC

**Comment by kuramajssken001** [comment] 2016-08-11 05:57
thanks phatcat

**Comment by Phatcat** [comment] 2016-08-11 06:03
@kuramajssken001 

> Could you please provide the details on what you were doing on this server if you were in game when this crash happened, if anything at all?

few days later

> We are going to need the steps here you used to produce this crash or we will not be able to help you since you did not provide a debug crash log..

That was almost 2 months ago now...

So I close it and now you answer; not with any details as requested, but with sarcasm. Don't care. Do proper issue reporting next time.

**Comment by kuramajssken001** [comment] 2016-08-11 13:15
@Phatcat

**Comment by Phatcat** [comment] 2016-08-11 13:21
Sounds like you at least aint still struggling with it.

Sorry for my reaction towards you.
