### ISSUE TITLE
🐛 [Bug Report] Hyjal Server Crash before Lady Proudmoore Teleport

### ISSUE THREAD

**Issue by buenodart** [cmangos/issues#2244] opened 2020-08-18 00:13 UTC
## 🐛 Bugreport

In Hyjal, after the second boss, Anetheron, We talk to Jaina... (gossip menu: "Until we meet again, Lady Proudmooore")
When she starts to walk the server Crash

### Expected behavior

Teleport everyone after gossip -> profit.

### Version & Environment

Client Version: "2.4.3" (TBC)

CMaNGOS Repo & Commit Hash: [TBC](https://github.com/cmangos/mangos-tbc/tree/6edb858f19c8c8c4de6fd15a37867b5bb44e7239)

Database Repo & Commit Hash: [TBC](https://github.com/cmangos/tbc-db/tree/d579c2b1e20aaaff3b7135916aea988dd18ef4a4)

Operating System: Ubuntu 18.04.4 LTS

### Steps to reproduce
1. Get any character (GM or Normal char with party)
2. Go to Hyjal
3. Start Wave one, Kill Boss Rage Winterchill.
4. Start Wave two, Kill Boss Anetheron.
4. Talk to Lady Proudmore
5. Server Crash

### Crashlog

WaypointMovementGenerator::LoadPath: Creature (Entry: 17906 Guid: 9000569) doesn't have waypoint path 0
void WaypointMovementGenerator<Creature>::InitializeWaypointPath> unable to intialize path for Creature (Entry: 17906 Guid: 9000569)
WaypointMovementGenerator::LoadPath: Creature (Entry: 17906 Guid: 9000570) doesn't have waypoint path 0
void WaypointMovementGenerator<Creature>::InitializeWaypointPath> unable to intialize path for Creature (Entry: 17906 Guid: 9000570)
WaypointMovementGenerator::LoadPath: Creature (Entry: 17906 Guid: 9000571) doesn't have waypoint path 0
void WaypointMovementGenerator<Creature>::InitializeWaypointPath> unable to intialize path for Creature (Entry: 17906 Guid: 9000571)
WaypointMovementGenerator::LoadPath: Creature (Entry: 17906 Guid: 9000572) doesn't have waypoint path 0
void WaypointMovementGenerator<Creature>::InitializeWaypointPath> unable to intialize path for Creature (Entry: 17906 Guid: 9000572)
WaypointMovementGenerator::LoadPath: Creature (Entry: 17906 Guid: 9000573) doesn't have waypoint path 0
void WaypointMovementGenerator<Creature>::InitializeWaypointPath> unable to intialize path for Creature (Entry: 17906 Guid: 9000573)
WaypointMovementGenerator::LoadPath: Creature (Entry: 17906 Guid: 9000574) doesn't have waypoint path 0
void WaypointMovementGenerator<Creature>::InitializeWaypointPath> unable to intialize path for Creature (Entry: 17906 Guid: 9000574)
WaypointMovementGenerator::LoadPath: Creature (Entry: 17906 Guid: 9000575) doesn't have waypoint path 0
void WaypointMovementGenerator<Creature>::InitializeWaypointPath> unable to intialize path for Creature (Entry: 17906 Guid: 9000575)
Segmentation fault (core dumped)

**Comment by Lillecarl** [comment] 2020-10-25 18:58
https://github.com/cmangos/mangos-tbc/blob/master/src/game/MotionGenerators/WaypointMovementGenerator.cpp#L425

Nextnode values seem to be null in the Lady Jaina case.

**Comment by killerwife** [comment] 2020-10-25 19:14
@AnonXS check tbc db data for her versus voa, including SD2 path

**Comment by Lillecarl** [comment] 2020-10-25 19:46
https://gist.github.com/Lillecarl/d3a87485ff326407a4e1e967f8e0379b Here's a backtrace, actually a segfault.

**Comment by Lillecarl** [comment] 2020-10-25 20:40
Reverting https://github.com/cmangos/mangos-tbc/commit/339d950cb454978aac7d1582e85a0ed8969dde5e#diff-40c4e9f120f1176f9f84d7f1ffe4a6dd77dd5f0b21ab22dbe73fe9ba2bcf29bc fixes the crash.

There's still the invalid waypoint stuff in the console though.
```
WaypointMovementGenerator::LoadPath: Creature (Entry: 17906 Guid: 9000534) doesn't have waypoint path 0
WaypointMovementGenerator::LoadPath: Creature (Entry: 17906 Guid: 9000535) doesn't have waypoint path 0
WaypointMovementGenerator::LoadPath: Creature (Entry: 17906 Guid: 9000536) doesn't have waypoint path 0
WaypointMovementGenerator::LoadPath: Creature (Entry: 17906 Guid: 9000537) doesn't have waypoint path 0
WaypointMovementGenerator::LoadPath: Creature (Entry: 17906 Guid: 9000538) doesn't have waypoint path 0
WaypointMovementGenerator::LoadPath: Creature (Entry: 17906 Guid: 9000539) doesn't have waypoint path 0
WaypointMovementGenerator::LoadPath: Creature (Entry: 17906 Guid: 9000540) doesn't have waypoint path 0
```

**Comment by Lillecarl** [comment] 2020-10-26 14:11
@killerwife I can vouch for this being an easy reproduce:
1. .gm on
2. .tele summit
3. walk into instance
4. walk into instance on the left
5. talk to Lady Jaina
6. Select bottom gossip option
7. She'll walk to the first waypoint (That's added by scriptdev I assume), once she reaches that waypoint she crashes the server.

@cyberium Care to take a look at this regression? It's related to your WP improvements from this summer somehow. I looked at it last night and wasn't able to figure it out yet.

**Comment by Lillecarl** [comment] 2020-10-26 14:51
https://github.com/cmangos/mangos-tbc/pull/403 Fixes this issue

**Comment by jimmybrancaccio** [comment] 2020-11-16 00:29
This is a duplicate of #2230. This looks like we can close this issue out and the other one, may you confirm @Lillecarl?

**Comment by Lillecarl** [comment] 2020-11-16 07:26
Fixed in https://github.com/cmangos/mangos-tbc/commit/b373ab9b3848bb832e3eb91d344fa84e3bead906

**Closed** 2020-11-16 11:48 UTC
Labels: Info: Needs Feedback, Info: Needs Replication, System: NPC, Version: TBC
