### ISSUE TITLE
Shaman Totems - Don't Ignore Hunter Traps

### ISSUE THREAD

**Issue by Alexej21** [cmangos/issues#1817] opened 2018-12-30 13:38 UTC
**Current behavior**: 
it's same as on mangosone
https://www.getmangos.eu/bug-tracker/mangos-one/shaman-totems-r1435/
**Expected behavior**: 
Shaman Totems will ignoring Hunter Traps

**Comment by killerwife** [comment] 2018-12-31 21:59
I can chime in on adding more info. Basically AOE ignores totems by default. We have a grid searcher for trap GOs in place which does not do all the check the spell targeting does. The fix here is to unify both systems. Thats the theory, I myself do not have time for it atm.

**Comment by ulfgebhardt** [comment] 2019-01-01 12:31
Totems have one really big problem. How ?  When I place Trap and in Trap radius I place Totem , Totem disappear Trap and got immune. I think Traps have some specific Area of Effect Immunity. Why ? Because when i use some other Area of Effect for example Volley, Totem dont got immune and isnt destroyed. For correct functionality ,Totems must have specific Area of Effect Immunity vs Traps.

1. Trap dissapeared with totem.
![image](https://user-images.githubusercontent.com/1238238/50572855-712ef080-0dc9-11e9-9207-4fdaf4ab7084.png)

2. Totem ignore Volley(Area of Effect)
![image](https://user-images.githubusercontent.com/1238238/50572858-79872b80-0dc9-11e9-86f2-fdc7c2e28c13.png)

This is just a copy of the Bugreport found [here](https://www.getmangos.eu/bug-tracker/mangos-one/shaman-totems-r1435/)

**Comment by Alex2162** [comment] 2019-01-11 02:08
**Current behavior**:  Hunter Traps are taken by Shaman Totems. When i place hunter trap ,like Freezing Trap near shaman totem ,like Tremor Totem then Trap disappear and its says Immune.

**Expected behavior**: Hunter Traps will be ignored by Shaman Totems.

**Steps to reproduce**:
1.  Shaman spawn totem like Tremor Totem.
2.  Hunter spawn trap like Freezing Trap in their proc radius, near totem or on place where is          
    Tremor Totem.
3. Freezing Trap disappear when is in contact with Tremor Totem and totem says immune.

**Client version**: 
2.4.x

**Operating system**: 
Windows 8.1 x64

**Comment by al3xc1985** [comment] 2020-02-28 05:35
@killerwife this can be closed as I remember

**Comment by al3xc1985** [comment] 2020-03-07 07:11
@killerwife we can close it

**Closed** 2020-03-07 10:31 UTC
Labels: Info: Needs Replication, System: Spells
