### ISSUE TITLE
[Classic] Archmage Arugal evades

### ISSUE THREAD

**Issue by bdebaere** [cmangos/issues#1712] opened 2018-09-29 19:50 UTC
**Current behavior**: 
Archmage Arugal evades all the time when switching to the other balcony. It's impossible to kill him like this.

**Expected behavior**: 
You can kill Archmage Arugal.

**Steps to reproduce**:

1. .go creature 16255.
2. Kill him slowly.
3. Watch as he teleports you can no longer attack him, every attack evades.

**Client version**: 
1.12.1
**Commit hash**: 
Latest
**Database version**: 
Latest
**Operating system**: 
Win10

[//]: # (If this is a crash report, include the crashlog from a debug build with https://gist.github.com/)

**Comment by cala** [comment] 2019-03-26 16:08
Hi,

Evade was changed some months ago since your report. Could take some time to test it again and confirm the issue still exists, please?

**Comment by bdebaere** [comment] 2019-03-26 18:13
@cala It looked well until the second teleport. The first one no evade at all. He kept shooting Shadow Bolts at me. By the second one he was out of mana. And so when he teleported to the balcony he couldn't attack me from a distance. He started running to me to try and melee me but couldn't path to me. Because he couldn't path to me he reached evade mode once again.
So it looks like the evade **on** a balcony is fixed, however I wouldn't consider this issue fixed yet. I'm unsure what is supposed to happen when he gets out of mana but as of now tries to path to you to try and melee you, but he reaches evade once again because getting up the stairs is apparently too hard for this old wizard.

Also I've seen him teleport twice in a row. Once to the balcony on the east side and then immediately to the balcony on the south side without ever casting anything on the balcony on the east side. Not sure if this is a bug though.
Also I'm unsure if the Shadow Teleport buff he gets should be visible.

**Comment by bdebaere** [comment] 2019-03-26 18:18
https://github.com/cmangos/classic-db/commit/303f5d05d8c76dfbaeea9db9b38c0c5e8f267e12
https://github.com/bdebaere/mangos-classic/commit/7fa4124748e2f378e209c82bd7d0dea448482f02

**Comment by cala** [comment] 2019-03-29 14:14
Thank you for this new feedback and taking the time to test again.

I've tested this issue but I was unable to reproduce the out of reach evade that you are describing: he was always able to run towards my player or at least was not evading the few cases where he wasn't able to find a path.

Aside from the visibility of the buff (Shadow Teleport), the two other behaviours you are describing (running melee when OOM and teleporting twice in a row) sound ok to me.

**Comment by bdebaere** [comment] 2019-03-29 17:32
@cala Give me some time I’ll try to get a video of it.

**Comment by cala** [comment] 2020-04-20 21:05
Tested this evening and even on platform, with no mana, Arugal does not evade. I guess this was fixed some way or another. Closing this issue. Thank you.

**Closed by cala** 2020-04-20 21:05 UTC
Labels: Info: Needs Replication, System: Maps, System: Miscellaneous, Version: Classic, Version: TBC, Version: WotLK
