### ISSUE TITLE
[CLASSIC] VMAP Issue in Shadowglen (Teldrassil)

### ISSUE THREAD

**Issue by Argonn** [cmangos/issues#892] opened 2016-04-11 14:29 UTC
**Current behavior**: 
When you walk to the NPC that is sitting by the cave (North of Shadowglen). And pull some spiders to follow you up to the NPC, they will start 'Jumping' up and down instead of just walking on the floor.

**Expected behavior**: 
They should walk along the mesh.

**Steps to reproduce**:
1. Create a Night-elf
2. Walk north in the ShadowGlen area
3. Pull a nearby enemie into the small mountain path leading to the NPC sitting  there.(http://www.wowhead.com/npc=8584/iverron)

**Client version**: 
1.12.X Client

**Database version**: 
Classic DB 1.6.5 "The wailing pet. the midsummer joy and all that"

**Operating system**: 
Windows 7 Enterprise

**Comment by Argonn** [comment] 2016-04-11 20:35
This happend to more NPC's within Teldrassil

**Comment by Neotmiren** [comment] 2016-06-19 08:48
@Argonn, your link to https://snowfallwow.com/ is interesting (reverting to patches older than 1.12, I mean).

Could you say, were stats of creatures more hardcore in older patches (in general)? There is massive nerf last year due to filling Classic DB with stats from "Bestiary", and so it is interesting to know about previous Classic creature data in DB - could it be related to older patches, or someone maked it up? That data  is surely not from TBC or WotLK, which lowered stats even more.

Is raw CMaNGOS core used on snowfallwow server?

As for the issue, you should check if disabling mmaps helps. I have not such issues in the modified cMangos core long ago, but its code is not identical to current CMaNGOS and besides I had fixed VMAP bug (similar to yours?) related to TerrainInfo::GetHeightStatic(), which caused weird movement of orcs in Render's Rock cave (NW of Redridge Mountains) with enabled mmaps only.

**Comment by Argonn** [comment] 2016-06-25 11:31
@neotmiren Patch 1.11 gave most creatures a big nerf. allot of hard encounters where made non elite etc. im currently on holiday, but when i return i could give some more intel

**Comment by Argonn** [comment] 2016-06-25 11:32
I will try to disable mmaps. and yes snowfall is cmangos with our own fixes patches and code

**Comment by Neotmiren** [comment] 2016-06-27 01:00
I have checked behaviour of an old executable and in fact the spiders walk above ground at some spots. In my current version they perfectly move on the ground surface. So it is probably the same problem as in Render's Rock cave.

And about the nerf you say, is it related only to some named/unique creatures, or they lowered stats for regular creatures as well?

Another big subject in question is attack speed: old database data has low values for many of creatures (fast attacks). Now is is replaced with higher delays (like 2.0 vs 1.2), and of course this leads to significant dps reduction, because there is no compensation with increased mindmg..maxdmg for each attack. Could it be a nerf, or old database data has incorrectly mixed values from different sources?..

**Comment by Nightfly510** [comment] 2016-06-29 15:54
@Neotmiren Can you document your fix for the Render's Rock cave you mention?  You site a reference to _**TerrainInfo::GetHeightStatic()**_.  I am interested to see a current solution/workaround for this problem.

A couple of years back I spent a fair bit of time with the CMangos codebase, trying to resolve certain quirks from back then.  This height adjust bug has been around since then and before, and I now remember (after perusing some older bug threads here) that I had made a pretty effective fix for the buggy cave movements/evading back when the _**UpdateAllowedZ()**_ was still in the codebase.  Things seem to have changed a fair bit since then, so if you have a current fix for these I'd love to see how you did it!

**Comment by Neotmiren** [comment] 2016-06-29 17:44
Sorry, it is not what could be called "current fix". As regarding UpdateAllowedPositionZ(), it is still present in current code and the old fix should work probably.

I forked from CMaNGOS in autumn of 2014, though did not create .git repository and since that time only trustworthy new commits from CMaNGOS were transferred to it. I play World of Warcraft myself, never interested in developing for the sake of developing, and therefore cannot bear with endless, replenishing CMaNGOS game-breaking issues (and wonder how people can bear). To not say much... all details are available by the link in my profile. Ask if something is not clear.

**Comment by Argonn** [comment] 2016-06-30 10:57
Attack speed will not change dps. its just more annoying for spell casters

**Comment by Argonn** [comment] 2016-06-30 11:56
forget my last comment. its maxDmg- minDmg * attackspeed. not dps as flat stat

**Comment by Nightfly510** [comment] 2016-07-01 13:08
After some testing on the original issue, I have gained some additional information which may be of help in resolving this issue.  I have seen a lot of cases just like this (creatures do not follow terrain mesh, but raise above ground while pathing) over the few years that I have spent playing around with the cmangos codebase.  It usually happens when there is a significant difference in height from origin to destination.

I believe what is occurring is that there is a discrepancy between the server and client as to the correct location of the entity's Z coordinate:  the server seems to be erroneously reporting the entity location mid-path higher than what it actually is (should be).

Behavior can be duplicated with the player avatar by using the _**.mmap path go**_ admin command while standing near the NE npc as mentioned in the original report and targeting a spider down the chasm.  During path motion, use of the _**.gps**_ (with additional VMAP_DEBUG enabled, and make sure to clear your target so gps will use player location) command reveals that there is frequently a difference of 2.0-5.0 units between the unit's vertical Z position and the true ground Z value.

It is my presumption that perhaps the spline motion position calculation may be the culprit, as I have traced the code as far as that, trying to identify and erroneous places the unit's Z-position might be getting incorrectly adjusted.  However, my understanding of this code is rather limited.

If there indeed was a fix to this issue from some other codebase, as @Neotmiren indicated, it would be good to identify it and apply it here.

I have reapplied my patch for the quirky cave dwellers by capping the max value that WorldObject::UpdateAllowedPositionZ() is allowed to change Z by.  I believe the original reported issue to be unrelated to this, however.

What is indeed strange about this issue is that the mmap pathing seems to show a perfect path along the terrain when tested via the _**.mmap path**_ admin command.

**Comment by ryancheung** [comment] 2016-11-29 10:10
@Nightfly510 I've tested a lot today and found there's nothing related Z-position updating, it's just the path points generated by PathFinder that have some z coordinate is above that ground. 

So this is still a mmap path finding issue.

**Comment by BareRose** [comment] 2016-12-30 23:48
Can confirm that this happens virtually everywhere where there are steep enough slopes (seen it happen in Valley of Trials with scorpions too). It's really immersion-breaking.

Can someone give me a quick TL;DR of how mmap pathfinding is done (and where the PathFinder is, don't have the sources handy atm)? May be able to correct this if it's "just" an issue with z coordinates in paths (and not something deeper).

**Comment by dagochen** [comment] 2016-12-31 00:01
Is there something  to get the z value of some give x and y coordinates to get the correct height?

**Comment by boxa** [comment] 2016-12-31 07:42
simple add into PathFinder.cpp, and issue gone
```
void PathFinder::BuildPointPath(const float* startPoint, const float* endPoint)
{
...
        m_type = PathType(PATHFIND_NORMAL | PATHFIND_NOT_USING_PATH);
    }

+    for (uint32 i = 0; i < m_pathPoints.size(); ++i)
+        m_sourceUnit->UpdateAllowedPositionZ(m_pathPoints[i].x, m_pathPoints[i].y, m_pathPoints[i].z);
 
   DEBUG_FILTER_LOG(LOG_FILTER_PATHFINDING, "++ PathFinder::BuildPointPath path type %d size %d poly-size %d\n", m_type, pointCount, m_polyLength);
}
```

**Comment by cyberium** [comment] 2016-12-31 10:54
Very Hight cpu cost solution. But it should improve Z accuracy.

**Comment by BareRose** [comment] 2016-12-31 11:51
Just tried out that fix, and it does seem to fix Z accuracy. Seems sorta badaidy, but probably good enough. The movement system is eventually going to get a rewrite anyway.

As for the CPU cost... unless BuildPointPath gets called A LOT and paths contain many points the increase in CPU load should be negligible.

Would be sweet if this fix could be added in and all related issues closed, unless a cleaner solution is in the works ofc.

**Comment by cyberium** [comment] 2016-12-31 12:25
The CPU cost is not fegligible ;)
That loob will be done for each generated path.
Path contain at least 2 points.
For each point map and vmap height will be computed, compared. And that involving BIH.
So no it will not be negligible. However it would be nice to quatify it.

**Comment by BareRose** [comment] 2016-12-31 13:28
How often do paths get generated then? Every time something moves? Would be good to quantify it (and maybe find a more efficient implementation).

Also why don't paths just automatically have the correct Z positions? Seems like an oversight in how paths are handled.

**Comment by MrMarvin** [comment] 2016-12-31 15:42
I just added a line to log z value fixes on each path generation:
```

    // see https://github.com/cmangos/issues/issues/892#issuecomment-269854308
    uint32 fixed_count = 0;
    for (uint32 i = 0; i < m_pathPoints.size(); ++i){
        float old_z = m_pathPoints[i].z;
        m_sourceUnit->UpdateAllowedPositionZ(m_pathPoints[i].x, m_pathPoints[i].y, m_pathPoints[i].z);
        if (old_z != m_pathPoints[i].z)
            fixed_count++;
    }
    DEBUG_FILTER_LOG(LOG_FILTER_PATHFINDING, "++ PathFinder::BuildPointPath fixing path z values: %d fixed / %d total\n", fixed_count, m_pathPoints.size());
```
and from running an empty (like in not a single player connected) mangosd, it generates roughly a thousands paths per minute. In the 4 minutes it let in ran, it was called 4387 times. However, I feel this is not a good measurement, as i suspect the PathFinder to be highly dependent on player activity.

Please note that from the said 4387 calls, a total of 14413 points were calculated of which 9274 got their z-value fixed by `UpdateAllowedPositionZ`. Thats ~ 65%! So I'd go with @BareRose here:
> Also why don't paths just automatically have the correct Z positions? Seems like an oversight in how paths are handled.

**Comment by Laizerox** [comment] 2016-12-31 16:16
Because each xy can have multiple z values based on layer/terrain/wmo.

Therefore we need to find/calculate suitable for us.

**Comment by cyberium** [comment] 2016-12-31 16:23
Its by design. mmap cannot be so accurate than vmap/map. We have to define some plane that represent the walkable area. That plane is composed by triangle/polygon. The more we have triangles, the more accurate will be the result, the more big mmap file will be, and the more cpu power will be needed to create a path from point A to point B.

So we have to deal with compromise. And mmap coordinate represent in any case average position of the walkable plane/point. 
Mmap path generator is not able to use directly map/vmap data so it have to use the mmap file and generate those point from the value it have. That's why generated point are average.

Good news is @namreeb is working hard to improve all of this. And i made good progress lately.
We may expect some big change on that matter in next following week ;)

If you want to help, he need to get some help to find problematic zone.
So it will be kind if you could do some research, make some screen and give coordonate if you found some.
And as always when we'll get some release here. We need feedback. Because often when a devs release something he have no feedback in reasonable amount of time. And 3-6 month latter we can see some issue related to them appear. (When dev do other stuff and may even forget the details of his implementation)

Voila i hope its more clear ;)

**Comment by dagochen** [comment] 2016-12-31 16:31
In Silithus are a lot of places where this kind of bumping of NPCs movement happens.
I provided a link to it here: http://datenbank.classic-wow.org/?maps=1377:274721528366598410585424569443467876481890457876

**Comment by BareRose** [comment] 2016-12-31 16:47
Wouldn't it be easier to include all possible z values for a given x/y? Then the paths could just use the closest one. Using average is - no offense - pretty stupid. Making it average and then bandaiding in every problem area is a terrible solution. If you're only going to use a single z value, why don't you try using the lowest (which is usually the floor)? May still need bandaiding, but definitely less as like 90% of the z issues would be solved that way.

**Comment by Grz3s** [comment] 2016-12-31 17:20
hi
Nice that someone reported this... Le'ts hope that @namreeb's project will fix this issue...
I  can give you example .. where it happens 100% .. 
https://www.youtube.com/watch?v=vQyw01P_WyE&feature=youtu.be
You can see ... that mostly.. in this kind of narrow paths .. this isse happens.
I tried .. even tried to move slightly waypoints ... it never halped..
GL
;)

**Comment by cala** [comment] 2016-12-31 18:10
I still don't have a PC at hand to make a video but this issue can also be seen with `go creature id 12118`
This is Lucifron and his two linked NPCs starting their pathing on a slope in MC. They move below and above the ground.

**Comment by BareRose** [comment] 2017-01-01 14:57
Looking at the mmap generator's source I've found a whole lot of configuration parameters in it (like maximum walkable angle and such). What if this isn't an issue with cMangos at all, but rather a problem in mmap/vmap generation? There's another minor issue I noticed a while back that may be connected: In Valley of Trials if you walk up against some of the cactuses your character will be able to walk up some of the smaller ones, which looks quite weird. Could this be an issue with config.walkableHeight in mmap generation? Or does player movement use an entirely different kind of map?

**Comment by ryancheung** [comment] 2017-01-03 04:45
@cala I think Lucifron's waypoint movement is bugged in database. There's only 5 waypoint points  in DB for it. The distance of one point to next point is too large and there may be slope between the two points.

**Comment by Lillecarl** [comment] 2017-01-03 15:51
http://pastebin.com/kmDTy62g <- From @malcrom

**Comment by killerwife** [comment] 2017-01-03 17:52
@Grz3s can you look at that data?

**Comment by Grz3s** [comment] 2017-01-03 19:23
I'll add this to my to do list :+1: 
thx @malcrom

**Comment by Saltgurka** [comment] 2017-01-28 13:02
I'll take a look at the molten core movement this weekend and try to port it to all three databases :)

**Comment by AnonXS** [comment] 2019-01-28 11:04
MoveChase seems to be fixed at this location, MoveHomeGen seems to pose issues as npcs when evading start clipping through terrain.

**Comment by killerwife** [comment] 2021-12-17 21:40
Move home clipping through terrain intended.

**Closed by killerwife** 2021-12-17 21:40 UTC
Labels: System: M/V-Maps / Movement, Version: Classic (1.12), Info: Needs Replication / Information / Feedback, System: Creature (Spawn / Waypoints / Texts etc.)
