### ISSUE TITLE
[WOTLK] Client Crashes During VehicleInfor::Board()

### ISSUE THREAD

**Issue by xfurry** [cmangos/issues#1546] opened 2018-01-21 20:18 UTC
**Current behavior**: 
Client crash when many vehicles with accessories are loaded to the grid
**Expected behavior**: 
Not crashing
**Steps to reproduce**:

1. Go to Ulduar raid instance
2. Set character speed to something high. 5 or more.
3. Run around the first part of the instance where there are a lot of flying vehicles, before the first boss.
4. Crash is kind of random. There isn't a clear way to replicate it. You might need to do this a few times, maybe even reset the instance, in order to experience it.
5. Crash can be experienced in normal playing conditions, but it's more difficult to replicate. Usually it requires a vehicle with a creature passenger.
6. There is one error visible on the server console

```
TransportSystem.cpp:49: Error: Assertion in TransportBase::~TransportBase failed: m_passengers.size() == 0
TransportSystem.cpp:49: Error: Assertion in TransportBase::~TransportBase failed: m_passengers.size() == 0
TransportSystem.cpp:49: Error: Assertion in TransportBase::~TransportBase failed: m_passengers.size() == 0
```

Most likely the crash happens on this code:
https://github.com/cmangos/mangos-wotlk/blob/master/src/game/Entities/Vehicle.cpp#L240 
If we take out the movement part, it won't happen.

[//]: # (If this is a crash report, include the crashlog from a debug build with https://gist.github.com/)

**Comment by Fra298** [comment] 2018-03-29 21:11
Happening also when closing server console under windows or simply when using CTRL-C in console when mangosd is running (even if server is just started)

**Comment by jimmybrancaccio** [comment] 2018-11-27 12:09
I can also confirm this happens with cmangos/mangos-wotlk@0592a05

```
12:03:10 12:05:01 GameEvent 60 "World's End Tavern - L70ETC Concert" removed.
12:05:01 Next game event check in 180 seconds.
server shutdown 10
mangos>/home/mangos/wotlk/mangos/src/game/Maps/TransportSystem.cpp:49: Error: Assertion in ~TransportBase failed: m_passengers.empty()/home/mangos/wotlk/mangos/src/game/Maps/TransportSystem.cpp:49: Error: Assertion in ~TransportBase failed: m_passengers.empty()12:06:07 Halting process...
```

**Comment by killerwife** [comment] 2021-12-19 15:40
Need reproduction algorithm.

**Comment by xfurry** [comment] 2021-12-20 19:12
> Need reproduction algorithm.

I'm not sure if this still happens after all the changes you've done. I will check it these days and come back to you.

**Comment by al3xc1985** [comment] 2022-02-02 21:31
@xfurry these days? is 02 Feb...:)))) hope you understand I joke

**Comment by insunaa** [comment] 2023-10-28 12:34
I've fixed that server error in my Flame Leviathan Pull Request, but I've never had the client crash. I'll close the issue tentatively as I have never experienced it and the assertion will be fixed soon:tm:

Edit: To clarify: this issue was likely caused by matryoshka vehicles: The Flame Leviathan for example has a Unit named "Flame Leviathan Seat" as a passenger, this Flame Leviathan Seat meanwhile has "Leviathan Defense Turret" and "Overload Control Device" as passengers.
When the Flame Leviathan object is deconstructed it also deconstructs the Flame Leviathan TransportBase, but it doesn't check if the transportbase itself had passengers that also have passengers, so they get deconstructed before having all passengers unboarded => assertion triggers

**Closed by insunaa** 2023-10-28 12:34 UTC
Labels: System: Player Controlled Units, Expansion: WotLK (3.3.5), Type: Client / Core Crash, Info: Needs Development
