### ISSUE TITLE
🐛 [Bug Report] When Starting Server It Failed to Load DB Data From Fully Populated DB

### ISSUE THREAD

**Issue by apostolovm** [cmangos/issues#2228] opened 2020-07-09 14:00 UTC
## 🐛 Bugreport
I have followed all the steps with no errors. When I have tried to run **./bin/mangosd -c etc/mangosd.conf -a etc/playerbot.conf**
There where multiple errors for missing. Here is a simple example:

_2020-07-09 16:11:23 ERROR:Spell 100 listed in `spell_facing` does not exist_
How ever when I did check there is record
mysql> select * from spell_facing where entry = '100';
+-------+------------------+
| entry | facingcasterflag |
+-------+------------------+
| 100 | 1 |
+-------+------------------+

The entire db is populated.
### Expected behavior

It should reach mangos command promot
mangos> 
### Version & Environment
Client Version:  - "1.12.1" (CLASSIC)
CMaNGOS Repo & Commit Hash:  - [CLASSIC](https://github.com/cmangos/mangos-classic/tree/c30c468337ec9554293ba3ced065d27813fb748b
Operating System: Linux Ubuntu 16.04

### Crashlog

- None

**Comment by cyberium** [comment] 2022-02-10 12:33
Not able to reproduce, you may had forget base files
Closing as its an old report feel free to reopen it if its still the case.

**Closed by cyberium** 2022-02-10 12:33 UTC
Labels: Version: Classic (1.12), Info: Needs Replication, Type: Support
