### ISSUE TITLE
🐛 [Bug Report]  prospect fix

### ISSUE THREAD

**Issue by Nightingale9002** [cmangos/issues#3674] opened 2024-02-08 12:07 UTC
### Bug Details

https://github.com/cmangos/issues/issues/3542

this way can only prevent from benefiting illegally, not really right.

### Steps to Reproduce

1.
2.
3.
4.

### Suggested Workaround

#   \src\game\Spells\SpellEffects.cpp
line 8596
#########################################################################

    #  /loot->ShowContentTo(p_caster);

    loot->AutoStore(p_caster);
    loot->Release(p_caster);

### Core SHA1 Commit Hash

*

### Database SHA1 Commit Hash

*

### Operating System

Windows

### Client Version

1.12.1 (Classic)

**Comment by insunaa** [comment] 2024-02-08 12:10
Duplicate of https://github.com/cmangos/issues/issues/3542
if your issue still exists don't open a new one, instead re-open (or don't close) the old one please.

**Closed as not planned by insunaa** 2024-02-08 12:10 UTC
Labels: Info: Needs Replication
