### ISSUE TITLE
🐛 [Crash Report] Core crashes when using Dispel Magic spell

### ISSUE THREAD

**Issue by cala** [cmangos/issues#2107] opened 2020-01-28 15:02 UTC
## 🐛 Bugreport
Classic core (and possibly TBC/WotLK) is crashing after a few minutes.
To be more accurate: Classic core crashes when doing Onyxia raid with bots loaded as I was not able to replicate the crash with a single player or with only real players. It happens every time with bots though. Unfortunately, there is no crash log generated so I cannot even give a call stack... It seems to happen at combat start or right after.

Core log at the moment of the last crash:
```
Aura: construct Spellid : 18728, Aura : 79 Target : 1 Damage : 0
AURA MOD DAMAGE type:1 negative:0
Holder of spell 18728 now is in use
Spell 18737 Effect0 : 6 Targets: Pet (Petnumber: 497 Guid: 23), -, -
Spell: Aura is: 133
Aura: construct Spellid : 18737, Aura : 133 Target : 1 Damage : 0
Holder of spell 18737 now is in use
Spell 18740 Effect0 : 6 Targets: Pet (Petnumber: 497 Guid: 23), -, -
Spell: Aura is: 132
Aura: construct Spellid : 18740, Aura : 132 Target : 1 Damage : 0
Holder of spell 18740 now is in use
Sending SMSG_SPELL_GO id=12625
CHAT: packet received. type 1, lang 7
Command: gm off [Player: Annela (Account: 6) X: -97.619904 Y: -108.379745 Z: -39.312309 Map: 249 Selected: Player Eleonora (Guid: 8)]
Respawning...
Creature (Entry: 2721 Guid: 14774) follow to Creature (Entry: 2714 Guid: 14772)
Sending SMSG_SPELL_START id=988
Sending SMSG_SPELL_GO id=988
Spell 988 Effect0 : 38 Targets: Player Eleonora (Guid: 8), -, -
Aura 22 now is remove mode 3
Segmentation fault: 11
```
Annela is the real player has one can guess because it uses GM commands.
Eleonora is a Priest bot and spell 988 is Dispel Magic. I don't know if this is related.

### Expected behavior
No crash, I think.

### Version & Environment

Client Version: 1.12.1

CMaNGOS Repo & Commit Hash: 

https://github.com/cmangos/mangos-classic/commit/3b3df96c90e06691ae6324cfb0b3341180d2e414

Database Repo & Commit Hash: 

Operating System: 

macOS 10.14.6

### Steps to reproduce
1. Enter Onyxia's Lair with a player and a raid with bots (possibly a priest ?)
2. Engage one of the four trash mobs before Onyxia
3. Rince & repeat until core crashes

### Crashlog

None… :'(

**Comment by cala** [comment] 2020-01-28 15:37
I'm able to consistently reproduce it and it seems to be related with dispelling as the core crashed again right after the bot tried to cast Dispel Magic. If a real player cast the same spell the core crashes also whenever the target is a bot or a real player.

This means this is unrelated to Playerbot, though my first report hinted the opposite.

**Comment by Yatzii93** [comment] 2020-01-28 16:00
hmmm running the TBC core and I would of 100% had live crashes if this was a problem my end. Unless it's a very recent commit I haven't pulled in yet.

**Comment by Yatzii93** [comment] 2020-01-28 16:01
Can you not just run the build in debug mode with debugging on. Cause the crash and you should be shown exactly where the problem is originating from.

**Comment by cala** [comment] 2020-01-28 16:23
Would I have an IDE that I could attach to the executable I am running, sure I would do that. But I have not (sloooowly working on this, though).
Building from the command-line in the meantime. So no live debug, sadly.

**Comment by killerwife** [comment] 2020-01-28 20:42
Dispel does crash and I have fix, will push today.

**Comment by killerwife** [comment] 2020-01-28 21:16
Should be fixed: https://github.com/cmangos/mangos-tbc/commit/c700b8fdd9f07aa3c845b774fb689994e6ba7c0a

**Closed** 2020-01-29 11:01 UTC
Labels: Info: Needs Testing, Info: Replicated, System: Spells, Type: Core Crash, Version: Classic
