### ISSUE TITLE
💬 [Support Request] [WotLK] DB Errors

### ISSUE THREAD

**Issue by adellaci** [cmangos/issues#2179] opened 2020-04-25 19:20 UTC
I updated this morning 9:00am EST. I was going through my log s and i have these few DBErrors.log entries;
2020-04-25 12:58:13 Gameobject (Entry: 188067 GoType: 5) have too small size=0.000000
2020-04-25 12:58:13 Gameobject (Entry: 188142 GoType: 5) have too small size=0.000000
2020-04-25 12:58:13 Gameobject (Entry: 188073 GoType: 5) have too small size=0.000000
2020-04-25 12:58:13 Gameobject (Entry: 188072 GoType: 5) have too small size=0.000000
2020-04-25 12:58:13 Gameobject (Entry: 187882 GoType: 2) have too small size=0.000000
2020-04-25 12:58:13 Gameobject (Entry: 188077 GoType: 1) have too small size=0.000000
2020-04-25 12:58:13 Gameobject (Entry: 190720 GoType: 3) have data7=190721 but trap GO (Entry 190721) not exist in `gameobject_template`.
2020-04-25 12:58:13 Gameobject (Entry: 194461 GoType: 8) have data2=194645 but trap GO (Entry 194645) not exist in `gameobject_template`.
2020-04-25 12:58:13 Gameobject (Entry: 195090 GoType: 8) have data2=195089 but trap GO (Entry 195089) not exist in `gameobject_template`.
2020-04-25 12:58:13 Gameobject (Entry: 194752 GoType: 10) have too small size=0.000000
2020-04-25 12:58:13 Gameobject (Entry: 202931 GoType: 5) have too small size=0.000000
Have i done something wrong on my update or is this expected ? 

I also have many more DBError Log is a total of 4406 lines long. Too large to paste here

Client Version - "3.3.5a" (WOTLK)

  Commit Hash -  [WOTLK](https://github.com/cmangos/mangos-wotlk/tree/ed6f5be404e5eea8e6079341360f086103baca7a

  Database Version - [WOTLK](https://github.com/cmangos/wotlk-db/tree/b4a43ac6cdcb202eb57337d1828b40a9beb97271)

 
  Operating System - Ubuntu 18.04 LTS Server

### Steps to reproduce
1.start mangosd
2.Review log after startup is finished

**Comment by Grz3s** [comment] 2020-04-25 21:15
i cant reproduce this error even with loglvl =3
Pls do clean install and check again

**Comment by Grz3s** [comment] 2020-04-25 21:18
another thing:
`2020-04-25 12:58:13 Gameobject (Entry: 190720 GoType: 3) have data7=190721 but trap GO (Entry 190721) not exist in gameobject_template.`
We do have `190721` in DB -- pls use latest DB

**Comment by evil-at-wow** [comment] 2020-04-25 21:49
To be fair the commit he link to is pointing to the latest database version (ok, not any more when I write this, but just the last two commits missing and none of them change gameobject_template).

So I think @Grz3s' first suggestion applies here. Did you run the InstallFullDB.sh script @adellaci or did you update (semi-)manually?

**Comment by adellaci** [comment] 2020-04-26 09:39
Yes i did run InstallFullDB.sh. I was searching through updates for a while and found that  "sql/base/dbc/original_data" folder & "sql/base/dbc/cmangos_fixes" folder had not been applied. I plan on wiping the Databases and starting from scratch again.

**Comment by al3xc1985** [comment] 2020-04-26 10:46
It happend to me either to not apply all the updates...
There are probably 2 many updates, and somehow it misses some of them from time to time

I suggest to create a full db release as soon as possible @Grz3s . What do you think?

**Comment by Grz3s** [comment] 2020-04-26 11:10
why not to use ./installfulldb.sh .. this will add (if set correct) all req updates from db and core
@al3xc1985 yes i know ... its comming soon*

**Comment by adellaci** [comment] 2020-04-26 13:39
Completed  rebuilding database from scratch
DBErrors.log
2020-04-26 09:16:34 Gameobject (Entry: 188067 GoType: 5) have too small size=0.000000
2020-04-26 09:16:34 Gameobject (Entry: 188142 GoType: 5) have too small size=0.000000
2020-04-26 09:16:34 Gameobject (Entry: 188073 GoType: 5) have too small size=0.000000
2020-04-26 09:16:34 Gameobject (Entry: 188072 GoType: 5) have too small size=0.000000
2020-04-26 09:16:34 Gameobject (Entry: 187882 GoType: 2) have too small size=0.000000
2020-04-26 09:16:34 Gameobject (Entry: 188077 GoType: 1) have too small size=0.000000
2020-04-26 09:16:34 Gameobject (Entry: 190720 GoType: 3) have data7=190721 but trap GO (Entry 190721) not exist in `gameobject_template`.
2020-04-26 09:16:34 Gameobject (Entry: 194461 GoType: 8) have data2=194645 but trap GO (Entry 194645) not exist in `gameobject_template`.
2020-04-26 09:16:34 Gameobject (Entry: 195090 GoType: 8) have data2=195089 but trap GO (Entry 195089) not exist in `gameobject_template`.
2020-04-26 09:16:34 Gameobject (Entry: 194752 GoType: 10) have too small size=0.000000
2020-04-26 09:16:34 Gameobject (Entry: 202931 GoType: 5) have too small size=0.000000
2020-04-26 09:16:35 Item (Entry: 3034) has unexpected RequiredDisenchantSkill (0) for non-disenchantable item class (6), reset it.
2020-04-26 09:16:35 Item (Entry: 8840) has unexpected RequiredDisenchantSkill (0) for non-disenchantable item class (9), reset it.
2020-04-26 09:16:35 Item (Entry: 46349) marked as disenchantable by RequiredDisenchantSkill, but not have disenchanting loot id.

Lots of these;
2020-04-26 09:16:38 Spell (ID: xxxxx) has effect EffectImplicitTargetA/EffectImplicitTargetB = 38 (TARGET_UNIT_SCRIPT_NEAR_CASTER), but does not have record in `spell_script_target`

2020-04-26 09:16:55 Creature (Entry: 1344) has spell 19834 defined in `auras` field in `creature_template_addon, but spell is no self-only spell`.

2020-04-26 09:16:56 Creature (GUID: 46) has spell 1244 defined in `auras` field in `creature_addon, but spell is no self-only spell`.

2020-04-26 09:17:01 Table 'item_loot_template' entry 5858 (item entry with ITEM_FLAG_LOOTABLE) not exist but used as loot id in DB.

and it goes on for a total of 4028 entries

**Comment by Grz3s** [comment] 2020-04-26 13:52
can you say step by step how you rebuilding your DB ?

**Comment by adellaci** [comment] 2020-04-26 14:05
yes
DROP tables (,mangos)
CREATE DATABASE mangos DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
CREATE USER IF NOT EXISTS 'mangos'@'localhost' IDENTIFIED BY 'mangos';
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, ALTER, LOCK TABLES, CREATE TEMPORARY TABLES ON mangos.* TO 'mangos'@'localhost';

mysql -umangos -p mangos < ~/mangos/sql/base/mangos.sql

for sql_file in $(ls ~/mangos/sql/base/dbc/original_data/.sql); do mysql -umangos -p --database=mangos < $sql_file ; done
for sql_file in $(ls ~/mangos/sql/base/dbc/cmangos_fixes/.sql); do mysql -umangos -p --database=mangos < $sql_file ; done

./InstallFullDB.sh

**Comment by Grz3s** [comment] 2020-04-26 14:08
is this error `Gameobject (Entry: 190720 GoType: 3) have data7=190721 but trap GO` still on that list?

**Comment by adellaci** [comment] 2020-04-26 14:11
yes

**Comment by Grz3s** [comment] 2020-04-26 14:28
pls give me all your error .. use https://paste2.org/

**Comment by adellaci** [comment] 2020-04-26 14:30
https://paste2.org/vIP6Ud8m

**Comment by Grz3s** [comment] 2020-04-26 14:53
from mangosd.conf whats are these values?
LogLevel = ?
LogFileLevel = ?

**Comment by adellaci** [comment] 2020-04-26 15:00
LogLevel = 0
LogFileLevel =1

**Comment by Grz3s** [comment] 2020-04-26 15:01
and last thing... 
did you build release or debug?

**Comment by adellaci** [comment] 2020-04-26 15:20
build-release

**Comment by Grz3s** [comment] 2020-04-26 15:25
no idea how u managed to see all those errors, maybe koz of this: Ubuntu 18.04 LTS Server (no idea)
but thing is... looks like theyre valid... (just tested some) .. I'll spend some time on them .. 
will see what can be fixed ;)

**Comment by adellaci** [comment] 2020-04-26 17:58
@Grz3s woudl like me to close this out and open one in Database Tracker?

**Comment by Grz3s** [comment] 2020-04-26 17:59
leave this one here

**Comment by Grz3s** [comment] 2020-04-27 00:54
Pls Close this one
Was reported again in right place: https://github.com/cmangos/wotlk-db/issues/313

**Closed** 2020-04-27 01:55 UTC
Labels: Type: Support
