### ISSUE TITLE
[WotLK] Shadowmeld responds with "You must be in front of your target"

### ISSUE THREAD

**Issue by mangostaters** [cmangos/issues#1102] opened 2016-09-21 15:30 UTC
**Current behavior**: Shadowmeld does not activate when clicked; "You must be in front of your target," popup appears

**Expected behavior**: Shadowmeld should occur

**Steps to reproduce**: Make Night Elf, try to shadowmeld

**Client version**: WotLK 3.3.5a

**Commit hash**: ?

**Database version**:  DB listed as "UDB_0.12.2_mangos_11792_SD2_2279.sql" in folder

**Operating system**: Win 10 64x

**Comment by devmaximus** [comment] 2016-09-21 16:37
this probably relates to the following line, https://github.com/cmangos/mangos-wotlk/blob/master/src/game/Spell.cpp#L5190 .

however, the issue is probably the same across classic, tbc and wrath with orientation desynch which still requires more research to identify the root cause. now that the method to properly check front/back facing is implemented it exposes the desynch issue.

**Comment by mangostaters** [comment] 2016-09-21 18:07
If I wanted to help find the root cause, where would I start? Or is that heavy coding territory where those with knowledge should work?

**Comment by Phatcat** [comment] 2016-09-21 18:14
You can work on anything you want here; you may not get it right, but we don't discourage anyone from working at any perticular area.

My two cents on this issue; shadowmeld should never throw up any errors regarding your target, ever, as it's a cast that relies on you not being polymorphed and not moving, the target should have no say whatsoever.. so while it is true that we have desync problems (especially relating to mob orientation) this issue shouldn't be here regardless.

**Comment by Phatcat** [comment] 2016-09-22 03:08
https://github.com/cmangos/mangos-classic/pull/56

**Comment by Phatcat** [comment] 2016-10-04 16:36
I am not able to reproduce this at all, I am able to use shadowmeld just fine.. a bit too fine in fact; I can activate it in combat, effectively working like a vanish / feign death removing all aggro and resetting mob attackers.

**Comment by Phatcat** [comment] 2016-11-12 22:44
> effectively working like a vanish / feign death removing all aggro and resetting mob attackers.

which is how it's supposed to be for wotlk I guess. gonna close this as I cannot reproduce, tried several times now, doesn't matter if I'm not combat or has a target or not.

**Closed by Phatcat** 2016-11-12 22:44 UTC
