### ISSUE TITLE
[Classic] Priest Mind Soothe aggro's 100% time.

### ISSUE THREAD

**Issue by lduguid** [cmangos/issues#1566] opened 2018-02-22 19:31 UTC
**Current behavior**: 

Priest Mind Soothe aggro's NPC 100% time.

**Expected behavior**: 

Not aggro NPC being mind soothed

**Steps to reproduce**:

1. Create Level 46 Priest (Human)
2. Cast Rank 2 Mind Soothe on any NPC equal or lower level
3. 

NOTES: Did not test Rank 1
             Mind control and Mind vision work OK
             Works fine with latest TBC code and DB.
             
**Client version**: 
1.12.1

**Commit hash**: 
commit 5828dddbbc1a3fad09e85401ba1dff5536f01b17

**Database version**: 

Classic database v1.9.0 'The Black Dragonflight'.
commit 2491fd334cf5c9da07d16dc1bf5cd3b957974d5c

**Operating system**: 

Windows 8.1

[//]: # (If this is a crash report, include the crashlog from a debug build with https://gist.github.com/)

**Comment by cala** [comment] 2018-02-27 16:10
Thank you for your report. This is a duplicate of : https://github.com/cmangos/issues/issues/403

**Closed by cala** 2018-02-27 16:10 UTC
