### ISSUE TITLE
Chess Event Bug

### ISSUE THREAD

**Issue by rayonpt** [cmangos/issues#1531] opened 2018-01-09 12:59 UTC
**Current behavior**: 
When you start the Chess Event Game, the King immediatly runs to the stairs
**Expected behavior**: 
The king should stay in the chess event and not run to the stairs
**Steps to reproduce**:

1. Talk with the king
2. Control the king
3. Win the chess event

**Client version**: 
2.4.3
**Commit hash**: 
82ecb96  
**Database version**: 
5d37ac9
**Operating system**: 
Windows 10 Pro

[//]: # (If this is a crash report, include the crashlog from a debug build with https://gist.github.com/)

**Comment by jimmybrancaccio** [comment] 2018-11-17 08:14
Closing as a duplicate of #827.

**Closed by jimmybrancaccio** 2018-11-17 08:14 UTC
