### ISSUE TITLE
Wrong Battleground Flag Updates

### ISSUE THREAD

**Issue by Baynar** [cmangos/issues#1872] opened 2019-02-09 03:11 UTC
**Current behavior**: 
When you pick up the flag and start running to cap it, when you leave zone Warsong Lumber into Warsong Gulch or vice versa for the other faction, the state of the 2 horde and alliance captures will change, if you are horde carrying the alliance flag and score is 0/0 then when you enter Warsong Gulch score will shift and now will display that the horde flag was captured and will not update even if you cap the flag untill you re-enter area Warsong gulch.
**Expected behavior**: 
Should update correctly when moving from 1 area to another
**Steps to reproduce**:
1. enter a bg
2. pick up flag of either team
3. run to the middle of the map to enter zone Warsong Gulch
4. check flag state on top of the screen

**Client version**: 
2.4.3
**Commit hash**: 
7052bb443ba58478423f35a1e0c607014973f20d
**Database version**: 
fd4550ffce1f5bc8fed64775531a32446164c467
**Operating system**: 
Windows 10

[//]: # (If this is a crash report, include the crashlog from a debug build with https://gist.github.com/)

**Comment by berserkingyadis** [comment] 2019-02-09 22:04
What is the command to start a bg? Normally you need alot of ppl right?

**Comment by AnonXS** [comment] 2019-02-09 22:07
.debug bg

**Comment by Baynar** [comment] 2019-02-10 10:49
I had it setup min player 1, then i tought that might be the the reason so i tried with a clean bg both with debug and alot of accounts logged and got same results, this behaviour persists on the latests core, 1 month old core and my oldest 4 month old core.

Everything was tested with clean db and core to make sure its not something i changed.

**Comment by yatzi888** [comment] 2019-02-12 22:21
Can confirm.

**Comment by 5man999** [comment] 2019-04-15 12:33
Ok so I've been doing some digging around to try and find the cause and I can definitly pin it down to how the world states are being intilized. 

Using the code trinitycore utilizes I can get the flag states not change on when a player switches zone. However, I can't seem to get the intial states to fill on WSG entry. Right now a player needs to enter, then switch zone in the battleground to pick up the world states. At the beginning of a game no world states show and only after both teams have carried out an action that would trigger an update will it display for both. The first flag pickup for each team does not update for both though. Only the team that takes the flags.

This is the code that produces the results Im describing - Tried my best to get the first world states to show but no luck. However, I'm sure it would be better to figure out why the world states arent updating properly using the cmangos code.

void BattleGroundWS::FillInitialWorldStates(WorldPacket& data, uint32& count) //uint32& count
{
    //FillInitialWorldState(data, count, BG_WS_FLAG_CAPTURES_ALLIANCE, m_TeamScores[TEAM_INDEX_ALLIANCE]);
	//FillInitialWorldState(data, count, BG_WS_FLAG_CAPTURES_HORDE, m_TeamScores[TEAM_INDEX_HORDE]);

	data << uint32(BG_WS_FLAG_CAPTURES_ALLIANCE),count << uint32(m_TeamScores[TEAM_INDEX_ALLIANCE]);
	data << uint32(BG_WS_FLAG_CAPTURES_HORDE), count << uint32(m_TeamScores[TEAM_INDEX_HORDE]);

    if (m_FlagState[TEAM_INDEX_ALLIANCE] == BG_WS_FLAG_STATE_ON_GROUND)
		data << uint32(BG_WS_FLAG_UNK_ALLIANCE), count << uint32(-1);
	else if (m_FlagState[TEAM_INDEX_ALLIANCE] == BG_WS_FLAG_STATE_ON_PLAYER)
	{
		data << uint32(BG_WS_FLAG_UNK_ALLIANCE), count << uint32(1);
	}
    else
		//data << uint32(BG_WS_FLAG_UNK_ALLIANCE) << uint32(0);
		FillInitialWorldState(data, count, BG_WS_FLAG_UNK_ALLIANCE, 0);

    if (m_FlagState[TEAM_INDEX_HORDE] == BG_WS_FLAG_STATE_ON_GROUND)
		data << uint32(BG_WS_FLAG_UNK_HORDE), count << uint32(-1);
	else if (m_FlagState[TEAM_INDEX_HORDE] == BG_WS_FLAG_STATE_ON_PLAYER)
	{
		data << uint32(BG_WS_FLAG_UNK_HORDE), count << uint32(1);
		//FillInitialWorldState(data, count, BG_WS_FLAG_UNK_HORDE, 1);
	}
    else
		data << uint32(BG_WS_FLAG_UNK_HORDE), count << uint32(0);
		//FillInitialWorldState(data, count, BG_WS_FLAG_UNK_HORDE, 0);
		

	data << uint32(BG_WS_FLAG_CAPTURES_MAX), count << uint32(BG_WS_MAX_TEAM_SCORE);

	if (m_FlagState[TEAM_INDEX_HORDE] == BG_WS_FLAG_STATE_ON_PLAYER)
	{
		data << uint32(BG_WS_FLAG_STATE_HORDE), count << uint32(2);
		//FillInitialWorldState(data, count, BG_WS_FLAG_STATE_HORDE, 2);
	}
    else
		data << uint32(BG_WS_FLAG_STATE_HORDE), count << uint32(1);
		//FillInitialWorldState(data, count, BG_WS_FLAG_STATE_HORDE, 1);


	if (m_FlagState[TEAM_INDEX_ALLIANCE] == BG_WS_FLAG_STATE_ON_PLAYER)
	{
		data << uint32(BG_WS_FLAG_STATE_ALLIANCE), count << uint32(2);
		//FillInitialWorldState(data, count, BG_WS_FLAG_STATE_ALLIANCE, 2);
	}
    else
		data << uint32(BG_WS_FLAG_STATE_ALLIANCE), count << uint32(1);
		//FillInitialWorldState(data, count, BG_WS_FLAG_STATE_ALLIANCE, 1);

}

**Comment by 5man999** [comment] 2019-04-15 17:50
Ok ignore my previous jargin, been slamming my head against this for a while now. Noob problems! But I found what seems to be a quick hack solution, atleast in the interim. So what clicked, correct me if I am wrong. The worldstates updates on switch zone are triggered in player.cpp
```

if (bg && bg->GetTypeID() == BATTLEGROUND_WS)
					bg->FillInitialWorldStates(data, count);
```

Seeing as all the worldstate in BattlegroundWS.cpp run their own FillInitialWorldState. The one in player.cpp isn't needed. However, it is needed for first entry to get the 0/3 counters. 

Adding this seems to work in the sense that it lets it run once on entry but not for the rest of the bg. I also have it so the counter resets on battleground leave. 

case 3277:                                  // WS
			if (Worldstateupdate != 1)
			{
				if (bg && bg->GetTypeID() == BATTLEGROUND_WS)
					bg->FillInitialWorldStates(data, count);
				Worldstateupdate = 1;
			}

Need to do more testing to make sure I'm not just getting flooky results and its going to fall over somewhere.

**Comment by 5man999** [comment] 2019-04-15 19:39
Moving it into Crossfaction Join battleground works fairly well, doesn't address peolpe who relog or disconnect:

```
void Player::CFJoinBattleGround()
{
    if (!sWorld.getConfig(CONFIG_BOOL_CFBG_ENABLED))
        return;

    FixLanguageSkills();

    if (!NativeTeam())
    {
        SetByteValue(UNIT_FIELD_BYTES_0, 0, getFRace());
        setFaction(getFFaction());
    }
	if (GetZoneId() == 3277)
	{
		FakeDisplayID();

		BattleGround* bg = GetBattleGround();
		uint32 mapid = GetMapId();
		uint32 Areamap;
		uint32 Zoneid = GetZoneId();
		Areamap = GetAreaId();

		uint32 count = 0;                                       // count of world states in packet

		WorldPacket data(SMSG_INIT_WORLD_STATES, (4 + 4 + 4 + 2 + 8 * 8)); // guess
		data << uint32(mapid);                                  // mapid
		data << uint32(Zoneid);                                 // zone id
		data << uint32(Areamap);                                 // area id, new 2.1.0
		size_t count_pos = data.wpos();
		data << uint16(0);                                      // count of uint64 blocks, placeholder

			// Current arena season
		FillInitialWorldState(data, count, 0xC77, sWorld.getConfig(CONFIG_UINT32_ARENA_SEASON_ID));

		if (bg && bg->GetTypeID() == BATTLEGROUND_WS)
			bg->FillInitialWorldStates(data, count);

		if (InstanceData* instanceData = GetMap()->GetInstanceData())
			instanceData->FillInitialWorldStates(data, count, Zoneid, Areamap);

		data.put<uint16>(count_pos, count);                     // set actual world state amount

		GetSession()->SendPacket(data);

		sWorld.InvalidatePlayerDataToAllClient(this->GetObjectGuid());
	}

}
```
Could the issue be related to SendInitWorldStates being incorrectly called here: As in it shouldnt be triggering for a areamap change on the Warsong Map.

I'm done for now. Not sure why I put myself through this.
https://github.com/cmangos/mangos-tbc/blob/master/src/game/Entities/Player.cpp#L6853

**Comment by Yatzii93** [comment] 2019-04-20 03:03
Hack Fix that works with no problems -
```

void Player::UpdateZone(uint32 newZone, uint32 newArea, bool force)
{
    AreaTableEntry const* zone = GetAreaEntryByAreaID(newZone);
    if (!zone)
        return;

    if (m_zoneUpdateId != newZone || force)
    {
		if (newZone == 3277)
		{
			SendInitWorldStates(newZone, newArea);
			sWorldState.HandlePlayerLeaveArea(this, m_areaUpdateId);
			sWorldState.HandlePlayerEnterArea(this, newArea);
		}
        // handle outdoor pvp zones
        sOutdoorPvPMgr.HandlePlayerLeaveZone(this, m_zoneUpdateId);
        sWorldState.HandlePlayerLeaveZone(this, m_zoneUpdateId);
        sOutdoorPvPMgr.HandlePlayerEnterZone(this, newZone);
        sWorldState.HandlePlayerEnterZone(this, newZone);

    }

    if (m_areaUpdateId != newArea || force)
    {
		if (!(newZone == 3277))
		{

			SendInitWorldStates(newZone, newArea); // only if really enters to new zone, not just area change, works strange...

			sWorldState.HandlePlayerLeaveArea(this, m_areaUpdateId);
			sWorldState.HandlePlayerEnterArea(this, newArea);

			if (sWorld.getConfig(CONFIG_BOOL_WEATHER))
			{
				Weather* wth = GetMap()->GetWeatherSystem()->FindOrCreateWeather(newZone);
				wth->SendWeatherUpdateToPlayer(this);
			}
		}
    }
```

**Comment by Yatzii93** [comment] 2019-05-31 00:31
So I relooked at this recently and another alternative is to switch m_FlagState[<faction>] around here as shown in my repo. 

https://github.com/Yatzii93/mangos-tbc/blob/9ab5855f4c7bfb9e6ef1bcf606da7a70267b49e4/src/game/BattleGround/BattleGroundWS.cpp#L592-L597

Theres also another bug involving how the flag is picked up from the ground. If both team flag states are set as on the ground, the code can't differenciate as to which flag is being clicked so ultimatly you end up in situations where a faction return their flag but also gains the enermy flag.

I did a small change in both cases shown here to stop the occurance. I have however lost the global message that states who returned a flag, I haven't given it a second of troubleshooting as of yet might be a simple fix to bring it back. I'll probz investigate it in the near future.

https://github.com/Yatzii93/mangos-tbc/blob/9ab5855f4c7bfb9e6ef1bcf606da7a70267b49e4/src/game/BattleGround/BattleGroundWS.cpp#L392

Not sure if I should do a PR for this, I can't tell if something is considered a hack fix or a good fix.

**Comment by BenDol** [comment] 2019-05-31 15:54
Could open up a PR with your battleground changes, then we can go through it some more. I want to test it, but the comments here are a little fragmented.

**Comment by killerwife** [comment] 2019-05-31 15:58
@yatzi888 open up a PR definitely and then ping me.

**Comment by BenDol** [comment] 2019-06-01 06:18
@Yatzii93 If I'm understanding correctly, there are actually a few issues mentioned in this thread, right? State updates synchronizations and flipped flag icon states? Look forward to looking at the full PR.

**Comment by Yatzii93** [comment] 2019-06-01 22:34
I'll get on it!

**Comment by al3xc1985** [comment] 2020-03-19 20:52
@killerwife  this can be closed... it works perfect

**Closed** 2020-03-19 21:00 UTC
Labels: Info: Needs Development, Info: Replicated, System: Miscellaneous, Version: TBC
