### ISSUE TITLE
[Classic]+[TBC] Battlegrounds Spirit healers sometimes does not revive.

### ISSUE THREAD

**Issue by Kelzior** [cmangos/issues#1169] opened 2016-11-28 13:38 UTC
Vanilla + TBC 

Current behavior: Sometimes in the Battlegrounds, the Spirit Healer of the faction bug, and does not revive anyone, so, everyone need to wait another 30 seconds to revive.

Expected behavior:
The Battleground Spirit Healer should aways revive the players.

**Comment by Kelzior** [comment] 2016-11-28 13:39
@Warlockbugs @namreeb

Any idea?

**Comment by Lillecarl** [comment] 2016-11-28 13:42
I can confirm this bug, it's ancient =)

**Comment by killerwife** [comment] 2016-11-28 14:52
I know about this. No clue what causes it. Eventually I will deal with it myself but atm I am spread too thin once again so if anyone wants to look at it, its an SD2 AI, likely heal spell fails due to some condition in the targeting system. Thats my first guess.

**Comment by Lillecarl** [comment] 2016-11-28 14:53
You get the aura, but the countdown window doesn't show.

**Comment by killerwife** [comment] 2016-11-28 14:55
Alright, I have no idea what triggers the window, interesting.

**Comment by Lillecarl** [comment] 2016-11-28 18:20
Duplicate of #1028

**Comment by robinsch** [comment] 2016-11-28 21:43
@killerwife SMSG_AREA_SPIRIT_HEALER_TIME

**Comment by killerwife** [comment] 2016-11-28 22:32
Okay, I looked at this, and I officially have no **** clue what is causing it.

**Comment by robinsch** [comment] 2017-01-04 16:40
Caused by periodic tick bug. Just store players in a vector and execute the ress every 30 seconds.

**Comment by killerwife** [comment] 2017-01-04 16:45
Wouldnt it be advisable to fix that periodic tick bug instead?

**Comment by robinsch** [comment] 2017-01-04 16:47
Yes, I'll wish you the best to find the cause of it.

**Comment by killerwife** [comment] 2017-01-04 16:48
My best guess would be the fact that channel removes aura without last tick of aura happening.

**Comment by robinsch** [comment] 2017-01-04 16:51
Nah, this is something that happens randomly.

**Comment by killerwife** [comment] 2017-01-04 16:52
Yes but it still is Periodic tick coupled with Channel

**Comment by robinsch** [comment] 2017-01-04 16:53
Happens with DOT ticks too.

**Comment by ulfgebhardt** [comment] 2017-01-04 17:05
Might be caused by timing errors. This Battleground Spirithealer bug appears more often when player join the graveyard late on the countdown (?)

**Comment by cyberium** [comment] 2017-09-10 08:34
Should be fixed

**Closed by cyberium** 2017-09-10 08:34 UTC
Labels: System-PvPZone, System-Scriptdev2, Version-Classic, Version-TBC
