### ISSUE TITLE
[Classic] Player take fatal fall damage on taxi exit

### ISSUE THREAD

**Issue by cala** [cmangos/issues#1061] opened 2016-08-29 08:05 UTC
**Current behavior**: 

After getting out of taxi, player takes fall damage and die. This happens right after unmounting the hyppoghryph/wyvern from Cenarion Hold (Silithus) to Marshal Refuge (Un'Goro crater), when the player reaches the ground. The fall damage and death appear in the combat log and in the server.log.
There is a huge altitude difference between the two zones, but I don't know if this is related though I could not reproduce with another path: Stormwind to Sentinel Hill in Westfall.

**Expected behavior**: 

After unmounting the griphon/hyppogryph/wyvern, the player should drop to the ground without any damage.

**Steps to reproduce**:
1. Have an Alliance player with the taxi nodes to Cenarion Hold (Silithus) and Marshal Refuge (Un'Goro crater)
2. `.tele cenarion` to get to Cenarion Hold and take the Alliance taxi to Marshal Refuge
3. Die horribly at landing in Un'Goro (it may not happen on the first taxi, so try again, the fly time is not too long)

**Client version**: 

Classic 12.1

**Commit hash**: 

https://github.com/cmangos/mangos-classic/commit/4c176a3c3f07a3a873998455e3c9d32f412d4192

**Database version**: 

Classic DB v1.6.5

**Operating system**: 

Mac OS X 10.6

**Comment by sidsukana** [comment] 2016-08-29 08:12
i solved this bug in valkyrie like this
```diff
diff --git a/src/game/WaypointMovementGenerator.cpp b/src/game/WaypointMovementGenerator.cpp
index d9ea92d..3279365 100644
--- a/src/game/WaypointMovementGenerator.cpp
+++ b/src/game/WaypointMovementGenerator.cpp
@@ -393,7 +393,9 @@ void FlightPathMovementGenerator::Finalize(Player& player)
         // update z position to ground and orientation for landing point
         // this prevent cheating with landing  point at lags
         // when client side flight end early in comparison server side
-        player.StopMoving(true);
+        //player.StopMoving(true);
+        // not need StopMoving here (stops in the air)
+        player.SetFallInformation(0, player.GetPositionZ());
     }
 }

```

**Comment by cala** [comment] 2016-08-29 10:00
I don't understand the removal of StopMoving() here. The SetFallInformation() looks fine, I'll test this soon.

**Comment by cala** [comment] 2016-08-30 20:30
Unfortunately, after applying your patch and taking the same taxi path as described above, my character still met the same squichy fate than a tomato thrown from the roof of a building. :(

**Comment by cyberium** [comment] 2016-11-18 12:46
Should be fixed by https://github.com/cmangos/mangos-classic/commit/779f1d4d207aea793eb64d762651766e221e8f57

**Comment by cala** [comment] 2016-11-18 13:28
Indeed, I forgot to close it myself. Sorry !

**Comment by cala** [comment] 2017-08-24 22:28
I'd like to reopen the issue. I build the last revision of the core, took a character from Cenarion Hold (Alliance) to Theramore and the same issue happened again. I assume this is related to the recent fly path changes, so poking @killerwife ;-)

**Comment by cala** [comment] 2017-08-25 07:59
It seems it's the removal of line https://github.com/cmangos/mangos-classic/commit/930228c4731587046bdbfed5753a4bb5f1f13cb3#diff-4e0dfbbcf97741384c2d68d25fc25686L241 that causes the bug to reappear.

**Comment by killerwife** [comment] 2017-08-25 08:02
Now its done in void FlightPathMovementGenerator::Finalize(Player& player). But why does it still occur? I will try to test soon myself.

**Comment by cala** [comment] 2017-08-25 08:48
Yes, I saw this, you use `player.SetFallInformation(0, player.GetPositionZ());` and the removed line was `GetPlayer()->SetFallInformation(0, movementInfo.GetPos()->z);`
This does not seem to be the same Z value to me, but I can be wrong.

I can perform a few tests on the current build if that can help you, but I won't be able to build/test new code until monday evening.

**Comment by killerwife** [comment] 2017-08-25 08:52
I have just tested on fresh mangos-tbc and couldn't reproduce the issue. I flew from Cenarion Hold (Alliance) to Theramore and nothing happened. Please let me know if you can reproduce it on TBC, or its only classic, and I need to set it up.

**Comment by cala** [comment] 2017-08-25 09:49
Okaayyyy... I tested again a few times on Classic and I'm not able to reproduce what I saw yesterday. I will test on TBC this evening and let you know.

Please, do not waste time on this until I'm able to reproduce it.

By the way, nice job on the multi-path taxi flights, it is much much smoother! 👍 👍

**Comment by killerwife** [comment] 2017-08-25 10:14
It still needs tweaking though. For example the menethil to stormwind one isnt cut properly atm.

**Closed** 2017-08-31 21:44 UTC
