### ISSUE TITLE
🐛 [Bug Report]Smooth Waypoints

### ISSUE THREAD

**Issue by miraco** [cmangos/issues#2050] opened 2019-10-27 00:28 UTC
## 🐛 Bugreport
Creatures are turning to hard when changing orientation/moving a curve. 

Thats the discussion from TrinityCore:
https://github.com/TrinityCore/TrinityCore/issues/22863

and a video how its currently working:
https://youtu.be/nWhuJ01wZhs 
### Expected behavior
Yes this video is from a higher Patch, but this worked in every expansion.
https://www.youtube.com/watch?v=osnXEEXwUH4

### Version & Environment
I guess this needs to get for all versions.
Client Version: 

CMaNGOS Repo & Commit Hash: 

d91eac1
https://github.com/cmangos/mangos-tbc/commit/d91eac113fa905aae801058f6a636922a8684998
Operating System: 
Windows
### Steps to reproduce
1. login
2. teleport stormwind
3. Profit

**Comment by Warlockbugs** [comment] 2020-01-08 19:26
NPC movement was revamped clientside starting somewhere around Cata. I suggest looking up videos of escort quests done in Classic-Wrath and then same quests (if possible due to world revamps) done in later patches: you will notice that unnatural turn rate was present in the game client.

Waypoints need a rewrite, but what is presented in the video as "expected behavior" is unfortunately not accurate for old versions of client engine.

**Comment by Grz3s** [comment] 2020-01-08 21:54
https://youtu.be/O_5gRE8vy0k?list=PLF5A2ABB39D69E22C&t=29    (guard) - 2009

**Comment by Warlockbugs** [comment] 2020-01-09 07:11
At the timecode you've linked above you can see that guard faces the next destination instantly, instead of doing npc equivalent of "slow rightclick drag turn" in the direction of the next waypoint. That is what i am talking about.

**Comment by Firefly1353** [comment] 2020-10-12 14:52
I don't know if this is of any use, but I stumbled upon something interesting recently:
The WotLK client seems to be able to use smooth rotation if unit flag 8 is set for a creature. I tested this with the guard from the video above (ID 3209) using an unmodified WotLK client and mangos-wotlk 6f9b0486:

```sql
UPDATE `creature_template` SET `UnitFlags` = `UnitFlags` | 8 WHERE `Entry` = 3209;
```

After that the guard rotated smoothly while following its path. This even works with random movement, so it does not seem to depend on the movement generator. If unit flag 8 is removed the old behaviour showed again:

```sql
UPDATE `creature_template` SET `UnitFlags` = `UnitFlags` & ~8 WHERE `Entry` = 3209;
```

**Comment by Warlockbugs** [comment] 2020-11-08 06:40
Flag 0x8 is what marks all player controlled units (players and their spawns like pets). It should never be set for anything in the database.
If you are looking for more technical curiosities, removing this flag from players enables NPC-like movement behaviors, such as client forcefully facing character towards the target.
Removing and adding this flag for an eye candy locally for each player is possible, but not viable as it introduces many unexpected side effects client-side, as there appears to be a lot of logic attached to this flag. You can test this in UI as well by calling WoW Lua API function [`UnitPlayerControlled`](https://wow.gamepedia.com/API_UnitPlayerControlled). Reviewing all possible side effects of changing this flag is not a trivial task and requires significant time dedication, which may be ultimately fruitless if one or more game-breaking side effects found.

Closing this issue as this report is effectively a custom feature request for unintended functionality for the timeline.

**Closed by Warlockbugs** 2020-11-08 06:40 UTC
Labels: Info: Needs Replication, System: Vehicles, Version: TBC

**Comment by Firefly1353** [comment] 2020-11-09 00:07
Thanks for the information, very interesting. Although this issue is closed I want to share another interesting part which affects smooth rotation on the client: MovementTemplateId. If setting this for example to 741 the creature will use smooth rotation:
```sql
UPDATE `creature_template` SET `MovementTemplateId` = 741 WHERE `Entry` = 3209;
```

It is necessary to clear the client's cache in order to see the change. The speed of the rotation seems to be connected to the field "SmoothFacingChaseRate" of "CreatureMovementInfo.dbc". Sadly, I could not find any further information on how this is actually used by the client or which other effects this can cause.

**Comment by ghost** [comment] 2022-10-01 12:13
A bit late, but if anyone's interested, you can use cyclic spline movement (SMSG_FLIGHT_SPLINE_SYNC) for smooth ground movement. I implemented this as a test:
https://gitlab.com/opfesoft/mod-stoabrogga/-/blob/c6ae73b783a9f264cde8ddf79ee5c29b44cf1660/src/stoabrogga.cpp#L290
It's for my own server software, but should be similar for other cores. This is how it looks in-game:
https://user-images.githubusercontent.com/61636993/193408176-5fd9d9f3-6133-4baa-9bae-728d7ab2c117.mp4

However, it's meant to be used for flying creatures only, e.g.:
https://user-images.githubusercontent.com/61636993/193408232-ea9980f8-a65a-4295-be14-2814faf842a4.mp4

**Comment by killerwife** [comment] 2022-10-01 12:51
We alrdy have it. Pathmovementgenerator, flying param set to true. Db movementtype 3. Sends spline sync tbc+ on heartbeat

**Comment by ghost** [comment] 2022-10-02 10:57
Thanks, did not know this. Just wanted to show another way of faking smooth movement for ground units. But using "MovementTemplateId" as mentioned above seems to be much easier to apply if someone wants to get rid of the abrupt turning.

**Comment by killerwife** [comment] 2022-10-02 12:07
Yes and the ground version of PathMovementGenerator is good alternative when pathfinding is being a total c***. Also, we already also have smoothed pathing on ground, albeit its not as nice as the cata+ smooth ground movement. It can be found in WaypointMovementGenerator, where intermediary points are being generated and sent for a rougly 5 second interval like on retail. PathMovementGenerator sends whole spline at once (like on retail too).
