### ISSUE TITLE
Spell Penetration is doing the oppersite of it's purposed function

### ISSUE THREAD

**Issue by 5man999** [cmangos/issues#1899] opened 2019-03-08 19:02 UTC
## 🐛 Bugreport

I'm not sure this is one of many problems with the current handling of spell resistances. However from my testing there seems to be a problem with Spell Penetration whereby it does the oppersite of it's purposed function.

This is with 214 spell penetration:
https://imgur.com/86fpQv7

### Expected behavior

It should reduce the amount resisted or stop spell resistance all together on a target.

### Version & Environment

Client Version: []  "2.4.3" (TBC)

CMaNGOS Repo & Commit Hash:  []() https://github.com/cmangos/mangos-tbc/commit/4add5bc92765d640e0e36e4c6d934a347d2c3610

Database Repo & Commit Hash:   cmangos/tbc-db@5b5e775

Operating System: [] Windows

### Steps to reproduce
1. Get some spell penetration
2. Use magic spell on a target with said resistance
3. Look at combat log to see every cast partial resisting
4. ...
5. Profit

### Crashlog

- [X] None

**Comment by 5man999** [comment] 2019-03-08 19:14
I went back to before the recent magic resistance commits and it seems to resolve the Spell Penetration bug however, Curse of the Elements is broken (causing similar results to the problem now). Although on the most recent version curse of the elements seems to be working, or atleast not as broken.

**Comment by 5man999** [comment] 2019-03-08 20:56
Reverting this change - https://github.com/cmangos/mangos-tbc/commit/fade76b5e31220b9267518dd165cca0d67f54813#diff-ca2439f8cc7d37988fda1b6f07e25e7fL3894 TO LINE 3914 seems to fix the problem.

**Comment by Warlockbugs** [comment] 2019-03-09 14:22
Fixed in;
https://github.com/cmangos/mangos-classic/commit/c00c2b2caf19cfb00f9db8e95f682b9296be423f
https://github.com/cmangos/mangos-tbc/commit/f90fc13fb096e3a6706ddca8fb3e9e71c5b8f01c
https://github.com/cmangos/mangos-wotlk/commit/cc1499ed261cd4c7b4f255a7cddf347d5ee0fe72

**Closed by Warlockbugs** 2019-03-09 14:22 UTC

**Comment by 5man999** [comment] 2019-03-09 14:34
@Warlockbugs Thanks! Will test it out asap

**Comment by 5man999** [comment] 2019-03-09 15:07
@Warlockbugs Hmmm resistance doesn't seem to be doing anything in a PVP setting with the current iteration. (Seems to be less in PVE but I'm not sure right now). In regard to PVP no amount of a magic school resistance causes the oposing player to experience partial or full resists when using spells of the same type.

**Comment by Warlockbugs** [comment] 2019-03-09 16:19
High levels require proportionally high resistance values to get more consistent RNG result. You should try testing resistance cap.

**Comment by 5man999** [comment] 2019-03-09 16:41
When I did the tests the attacking char was using shadowbolt with no spell pen. The oposing character had 165 shadow res using a combination of MotW, Shadow Protection, Shadow Resistance Aura. The latest iteration causes no partial resists to appear. Going back to the version that seems to work for me (reverted the SP commits) 165 shadow resistance causes nearly every cast of shadowbolt to partial resist or full resist. 

Admittedly I don't have a great understanding of how spell resistance is calculated but comparing to how I had it working before, it feels like it's not doing anything at the moment.

**Comment by Warlockbugs** [comment] 2019-03-09 16:54
Cannot reproduce. A naked 70 druid casting max rank of Wrath at 70 warrior with 253 nature resistance results in overwhelming majority of partials.

**Comment by 5man999** [comment] 2019-03-09 16:56
@Warlockbugs I'll check again and post screenshots if i get the same results. I'll also double check I'm compiling the latest.

**Comment by 5man999** [comment] 2019-03-09 17:29
I've found the reason for why spell resistance isn't doing anything for me, however I have no idea why the current iteration is producing this result. I could try compiling again, but ye for me spell resistance isn't applying correctly it's adding and also seems to be removing.

https://imgur.com/a/Dz0evTQ

**Comment by 5man999** [comment] 2019-03-10 14:50
I tested with the release here and I'm getting the same issue. spell resistance isn't applying to players on the lastest version.

**Comment by Warlockbugs** [comment] 2019-03-10 15:07
Still cannot reproduce.
![Screenshot](https://i.imgur.com/Uwyqkqe.png)

**Comment by 5man999** [comment] 2019-03-10 17:44
Werid! Just to add to the mystic of this issue. Reverting https://github.com/cmangos/mangos-tbc/commit/daa0b45745f765858cd803acc4f99b81ab7c2b68 solves the issue for me.

**Comment by 5man999** [comment] 2019-03-12 17:51
@Warlockbugs Did you try buffing yourself? Some stuff is working but Mark of the wild and Shadow Protection is definitly not applying correctly in the latest core.

**Comment by Warlockbugs** [comment] 2019-03-16 04:19
I've inspected the inner workings of aura handler `Aura::HandleAuraModResistanceExclusive()` and it is indeed no longer compatible with latest changes. There are more subtle issues than that, so a rework for resistance auras was long overdue is now required due to issues being exposed.

**Comment by 5man999** [comment] 2019-03-16 12:17
I see, you're the man! Thanks for the responce, I thought I was going a bit nutting trying to figure out why I was having problems :P As always love your work and will continue to help where I can.

**Comment by Warlockbugs** [comment] 2019-03-16 17:54
The issue you mentioned should now be solved among others.
