### ISSUE TITLE
[CLASSIC] Queued Maul Not Cancelled When Shifting Out of Bear Form

### ISSUE THREAD

**Issue by Trystanosaurus** [cmangos/issues#1530] opened 2018-01-07 08:45 UTC
**Current behavior**: 
With a druid in bear form, you can cast maul (id 6807) and then cancel bear form, your next attack in night elf/tauren form will still be the maul you had queued. This may affect other "your next attack" type powers in other forms/warrior stances.

**Expected behavior**: 
The maul is removed from the queue when you change out of bear form.

**Steps to reproduce**:

1. Get a druid in bear form.
2. Cast Maul just after an attack.
3. Cancel bear form and wait for the next attack.

**Client version**: 1.12.1

**Commit hash**: 067dd86

**Database version**: Classic-DB 1.8.5 - de40a13

**Operating system**: Windows 10

[//]: # (If this is a crash report, include the crashlog from a debug build with https://gist.github.com/)

**Comment by killerwife** [comment] 2021-12-19 16:14
Recently fixed by making no-rage heroic strike or maul fail and proceed to do normal melee. It fails on next melee as intended.

**Closed by killerwife** 2021-12-19 16:14 UTC
Labels: System: Spell, Version: Classic (1.12), Info: Needs Replication / Information / Feedback, Class.Druid
