### ISSUE TITLE
[TBC] Crash Logs Files Are Not Being Generated When Core Crashes

### ISSUE THREAD

**Issue by keyshuwen** [cmangos/issues#1568] opened 2018-02-24 07:14 UTC
**Current behavior**: 
Debug run.
Program crash, I can't see any crash log generated.
Can anyone tell me why? Thank you.

**Commit hash**: 
New

**Operating system**: 
vs ++ 2015
windos10 x64

[//]: # (If this is a crash report, include the crashlog from a debug build with https://gist.github.com/)

**Comment by keyshuwen** [comment] 2018-03-13 13:40
Crash logs files will not be produced.
Including the Crashes folder.

Is it the only thing that I met with such a strange problem? :blush:

**Comment by dagochen** [comment] 2018-08-09 14:55
@Phatcat @Tobschinski 
same here, any ideas?

**Comment by jimmybrancaccio** [comment] 2018-11-24 19:34
@keyshuwen @dagochen Is this still an issue for you on the latest commits?

**Comment by Levitanious** [comment] 2019-02-10 15:09
No info about how the core was set up (it can be anything from folder permissions to core bug, so any additional info would help).

We need someone to reproduce it again.

**Comment by CabrasDaPeste** [comment] 2019-02-10 15:17
I aways run my core on debug mode, and I never saw any generated file or folder regarding any crash that I have

**Comment by Levitanious** [comment] 2019-02-10 17:45
"Crashes" folder on windows is a windows-specific thing. On *nix-es you have diffirent facilities for that kind of stuff.

**Comment by jimmybrancaccio** [comment] 2019-06-08 23:50
Closing this issue out. If anyone is still having a problem, please open a new issue with full details.

**Closed by jimmybrancaccio** 2019-06-08 23:50 UTC
Labels: Info: Needs Feedback, Info: Needs Replication, Type: Core Crash, Version: TBC

**Comment by Phatcat** [comment] 2019-06-09 09:38
Calling out Jimmy for bullshit closing of random issues. Before closing make sure you at least can't reproduce it yourself, don't just guess.

Especially since you can see it's an issue several people have confirmed.

Re-open this issue please.

**Comment by BenDol** [comment] 2019-06-09 09:41
_please open a new issue with full details._ the OP hasn't replied since `Mar 14, 2018` seems reasonable to me.

**Comment by Phatcat** [comment] 2019-06-09 10:13
I digress, but only because Levi says he's not able to reproduce (so he actually tested) as well as the 2 original reporters being unresponsive even after being tagged. But this is just 1 of the many issues that were closed, and while this one may not have been a premature closure, a lot of the others are.

**Comment by dagochen** [comment] 2019-06-11 18:22
The missing answer in my case did not meant "yes, problem still exists" nor did it say "problem is solved now!"... I didn't answer because a) no time and b) no more interest 

So in this point @Phatcat is right, you should try it out yourself....

Sorry guys :)

**Comment by cyberium** [comment] 2019-06-11 18:45
If OP, or even yourself @dagochen didn't even bother to respond within 6 month why a dev or a moderator should do bother?

When something really bother me i do my best to keep it others attention ;)

Open an new issue with new template if you confirm it, you'll be still able to link this closed issue.

**Comment by kepo123** [comment] 2021-04-28 13:20
Just to say that this bug still exists and as I can see it was reported back in 2018 and now is 2021... 👀😂
