### ISSUE TITLE
🐛 [Bug Report] [Classic] Loot Chest already in use.

### ISSUE THREAD

**Issue by zeeb92** [cmangos/issues#2576] opened 2021-12-04 05:57 UTC
### Bug Details

Encountered a spawned chest that was already opened and "in use" without ever being used.
![issuechestcmangos1](https://user-images.githubusercontent.com/60988327/144699228-0fc26249-9872-4559-9ad2-16176a9e2848.png)

### Steps to Reproduce

1. Make Undead
2. Goto Area
3. Get lucky with chest spawn
4. Get lucky getting the same issue. (No idea if it's a one time thing, but why would it be, looks like incorrect ID in the DB)

### Expected behavior

A closed loot chest that is not "in use".

### Suggested Workaround

Changing item id at that spawn location from an "in use" loot chest to a normal "unused" loot chest.
Smells like a database issue.

### Core SHA1 Commit Hash

80712b8bcdea7ffb9f9adeb71992f66b435a400e

### Database SHA1 Commit Hash

4381f995a026c74cb156d5902529b58275c3b4c2

### Operating System

Windows 10 x64

### Client Version(s)

- [X] 1.1.12 (Classic)
- [ ] 2.4.3 (The Burning Crusade)
- [ ] 3.3.5a (Wrath of the Lich King)

**Comment by rosen40** [comment] 2021-12-04 13:49
wrong state for the gobject spawn entry

**Comment by zeeb92** [comment] 2021-12-04 18:20
Can we have a "confirmed" slapped on this?

**Comment by AnonXS** [comment] 2021-12-04 19:57
we cant as we're not able to reproduce this issue 100% and it happens with ore nodes mostly.

**Comment by MilkmanMHOC** [comment] 2022-02-18 02:26
I can confirm this is happening still.  Noticed it in Wailing Caverns as there is always a few chests in there, they all looked 'open' and were 'already in use'.  This bug was not present in the June/July build i was running until very recently.   Not sure that is much help, but might narrow down being able to recreate the issue.

**Comment by cala** [comment] 2022-02-18 07:08
I will look into this.

**Comment by MilkmanMHOC** [comment] 2022-02-18 20:32
A quick check of WC showed all the chests working now.

**Comment by cala** [comment] 2022-02-18 22:39
Thanks. Closing this, then.

**Closed by cala** 2022-02-18 22:39 UTC
Labels: Info: Needs Replication
