### ISSUE TITLE
Blessing of Sacrifice, Paladin, TBC 2.4.3

### ISSUE THREAD

**Issue by ETH-Raphael-Bosshart** [cmangos/issues#3096] opened 2022-08-01 09:31 UTC
### Bug Details

Blessing of Sacrifice isn't working correctly in PvP. While it is active on a mate, who's getting damaged in the next step, the damage conveyed to the paladin doesn't stop fear, blind nor sheep (see video) as it actually should. 

https://user-images.githubusercontent.com/72579068/182120650-1fb90042-e51c-4da4-be73-f8d43aefd849.mp4

### Steps to Reproduce

1.Cast Blessing of Sacrifice on mate
2.Sheep Paladin
3.Damage mate
4.Paladin stays in sheep

### Expected behavior

The damage conveyed from the mate should break sheep, blind or fear.

### Suggested Workaround

Please fix as soon as possible since it is a key spell for paladin, especially heal.

### Core SHA1 Commit Hash

f19a58e8a

### Database SHA1 Commit Hash

db459949

### Operating System

Linux (Ubuntu 20.04 LTS)

### Client Version

2.4.3 (The Burning Crusade)

**Comment by killerwife** [comment] 2022-08-01 10:07
Well I am kinda going to need evidence for this. Because I changed it into what it is right now. @henhouse any idea?

**Comment by ETH-Raphael-Bosshart** [comment] 2022-08-01 11:06
On last core the sheep was broken. 

Blessing of Sacrifice: Blesses a party or raid member, reducing their damage taken by 30%, **but you suffer 100% of damage prevented.**
Sheep: Transforms the enemy into a sheep, wandering around incapacitated for 1 min. While affected, the victim cannot take actions but will regenerate health very quickly. **Damage will cancel the effect**. Limit 1.

Blessing of Sacrifice can be used to avoid being the victim of in [PvP]. Bless a person who is quite likely to draw enemy fire. This way, if you're afflicted by  [[Polymorph]](https://wowpedia.fandom.com/wiki/Polymorph),  [[Sap]](https://wowpedia.fandom.com/wiki/Sap),  [[Repentance]](https://wowpedia.fandom.com/wiki/Repentance) or any other of incapacitating effect, the damage transferred to you would break Crowd Control.
Source: https://wowpedia.fandom.com/wiki/Blessing_of_Sacrifice

**Comment by henhouse** [comment] 2022-08-04 17:39
> Well I am kinda going to need evidence for this. Because I changed it into what it is right now. @henhouse any idea?

@killerwife The Wowpedia article does clarify that it does indeed works this way (dmg transferred breaks cc on pala). Did you want me to specific check some other mechanic? Blind and Sheep are not directly mentioned but they are supposed to instantly break on damage. Fear has a chance to be removed, so that should still work as intended on damage transfer.

**Comment by ETH-Raphael-Bosshart** [comment] 2022-08-07 16:51
Will it be fixed soon? There's another bug too:
- Priests are able to dispel bubble with normal dispel (and not mass dispel)
@killerwife @henhouse

**Comment by miraco** [comment] 2022-09-05 22:33
I know its not the best source but so far its the best i can find for it.
https://wowpedia.fandom.com/wiki/Blessing_of_Sacrifice?oldid=1555497

> Blessing of Sacrifice can be used to avoid being the victim of [Crowd Control](https://wowpedia.fandom.com/wiki/Crowd_Control) in [PvP](https://wowpedia.fandom.com/wiki/PvP). Bless a person who is quite likely to draw enemy fire. This way, if you're afflicted by [[Polymorph]](https://wowpedia.fandom.com/wiki/Polymorph), [[Sap]](https://wowpedia.fandom.com/wiki/Sap), [[Repentance]](https://wowpedia.fandom.com/wiki/Repentance) or any other of incapacitating effect, the damage transferred to you would break Crowd Control.

**Comment by ghost** [comment] 2022-09-05 23:12
https://youtu.be/ClnYXyqLmvg?t=12

**Comment by AnonXS** [comment] 2022-09-05 23:32
![grafik](https://user-images.githubusercontent.com/19734826/188520445-437e9c11-63ef-4ddf-810e-e87d281a268a.png)
![grafik](https://user-images.githubusercontent.com/19734826/188520603-edc82b1d-4c79-41ae-a414-0b12af31acb4.png)
![grafik](https://user-images.githubusercontent.com/19734826/188520616-bac35b1f-fb8c-40eb-a313-af42cb9f830f.png)

**Comment by killerwife** [comment] 2022-09-11 17:39
https://github.com/cmangos/mangos-tbc/commit/bbd0ddfc4001fefed45c191fe6919265aa5ddb55

**Closed as completed by killerwife** 2022-09-11 17:39 UTC
Labels: System: Spells, Expansion: TBC (2.4.3), Info: Needs Testing, Info: Needs Development, Class: Paladin
