### ISSUE TITLE
🐛 [Bug Report] Guild Control can be accessed by anyone, no matter the rank

### ISSUE THREAD

**Issue by kepo123** [cmangos/issues#2462] opened 2021-05-18 18:51 UTC
## 🐛 Bugreport

Guild Control can be accessed by anyone, no matter the rank.

### Expected behavior

Only the Guild Leader should have access to the Guild Control.

### Version & Environment

Client Version: "2.4.3" (TBC)

CMaNGOS Repo & Commit Hash: https://github.com/cmangos/mangos-tbc/commit/aa75d69f31f4531da5bb92bf594915845fb57ef3

Database Repo & Commit Hash: https://github.com/cmangos/tbc-db/commit/b7be096f3331b1a68d0a6b401a363213b75cc45e

Operating System: Windows Sever 2012 R2

### Steps to reproduce
1. create a guild
2. go make custom ranks
3. login with the lowest -rank character that is in the guild
4. open the guild panel:
5. 
![image](https://user-images.githubusercontent.com/17118210/118706421-02c81d00-b822-11eb-8ad1-ee90ca57c1ab.png)

### Crashlog

- None

**Comment by nate123456** [comment] 2021-06-06 07:31
In classic, in a guild with custom ranks, Guild control for the lowest rank is disabled as expected. 

The tag `Version: TBC` should be added to this issue so someone with TBC can attempt to replicate.

**Comment by kelbren** [comment] 2021-06-14 02:18
I was not able to replicate this, tried it on TBC and WOTLK both worked as expected.

**Comment by AnonXS** [comment] 2021-06-14 15:52
you can access the guild control with
```/script GuildFrameControlButton:Enable();```
but trying to confirm changes results in
`You don't have permission to do that.`
not sure if the script should work though.

**Comment by cyberium** [comment] 2022-02-15 09:26
Not able to reproduce either. Until someone can provide another way to reproduce this i'll closing this issue

**Closed by cyberium** 2022-02-15 09:26 UTC
Labels: Version: TBC (2.4.3), Info: Needs Replication
