### ISSUE TITLE
🐛 [Bug Report]  Blizzard interrupted fix

### ISSUE THREAD

**Issue by Nightingale9002** [cmangos/issues#3673] opened 2024-02-08 12:04 UTC
### Bug Details

if blizzard resisted at first dot, the spell will be interrupeted

### Steps to Reproduce

1. learn spell 10      (bilzzard)
2.cast blizzard to a creature higher level than the caster 
3.
4.

### Suggested Workaround

#   \src\game\Spells\Spell.cpp
#########################################################################
line 4258

    if (IsChanneledSpell(m_spellInfo) && (ihit.missCondition == SPELL_MISS_RESIST || ihit.missCondition == SPELL_MISS_REFLECT))
    {
        #add
        if (IsPersistentAuraEffect(*m_spellInfo->Effect))
        {
            //
        }
        else
        {
            m_duration = 0;                              // cancel aura to avoid visual effect continue
            ihit.effectDuration = 0;
            ++miss;
        }
    }

### Core SHA1 Commit Hash

https://github.com/cmangos/mangos-tbc

### Database SHA1 Commit Hash

*

### Operating System

windows

### Client Version

2.4.3 (The Burning Crusade)

**Comment by insunaa** [comment] 2024-02-08 12:06
duplicate of https://github.com/cmangos/issues/issues/3614 which is already resolved.

**Closed as completed by insunaa** 2024-02-08 12:06 UTC
Labels: Info: Needs Replication
