### ISSUE TITLE
🐛 [Bug Report] 

### ISSUE THREAD

**Issue by nsrcc** [cmangos/issues#3767] opened 2024-09-16 23:39 UTC
### Bug Details

First of all, I would like to express my gratitude to you!
The first task after human birth cannot be submitted.

<img width="1203" alt="Thanks01" src="https://github.com/user-attachments/assets/e1444672-436e-4245-8546-9182ca241c51">
<img width="1152" alt="Thanks02" src="https://github.com/user-attachments/assets/a2695abe-767f-43f2-95cb-9bd5ce625d0d">

### Steps to Reproduce

1.
2.
3.
4.

### Core SHA1 Commit Hash

Sorry, I don't know how to get it.

### Database SHA1 Commit Hash

Sorry, I don't know how to get it.

### Operating System

win11 23H2

### Client Version

3.3.5a (Wrath of the Lich King)

**Comment by cpevors** [comment] 2024-09-17 00:18
Totally unhelpful addition, but the phrasing “…after human birth” made me nearly spit out my Scotch.

**Comment by insunaa** [comment] 2024-09-17 05:58
duplicate of https://github.com/cmangos/wotlk-db/issues/1322

**Closed as completed by insunaa** 2024-09-17 05:58 UTC
Labels: Info: Needs Replication
