### ISSUE TITLE
🐛 [Bug Report] [TBC] Shadow Lord disappears after Mind-controll due no combat

### ISSUE THREAD

**Issue by ykslol** [cmangos/issues#2182] opened 2020-04-26 16:01 UTC
## 🐛 Bugreport
While Shadow Lord casts mind-controll, it gets out from combat and when the cast expires - disappears.
Also when u get this debuf u come to boss and thats all. 

### Expected behavior
I think, he should continue to be in combat after debuf.
Also, wowhead discription of this debuf say - "Incites chaos in the minds of all enemies, causing them to randomly attack each other."
All people in party should become enemies and fight each other while debuf lasts. 

This debuf looks like an one debuf in molten core, where someone in your party could to atack you under it. 

### Version & Environment
Client Version: "2.4.3" (TBC)
CMaNGOS Repo & Commit Hash: [TBC](https://github.com/cmangos/mangos-tbc/tree/7c50c57e)
Database Repo & Commit Hash: [TBC](https://github.com/cmangos/tbc-db/tree/f7ef4c5)

Boost: 1.62.0
OpenSSL: 1.1.0l
gcc (GCC) 7.3.0
mysql Ver 15.1 Distrib 10.1.44-MariaDB, using readline 5.2
runing under docker image ubuntu:18.04 - kernel 4.4.0-174-generic
Operating System: Linux Flavor

1. Get 70 lvl
2. Get [Shadow Labyrinth Key](https://www.wowhead.com/item=27991/shadow-labyrinth-key)
3. Go [Shadow Labyrinth](https://www.wowhead.com/shadow-labyrinth)
4. Go to [Blackheart the Inciter](https://www.wowhead.com/npc=18667/blackheart-the-inciter)
5. Start fight with him
6. Wait for first cast of [Incite Chaos](https://www.wowhead.com/spell=33676/incite-chaos)
7. After cast complets - [Blackheart the Inciter](https://www.wowhead.com/npc=18667/blackheart-the-inciter) disappear due no combat
![WoWScrnShot_042620_183947](https://user-images.githubusercontent.com/20792687/80312803-202de180-87f0-11ea-81a9-ed7ca772fa26.jpg)
![WoWScrnShot_042620_183941](https://user-images.githubusercontent.com/20792687/80312806-215f0e80-87f0-11ea-90d5-808393e6fc01.jpg)

**Comment by cala** [comment] 2020-04-27 15:42
Closing as duplicate of https://github.com/cmangos/issues/issues/1908
Thank you.

**Closed by cala** 2020-04-27 15:42 UTC
Labels: Info: Needs Replication
