### ISSUE TITLE
Zul'Aman Nalorakk Runs Through the Ground After a Reset

### ISSUE THREAD

**Issue by yatzi888** [cmangos/issues#1839] opened 2019-01-20 13:39 UTC
**Current behavior**:  When a group wipes or the boss is reset he runs through the ground, towards the edges of the map. 

https://youtu.be/ruhN23pr-Aw

**Expected behavior**: Should go back to original position

**Steps to reproduce**:

1. .go c Nalorakk
2. Aggro then .die on yourself
3. Watch Nalorakk leave the game

**Client version**: 2.4.3

**Commit hash**: ea58208edb97ca294961ab2a2045cfda77860ec3

**Database version**: 5d467bd4dc3bb73a4a4b4ed8629050c8cf497309

**Operating system**: Windows Server 2012 

[//]: # (If this is a crash report, include the crashlog from a debug build with https://gist.github.com/)

**Comment by Ve1vet** [comment] 2019-01-20 18:46
You will find him later in the middle of the map among frogs 🤣 
He glitching because of event. If you die on event pharse, event will just hangs.
This was my patch to prevent hanging event. Not remember if he fixes his running out... I wasn't fix anything for 2 years already...
```diff
@@ -116,7 +116,7 @@ void instance_zulaman::OnCreatureDeath(Creature* pCreature)
         case NPC_TRIBES_MAN:
         case NPC_WARBRINGER:
         case NPC_AXETHROWER:
-            if (m_aNalorakkEvent[m_uiBearEventPhase].sBearTrashGuidSet.find(pCreature->GetObjectGuid()) != m_aNalorakkEvent[m_uiBearEventPhase].sBearTrashGuidSet.end())
+            /*if (m_aNalorakkEvent[m_uiBearEventPhase].sBearTrashGuidSet.find(pCreature->GetObjectGuid()) != m_aNalorakkEvent[m_uiBearEventPhase].sBearTrashGuidSet.end())
             {
                 ++m_aNalorakkEvent[m_uiBearEventPhase].uiTrashKilled;
                 if (m_aNalorakkEvent[m_uiBearEventPhase].uiTrashKilled == m_aNalorakkEvent[m_uiBearEventPhase].sBearTrashGuidSet.size())
@@ -133,7 +133,7 @@ void instance_zulaman::OnCreatureDeath(Creature* pCreature)
                         }
                     }
                 }
-            }
+            }*/
             break;
     }
 }
@@ -401,6 +401,17 @@ void instance_zulaman::SendNextBearWave(Unit* pTarget)
             }*/
         }
     }
+     ++m_uiBearEventPhase;
+    if (Creature* pNalorakk = GetSingleCreatureFromStorage(NPC_NALORAKK))
+    {
+        if (m_uiBearEventPhase == MAX_BEAR_WAVES)
+            pNalorakk->RemoveFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_PASSIVE);
+        else
+        {
+            pNalorakk->SetWalk(false);
+            pNalorakk->GetMotionMaster()->MovePoint(1, aBearEventInfo[m_uiBearEventPhase].fX, aBearEventInfo[m_uiBearEventPhase].fY, aBearEventInfo[m_uiBearEventPhase].fZ);
+        }
+    }
 
     m_bIsBearPhaseInProgress = true;
 }
```

**Comment by Ve1vet** [comment] 2019-01-20 19:02
This is still not blizzlike. Nalorakk start run out earlier than it should( because ++m_uiBearEventPhase called to early  ) + i only learn sd2 at that time, but at least event not glitching any more.

**Comment by yatzi888** [comment] 2019-01-23 02:17
I'd be tempted to just remove the RP. I do remember reading that @killerwife had a fix he was going to export or maybe I'm remembering wrong. I can get around the RP event but him leaving the map in a panic is a real show stopper haha xD

**Comment by Ve1vet** [comment] 2019-01-23 03:10
@yatzi888 you can just create new "test" branch, apply those patches & test.
If not working, than something wrong with evade function or coordinates.

**Comment by yatzi888** [comment] 2019-01-25 11:43
@Ve1vet Going to compile with your changes tonight or tomorrow night. Will get back to you. Thanks :)

**Comment by yatzi888** [comment] 2019-01-26 02:58
@Ve1vet Well i got it to work lol - https://github.com/yatzi888/mangos-tbc/commit/60b955d8776e354352141ff8ad975e8fbdd1a841 Pretty sure this isn't PR suitable ;) haha

**Comment by MantisLord** [comment] 2019-06-25 00:35
Duplicate of https://github.com/cmangos/issues/issues/1023

Fixed by:
https://github.com/cmangos/mangos-tbc/commit/0299aebf9e2ef34201dabe9c5244d7f1647ac746
https://github.com/cmangos/mangos-tbc/commit/d3568066edb28b7982f9de47feae29c827e2f228
https://github.com/cmangos/mangos-tbc/commit/edb97e1d5dfac79e68738e03912f20c75e1ef263

**Closed by MantisLord** 2019-06-25 00:35 UTC
Labels: Info: Needs Testing, System: NPC, Type: Patch, Version: TBC
