### ISSUE TITLE
🐛 [Bug Report] [WoTLK] Hunter's Traps causes server to crash

### ISSUE THREAD

**Issue by adellaci** [cmangos/issues#3654] opened 2024-01-14 22:59 UTC
### Bug Details

When  in Gnomeregan, and BlackFathom Deeps with my hunter if any of his trap are triggers it causes the server to crash. Does not seem to happen outside of dungeons 

### Steps to Reproduce

1.Enter any Dungeon with a hunter 
2.Set trap and let NPC trigger it
3.
4.

### Expected behavior

Not crash server

### Core SHA1 Commit Hash

27999d818ce8b308e30a24526b7705335d5b3dbc

### Database SHA1 Commit Hash

b276c0f5b99b0daaca23edd4117eac5c1f73c960

### Operating System

Ubuntu Server LTS 20.04 / Ubuntu Desktop 22.04 Client

### Client Version

3.3.5a (Wrath of the Lich King)

**Comment by Karth-Xyver** [comment] 2024-01-17 15:00
Could you specify what NPC and what trap exactly cause the crash? I've tried Immolation traps on a few NPCs in both dungeons and it didn't crash for me.

**Comment by adellaci** [comment] 2024-01-17 21:01
I will in a week or so, i am currently running memory leak test on WoTLK #3140

**Comment by adellaci** [comment] 2024-01-21 17:19
@Karth-Xyver 
Core: 92612ede3331f05ee148364beee09ef64100d6c1
Database: a24bd2dd7cec2345c5b4c0798a359d6d0bab0fb8

Here is a video: https://drive.proton.me/urls/F4WQK5BH14#cs6tt1o4XSeG

**Comment by insunaa** [comment] 2024-01-29 14:29
Can't reproduce.
Try disabling all addons and check if the crash still occurs.

**Comment by adellaci** [comment] 2024-01-29 17:36
Because of other issues with that character, I am going create a new hunter, and report back.

Jan 29, 2024 09:29:15 insuna ***@***.***>:

**Comment by Nrezinorn** [comment] 2024-02-07 23:50
Core: eff384a85689141e62bf7c58cbb7ad4e6c6738c7
Database: b186dcdf34e732d42899952b57e849326428e74c

Can Confirm this is happening with Immolation Trap.  The known areas / mobs were around the stagnant oasis and the centaurs.  It is not always an immediate crash. 

I watched it happen:
Trap is triggered, DOT applied, it ticks 2-3 times applying damage, and on a tick interval - server crashes.

```
#0  0x000055fe95ab0f06 in Object::GetUInt64Value (index=<optimized out>, this=<optimized out>)
    at /home/wowserver/mmo/mangos-wotlk/src/game/Entities/Object.h:463
463                 MANGOS_ASSERT(index + 1 < m_valuesCount || PrintIndexError(index, false));
[Current thread is 1 (Thread 0x7f0a394ac6c0 (LWP 4544))]
bt
#0  0x000055fe95ab0f06 in Object::GetUInt64Value (index=<optimized out>, this=<optimized out>)
    at /home/wowserver/mmo/mangos-wotlk/src/game/Entities/Object.h:463
#1  Object::GetGuidValue (index=<optimized out>, this=<optimized out>) at /home/wowserver/mmo/mangos-wotlk/src/game/Entities/Object.h:487
#2  Object::GetObjectGuid (this=<optimized out>) at /home/wowserver/mmo/mangos-wotlk/src/game/Entities/Object.h:409
#3  Unit::SpellDamageBonusTaken (stack=1, damagetype=DOT, pdamage=21, spellInfo=0x7f0a20c6d150, schoolMask=SPELL_SCHOOL_MASK_FIRE, caster=0x0,
    this=0x7f09f71a6230) at /home/wowserver/mmo/mangos-wotlk/src/game/Entities/Unit.cpp:8080
#4  Unit::SpellDamageBonusTaken (this=this@entry=0x7f09f71a6230, caster=caster@entry=0x0, schoolMask=SPELL_SCHOOL_MASK_FIRE,
    spellInfo=spellInfo@entry=0x7f0a20c6d150, pdamage=21, damagetype=damagetype@entry=DOT, stack=1)
    at /home/wowserver/mmo/mangos-wotlk/src/game/Entities/Unit.cpp:8064
#5  0x000055fe95d014f9 in Aura::PeriodicTick (this=0x7f09e822ba80) at /home/wowserver/mmo/mangos-wotlk/src/game/Spells/SpellAuras.cpp:8163
#6  0x000055fe95cf01c8 in Aura::UpdateAura (diff=101, this=<optimized out>) at /home/wowserver/mmo/mangos-wotlk/src/game/Spells/SpellAuras.h:511
#7  SpellAuraHolder::Update (this=0x7f09eb963cf0, diff=101) at /home/wowserver/mmo/mangos-wotlk/src/game/Spells/SpellAuras.cpp:10915
#8  0x000055fe95a9b43b in SpellAuraHolder::UpdateHolder (diff=101, this=0x7f09eb963cf0) at /home/wowserver/mmo/mangos-wotlk/src/game/Spells/SpellAuras.h:148
#9  Unit::_UpdateSpells (this=this@entry=0x7f09f71a6230, time=time@entry=101) at /home/wowserver/mmo/mangos-wotlk/src/game/Entities/Unit.cpp:4647
#10 0x000055fe95a9b5bb in Unit::Update (diff=101, this=0x7f09f71a6230) at /home/wowserver/mmo/mangos-wotlk/src/game/Entities/Unit.cpp:434
#11 Unit::Update (this=0x7f09f71a6230, diff=diff@entry=101) at /home/wowserver/mmo/mangos-wotlk/src/game/Entities/Unit.cpp:406
#12 0x000055fe95988ce1 in Creature::Update (this=0x7f09f71a6230, diff=101) at /home/wowserver/mmo/mangos-wotlk/src/game/Entities/Creature.cpp:797
#13 0x000055fe95ba6028 in Map::Update (this=0x55feb03b6750, t_diff=@0x7f09f71b2638: 101) at /home/wowserver/mmo/mangos-wotlk/src/game/Maps/Map.cpp:868
#14 0x000055fe95bb15d2 in MapUpdateWorker::execute (this=0x7f09f71b2620) at /home/wowserver/mmo/mangos-wotlk/src/game/Maps/MapWorkers.h:52
#15 0x000055fe95bbc9dc in MapUpdater::WorkerThread (this=0x55fea061a628) at /home/wowserver/mmo/mangos-wotlk/src/game/Maps/MapUpdater.cpp:96
#16 0x00007f0a3c0e1943 in std::execute_native_thread_routine (__p=0x55feb0396d80) at /usr/src/debug/gcc/gcc/libstdc++-v3/src/c++11/thread.cc:104
```

**Comment by al3xc1985** [comment] 2024-02-10 21:56
hmm, so this was the crash I encountered without knowing what happend in ICC

**Comment by kelbren** [comment] 2024-02-22 18:23
I have been using this fix for a while now, and it seems to resolve the error, not further crashes with immolation trap and serpent sting.

**Comment by al3xc1985** [comment] 2024-03-14 00:05
@adellaci or @Nrezinorn can u confirm fixing this?

**Comment by Nrezinorn** [comment] 2024-03-15 02:59
@al3xc1985 Been using the proposed fix for almost a month, no crashes to report.

**Comment by al3xc1985** [comment] 2024-03-15 07:13
@insunaa Iguess we can close this one

**Closed as completed** 2024-03-15 10:34 UTC
Labels: System: Spells, Expansion: WotLK (3.3.5), Info: Needs Replication, Type: Client / Core Crash, Class: Hunter
