### ISSUE TITLE
🐛 [Bug Report] Stacking Mage Intellect Buffs

### ISSUE THREAD

**Issue by Patrick-Barry** [cmangos/issues#3311] opened 2023-03-03 14:01 UTC
### Bug Details

Its currently possible to have both Arcane Intellect and Arcane Brilliance buffs at the same time.

### Steps to Reproduce

1. Cast Arcane Intellect on yourself
2. Cast Arcane Brilliance on yourself

### Expected behavior

Only one of the buffs should be possible on a character at a time. 

### Core SHA1 Commit Hash

9dda20822cd83f508208cabdfab752bfd5ebdf76

### Database SHA1 Commit Hash

024b534d5468bc74634367aa49a50e6ea6b04c67

### Operating System

Windows 10

### Client Version

3.3.5a (Wrath of the Lich King)

**Comment by insunaa** [comment] 2023-03-03 14:11
Closing as duplicate of https://github.com/cmangos/issues/issues/2207

**Closed as completed by insunaa** 2023-03-03 14:11 UTC
Labels: Info: Needs Replication
