### ISSUE TITLE
🐛 [Bug Report] Hunter & Druid & Shaman Talent and Spell Issue

### ISSUE THREAD

**Issue by yhmark** [cmangos/issues#2142] opened 2020-03-05 01:21 UTC
### Expected behavior

I reported this bug two weeks ago.
**here https://github.com/cmangos/issues/issues/2125**

Didn't wait for useful feedback, am I not filling in the Commit Hash?
I hope to resolve this bug, it seriously impresses the game experience.

I re-describe the key points:
1.Druid lean talent "Improved Leader of the Pack", not only "Leader of the Pack"
2. Druid change from human to bear or cheetah

![德鲁伊-强化兽群领袖](https://user-images.githubusercontent.com/11365520/75938282-5ae75d80-5ec2-11ea-94a1-e8a9b9089489.png)

### Version & Environment

Client Version: "2.4.3" (TBC)

CMaNGOS Repo & Commit Hash: 5b6e8a7d618974ae9ab2e3439922e6e4a6e7ace7

Database Repo & Commit Hash: 45ce1e50bb8bea4bf5e72818e0ae5aa3796954d9

Operating System: Linux Flavor

### Steps to reproduce
1.Druid lean talent "Improved Leader of the Pack", not only "Leader of the Pack"
2.Shaman lean talent "Unleashed Rage"
3.Druid and Shaman join the same group
4. Druid from human to bear or cheetah
5. Then once the talent "Unleashed Rage" is triggered, you can see that the attack power is abnormal from the properties panel

### Crashlog

- None

**Comment by Yatzii93** [comment] 2020-03-08 23:10
Still cannot reproduce this myself. Maybe @killerwife can provide some confirmation if this is present in the github repo or someone else.

**Comment by yhmark** [comment] 2020-03-09 13:01
how can i @killerwife ?

**Comment by jimmybrancaccio** [comment] 2020-11-15 23:46
Closing this as a duplicate of #2125.

**Closed by jimmybrancaccio** 2020-11-15 23:46 UTC
Labels: Info: Needs Replication
