### ISSUE TITLE
[Classic] Double logout crash

### ISSUE THREAD

**Issue by katz1** [cmangos/issues#915] opened 2016-05-07 11:19 UTC
It happened to me twice so far, that after I log out with a character the server crashes. I couldn't find any error in the server logs. (Or to be more precise there was a Segmentation fault, but that always shows up when I shutdown the server.)

I found something strange however in Char.log. In the two cases the server crashed two logouts were logged:

```
2016-04-27 22:47:18 Account: 6 (IP: X.X.X.X) Logout Character:[Katz] (guid: 4)
2016-04-27 22:47:18 Account: 6 (IP: X.X.X.X) Logout Character:[Katz] (guid: 4)
```
```
2016-05-07 08:59:26 Account: 6 (IP: X.X.X.X) Logout Character:[Katz] (guid: 4)
2016-05-07 08:59:29 Account: 6 (IP: X.X.X.X) Logout Character:[p] (guid: 632)
```

In the second case the logout info is bogus, I was alone in the server in both cases (and there is no character with the 632 guid).

The first crash happened on a Debian server, the second one is on a Raspbian one.

**Comment by keyshuwen** [comment] 2016-05-08 13:47
I am also the problem.. :(

**Comment by cyberium** [comment] 2016-05-08 14:51
This bug is confirmed, we are working on it.

**Comment by krauterz** [comment] 2016-05-13 03:55
I am also experiencing this on a populated server.
Not meaning to rush you cyberium but I would not know where to start. is there a work around for this atm?

**Comment by krauterz** [comment] 2016-05-13 03:55
[mangosd.exe_[13-5_3-15-3].txt](https://github.com/cmangos/issues/files/262541/mangosd.exe_.13-5_3-15-3.txt)

**Comment by r4z0r84** [comment] 2016-05-13 05:02
Seems like an issue with loot + logging out, not so much logging out alone.

More so try running it from a C:\directory instead of your desktop as it may not have read/write access to save player's locations to the db, might also not have correct permissions for the character db itself.

I've gotten multiple lines in my char.log before and it hasn't caused a crash, its more crashed while it was updating the db itself.

Hope this information helps you.

**Comment by krauterz** [comment] 2016-05-13 05:10
Its to do with checking/writing the character inventory on logout. particularly on checking mail. server was in c:/ before and still crashed.

**Comment by krauterz** [comment] 2016-05-13 05:13
well actually it is in c:/ now rather. that log is from when it was not.

**Comment by krauterz** [comment] 2016-05-13 05:36
Also razor don't forget this is the 1.12 core. might not affect 2.4.3

**Comment by r4z0r84** [comment] 2016-05-13 05:42
I'd definitely check the permissions you have set on the character db, sounds like it doesn't have drop/delete enabled. But of course it could definitely just be within the core itself, 
I'd first try and revert this commit:
https://github.com/cmangos/mangos-classic/commit/f12ff28c81640c77bd76dee63bb2232a51633fca

**Comment by Laizerox** [comment] 2016-05-13 06:04
@r4z0r84 Reverting that won't solve the issues, because it will still happen during logout. Without that commit .kick command will not work in game because nothing will be closing Session socket.

However that will help us to fix an actual problem.

@namreeb https://gist.github.com/Laizerox/73a80f069cd3c0e174452bcc16e30454 here's related crash report

**Comment by krauterz** [comment] 2016-05-13 06:31
nice @Laizerox, this just occurred again, I caught the character that caused it and chatted to him. said all he did was log out. confirmed nothing to do with looting. thanks guys :)

**Comment by Laizerox** [comment] 2016-05-13 06:32
@krauterz Could you post your mangosd.exe dump file?

**Comment by krauterz** [comment] 2016-05-13 06:34
forgive me for the lingo, but I take it you mean the crash report?
[mangosd.exe_[13-5_6-20-22].txt](https://github.com/cmangos/issues/files/262633/mangosd.exe_.13-5_6-20-22.txt)

**Comment by Laizerox** [comment] 2016-05-13 06:41
From my quick observation in yuor scenario during logout we release loot, _player is valid at that time, we try to fetch loot for player so we could release it and during GetLoot() player is likely invalid.

So my guess would be player was deleted earlier by other? thread this could also happen during mine WorldSession::Update(), the session is gets deleted while in update trying to acquire lock onto invalid mutex, I guess. @namreeb can correct me if I'm wrong.

**Comment by krauterz** [comment] 2016-05-13 06:57
this might sound blonde. forgive me. I am new to C. could we not just omit the few lines regarding loot at logout all together? would that get the ball rolling?

**Comment by namreeb** [comment] 2016-05-13 19:31
@katz1 when the 2x logout in the character log happened to you, how did you logout?  /logout?  Did you also .kick yourself, or alt-f4, or anything like that?

**Comment by katz1** [comment] 2016-05-13 19:56
@namreeb 
I am 99% sure I simply clicked on Exit Game in the main menu in both cases.

**Comment by krauterz** [comment] 2016-05-13 20:24
@namreeb I did tell everyone on the server to alt f4 instead of logging out if they could remember to a few days ago. crashes seem to be less often.
but this could be a placebo effect.

**Comment by namreeb** [comment] 2016-05-14 00:20
I've just pushed commit https://github.com/cmangos/mangos-classic/commit/6fce965461e23e68ea831bc01b2499f1bc3df3e1 to hopefully resolve this issue.  Can you please try it and report back here if it works?

**Comment by krauterz** [comment] 2016-05-14 04:50
Building now and will report back in about 6 hours if it works :) sooner if it doesnt. thankyou for the fast response @namreeb. a lot of people will be very happy if it works.

**Comment by krauterz** [comment] 2016-05-14 06:38
Longest its ever been up. Things are looking promising. thanks @namreeb for your swift fix :)

**Comment by katz1** [comment] 2016-05-14 16:05
@namreeb 
This may be unrelated, but the server is not letting me login after I logged out. I don't remember this happening before the fix. I relogged numerous times successfully before this happened.

```
WORLD: Received opcode CMSG_LOGOUT_REQUEST, security 0
The value of player Katz at save:
HP is:                  238             MP is:                  0
AGILITY is:             33.000000               STRENGTH is:            26.000000
INTELLECT is:           20.000000               SPIRIT is:              28.000000
STAMINA is:             30.000000
Armor is:               252             Block is:               0.000000
HolyRes is:             0               FireRes is:             0
NatureRes is:           0               FrostRes is:            0
ShadowRes is:           10              ArcaneRes is:           0
MIN_DAMAGE is:          9.321428        MAX_DAMAGE is:          13.321428
MIN_OFFHAND_DAMAGE is:  4.371428        MAX_OFFHAND_DAMAGE is:  5.371428
MIN_RANGED_DAMAGE is:   9.185715        MAX_RANGED_DAMAGE is:   14.185715
ATTACK_TIME is:         1500            RANGE_ATTACK_TIME is:   2200
PLAYER: UpdateHonor
Player: channels cleaned up!
Aura 155 now is remove mode 5
Aura 154 now is remove mode 5
Aura 42 now is remove mode 5
Aura 22 now is remove mode 5
Aura 10 now is remove mode 5
Player: channels cleaned up!
SESSION: Sent SMSG_LOGOUT_COMPLETE Message
Build enum data for char guid 2 from account 6.
Build enum data for char guid 3 from account 6.
Map::GetHitPosition vmaps corrects gained with static objects! new dest coords are X:-765.033936 Y:-617.544800 Z:17.956100
Grid[30,26] on map 0 moved to IDLE state
Map::GetHitPosition vmaps corrects gained with static objects! new dest coords are X:-1884.166504 Y:2045.355347 Z:64.588303
Sending SMSG_SPELL_GO id=12625
WorldSocket::HandleAuthSession: client build 5875, account KATZ, clientseed 57A8CFD0
WorldSocket::HandleAuthSession: (s,v) check s: F13509F90DC442A692CB04E78C5CFBFDFC9305E1B6645BAD5BFD68FB685F3FA9 v: 654113B417F1748CB1D1E43F08E9140AED74522AF532FB3FE0B4447E8E2C4D3C
WorldSocket::HandleAuthSession: Client 'KATZ' authenticated successfully from 192.168.0.9.
WorldSocket::HandleAuthSession: client build 5875, account KATZ, clientseed 5AFCE53B
WorldSocket::HandleAuthSession: (s,v) check s: F13509F90DC442A692CB04E78C5CFBFDFC9305E1B6645BAD5BFD68FB685F3FA9 v: 654113B417F1748CB1D1E43F08E9140AED74522AF532FB3FE0B4447E8E2C4D3C
WorldSocket::HandleAuthSession: Client 'KATZ' authenticated successfully from 192.168.0.9.
WorldSocket::HandleAuthSession: client build 5875, account KATZ, clientseed CAF6BE37
WorldSocket::HandleAuthSession: (s,v) check s: F13509F90DC442A692CB04E78C5CFBFDFC9305E1B6645BAD5BFD68FB685F3FA9 v: 654113B417F1748CB1D1E43F08E9140AED74522AF532FB3FE0B4447E8E2C4D3C
WorldSocket::HandleAuthSession: Client 'KATZ' authenticated successfully from 192.168.0.9.
```

I tried logging in multiple times but it stuck on 'Connected'. I could not shutdown the server with the shutdown command after this, had to force it off.

**Comment by namreeb** [comment] 2016-05-14 17:16
@katz1 I'd be surprised if it were related.  Would you mind reposting this in a new issue?

**Comment by krauterz** [comment] 2016-05-14 20:47
@namreeb @katz1 Can confirm this issue is fixed, however I have not encountered this bug @katz1, not to say its not related, but we have had a stable 30 users for over 12 hours since updating the core.
thanks again Namreeb :)

**Comment by namreeb** [comment] 2016-05-15 05:35
Marking this as fixed.

**Closed by namreeb** 2016-05-15 05:35 UTC

**Comment by katz1** [comment] 2016-05-15 09:40
@namreeb 

> Would you mind reposting this in a new issue?

I think I'll wait until it happens once more. I had some weird network issues lately, so it could have been just related to that.

**Comment by cyberium** [comment] 2016-05-15 11:13
Nice that this bug seem resolved.
However:
- i hope @krauterz will continue to give other kind of feedback ;)
- the fix itself may need a little rewrite.

**Comment by krauterz** [comment] 2016-05-17 00:23
@cyberium if what you mean by that is add commits, I definitely will when we come up with something of any worth to the community :)

**Comment by keyshuwen** [comment] 2016-05-17 07:59
016-05-17 15:42:59 ERROR:SESSION: received unexpected opcode CMSG_REQUEST_RAID_INFO (0x02CD) the player has not logged in yet

crash.......

**Comment by Laizerox** [comment] 2016-05-17 08:01
Need more information regarding that... Logs etc?

**Comment by keyshuwen** [comment] 2016-05-17 08:10
Strange, I have not received any logs..I continue to track this issue.
