### ISSUE TITLE
Loot Not Showing All Party Members

### ISSUE THREAD

**Issue by Nett118** [cmangos/issues#1869] opened 2019-02-06 18:23 UTC
**Current behavior**: 
When the first person loots they do not see all loot (grey/white items). After second person loots then all random loot becomes viewable by both party members. Tried all party loot systems, even free for all and the random loot (grey/white items) are not visible by both party members until both have had a chance to click on the creature. First party member has to close the loot window and reopen to see all loot.
Seems to have started this after commit "Add Debug lootdropstats command" [0242fb6]
**Expected behavior**: 
Both party members see all loot.
**Steps to reproduce**:

1. Join a party.
2. Kill an npc.
3. Loot and compare with other party memebers.

**Client version**: 
3.3.5 
**Commit hash**: 
ba78c624974c53ee071cc5e64c95b9c6989c4320
**Database version**: 
PSDB
**Operating system**: 
Win7 64-bit

**Comment by Levitanious** [comment] 2019-02-06 19:06
Related to <https://github.com/cmangos/mangos-wotlk/commit/0242fb6c8b83b62b89212d054931a0bf81af1927>

**Comment by Levitanious** [comment] 2019-02-06 21:13
Unless @cyberium has something to add -- i'd suggest @jimmybrancaccio to close it or hand over to someone else.

**Comment by Tobschinski** [comment] 2019-02-06 21:18
> Tried all party loot systems, even free for all

idk about this one

**Comment by Levitanious** [comment] 2019-02-06 21:19
Free For All worked for new clear build, accroding to @berserkingyadis

**Comment by berserkingyadis** [comment] 2019-02-06 21:28
trying to replicate this i went ahead and killed some mobs with different loot modes:
group loot (top right killed mob): 
![grouploot_topright_kill](https://user-images.githubusercontent.com/9959527/52374677-28b8c180-2a5e-11e9-913a-56c07a947541.jpg)
free for all
![freeforall](https://user-images.githubusercontent.com/9959527/52374700-39693780-2a5e-11e9-86bc-bca510c376e1.jpg)
masterloot
![masterlooter](https://user-images.githubusercontent.com/9959527/52374728-4b4ada80-2a5e-11e9-8adc-4d8f8b2ae584.jpg)
need before greed (top right got kill)
![needbeforegreed](https://user-images.githubusercontent.com/9959527/52374745-56056f80-2a5e-11e9-81c9-5a8416073ce5.jpg)
roundrobin
![roundrobin](https://user-images.githubusercontent.com/9959527/52374771-6584b880-2a5e-11e9-9acb-59eaa78a42e3.jpg)

after releasing the first loot window with the character who had all loot, all chars could loot everything

**Closed** 2019-02-06 21:30 UTC
Labels: System: Loot, Version: WotLK

**Comment by Rog360** [comment] 2019-02-06 22:30
Ok, So it's not a bug it's a feature! Sorry to all involved in checking it and a Big Thanks for setting us straight... ;)
