### ISSUE TITLE
Zalazane Quest Progress Gets Stuck on 1/8 Hexed Trolls

### ISSUE THREAD

**Issue by Pifanjr** [cmangos/issues#1913] opened 2019-03-20 08:00 UTC
### Expected behavior
Quest is completed once you've killed Zalazane, 8 Hexed Trolls and 8 Troll Shaman

### Version & Environment

Client Version: [2.4.3]

CMaNGOS Repo & Commit Hash: e271f0e290ec0df9f936eb1d45979f4ca5a75a7e

Database Repo & Commit Hash: (unkown)

(see https://github.com/cmangos/issues/issues/1910, as I'm playing on Ansem's server)

### Steps to reproduce
1. Accept Zalazane quest
2. Kill 8 Troll Shaman, 8 Hexed trolls and Zalazane
3. You might have to kill an extra Hexed troll (it might be an overflow error)
4. Notice that the amount of Hexed trolls killed is stuck at 1/8.

### Crashlog

```
WoWBuild: 18606
Realm: [redacted]
Local Zone: Echo Isles, Durotar
Local Player: Kandor, 0000000000000019, (-1265.02,-5446.24,5.49814)
Locked Target: Hexed Troll, F130000C870032EC, (-1286.38,-5478.61,4.07621)
Last Enemy Target: Hexed Troll, F130000C870032EC, (-1286.38,-5478.61,4.07621)

=========================================================
Assertion Failed!

 App:         /Users/prive/Downloads/World of Warcraft 2.4.3/World of Warcraft.app
 File:        /Volumes/F2/usrbuild/xb/build/WoW_8606patch2.4.3/WoW/Source/Mac/../../../Engine/Source/Tempest/c3spline.cpp
 Line:        688
 Time:        2019-03-20 07.58.44 CET

 Assertion:   CMath::fnotequal_((pts[i+1] - pts[i]).SquaredMag(), 0.0f)

---------------------------------------------------------
Thread 0 (0x303) (Current)
  0 0x0004393a <unknown>
  1 0x00043f38 <unknown>
  2 0x000512e8 <unknown>
  3 0x000049c5 <unknown>
  4 0x00398b7c <unknown>
  5 0x00399092 <unknown>
  6 0x0038b46b <unknown>
  7 0x000a1464 <unknown>
  8 0x000a1def <unknown>
  9 0x000a31b6 <unknown>
 10 0x003a33f6 <unknown>
 11 0x003a4972 <unknown>
 12 0x005dd68e <unknown>
 13 0x0017c905 <unknown>
 14 0x0000b5ea <unknown>
 15 0x002bb224 <unknown>
 16 0x002c05f7 <unknown>
 17 0x002c0882 <unknown>
 18 0x00011f05 <unknown>
 19 0x000036f9 <unknown>
 20 0x92f3bbca _InvokeEventHandlerUPP(OpaqueEventHandlerCallRef*, OpaqueEventRef*, void*, long (*)(OpaqueEventHandlerCallRef*, OpaqueEventRef*, void*)) + 26
 21 0x92ed507c DispatchEventToHandlers(EventTargetRec*, OpaqueEventRef*, HandlerCallRec*) + 2027
 22 0x92ed41da SendEventToEventTargetInternal(OpaqueEventRef*, OpaqueEventTargetRef*, HandlerCallRec*) + 376
 23 0x92ed4056 _SendEventToEventTargetWithOptions + 40
 24 0x92eef0a1 ToolboxEventDispatcherHandler(OpaqueEventHandlerCallRef*, OpaqueEventRef*, void*) + 1306
 25 0x92ed54fb DispatchEventToHandlers(EventTargetRec*, OpaqueEventRef*, HandlerCallRec*) + 3178
 26 0x92ed41da SendEventToEventTargetInternal(OpaqueEventRef*, OpaqueEventTargetRef*, HandlerCallRec*) + 376
 27 0x92eef62d _SendEventToEventTarget + 33
 28 0x9306fef5 _ToolboxEventDispatcher + 82
 29 0x9306fdbb _RunApplicationEventLoop + 192
 30 0x0000382a <unknown>
 31 0x000024fe <unknown>
 32 0x00002425 <unknown>
 33 0x00000002 <unknown>



Thread 1 (0x9c03)
  0 0xa7b752fe _mach_wait_until + 10
  1 0xa7afbb0e _nanosleep + 322
  2 0xa7afb993 _usleep + 54
  3 0x0004e178 <unknown>
  4 0x00044a61 <unknown>
  5 0xa7c275e8 __pthread_body + 137
  6 0xa7c2a7d7 __pthread_start + 82
  7 0xa7c267a6 _thread_start + 34
  8 0x00000000 <unknown>



Thread 2 (0x6003)
  0 0xa7b9454a ___sem_wait_nocancel + 10
  1 0x00044a61 <unknown>
  2 0xa7c275e8 __pthread_body + 137
  3 0xa7c2a7d7 __pthread_start + 82
  4 0xa7c267a6 _thread_start + 34
  5 0x00000000 <unknown>



Thread 3 (0x8b37)
  0 0xa7b751a2 _mach_msg_trap + 10
  1 0xa7b756f3 _mach_msg + 47
  2 0x99ef2c68 _glcDebugListener + 416
  3 0xa7c275e8 __pthread_body + 137
  4 0xa7c2a7d7 __pthread_start + 82
  5 0xa7c267a6 _thread_start + 34
  6 0x00000000 <unknown>



Thread 4 (0xac07)
  0 0xa7b751a2 _mach_msg_trap + 10
  1 0xa7b756f3 _mach_msg + 47
  2 0xa7b8d382 _mach_msg_server + 313
  3 0x0002c638 <unknown>
  4 0xa7c275e8 __pthread_body + 137
  5 0xa7c2a7d7 __pthread_start + 82
  6 0xa7c267a6 _thread_start + 34
  7 0x00000000 <unknown>



Thread 5 (0xad03)
  0 0xa7b752fe _mach_wait_until + 10
  1 0xa7afbb0e _nanosleep + 322
  2 0xa7afb993 _usleep + 54
  3 0x00014e91 <unknown>
  4 0x000d78b7 <unknown>
  5 0x0010ca43 <unknown>
  6 0x0010cc30 <unknown>
  7 0x952986c1 -[NSThread main] + 39
  8 0x95298570 ___NSThread__start__ + 1242
  9 0xa7c275e8 __pthread_body + 137
 10 0xa7c2a7d7 __pthread_start + 82
 11 0xa7c267a6 _thread_start + 34
 12 0x00000000 <unknown>



Thread 6 (0xae03)
  0 0xa7b787b2 ___psynch_cvwait + 10
  1 0xa7c2ab30 __pthread_cond_wait + 751
  2 0xa7c285cd _pthread_cond_wait + 25
  3 0x0028af73 <unknown>
  4 0x0006df0c <unknown>
  5 0x0010ca43 <unknown>
  6 0x0010cc30 <unknown>
  7 0x952986c1 -[NSThread main] + 39
  8 0x95298570 ___NSThread__start__ + 1242
  9 0xa7c275e8 __pthread_body + 137
 10 0xa7c2a7d7 __pthread_start + 82
 11 0xa7c267a6 _thread_start + 34
 12 0x00000000 <unknown>



Thread 7 (0x13907)
  0 0xa7b751a2 _mach_msg_trap + 10
  1 0xa7b756f3 _mach_msg + 47
  2 0x934e9a82 HALB_MachPort::SendMessageWithReply(unsigned int, unsigned int, unsigned long, unsigned long, mach_msg_header_t*, bool, unsigned int) + 126
  3 0x934c1c3b HALB_MachPort::SendSimpleMessageWithSimpleReply(unsigned int, unsigned int, int, int&, bool, unsigned int) + 49
  4 0x934bebcb HALC_ProxyIOContext::IOWorkLoop() + 1589
  5 0x934be342 HALC_ProxyIOContext::IOThreadEntry(void*) + 236
  6 0x934f26d0 invocation function for block in HALC_ProxyIOContext::HALC_ProxyIOContext(unsigned long, unsigned int) + 20
  7 0x934bdfcf HALB_IOThread::Entry(void*) + 71
  8 0xa7c275e8 __pthread_body + 137
  9 0xa7c2a7d7 __pthread_start + 82
 10 0xa7c267a6 _thread_start + 34
 11 0x00000000 <unknown>



Thread 8 (0x13703)
  0 0xa7b752fe _mach_wait_until + 10
  1 0x949b5075 _MPDelayUntil + 22
  2 0x0068f807 <unknown>
  3 0x006b52a9 <unknown>
  4 0xa7c275e8 __pthread_body + 137
  5 0xa7c2a7d7 __pthread_start + 82
  6 0xa7c267a6 _thread_start + 34
  7 0x00000000 <unknown>



Thread 9 (0x13507)
  0 0xa7b752fe _mach_wait_until + 10
  1 0x949b5075 _MPDelayUntil + 22
  2 0x0068f807 <unknown>
  3 0x006b52a9 <unknown>
  4 0xa7c275e8 __pthread_body + 137
  5 0xa7c2a7d7 __pthread_start + 82
  6 0xa7c267a6 _thread_start + 34
  7 0x00000000 <unknown>



Thread 10 (0x13403)
  0 0xa7b787b2 ___psynch_cvwait + 10
  1 0xa7c2ab30 __pthread_cond_wait + 751
  2 0xa7c2a1da _pthread_cond_timedwait + 27
  3 0x0028ae6d <unknown>
  4 0x002ab8f8 <unknown>
  5 0x002aba42 <unknown>
  6 0x0010ca43 <unknown>
  7 0x0010cc30 <unknown>
  8 0x952986c1 -[NSThread main] + 39
  9 0x95298570 ___NSThread__start__ + 1242
 10 0xa7c275e8 __pthread_body + 137
 11 0xa7c2a7d7 __pthread_start + 82
 12 0xa7c267a6 _thread_start + 34
 13 0x00000000 <unknown>



Thread 11 (0xcd03)
  0 0xa7b7a406 ___select_nocancel + 10
  1 0xa7b7837d _select + 78
  2 0x002aae38 <unknown>
  3 0x002abdf6 <unknown>
  4 0x0010ca43 <unknown>
  5 0x0010cc30 <unknown>
  6 0x952986c1 -[NSThread main] + 39
  7 0x95298570 ___NSThread__start__ + 1242
  8 0xa7c275e8 __pthread_body + 137
  9 0xa7c2a7d7 __pthread_start + 82
 10 0xa7c267a6 _thread_start + 34
 11 0x00000000 <unknown>



Thread 12 (0xd20b)
  0 0xa7b751a2 _mach_msg_trap + 10
  1 0xa7b756f3 _mach_msg + 47
  2 0x938ea9f9 ___CFRunLoopServiceMachPort + 289
  3 0x938ea0ba ___CFRunLoopRun + 3196
  4 0x938e9141 _CFRunLoopRunSpecific + 584
  5 0x9390213f _CFRunLoopRunInMode + 82
  6 0x92b62c6f -[__CoreSchedulingSetRunnable runForever] + 654
  7 0x92b62860 +[__CoreSchedulingSetRunnable _run:] + 129
  8 0x952986c1 -[NSThread main] + 39
  9 0x95298570 ___NSThread__start__ + 1242
 10 0xa7c275e8 __pthread_body + 137
 11 0xa7c2a7d7 __pthread_start + 82
 12 0xa7c267a6 _thread_start + 34
 13 0x00000000 <unknown>



Thread 13 (0xd717)
  0 0xa7b9454a ___sem_wait_nocancel + 10
  1 0x006b5275 <unknown>
  2 0xa7c275e8 __pthread_body + 137
  3 0xa7c2a7d7 __pthread_start + 82
  4 0xa7c267a6 _thread_start + 34
  5 0x00000000 <unknown>



Thread 14 (0xd80f)
  0 0xa7b9454a ___sem_wait_nocancel + 10
  1 0x006b5275 <unknown>
  2 0xa7c275e8 __pthread_body + 137
  3 0xa7c2a7d7 __pthread_start + 82
  4 0xa7c267a6 _thread_start + 34
  5 0x00000000 <unknown>



Thread 15 (0x12d0b)
  0 0xa7b787b2 ___psynch_cvwait + 10
  1 0xa7c2ab30 __pthread_cond_wait + 751
  2 0xa7c2a1da _pthread_cond_timedwait + 27
  3 0x0028ae6d <unknown>
  4 0x00512f76 <unknown>
  5 0x0010ca43 <unknown>
  6 0x0010cc30 <unknown>
  7 0x952986c1 -[NSThread main] + 39
  8 0x95298570 ___NSThread__start__ + 1242
  9 0xa7c275e8 __pthread_body + 137
 10 0xa7c2a7d7 __pthread_start + 82
 11 0xa7c267a6 _thread_start + 34
 12 0x00000000 <unknown>



Thread 16 (0xd13f)
  0 0xa7b752fe _mach_wait_until + 10
  1 0x949b5075 _MPDelayUntil + 22
  2 0x0068f807 <unknown>
  3 0x006b52a9 <unknown>
  4 0xa7c275e8 __pthread_body + 137
  5 0xa7c2a7d7 __pthread_start + 82
  6 0xa7c267a6 _thread_start + 34
  7 0x00000000 <unknown>



Thread 17 (0x1d3b)
  0 0xa7b76abe ___workq_kernreturn + 10
  1 0xa7c269a1 __pthread_wqthread + 422
  2 0xa7c26782 _start_wqthread + 34
  3 0x001e4008 <unknown>



Thread 18 (0x3237)
  0 0xa7b76abe ___workq_kernreturn + 10
  1 0xa7c269a1 __pthread_wqthread + 422
  2 0xa7c26782 _start_wqthread + 34
  3 0x003c4008 <unknown>



=========================================================
```

**Comment by jimmybrancaccio** [comment] 2019-03-20 14:52
@Pifanjr Please provide the core and database commit hashes.

**Comment by PterhaarAB** [comment] 2019-03-20 15:24
I don't have access to those, as I'm not the owner of the server. However, Ansem is and he posted them in the issue I linked (although see https://github.com/cmangos/issues/issues/1910#issuecomment-474567275)

**Comment by jimmybrancaccio** [comment] 2019-03-20 15:29
@Pifanjr Please ensure whatever you're referring to is current/correct and edit your original submission to include the commit hash information in there.

**Comment by BenDol** [comment] 2019-05-26 14:54
Was unable to reproduce this issue on the latest core/db.

**Comment by jimmybrancaccio** [comment] 2019-05-27 19:15
As per @BenDol I am closing this out. @Pifanjr if you're still experiencing the problem please open a new issue including all necessary information.

**Closed by jimmybrancaccio** 2019-05-27 19:15 UTC
Labels: Info: Incomplete, Info: Needs Replication, System: Quests, Type: Client Crash, Version: TBC
