### ISSUE TITLE
[TBC]Karazhan chess_event doesn't work

### ISSUE THREAD

**Issue by cqqjjf** [cmangos/issues#1352] opened 2017-04-10 13:19 UTC
Karazhan chess_event doesn't work at mangos-TBC core

**Comment by rmzV** [comment] 2017-06-21 06:15
same on Wotlk branch

**Comment by jimmybrancaccio** [comment] 2018-11-17 08:15
Closing as a duplicate of #827.

**Closed by jimmybrancaccio** 2018-11-17 08:15 UTC
Labels: System-Scriptdev2, Version-TBC, Version-WotLK

**Comment by cala** [comment] 2018-11-17 08:31
Wow! A storm of closing is coming. ^_^
