### ISSUE TITLE
Pet Talent: Guard Dog

### ISSUE THREAD

**Issue by tarwyn** [cmangos/issues#305] opened 2013-12-09 20:21 UTC
Threat effect works, but not the happiness effect.

**Comment by jimmybrancaccio** [comment] 2018-11-24 03:37
@tarwyn Can you confirm this is still in issue in the latest commits?

**Comment by jimmybrancaccio** [comment] 2019-06-08 23:39
Closing this issue out. If anyone is still having a problem, please open a new issue with full details.

**Closed by jimmybrancaccio** 2019-06-08 23:39 UTC
Labels: Info: Needs Feedback, Info: Needs Replication, System: Pet, System: Spells

**Comment by Phatcat** [comment] 2019-06-09 09:36
Jimmy... why do you keep closing stuff randomly...

What more 'full details' do you need? Threat effect works but the happiness effect doesn't.

Stop closing out issues you can't even be bothered to test yourself if it's fixed or not. Its sloppy. Re-open this issue.

**Comment by Yatzii93** [comment] 2019-06-09 09:39
I mean the issue is so lacking in information I'd close it too. Worked way to much IT support, this is pretty common practice in such an event.

**Comment by Phatcat** [comment] 2019-06-09 09:41
What more info do you want? The taltent is a pet talent, one with 2 parts. one part is working, the other part is not. Do you need a step by step guide on how to create a hunter? how to tame a pet? what exactly are you guys expecting? So because of formalities you wanna turn a blind eye to issues and bugs?

**Comment by Phatcat** [comment] 2019-06-09 09:42
![image](https://user-images.githubusercontent.com/1907820/59157480-9972f780-8aab-11e9-8ae7-dc475b7fb4ab.png)

**Comment by Yatzii93** [comment] 2019-06-09 09:43
I see your point, in this case theres not much that needs to be said. Just defending Jim, I'm sure it's not malicious.

**Comment by Phatcat** [comment] 2019-06-09 09:58
No what it is, is it's lazy. You don't close an already open (and thereby established) issue without confirming yourself if it's still present, you don't ask others to do the work for you, and then after no-one has, you just close it. This obscures issues, and is damaging to the development process. All it does is give the appearance that issues are getting worked on, when they in fact aren't. I'm seriously flabbergasted by this behavior. And this is not the first time he's doing this either, I've called him out on this here before.

**Comment by jimmybrancaccio** [comment] 2019-06-09 19:35
There is zero steps for replication. Provide them and the other information for a complete bug report and I will have the issue reopened.

Also, if you're going to be disrespectful and toxic, go find another community @Phatcat. Thanks.

**Comment by ulfgebhardt** [comment] 2019-06-11 12:26
Since this was closed. Can you open a new Issue respecting the basic requirements for an issue @Phatcat ?
<3
