### ISSUE TITLE
🐛 [Bug Report] creature don't leave aggro

### ISSUE THREAD

**Issue by ClassicW** [cmangos/issues#3259] opened 2022-12-16 18:53 UTC
### Bug Details

the mob arggro doesn't let go, once the aggro is taken. the creatures never let go again. I want to note that this problem was not there 1 month ago.

![image](https://user-images.githubusercontent.com/71378304/208167754-c5aa76d0-e5e3-429c-979a-b5eaac20ffa9.png)

### Steps to Reproduce

1.aggro a creature
2. run
3.
4.

### Expected behavior

The creature must leave

### Crash Log

no

### Core SHA1 Commit Hash

1

### Database SHA1 Commit Hash

1

### Operating System

linux

### Client Version

1.12.1 (Classic)

**Comment by ssj17vegeta** [comment] 2022-12-17 10:18
It's a duplicate of https://github.com/cmangos/issues/issues/3235 . Should be closed.

**Closed as not planned** 2022-12-17 10:19 UTC
Labels: Info: Needs Replication
