### ISSUE TITLE
You Can Loot Disenchanted Items Twice

### ISSUE THREAD

**Issue by CabrasDaPeste** [cmangos/issues#1770] opened 2018-11-23 01:45 UTC
**Current behavior**:
If you click twice real fast after disenchant an item, you'll get the items twice, duplicating them.

This issue is related to the new looting system.

**Expected behavior**: 
You shouldn't be able to get doubled itens.

**Steps to reproduce**:

1. .learn 28029
2. .setskill 333 375
3. .add 25157
4. Use Disenchant on the [Serpentlord Claymore]
5. When the looting window opens, click twice real fast to loot the item.
6. Reproduced.

**Client version**: 
2.4.3 (8606)

**Commit hash**: 
00666387394559dcc8ba5b589a305b3dfe033fb5

**Database version**: 
370151f3e6f07cf1ce625a10b94b8a0a8410d281

**Operating system**: 
Debian 9

[//]: # (If this is a crash report, include the crashlog from a debug build with https://gist.github.com/)

**Comment by berserkingyadis** [comment] 2018-11-23 12:37
Cant reproduce. You can only loot 1 times the yield. Maybe im not double fast enough

commt: 637aeb57f9358e156853d42c4d7c47a3b5aac14a

os: archlinux

**Comment by cyberium** [comment] 2018-11-23 20:01
Should be fixed

**Closed by cyberium** 2018-11-23 20:01 UTC
Labels: System-Loot, Version-TBC
