### ISSUE TITLE
🐛 [Bug Report] Quest The End Of The Deserters cannot be completed

### ISSUE THREAD

**Issue by stealthgun** [cmangos/issues#2219] opened 2020-06-01 17:48 UTC
## 🐛 Bugreport
The qeust The End Of The Deserters (id 11134) cannot be completed, you need to kill the NPC "Gavis Greyshield" (guid: 30775) for it to count as completed but with 1hp left he absorbs all damage. You can only complete the quest by a GM .die command.

### Expected behavior
From what i can see from wowhead: https://www.wowhead.com/quest=11134/the-end-of-the-deserters you should beable to kill the NPC so the quest sets as completed.

### Version & Environment
Client Version:
"2.4.3" (TBC)

Client Version: 2.4.3
CMaNGOS Repo & Commit Hash: cmangos/mangos-tbc@19d3644

Database Repo & Commit Hash: cmangos/tbc-db@2791ec8

Operating System: Win 2019

### Steps to reproduce
1. Accept quest 11134
2. Attack the NPC
3. Wait for him to get 1 hp

### Crashlog
- None

**Comment by jimmybrancaccio** [comment] 2020-11-16 00:21
@Grz3s May you confirm if the above commit resolved this issue? If so let's close out this issue! 😄

**Comment by Grz3s** [comment] 2020-11-16 00:24
fix was added to wotlkdb...  and should be backported to TBC.. 
i didnt close it because noone confirmed ..that it was backported...

**Comment by jimmybrancaccio** [comment] 2020-11-16 00:57
Sounds good, thanks @Grz3s.

**Comment by al3xc1985** [comment] 2021-02-20 16:53
@AnonXS can we close this?

**Closed** 2021-02-20 17:17 UTC
Labels: Info: Needs Backport - TBC, System: Quests, Version: TBC
