### ISSUE TITLE
[TBC]Fleeing Movement Generator broken

### ISSUE THREAD

**Issue by DanielBallaSZTE** [cmangos/issues#1328] opened 2017-03-07 21:31 UTC
FleeingMovementGenerator is completly broken.
Just try it. Fear anyone, and watch the movement. Random teleports, fear through vmap etc..
Needs a HUGE rework

**Comment by Muehe** [comment] 2017-03-10 00:52
Duplicate of https://github.com/cmangos/issues/issues/1310?

**Comment by cyberium** [comment] 2017-09-10 11:28
yes duplicate

**Closed by cyberium** 2017-09-10 11:28 UTC
