### ISSUE TITLE
[TBC] Disciple of Naralex misbehavior

### ISSUE THREAD

**Issue by thrd92** [cmangos/issues#1221] opened 2017-01-12 08:25 UTC
**Current behavior**: Disciple of Naralex becomes neutral to players during the event (no more friendly), and he becomes attackable when he's entering combat, also he's ignoring the mobs (uncleared trash) on his way (no aggro).
![wowscrnshot_011217_124251](https://cloud.githubusercontent.com/assets/15037150/21882258/7e951946-d8cb-11e6-8521-f848e44db061.jpg)

**Expected behavior**: Disciple of Naralex should be friendly https://youtu.be/dVdUzMpLvoM?t=1182

**Steps to reproduce**:

1. Kill the required bosses in Wailing Caverns to be able to start event, talk to Disciple of Naralex...

**Client version**: 2.4.3

**Commit hash**: https://github.com/cmangos/mangos-tbc/commit/190221606936b044e32ebd737ff5c01cd7049983

**Database version**: Latest TBC-DB

**Operating system**: Debian 8.6 amd64

[//]: # (If this is a crash report, include the crashlog from a debug build with https://gist.github.com/)

**Comment by killerwife** [comment] 2017-01-12 11:32
I have a fix for this, but its a core issue. Hold on.

**Comment by killerwife** [comment] 2017-01-12 11:34
GossipSelect_npc_disciple_of_naralex function
Remove
            pCreature->SetFactionTemporary(FACTION_ESCORT_N_ACTIVE, TEMPFACTION_RESTORE_RESPAWN);

After that it works as intended afaik. @cyberium in case you would want to close this issue :)

**Comment by Tobschinski** [comment] 2017-01-12 17:04
What faction does he have in that screenshot?

**Comment by killerwife** [comment] 2017-01-12 17:16
Who knows, I just know when I made that change that he should be friendly to players.

**Comment by Tobschinski** [comment] 2017-01-12 17:42
Well, FACTION_ESCORT_N_ACTIVE = 250 is also super friendly (and appropriate) ... I just did the event with no issues at all (in vanilla though)

**Comment by killerwife** [comment] 2017-01-12 17:43
That does not really help.

**Comment by Rushor** [comment] 2017-01-12 17:58
FACTION_ESCORT_N_ACTIVE = 250 is used very often in serveral escortquests (horde and alliance will be firendly but monsters will be hostile towards the escortnpc)

**Comment by Tobschinski** [comment] 2017-01-12 17:59
The reason to request more info. This does not look like faction 35 or 250 and nothing else is used.

**Comment by killerwife** [comment] 2017-01-12 18:03
I suggest you log on to TBC and look for yourself.

**Comment by Tobschinski** [comment] 2017-01-12 18:17
Or I just wait for thrd92 to answer my initial question ... if he can find it now.

**Comment by thrd92** [comment] 2017-01-12 18:24
@Tobschinski Looks like the NPC is neutral (yellow unit frame) during the event, before the event NPC has green unit frame, so he's friendly at least.

**Comment by thrd92** [comment] 2017-01-12 18:31
So, before event faction is 35, during the event faction is 1986.

**Comment by Tobschinski** [comment] 2017-01-12 18:50
Makes sense because of [this](https://github.com/cmangos/mangos-tbc/blob/master/src/scriptdev2/ScriptMgr.h#L56), thank you!

I'd suggest to use FACTION_ESCORT_N_NEUTRAL_ACTIVE = 250 then.

**Comment by killerwife** [comment] 2017-01-12 18:52
Do we need to change faction? I mean this is sniff territory.

**Comment by Tobschinski** [comment] 2017-01-12 18:56
I can only offer you one from MOP.

```
[0] UpdateType: Values
[0] Object Guid: Full: - Creature/0 -/- Map: 43 Entry: 3678 Low: 35423214
[0] UNIT_FIELD_FACTIONTEMPLATE: 250/3.503246E-43
[0] UNIT_NPC_FLAGS: 0/0
```

**Comment by killerwife** [comment] 2017-01-12 18:56
Yes but during that the whole event was changed. So it isnt reliable imo.

**Comment by Rushor** [comment] 2017-01-12 19:46
i will search for an older sniff - bump me in this issue after 10 days if i forgot it

**Comment by OriginsDev** [comment] 2017-01-24 00:08
Bump @Rushor

**Closed** 2017-09-12 08:26 UTC
