### ISSUE TITLE
The Final Code Quest Finishing Doesn't Kill All Enemies

### ISSUE THREAD

**Issue by datchannin** [cmangos/issues#1957] opened 2019-06-03 22:10 UTC
## 🐛 Bugreport
After Mana Bomb activated it should detonation and kill npc. But it kills only several npc.
![image](https://user-images.githubusercontent.com/39913306/58837717-0e39d200-8665-11e9-95ab-f62a2193a16a.png)

Green circles on the picture are stayed alive.

And this is on the console:
![image](https://user-images.githubusercontent.com/39913306/58837776-3de8da00-8665-11e9-9f55-f6ffb396da44.png)

### Expected behavior
They should be killed by detonation.

### Version & Environment
Client Version: ["2.4.3" (TBC)]

CMaNGOS Repo & Commit Hash: 2bd07043438cbae4b64352e9d14d35cf49c109b4
Database Repo & Commit Hash: c8569c4265b62678a574a8c3951a871ef5662843

Operating System: [Win 64]

### Steps to reproduce
1. .quest add 10446
2. .tele Terokkar
3. go to manabomb
4. .additem 29912
5. use manabomb
6. Profit

### Crashlog
- None

**Comment by killerwife** [comment] 2019-06-04 06:54
@Saltgurka missing export?

**Comment by Saltgurka** [comment] 2019-06-04 07:36
Will take a look

**Comment by berserkingyadis** [comment] 2019-06-14 15:12
Can confirm that there are Warlocks who appear not to be fazed by the mana bomb. They remain alive. Same as in the image in first post. The dead ones have a "Mana Bomb Explosion" Effect/Buff.

![image](https://user-images.githubusercontent.com/9959527/59519024-43e18500-8ec7-11e9-879e-d163a4bcbd40.png)

I also have these spline errors.

`MoveSpline::init_spline: zero length spline, wrong input data?
MoveSpline::init_spline: zero length spline, wrong input data?
MoveSpline::init_spline: zero length spline, wrong input data?
MoveSpline::init_spline: zero length spline, wrong input data?`

client: tbc 2.4.3
core: 21d7effd47831b694378c7e83cded797aca05112
db: 48d78b7338825725c96f00004003b429571af77e
os: Windows 10 x64

**Comment by Saltgurka** [comment] 2019-06-14 16:15
The issue is related to line of sight. Due to the trigger c.20767 that casts s.35513 being inside the gameobject, only some NPCs are hit by it.
Killerwife already has a working fix for it that will be committed soon.

As for the spline errors I have no idea. Maybe it occurs for the npcs that are hit by the explosion and dies, thus losing their path.

**Comment by Saltgurka** [comment] 2019-06-28 19:41
Issue should now be resolved

**Closed by Saltgurka** 2019-06-28 19:41 UTC
Labels: Info: Needs Development, Info: Replicated, System: NPC, System: Spells, Version: TBC
