### ISSUE TITLE
[CLASSIC] Caster Animation is Bugged While Attacking

### ISSUE THREAD

**Issue by mlchai** [cmangos/issues#1181] opened 2016-12-02 08:36 UTC
**Current behavior**: 
When running away from a caster monster, the animation might bug out in that they stay in the same pose but keep moving or seem to violently twitch in the same spot for a second or two. The pose that it's stuck in seems to be the casting animation, so it might be trying to cast and run at the same time.

**Expected behavior**: 
Caster monster running after you should have a smooth running animation before deciding to cast.

**Steps to reproduce**:

1. Go to East Vale Loggin Camp or Stone Cairn Lake in Elwynn Forest.
2. Aggro a caster monster.
3. Run away and look behind you.

**Client version**: 
1.12.1

**Commit hash**: 

**Database version**: 

**Operating system**: 
Windows 10

[//]: # (If this is a crash report, include the crashlog from a debug build with https://gist.github.com/)

**Comment by Phatcat** [comment] 2019-02-08 02:09
Can't reproduce this, went to eastvale logging camp, pulled a caster mob and had it chase me around for a while trying to cast spells on me, it would never try to run and cast at the same time, when it got in range, it would stop running and start casting, if I got out of range while it was casting, it would stop casting and start pursuing, if I had a bit of distance between me and the mob it would not be twitching at any point in the chase, just chase normally until it got in range and then it'd start casting. Seemed as smooth as it should be (as smooth as when a player goes from running to standstill to casting a spell).

**Comment by AnonXS** [comment] 2019-02-08 11:35
There are still issues with cast animations going off wrongly in certain situations, but the generic combat casting seems to be working just fine now.

Closing due to posted cases can not be reproduced anymore.

**Closed by AnonXS** 2019-02-08 11:35 UTC
Labels: System: Spells, Version: Classic
