### ISSUE TITLE
[Classic]Creature summon pet

### ISSUE THREAD

**Issue by kuramajssken001** [cmangos/issues#1041] opened 2016-08-11 17:14 UTC
**Current behavior**: 
Creature summon pet level grester than creature.
**Expected behavior**: 

**Steps to reproduce**:

1. 
2. 
3. 

**Client version**: 

**Commit hash**: 

**Database version**: 

**Operating system**: 

[//]: # (If this is a crash report, include the crashlog from a debug build with https://gist.github.com/)

**Comment by Tobschinski** [comment] 2016-08-11 18:38
???

**Comment by cyberium** [comment] 2016-08-11 18:43
i let you till tomorrow to give more information about what creature id, what pet or i'll close this.
Yes iam in my good days :)

**Comment by Phatcat** [comment] 2016-08-11 19:52
I know this issie actually.

It is not very well reported but what he's trying to say is that its possible to cast tame beast on creatures which are higher level than yourself, and the spell wont fail until completely done channelling.

**Comment by dazidkk** [comment] 2016-08-11 19:56
Sounds like this fix can be converted to the pom issue? no :p

**Comment by Phatcat** [comment] 2016-08-11 20:04
Yeah, unless its about what i mentioned i really have no idea what he means. The more i read the report the less i think its about taming...

**Comment by dazidkk** [comment] 2016-08-11 20:10
Not alot of detail indeed.

**Comment by kuramajssken001** [comment] 2016-08-12 05:45
I am sorry, my English is poor.
Creature  Entry:4463   level 22
pet  Entry:12922   level  46

.go -8860.081 -2521.096 134.746 0

**Comment by Phatcat** [comment] 2016-08-12 06:02
Ahhhhhhhh, see, this is actually a DB issue if anything, sorry for the confusion. 
Levels are not hardcoded in the core but handled by the database. 

You should post the issue ticket here instead: https://github.com/classicdb/database

Closing this issue. Not because it's wrong, but because it's not core related.

**Closed by Phatcat** 2016-08-12 06:02 UTC

**Comment by kuramajssken001** [comment] 2016-08-12 06:08
This is the core problem.@Phatcat

**Comment by kuramajssken001** [comment] 2016-08-12 06:19
existing problem,need open this.But not classicDB Error.

**Comment by Phatcat** [comment] 2016-08-12 06:38
you mean this level 23 summoner and his level 23 pet?

![snipped](https://cloud.githubusercontent.com/assets/1907820/17614650/2b43e7da-6068-11e6-9a06-148fab2c8aee.JPG)

**Comment by Phatcat** [comment] 2016-08-12 06:43
https://github.com/kuramajssken001/mangos-classic
Looks quite custom.

Yeah, I'm gonna keep this closed.

**Comment by kuramajssken001** [comment] 2016-08-12 06:48
Ok, Im sorry. but thanks phatchat.

**Comment by Phatcat** [comment] 2016-08-12 07:07
There's nothing wrong with running custom changes but you should always verify your bugs against current cmangos/master with the newest related db to see if the bug is caused by your own changes.
