### ISSUE TITLE
🐛 [Bug Report] Error in instance_dungeon_encounters table, probably sql file format was updated

### ISSUE THREAD

**Issue by Pnumekin** [cmangos/issues#3236] opened 2022-11-29 08:57 UTC
### Bug Details

I have this error when trying to start cmangos on a freshly compiled install (latest db):

Loading Dungeon Encounters...
Error in instance_dungeon_encounters table, probably sql file format was updated (there should be 24 fields in sql).

terminate called after throwing an instance of 'std::system_error'
  what():  Invalid argument
Aborted (core dumped)

### Steps to Reproduce

1.Compile cmangos
2.Get latest classic db and make a fresh install
3.Start cmangos

### Expected behavior

Should start without error crash.

### Crash Log

Loading Dungeon Encounters...
Error in instance_dungeon_encounters table, probably sql file format was updated (there should be 24 fields in sql).

terminate called after throwing an instance of 'std::system_error'
  what():  Invalid argument
Aborted (core dumped)

### Core SHA1 Commit Hash

763e9b3cd92064b6eb0d43b1c3cd4ac3b7879688

### Database SHA1 Commit Hash

61058fa91b12b0f9aab368ea44d6720245e20f9f

### Operating System

Ubuntu 20.04.4 LTS 5.4.0-124-generic

### Client Version

1.12.1 (Classic)

**Comment by insunaa** [comment] 2022-11-29 09:21
I got the same error until I did a reinstall of the world database. That was on TBC and WotLK tho, might be different here

**Comment by Pnumekin** [comment] 2022-11-29 09:34
You used TRUNCATE TABLE  in mangos db and reinstalled everything?
I tried to delete instance_dungeon_encounters table, then install new database but problem is still present.

**Comment by evil-at-wow** [comment] 2022-11-29 21:17
I had a similar issue a while ago in the TBC core. It was caused by cmangos/mangos-tbc@206695e7d75ff03cc5f7fde1c00a44e616450dfc, and I bet your issue is caused by the Classic backport of it being cmangos/mangos-classic@70da1e4f943f850304b6ed07c15ea6b8db3ef6b5. As you can see in that commit, the core now expects an extra field in the dungeon encounter table (namely CompleteWorldStateID), but there is no database update associated with that commit so the core doesn't even realize your database is out of date. I kind of understand why it was done without database update like we typically do when the structure changes, but I still think it would have been a better user experience otherwise...

Anyway, the solution for your issue is reasonably simple: just run 'sql/base/dbc/original_data/DungeonEncounter.sql' (as if it was a database update, but it's not an update; it's like all the data the core expects for this table) on your world database and you should be fine.

**Comment by killerwife** [comment] 2022-11-29 21:22
Herpity derpity, that should've been an update.

**Comment by Pnumekin** [comment] 2022-11-30 09:16
Thank you for the explanations !
Applying the DungeonEncounter.sql file fix the problem.

**Comment by evil-at-wow** [comment] 2022-11-30 14:56
Good to hear! Solution confirmed, so closing.

**Closed as completed by evil-at-wow** 2022-11-30 14:56 UTC
Labels: Info: Needs Replication
