### ISSUE TITLE
[Classic] Absorbing damage issues (Ice Barrier .etc)

### ISSUE THREAD

**Issue by wowmui** [cmangos/issues#1227] opened 2017-01-15 01:56 UTC
**Current behavior**: 
![image](https://cloud.githubusercontent.com/assets/12601614/21959572/3a688de2-db06-11e6-990b-13333d826f45.png)
If you got Shield spell auras for example: mage's Ice Barrier / priest's Power Word : Shield
and got crits  you will immediately die , and the damage numbers is negative. (Spell crit is normal , just the physical attack).
**Expected behavior**: 
Maybe the new crit API  caused this issue?
**Steps to reproduce**:

1. player mage .
2.  cast Ice Barrier
3. wait crits hit.

**Client version**: 
1.12.1
**Commit hash**: 
f62c79e21f1011188daaff3d983bd6fe8d225376
**Database version**: 
z2693_01
**Operating system**: 
WIN10
vs2015 x64

[//]: # (If this is a crash report, include the crashlog from a debug build with https://gist.github.com/)

**Comment by Warlockbugs** [comment] 2017-01-15 04:15
No, the recent crit API wasn't responsible for that. 😄 
Damage goes from normal to nuts [up here](https://github.com/cmangos/mangos-classic/blob/master/src/game/Unit.cpp#L1772) which was implemented [here](https://github.com/cmangos/mangos-classic/pull/152).
totalDamage has unsigned type overflow.

**Comment by Warlockbugs** [comment] 2017-01-15 04:59
Crit update was the cause, indirectly. :smile: Incompatibility during backporting from TBC core.
Should be fixed in https://github.com/cmangos/mangos-classic/commit/3b28b1e8d00d02dcef29ef381c5a109836b825b3

**Closed by Warlockbugs** 2017-01-15 04:59 UTC
