### ISSUE TITLE
Charge animation for creatures is only correctly played if target is within certain radius of the creature

### ISSUE THREAD

**Issue by Arnibou** [cmangos/issues#697] opened 2015-06-10 08:53 UTC
Effect charge in a spell when creature cast spell have not animation.
The creature don't go the target but the other effect spell works.

Exemple spell: 26561 (charge berseker)

If learn the spell at player and he casts the spell, it's work fine but not a creature.

**Comment by Appled** [comment] 2016-06-13 06:51
Bumping this.
This occurs with all creatures who have a spell with charge effect. For example, warlock's Fel Guard's intercept being one. Enemy target gets appropriate intercept stun but the Fel Guard just walks towards the enemy target instead of charging.
And this is from TBC.

**Comment by Phatcat** [comment] 2019-02-07 01:41
This here should be fixed for cases of player controlled pets with this PR; https://github.com/cmangos/mangos-classic/pull/372 - the problem is it is actually not casting the charge on it's target but on itself/noone, which makes it look like it ain't charging even though it is actually casting the spell 'correctly'. I can imagine this needs a similar sort of fix for creature spell casts in general that pethandler (WorldSession::HandlePetAction) has gotten in my pr.

**Comment by BenDol** [comment] 2019-05-31 01:05
Was this resolved?

**Comment by Phatcat** [comment] 2019-06-02 02:13
If you are referring to the PR of mine which was merged recently then only for player controlled creatures, not for mobs with an independent AI, as the example mentioned here.

Pets were showing the exact same symptoms and those were fixed with my PR, hence my comment about a similar fix possibly being the answer for independent creatures.

**Comment by killerwife** [comment] 2022-02-03 21:34
This should be resolved.

**Closed by killerwife** 2022-02-03 21:34 UTC
Labels: System: Spells, Version: Classic (1.12), Version: TBC (2.4.3), Version: WotLK (3.3.5), Info: Needs Replication
