### ISSUE TITLE
🐛 [Bug Report] moon-priestess-amara NPC 2151

### ISSUE THREAD

**Issue by Ischtaratu** [cmangos/issues#3271] opened 2022-12-28 13:32 UTC
### Bug Details

2 separate patrols:
1 patrol as it should be
1 separated, the guard also spawns, but stands motionless at the spawn point.

Problem does not occur at server start. however, after some time a second defective patrol seems to spawn.
![WoWScrnShot_122822_141952](https://user-images.githubusercontent.com/6404203/209819615-3121fda9-c44f-418e-96a1-c71945f1e7c3.jpg)
![WoWScrnShot_122822_142904](https://user-images.githubusercontent.com/6404203/209819881-4207255c-62f5-4e97-a426-3aec0057bad2.jpg)

### Steps to Reproduce

1. After Server start, 1 patrole 
2. some questing
3. came back, there is second patrol

### Core SHA1 Commit Hash

bb572100821d1fcfcf3ed5bfb45bf56c00c177ea

### Database SHA1 Commit Hash

24.12.22

### Operating System

W10 22H2

### Client Version

2.4.3 (The Burning Crusade)

**Comment by AnonXS** [comment] 2022-12-28 13:43
Reproduced. - https://github.com/cmangos/tbc-db/commit/735d167753d1292acc8638bb006020fa492c5788 (atleast no db issue, maybe related to spawn groups)

will let it run now for a bit, maybe it appears. did you use .respawn command?

![grafik](https://user-images.githubusercontent.com/19734826/209821819-dc850ab1-2dde-4ddc-bda3-42af02e795ba.png)

you go there then you go away so they despawn, then you go there again and you will have two x same patrol spawned.

**Comment by Ischtaratu** [comment] 2022-12-28 14:10
no ... no respawn ...oh ... oh wait ... yes i have reloaded the DB with reload because of translation ... ok ... and that has messed him up. Ok all right ... my fault!

**Comment by AnonXS** [comment] 2022-12-28 14:11
![grafik](https://user-images.githubusercontent.com/19734826/209824864-e5bbe83a-b913-4660-80c6-b744a75093e1.png)

**Comment by Ischtaratu** [comment] 2022-12-28 14:12
Yes ... this happen too

**Comment by AnonXS** [comment] 2022-12-28 14:13
![grafik](https://user-images.githubusercontent.com/19734826/209825097-3c27e8bc-c764-43a5-b5e1-946b81a4445d.png)
![grafik](https://user-images.githubusercontent.com/19734826/209825233-a55470d0-5fb8-4d28-a842-bbeaa9c6ed1b.png)

@killerwife

**Comment by Grz3s** [comment] 2022-12-28 21:08
this is .. exact same error I was talking about .. before
gives DB error:
`
FormationData::MoveSlotOwner> Unable to find free place in formation groupID: 29997 for Creature (Entry: 16599 Counter: 9001548) DBGuid: 57597
FormationData::AddInFormationSlot> Unable to free occupied slot by Creature (Entry: 16599 Counter: 9001548) DBGuid: 57597 for Creature (Entry: 16599 Counter: 9002407) DBGuid: 57597
`

**Comment by AnonXS** [comment] 2023-01-21 18:05
Thrallmar same issue:
```
2023-05-10 17:27:46 ERROR:FormationData::MoveSlotOwner> Unable to find free place in formation groupID: 29997 for Creature (Entry: 16599 Counter: 9011819) DBGuid: 57595
2023-05-10 17:27:46 ERROR:FormationData::AddInFormationSlot> Unable to free occupied slot by Creature (Entry: 16599 Counter: 9011819) DBGuid: 57595 for Creature (Entry: 16599 Counter: 9012593) DBGuid: 57595

2023-05-10 17:49:14 ERROR:FormationData::MoveSlotOwner> Unable to find free place in formation groupID: 29997 for Creature (Entry: 16599 Counter: 9011819) DBGuid: 57595
2023-05-10 17:49:14 ERROR:FormationData::AddInFormationSlot> Unable to free occupied slot by Creature (Entry: 16599 Counter: 9011819) DBGuid: 57595 for Creature (Entry: 16599 Counter: 9013404) DBGuid: 57595

2023-05-10 18:10:40 ERROR:FormationData::MoveSlotOwner> Unable to find free place in formation groupID: 29997 for Creature (Entry: 16599 Counter: 9011819) DBGuid: 57595
2023-05-10 18:10:40 ERROR:FormationData::AddInFormationSlot> Unable to free occupied slot by Creature (Entry: 16599 Counter: 9011819) DBGuid: 57595 for Creature (Entry: 16599 Counter: 9014122) DBGuid: 57595
```

leaving server running this turns into a total mess, everytime the error pops the spawn group is duplicated.

![grafik](https://user-images.githubusercontent.com/19734826/213880799-4a43a1c2-cc77-4f42-9679-fb84dc7556b9.png)

**Comment by miraco** [comment] 2023-03-18 11:38
I know i had this error too when reworking winterfall runners in winterspring.
https://github.com/cmangos/tbc-db/pull/1109/files
This fixed it and i never got the error after.

it had something to do with despawning, at the end of the road not all members of the group despawned thats why the new spawned group couldnt find a place in formation group.

**Comment by miraco** [comment] 2023-04-07 16:44
You could test this:
```
UPDATE `spawn_group` SET `MaxCount`='4' WHERE (`Id`='29997');
UPDATE `spawn_group` SET `MaxCount`='3' WHERE (`Id`='19999');
```

This should prevent to get more then 3/4 spawns. (Also added it for thrallmar npcs)

edit: nvm somehow it still spawns a 4th npc sometimes

**Comment by nicedeluxes** [comment] 2023-04-17 18:31
Is there a solution to the problem?

**Comment by nicedeluxes** [comment] 2023-04-17 18:33
> I know i had this error too when reworking winterfall runners in winterspring. https://github.com/cmangos/tbc-db/pull/1109/files This fixed it and i never got the error after.
> 
> it had something to do with despawning, at the end of the road not all members of the group despawned thats why the new spawned group couldnt find a place in formation group.

the solution does not work

**Comment by miraco** [comment] 2023-04-18 12:21
I am not sure we can fix this via db currently.
I just took some time to test this group on retail wotlk ptr to see what happens when:
1. Leader (Moon Priestess Amara) dies
2. Adds die

This is the outcome:
One of her adds dies, they respawn after x time on their spawn position and run all the way to the group getting back in their "SlotId".

The Leader Moon Priestess Amara dies, adds change their SlotId to get a "new leader" and continue path. Moon Priestess Amara respawns after x time.
When she respawned, the gets back "Leader" Slot and the adds just run straigth to her. They continue the path where adds stopped.

Videos of this:
Amara respawns:
https://youtu.be/Hd3_oVhrSTU 

Add respawns:
https://youtu.be/q-rF50TJA94 

Same happens with the group in Hellfire Pensiula.
For the group in Hellfire: they dont aggro together, you can also see this on video. If you aggro the leader for example, last mob didnt got aggro, he just continued the path.
I cuted this video a bit because else it would be 10mins long
Video:
https://youtu.be/R3AUQhwqJVY

**Comment by nicedeluxes** [comment] 2023-04-18 18:13
> I am not sure we can fix this via db currently. I just took some time to test this group on retail wotlk ptr to see what happens when:
> 
> 1. Leader (Moon Priestess Amara) dies
> 2. Adds die
> 
> This is the outcome: One of her adds dies, they respawn after x time on their spawn position and run all the way to the group getting back in their "SlotId".
> 
> The Leader Moon Priestess Amara dies, adds change their SlotId to get a "new leader" and continue path. Moon Priestess Amara respawns after x time. When she respawned, the gets back "Leader" Slot and the adds just run straigth to her. They continue the path where adds stopped.
> 
> Videos of this: Amara respawns: https://youtu.be/Hd3_oVhrSTU
> 
> Add respawns: https://youtu.be/q-rF50TJA94
> 
> Same happens with the group in Hellfire Pensiula. For the group in Hellfire: they dont aggro together, you can also see this on video. If you aggro the leader for example, last mob didnt got aggro, he just continued the path. I cuted this video a bit because else it would be 10mins long Video: https://youtu.be/R3AUQhwqJVY
> 
> Maybe not 100% related to this, but i also think we miss a flag in spawn_group system. (Flag_only_respawn_adds) This will mostly used be used from boss npcs with adds. (Like Watchkeeper Gargolmar in hellfire Ramparts or Maulgar in Gruuls'Lair) If the boss dies and the group wipes after, the boss shouldnt respawn, but adds that didnt die shouldnt despawn/respawn) If the adds die at the boss, and the group wipes after, all adds should respawn. Video for this: https://youtu.be/jfQqPp4XjD4

Please tell us more about spawn_group. (flag_only_respawn_adds). Where can I find this dependency in the code?

**Comment by Grz3s** [comment] 2023-04-18 18:21
issue is related to grid load/unload system.
Groups should be loaded/unloaded as one instead of each individual separatly. i spoke with createor about it some time ago... but it was forgotten.

If im correct .. making them all super ACTIVE (extraflag 4096) should eliminate issue, but thats not the solution we want. (good for tests BTW)

**Comment by miraco** [comment] 2023-04-18 18:24
> > I am not sure we can fix this via db currently. I just took some time to test this group on retail wotlk ptr to see what happens when:
> > 
> > 1. Leader (Moon Priestess Amara) dies
> > 2. Adds die
> > 
> > This is the outcome: One of her adds dies, they respawn after x time on their spawn position and run all the way to the group getting back in their "SlotId".
> > The Leader Moon Priestess Amara dies, adds change their SlotId to get a "new leader" and continue path. Moon Priestess Amara respawns after x time. When she respawned, the gets back "Leader" Slot and the adds just run straigth to her. They continue the path where adds stopped.
> > Videos of this: Amara respawns: https://youtu.be/Hd3_oVhrSTU
> > Add respawns: https://youtu.be/q-rF50TJA94
> > Same happens with the group in Hellfire Pensiula. For the group in Hellfire: they dont aggro together, you can also see this on video. If you aggro the leader for example, last mob didnt got aggro, he just continued the path. I cuted this video a bit because else it would be 10mins long Video: https://youtu.be/R3AUQhwqJVY
> > Maybe not 100% related to this, but i also think we miss a flag in spawn_group system. (Flag_only_respawn_adds) This will mostly used be used from boss npcs with adds. (Like Watchkeeper Gargolmar in hellfire Ramparts or Maulgar in Gruuls'Lair) If the boss dies and the group wipes after, the boss shouldnt respawn, but adds that didnt die shouldnt despawn/respawn) If the adds die at the boss, and the group wipes after, all adds should respawn. Video for this: https://youtu.be/jfQqPp4XjD4
> 
> Please tell us more about spawn_group. (flag_only_respawn_adds). Where can I find this dependency in the code?

I think you miss understood what I wrote, I was testing around retail ptr to see what we are missing/how different groups work.
Edited the post cause it has nothing to do with this issue tho 

what grz3s says seems to fix the issue for now

**Comment by nicedeluxes** [comment] 2023-04-21 17:52
`2023-04-12 19:57:38 ERROR:FormationData::MoveSlotOwner> Unable to find free place in formation groupID: 29997 for Creature (Entry: 16599 Counter: 9001911) DBGuid: 57594
2023-04-12 19:57:38 ERROR:FormationData::AddInFormationSlot> Unable to free occupied slot by Creature (Entry: 16599 Counter: 9001911) DBGuid: 57594 for Creature (Entry: 16599 Counter: 9111390) DBGuid: 57594
2023-04-12 19:57:38 ERROR:FormationData::MoveSlotOwner> Unable to find free place in formation groupID: 29997 for Creature (Entry: 16599 Counter: 9001912) DBGuid: 57595
2023-04-12 19:57:38 ERROR:FormationData::AddInFormationSlot> Unable to free occupied slot by Creature (Entry: 16599 Counter: 9001912) DBGuid: 57595 for Creature (Entry: 16599 Counter: 9111391) DBGuid: 57595
2023-04-12 19:57:38 ERROR:FormationData::MoveSlotOwner> Unable to find free place in formation groupID: 29997 for Creature (Entry: 16599 Counter: 9002661) DBGuid: 57596
2023-04-12 19:57:38 ERROR:FormationData::AddInFormationSlot> Unable to free occupied slot by Creature (Entry: 16599 Counter: 9002661) DBGuid: 57596 for Creature (Entry: 16599 Counter: 9111392) DBGuid: 57596`

cmangos tbc similar error

**Comment by Novivy** [comment] 2023-05-03 08:12
> Reproduced. - [cmangos/tbc-db@735d167](https://github.com/cmangos/tbc-db/commit/735d167753d1292acc8638bb006020fa492c5788) (atleast no db issue, maybe related to spawn groups)
> 
> will let it run now for a bit, maybe it appears. did you use .respawn command?
> 
> ![grafik](https://user-images.githubusercontent.com/19734826/209821819-dc850ab1-2dde-4ddc-bda3-42af02e795ba.png)
> 
> you go there then you go away so they despawn, then you go there again and you will have two x same patrol spawned.

How do you reproduce it @AnonXS ?

also this may fix it but I can't test as I can't 100% reproduce it:
https://github.com/cmangos/mangos-tbc/commit/3d04a5b622a8f187f5e5f3402a63289f04be363b
https://github.com/cmangos/mangos-tbc/commit/81dd030be5f607f5fd47ed41eda0200c91a9f26e

**Comment by Ischtaratu** [comment] 2023-05-04 01:27
Some scripts will stop if no player is in range. But when the player comes back, the script (like Antonio Pirelli in Elwynn Forest) doesn't start over, but adds another spawn. I assume this is part of the system to save memory. If all scripts were running permanently, the problem would probably be less, but the server would use a lot more RAM over time. Could it have anything to do with this?

**Comment by Novivy** [comment] 2023-05-04 09:10
Is it? I thought they were just stopped on grid unload

**Comment by Ischtaratu** [comment] 2023-05-04 09:30
it seems not in every situation. Antonio is starting on some point near lumber camp ... once i have followed him the full round ... Elwyn, Westfall, Duskwood and Redridge ... but if you run away ... sometimes he restart at Elwynn, and sometimes he walk forward from the last seen point ... i am not sure ... but could it be, that some scrips do not stop compleetly and the system spawn even aditionals ? ... i only ask questions ^-^

**Comment by miraco** [comment] 2023-05-04 09:51
Yes, some mobs have "ExtraFlags - 4096 CREATURE_EXTRA_FLAG_ACTIVE", this mobs should walk even if no player is in map, and afaik Antonion Pirelli was one of them.

All other creatures only get loaded to grid when player is in range. (If you didnt change config to have all npcs active in grid all the time)

> LoadAllGridsOnMaps

> #        Load grids of maps at server startup (if you have lot memory you can try it to have a living world always loaded)


For this issue, what grz3s mentioned seems to be right and for now 
```
UPDATE creature_template SET ExtraFlags = ExtraFlags | 4096 WHERE entry = 16599;
UPDATE creature_template SET ExtraFlags = ExtraFlags | 4096 WHERE entry = 2151;
UPDATE creature_template SET ExtraFlags = ExtraFlags | 4096 WHERE entry = 10604;
UPDATE creature_template SET ExtraFlags = ExtraFlags | 4096 WHERE entry = 10606;
```

This sql would fix it.

**Comment by Novivy** [comment] 2023-05-04 10:38
> Yes, some mobs have "ExtraFlags - 4096 CREATURE_EXTRA_FLAG_ACTIVE", this mobs should walk even if no player is in map, and afaik Antonion Pirelli was one of them.
> 
> All other creatures only get loaded to grid when player is in range. (If you didnt change config to have all npcs active in grid all the time)
> 
> > LoadAllGridsOnMaps
> 
> > # Load grids of maps at server startup (if you have lot memory you can try it to have a living world always loaded)
> 
> For this issue, what grz3s mentioned seems to be right and for now `UPDATE creature_template SET ExtraFlags = ExtraFlags | 4096 WHERE entry = 16599; UPDATE creature_template SET ExtraFlags = ExtraFlags | 4096 WHERE entry = 2151; UPDATE creature_template SET ExtraFlags = ExtraFlags | 4096 WHERE entry = 10604; UPDATE creature_template SET ExtraFlags = ExtraFlags | 4096 WHERE entry = 10606;`
> 
> This sql would fix it.

from the documention it says `creature is active object. Grid of this creature will be loaded and creature set as active` which from what I understand means grid will never unload

**Comment by evil-at-wow** [comment] 2023-05-04 16:58
> which from what I understand means grid will never unload

That's not entirely accurate, but practically speaking that's good enough from the point of view of that active object.

As I understand it, after working my way through a lot of related code when debugging crashes and memory leaks the past few months: active objects means these objects will keep being updated by the core, and when they move around - like NPCs traveling along a path - the core makes sure that grids are loaded as needed by active objects. That's not entirely the same as the grids won't be unloaded: taking the example above of traveling around from Elwynn to Westfall to Duskwood and Redridge, it could well be that grids in Elwynn are unloaded when the NPC is in Westfall or Duskwood. But they will be loaded again when the NPC makes its way there, similar as to what would be the case if a player is moving there. That's roughly what that active flag is doing: treat those creatures more like players.

Still, even when these NPCs are not active, they should not "multiply". So there's definitely a problem somewhere...

**Comment by evil-at-wow** [comment] 2023-05-17 21:56
After looking into this, I'm not convinced that making the affected creatures active, as suggested by Grz3s, would actually fix anything in this case. I also understand why despawning NPCs, like miraco did with the Winterfall runners, fixes things. But generally speaking that is not a working solution because many spawn groups, like the group with Moon Priestess Amara, don't need to despawn somewhere.

I traced the problem back to a check gone wrong when respawning a grid after a load/unload cycle in the case creatures use dynamic guids. While respawning a grid, the core checks if it actually needs to respawn a creature because it could still exist on a different grid (especially for creatures with longer paths), but this check basically always (and often incorrectly) said "doesn't exist" in the case of a dynamic guid creature so the core respawned it (= added a duplicate). And that resulted in the Formation errors because adding the duplicate to a still full group fails, and it also explains the "out of sync" groups that were seen because the duplicates are basically not in a formation at all, so typically the leader duplicate gets the pathing and the followers just keep standing still. Despawning creatures like miraco did with the Winterfall runners avoided the problem because they were rightfully respawned when the grid reloaded and the respawns were not duplicates (so they could be added to a then empty formation, and so on).

I just pushed a fix for this in the TBC core for testing, feedback welcome. Note that I doubt we now already get the correct behavior as noted by miraco in the videos (when killing parts of the spawn group), but at least the duplicates and associated mess should be gone now (at least that was the case for me when I tested this for the past few hours).

**Comment by AnonXS** [comment] 2023-05-21 02:36
The Moonpriest issue seems to be resolved too. Can someone else confirm?

**Comment by Ischtaratu** [comment] 2023-07-05 18:22
after 25 minutes of observation, I can confirm, the bug was hunted and killed! 👍

**Comment by evil-at-wow** [comment] 2023-07-08 17:41
Given the fix also landed in all core repositories in the meantime - see the commits referenced above - I think we can close this.
A new issue can be opened should anything still come to the surface.

**Closed as completed by evil-at-wow** 2023-07-08 17:41 UTC
Labels: Expansion: Classic (1.12), Expansion: TBC (2.4.3), Expansion: WotLK (3.3.5), System: Creatures, Info: Needs Development
