### ISSUE TITLE
[CLASSIC][TBC][WOTLK] ObjectAccessor::SaveAllPlayers used ReadGuard Caused Crash

### ISSUE THREAD

**Issue by cqqjjf** [cmangos/issues#1355] opened 2017-04-12 15:59 UTC
If player has any  pet,   pet->SaveToDB()  will call  getowner() that called ObjectAccessor::findplayer()

but It's locked.  So  Crashes

I hacked  that by remove the guard. But I think that's not a good idea.

**void
ObjectAccessor::SaveAllPlayers() const
{
   // HashMapHolder<Player>::ReadGuard g(HashMapHolder<Player>::GetLock());
    HashMapHolder<Player>::MapType& m = sObjectAccessor.GetPlayers();
    for (HashMapHolder<Player>::MapType::iterator itr = m.begin(); itr != m.end(); ++itr)
        itr->second->SaveToDB();
}**

**Comment by jimmybrancaccio** [comment] 2018-11-18 04:39
@cqqjjf Can you confirm if this is still an issue on the latest code? If so can you provide the exact steps needed to replicate the issue?

**Comment by Baynar** [comment] 2019-02-14 09:44
Can confirm that in the lastest core for TBC a583a8a679af3aef5fba0f861550b1e7495674ee

Sometimes .saveall command will crash server

**Comment by Phatcat** [comment] 2019-02-14 13:26
This is a duplicate of https://github.com/cmangos/issues/issues/787 and a proposed fix is already up here; https://github.com/cmangos/mangos-tbc/pull/264

**Comment by jimmybrancaccio** [comment] 2019-06-08 23:22
Closing this out as a duplicate of #787 as per @Phatcat.

**Closed by jimmybrancaccio** 2019-06-08 23:22 UTC
Labels: Info: Needs Feedback, Info: Needs Testing, System: Pet, Version: Classic, Version: TBC, Version: WotLK

**Comment by Phatcat** [comment] 2019-06-09 09:34
Really? Come on now... This is not done 'per me' or 'by me' or 'for me'. 
The original issue was closed because of the duplicate, which was silly since the original was the one with the best error description, and now you're closing the duplicate despite the issue not being fixed and the original issue remaining closed.

Would you be so kind as to stop randomly closing issues you aren't familiar with or have any idea if is still present or fixed or not and then re-open this issue again.

**Comment by jimmybrancaccio** [comment] 2019-06-09 19:33
@Phatcat You clearly stated 'This is a duplicate'.

**Comment by berserkingyadis** [comment] 2019-06-09 20:12
I think the other issue was closed in favor of this one, this has the suggested fix.
