### ISSUE TITLE
🐛 [Bug Report] Shadow Fang Keep prisoner can't reach courtyard door

### ISSUE THREAD

**Issue by Szymplo** [cmangos/issues#2222] opened 2020-06-12 14:03 UTC
## 🐛 Bugreport
Shadowfang Keep. Faction: Horde. After killing first boss Rethilgore i'm going to prison and open my faction prisoner. After talking to him, he can't go upstairs he is walking back to starting position after few steps and so on.

Mangos_version: aa971d7efe84f79b594021ba5381da4ce3b30c27
DB_version:         74bd066706dd8d35b73d789a7a6c5d7de8bd661a

i made rollback to:

Mangos_version: e2b26d22baf3da67a4bfd281cff17fe550414b4e
DB_version:         2791ec86dea22c1c72fdbebaacffa8f8a76dc5b9

and again it works fine. He can go up-stairs.

### Expected behavior
Horde prisoner should go upstairs and open door to courtyard

### Version & Environment
  Client Version: 2.4.3" (TBC)
  Commit Hash: aa971d7

  Database Version:

  - [TBC](https://github.com/cmangos/tbc-db/tree/74bd066706dd8d35b73d789a7a6c5d7de8bd661a)

Database Repo & Commit Hash: 74bd066

Operating System: Debian 10 Buster with 10.3.22-MariaDB 

### Steps to reproduce
1. Go to Shadowfang Keep
2. Kill Rethilgore
3. Go to Prison
4. Talk to Horde faction Prisoner
5. Check if he is stuck between prison-room and stairs

**Comment by lduguid** [comment] 2020-06-12 18:20
Not meaning to hijack this issue and I can create a new one if preferred (let me know) but it maybe related to the same cause as Deathstalker Erland in Silverpine forest on the quest Escorting Erland behaves in the exact same manner as faction prisoner. i.e. you start the escort/event and he just walks back and forth. There are no mobs or aggro etc. infereing with his actions, it is if he does 1 or 2 waypoints then returns back to start, rinse repeat.

**Comment by cala** [comment] 2020-06-18 12:27
Confirmed for Shadowfang Keep prisoner. I'll investigate it.

**Comment by esno** [comment] 2020-06-18 15:00
@cala I noticed such behavior for a lot of escort quests. it may related to cmangos/mangos-tbc@339d950cb454978aac7d1582e85a0ed8969dde5e. After reverting all commits related to the WaypointMovementGenerator they seem to work properly. didn't digged dipper into it.

**Comment by cala** [comment] 2020-06-18 20:28
@cyberium it seems that this issue is caused by the change you made in this commit https://github.com/cmangos/mangos-classic/commit/38b6514c719e5dbcd83df690c022fdc7914af71d (reverting this commit alone is enough to fix the issue).

**Comment by esno** [comment] 2020-06-18 20:57
I'm not that familar with the WaypointMovementGenerators.
Dropping this check may help https://github.com/cmangos/mangos-tbc/blob/master/src/game/MotionGenerators/WaypointMovementGenerator.cpp#L161-L162. still testing it but don't know the corner cases

**Comment by cala** [comment] 2020-06-18 20:58
Reproduce steps:

- `.gm on`
- `.go creature id 3914`
- Kill every hostile NPC in the room
- Open the gate to the friendly NPC related to player faction (Sorcer Ashcrombe if Alliance, Deathstalker Adamant if Horde)
- Speak to the related NPC and pick the gossip option
- Notice that the NPC starts moving and after reaching second point moves back to first point, again and again

**Comment by stealthgun** [comment] 2020-06-18 22:17
We are having the same issue with escort quests. Would rather have it that this change is reverted so we can keep using the latest version without having to manually revert every time an update is done.

**Comment by cyberium** [comment] 2020-06-18 22:30
@esno This issue is due to a forgotten rule for db makers.
A path should not start from 0 for waypoint movement gen.
I will tomorrow do a sanity check on path loading and ignore all those cases.
I first thought about adding 1 artificially core side but it may broke some script and make unnecessary code more complex.

So for all dbdevs that mean more work. I have count about 150 cases in tbc/classic. A bit less in Wotlk.

**Comment by AnonXS** [comment] 2020-06-18 22:39
```
SELECT * FROM `script_waypoint` WHERE `pointid` = 0;
SELECT * FROM `creature_movement` WHERE `point` = 0;
SELECT * FROM `creature_movement_template` WHERE `point` = 0;
```

**Comment by Grz3s** [comment] 2020-06-18 23:18
https://github.com/cmangos/wotlk-db/commit/b47e7a9baef4badc7dfe647f470d361b58177eb2#commitcomment-38884107
 - just to remind smth  ;)

**Comment by AnonXS** [comment] 2020-06-18 23:30
yeaaa hahaha!

**Comment by stealthgun** [comment] 2020-06-19 07:45
Ive created a simple sql script that will update all the pahts with a 0 value to +1 (so the whole path works agian).

`USE tbcmangos;
ALTER TABLE `script_waypoint`
DROP PRIMARY KEY;

UPDATE `script_waypoint` SET pointid = pointid+1 where entry in (SELECT entry FROM `script_waypoint` WHERE `pointid` = 0);

ALTER TABLE `script_waypoint`
ADD PRIMARY KEY (`entry`,`pathId`,`pointid`);

ALTER TABLE `creature_movement`
DROP PRIMARY KEY;

UPDATE `creature_movement` SET point = point+1 where `id` in (SELECT `id` FROM `creature_movement` WHERE `point` = 0);

ALTER TABLE `creature_movement`
ADD PRIMARY KEY (`id`,`point`);

ALTER TABLE `creature_movement_template`
DROP PRIMARY KEY;

UPDATE `creature_movement_template` SET point = point+1 where entry in (SELECT entry FROM `creature_movement_template` WHERE `point` = 0);

ALTER TABLE `creature_movement_template`
ADD PRIMARY KEY (`entry`,`pathId`,`point`);`

**Comment by stealthgun** [comment] 2020-06-19 08:12
The issue also resolves https://github.com/cmangos/issues/issues/2221 but he would not walk to the final destination anymore (so some dialog is said 1 way point to early)

**Comment by cyberium** [comment] 2020-06-19 08:14
@stealthgun Iam affraid its not that simple for db devs. They have to check if there is script associated with some node ids and have to update them too. If that is not done it may result to broken script/quest/escort.

**Comment by stealthgun** [comment] 2020-06-19 08:15
> @stealthgun Iam affraid its not that simple for db devs. They have to check if there is script associated with some node ids and have to update them too. If that is not done it may result to broken script/quest/escort.

Yeah we where commenting at the same time :) I've allready found 1 quest that is now off.

**Comment by stealthgun** [comment] 2020-06-19 18:57
The list for all the broken SD2 scripts are:

` 'npc_defias_traitor'
'npc_isillien'
'npc_taelan_fordring'
'npc_deathstalker_erland'
'npc_kinelory'
'npc_professor_phizzlethorpe'
'npc_prospector_remtravel'
'npc_wizzlecranks_shredder'
'npc_gilthares'
'npc_therylune'
'npc_disciple_of_naralex'
'npc_shadowfang_prisoner'
'npc_shadowfang_prisoner'
'npc_feero_ironhand'
'npc_morokk'
'npc_willix_the_importer'
'npc_stinky_ignatz'
'npc_tapoke_slim_jahn'
'npc_ogron'
'npc_galen_goodward'
'npc_daphne_stilwell'
'mob_scarlet_trainee'
'npc_rinji'
'npc_oox17tn'
'npc_00x09hl'
'npc_oox22fe'
'npc_dorius_stonetender'
'npc_phalanx'
'npc_rocknot'
'npc_hurley_blackbreath'
'npc_arei'
'npc_ame01'
'npc_grimstone'
'npc_paoka_swiftmountain'
'npc_kanati'
'npc_lakota_windsong'
'npc_captured_arkonarin'
'npc_keeper_remulos'
'npc_kaya'
'npc_tirion_fordring'
'npc_garments_of_quests'
'npc_garments_of_quests'
'npc_garments_of_quests'
'npc_garments_of_quests'
'npc_garments_of_quests'
'npc_reginald_windsor'
'npc_muglash'
'npc_ruul_snowhoof'
'npc_torek'
'npc_prospector_anvilward'
'npc_ranger_lilatha'
'npc_barnes'
'npc_wounded_blood_elf'
'npc_ancestral_wolf'
'boss_nightbane'
'npc_anchorite_truuen'
'npc_magwin'
'npc_squire_rowe'
'npc_thrall_old_hillsbrad'
'npc_fhwoor'
'npc_kayra_longmane'
'npc_demolitionist_legoso'
'npc_nagrand_captive'
'npc_nagrand_captive'
'npc_taretha'
'npc_shaheen'
'npc_khadgars_servant'
'npc_custodian_of_time'
'npc_drijya'
'npc_bessy'
'npc_captured_vanguard'
'npc_protectorate_demolitionist'
'npc_wilda'
'npc_akuno'
'npc_letoll'
'mob_bt_battle_fighter'
'mob_bt_battle_fighter'
'mob_bt_battle_fighter'
'npc_clintar_dw_spirit'
'npc_rizzle_sprysprocket'
'npc_dragonmaw_racer_muckjaw'
'npc_dragonmaw_racer_trope'
'npc_dragonmaw_racer_corlok'
'npc_dragonmaw_racer_ichman'
'npc_dragonmaw_racer_mulverick'
'npc_dragonmaw_racer_skyshatter'
'npc_skyguard_prisoner'
'npc_tanzar'
'npc_harkor'
'npc_ashli'
'npc_kraz'
'npc_amanishi_lookout'
'npc_harrison_jones_za'
`

**Comment by stealthgun** [comment] 2020-06-20 18:12
The pull request now contains all the scripts including the 'Shadow Fang Keep prisoner' when the PR is merged this should fix this issue together with the database fix.

**Comment by cala** [comment] 2020-06-20 20:52
> Iam affraid its not that simple for db devs. They have to check if there is script associated with some node ids and have to update them too. If that is not done it may result to broken script/quest/escort.

There are two main cases that could break things if we increase all points index by 1 when the initial point index is 0:

- scripts/events that are coded in core to trigger at a given point index. Usually those are SD2 scripts, using paths from `script_waypoints` but there are some cases of SD2 scripts also using paths from `creature_movement_template`
- Conditions that check current point index of a moving creature. Usually, those are used by DB Scripts but there are also some gossip menus that should only display if a NPC is at a given step of its pathway

Said otherwise, once these cases are solved, all remaining paths with initial point index = 0 can be blindly increased by one with the aforementioned SQL script of a similar one.

As @stealthgun seems to be in the mood of fixing every related SD2 script in a single batch PR, let's go that way (and many thanks for doing so).

However, for future isolated similar changes, I would like to have SQL changes in the same commit than the SD2 changes, thus everyone can clearly see what is being fixed.

**Comment by stealthgun** [comment] 2020-06-20 20:58
@cala, was told the DB was doing the database and nobody was doing the SD2 so I just did the SD2's they can be fixed together, but the PR is depended on `script_waypoints` beeing updated so I added the check for that in the PR so we can track it.

Hope not a real hassle for me doing it this way.

**Comment by cala** [comment] 2020-06-20 21:13
> Hope not a real hassle for me doing it this way.

Not at all! 😄 

I and other DB devs shall handle scripts in database that will be broken by increasing point index.

I was referring to SD2 scripts. As you noticed, the changes depends on `script_waypoint` being updated and I prefer for future changes that both the SQL table and SD2 C++ be updated within the same commit. However, as all your changes lie in a single PR, clearly related to this issue, it is pretty obvious that `script_waypoint` should and will be updated at some point in the process.

**Comment by cala** [comment] 2020-06-20 21:38
> was told the DB was doing the database and nobody was doing the SD2

Oh. I think I understand what caused the misunderstanding: some SQL tables are not supposed to be administrated by DB devs.

SD2 related tables are of these in order to prevent SQL and SD2 scripts from being out of sync (though some DB devs are also SD2 devs).

**Comment by cala** [comment] 2020-06-23 19:38
Fixed in https://github.com/cmangos/mangos-classic/commit/0840710a1104a3e57e13d08e20492aa2f5f13e9a

**Closed by cala** 2020-06-23 19:38 UTC
Labels: Info: Needs Replication
