### ISSUE TITLE
[TBC] Unknown Crashes

### ISSUE THREAD

**Issue by wowx** [cmangos/issues#992] opened 2016-07-02 19:06 UTC
**Current behavior**: 
Unknown crashes
**Expected behavior**: 
http://pastebin.com/gmydcAY1
and
http://pastebin.com/2Q3Bm4JQ
**Steps to reproduce**:

**Client version**: 
TBC
**Commit hash**: 

**Database version**: 

**Operating system**: 
linux debian 8.2 64bit jessie

**Comment by Undergarun** [comment] 2016-07-08 17:26
Confirmed.

**Comment by wowx** [comment] 2016-07-14 16:19
We got also new unknown crashes :( http://pastebin.com/AksDUBKD and http://pastebin.com/Gau5Yd3H

**Comment by Phatcat** [comment] 2016-08-03 07:18
How are these crashes confirmed?

I'm willing to bet these crashes are happening because you are running a custom core:
https://github.com/cmangos/mangos-tbc/pull/66

I see 'Mysteria' on your crashes; I know it's just a folder name but since that was the name of your PR with custom changes which you closed and indeed said you were going to add for your core.

We cannot help you if these crashes are not happening on stock cmangos.

 Undergarun very unlikely had the same crashes, but other crashes, crashes which I had to close cause he indeed could not confirm that he was running cmangos/master.

I am going to close this, for the reasons stated above. Feel free to strike me down and reopen it if I'm horribly mistaken.

**Closed by Phatcat** 2016-08-03 07:18 UTC

**Comment by SilvioDoMine** [comment] 2016-08-05 23:05
@Phatcat I'm using the last revision of cmangos and the lasted database, only with custom npcs, vendors and some bosses script removed (on the database). And I'm runing a LAN server on a coffe an the Core is getting unknown crash as well. The server simple shutdowns, and I can re-start again. 

I was running a much older version of cmangos with no problems. +10days of opened server without a crash or restart. So, I recompiled the new core with the lasted updates and I'm getting this unknown crashes.

**Comment by ulfgebhardt** [comment] 2016-08-06 16:23
Check if these crashes occur on double-login (one account logs twice)

**Comment by wowx** [comment] 2016-08-08 19:36
@Phatcat  Hmm we are running in yours Cmangos with some updates. And had we had those crashes before we apply ours updates.

**Comment by Phatcat** [comment] 2016-08-09 11:32
You should NOT run my cmangos, I do not keep that up to date very often, and I couldn't dream of doing custom stuff atm so it only contains work that is intended for cmangos/master anyways
 you should be running stock cmangos/master.

If you guys can take a clean cmangos core, with no custom updates, and go and reproduce these crashes on there, by all means re-report them and I'll re-open this and apologize. But for now any and all indication is that those crashes are happening on a custom core, and we cannot help with that.

**Comment by dazidkk** [comment] 2016-08-09 11:36
Do we even know, whats causing these crashes?
If so i can test them, on Classic to see if its an issue there.

**Comment by dazidkk** [comment] 2016-08-09 11:39
But Phatcat, Regarding the double login crash.
You cant reproduce this?

**Comment by Phatcat** [comment] 2016-08-09 11:48
No, I can't reproduce the crash on duplicate login, tried for a whole day, ran into a few other bugs but nothing like a crash.
OP of this PR https://github.com/cmangos/mangos-classic/pull/170 says he has a method of reproduction but it requires I set up a run environment in debian.

**Comment by dazidkk** [comment] 2016-08-09 11:51
Im using windows, and this error happens.
I can record the issue, and make a new issue.
Or i can show you on skype, dunno what you preffer.
Er jo dansker efter alt :smile:

**Comment by Phatcat** [comment] 2016-08-09 11:57
Hvorfor kommer du ikke på IRC? - Jeg er stort set altid på. Tænkte det godt med **dkk** i dit navn ^^

Jeg tror vi har bedt om crash dumps fra den crash jeg ved ikke hvor mange gange men ingen kan poste en crash dump; siden du er på windows og kan reproducere så vil det være tilstrækkeligt hvis du bare gider poste crash reporten, så kan vi se hvor problemet ligger helt rigtigt nemlig.

Sorry for the danish, we're a rare breed so we have to communicate in our native tongue when an encounter occurs :p
