### ISSUE TITLE
Classic - Lightning Shield

### ISSUE THREAD

**Issue by dazidkk** [cmangos/issues#1021] opened 2016-08-04 05:31 UTC
If you have 2 shamans, and both use lightning Shield, it instantly procs all of the charges.

**Comment by dazidkk** [comment] 2016-08-05 02:35
Found a fix, if anyone have the spellfamilymask for the trigger of the shield proc.
https://db.valkyrie-wow.org/?spell=26363

**Comment by Phatcat** [comment] 2016-08-11 04:41
Was this fixed, or..?

**Comment by sidsukana** [comment] 2016-08-11 06:14
@Phatcat https://github.com/cmangos/mangos-classic/pull/184

**Comment by Phatcat** [comment] 2016-08-11 06:16
Ah, I see. Well, it hasn't been merged yet so let's keep this open for now.

**Comment by cyberium** [comment] 2017-06-23 22:54
Someone can confirm its still not working? I cant reproduce.

**Closed** 2018-11-18 13:31 UTC
Labels: Version-Classic
