### ISSUE TITLE
[classic] Surprise crash

### ISSUE THREAD

**Issue by Phatcat** [cmangos/issues#1112] opened 2016-09-30 13:24 UTC
Crashed randomly after being idle for some hours. Quite a few hours actually.

I wasn't doing anything in particular before going idle; all I did was enter Blackrock spire, put on gm mode and then move down to where smolderweb is, then idle out due to AFK and exit the client, what... 3 - 4 hours later this crash happens?

https://gist.github.com/Phatcat/40839084f5374e746c03f75032162ec1

**Comment by cyberium** [comment] 2016-10-01 10:26
Still problem with dungeon map reset :/

**Comment by cyberium** [comment] 2016-12-02 06:42
cannot reproduce should be fixed

**Closed by cyberium** 2016-12-02 06:42 UTC
Labels: HasBacktrace, Version-Classic
