### ISSUE TITLE
Classic: Druid: Feral Swiftness

### ISSUE THREAD

**Issue by Kelzior** [cmangos/issues#616] opened 2015-02-15 18:28 UTC
Core: Lastest.

http://db.vanillagaming.org/?spell=24866

Expected result : talent will increase outdoor speed while in cat form
Actual result : talent increases outdoor speed in all forms as well as in humanoid form.

**Comment by cala** [comment] 2015-03-03 13:04
Duplicate of https://github.com/cmangos/issues/issues/434
Closing this one. Thank you.

**Closed by cala** 2015-03-03 13:04 UTC
