### ISSUE TITLE
Server Crashed Quite Easily

### ISSUE THREAD

**Issue by apo126** [cmangos/issues#1787] opened 2018-11-29 00:20 UTC
Latest mangos-wotlk requires new dataz, so they were extrated. There are some errors in MaNGOSExtractor_detailed.log:

Processing Map 724
[################################################################]
Warning: Some models could not be extracted, see below
Could not find file of model World\Expansion02\Doodads\Generic\Vrykul\Weapons\Vr_Bm__Shield_01.m2
Could not find file of model World\Expansion02\Doodads\Generic\Vrykul\Weapons\Vr_Bm__Shield_02.m2
Could not find file of model World\Expansion02\Doodads\Generic\Vrykul\Weapons\Vr_Bm__Sword_01.m2
Could not find file of model World\Expansion02\Doodads\Generic\Vrykul\Weapons\Vr_Bm__Sword_02.m2
Could not find file of model World\Expansion02\Doodads\Generic\Vrykul\Weapons\Vr_Bm__Sword_03.m2
Could not find file of model World\Generic\Quilboar\Passive Doodads\Leantos\Razorfen_Leanto03.m2
A few not found models can be expected and are not alarming.

Extracting GameObject models...
Extracting World\Wmo\Band\Final_Stage.wmo
No such file World\Wmo\Band\Final_Stage.wmo.
Couldn't open RootWmo!!!
Warning: Some models could not be extracted, see below
Could not find file of model World\Detail\Drkbus02.m2
Could not find file of model World\Detail\Drkbus04.m2
Could not find file of model World\Dreaming\Passivedoodads\Flowers\Dreambellflower02.m2
Could not find file of model World\Dreaming\Passivedoodads\Flowers\Dreampurpleflower03.m2
Could not find file of model World\Dreaming\Passivedoodads\Flowers\Dreamspinningflower01.m2
Could not find file of model World\Expansion01\Doodads\Coilfang\Activedoodads\Energytower\Coilfang_Towers_E_Particle.m2
Could not find file of model World\Expansion01\Doodads\Hellfirecitadel\Demonwing\Passivedoodads\Summon_Door\Hellfire_Dw_Summondoor.m2
Could not find file of model World\Expansion02\Doodads\Generic\Vrykul\Harpoon\Vr_Harpoon_01.m2
Could not find file of model World\Expansion02\Doodads\Generic\Vrykul\Weapons\Vr_Bm__Shield_02.m2
Could not find file of model World\Expansion02\Doodads\Generic\Vrykul\Weapons\Vr_Bm__Sword_01.m2
Could not find file of model World\Generic\Quilboar\Passive Doodads\Leantos\Razorfen_Leanto03.m2
A few of these warnings are expected to happen, so be not alarmed!
Done!

After everything finishes, the server will run. Then enter the client. Simply run from Astranaar to Felwood and then to Everlook, the server crashed once in Felwood; run again, crashed again at Everlook.

Strange problem. Running previous server with old dataz, the above crash never happened.

Please kindly check and help. Thanks!

**Comment by jimmybrancaccio** [comment] 2018-11-29 01:00
This is likely a duplicate of #1781. Please update us if otherwise, closing for now.

**Closed by jimmybrancaccio** 2018-11-29 01:00 UTC
Labels: Core Crash, Version: WotLK
