### ISSUE TITLE
🐛 [Bug Report] TBC.spells.common.Melee attack range too big when moving.

### ISSUE THREAD

**Issue by BlackBoar101** [cmangos/issues#2402] opened 2021-02-16 07:26 UTC
## 🐛 Bugreport

![IMG_20210123_103526](https://user-images.githubusercontent.com/77557058/108030775-ac332300-7027-11eb-86e7-1961f45dd37a.JPG)
![截屏_20210313_203408](https://user-images.githubusercontent.com/77557058/111030292-3db06d80-83f9-11eb-8356-e41a2d367a60.jpg)

the first one is a normal range
the second one is cm2.43.
when the mob is outside the screen it can still attack.so do the character.

it,s a nightmare for range classes.and feels ridiculous for melee classes.
it also affects gameplay needs position run.

### Expected behavior

leeway value on normal attack(white number damage) fix.
should be the same value as melee spell(even if they are not the same they are very close.)

### Version & Environment

Client Version: 
"2.4.3" (TBC)

CMaNGOS Repo & Commit Hash: 
https://github.com/cmangos/mangos-tbc/tree/1b990c3

Database Repo & Commit Hash: 
https://github.com/cmangos/mangos-tbc/tree/1b990c3

Operating System: 
win7
### Steps to reproduce
1.use hamstring to the mob
2.run around.move closer and away from the target at times.
3.you,ll feel the range 
4. ...
5. Profit

### Crashlog

- None

**Comment by BlackBoar101** [comment] 2021-03-13 10:58
@mantislord 
do you have time to take a look at this issue?its not hard to fix but its really affect a lot.

**Comment by killerwife** [comment] 2021-03-13 12:12
I am sorry but what is your evidence that it is wrong? Piercing howl is AOE and melee is single target, and they do indeed work differently.

**Comment by BlackBoar101** [comment] 2021-03-13 12:21
@killerwife  
what i mean is that when moving the mob,s attack range is enlarged greatly, its hand can reach the player out of the piercing howl range.

you can try both the player and the mob,s range.

**Comment by BlackBoar101** [comment] 2021-03-14 00:05
@killerwife 
if i still didnt make my issue understood.let me know.i will upload more evidience.

**Comment by AnonXS** [comment] 2021-03-14 00:09
maybe create a video, spells have leash too

**Comment by BlackBoar101** [comment] 2021-03-14 00:36
@anonxs
you got what i mean:normal attack "leeway" value too big.

**Comment by AnonXS** [comment] 2021-03-14 00:48
make a video, a screenshot cant proof shit. maybe someone has insane lag idk

**Comment by BlackBoar101** [comment] 2021-03-14 01:14
@anonxs video

https://user-images.githubusercontent.com/77557058/111054208-a3850f80-8462-11eb-8a2e-28fa5ed39c5e.mp4

**Comment by BlackBoar101** [comment] 2021-03-14 01:23
@anonx 

is this enough?
if not ,i can upload some classic 60 video.

**Comment by AnonXS** [comment] 2021-03-14 01:30
as comparrisson material please yes!

**Comment by BlackBoar101** [comment] 2021-03-14 01:53
@anonxs as you wish

https://user-images.githubusercontent.com/77557058/111054894-1e045e00-8468-11eb-8cbb-336e4398c252.mp4

**Comment by BlackBoar101** [comment] 2021-03-14 02:07
@anonxs
you can see the hand length(attack range) difference clearly now.

**Comment by BlackBoar101** [comment] 2021-03-14 02:39
@anonxs this is another video. you do normal damage but you cant cast melee spell.

https://user-images.githubusercontent.com/77557058/111055509-6888d900-846e-11eb-8b5b-973f6362d8e3.mp4

**Comment by BlackBoar101** [comment] 2021-03-14 04:11
@anonxs
in the 2006 video,
the warrior,s first swing and last swing looks both within 5-yards. though both characters are MOVING.

**Comment by BlackBoar101** [comment] 2021-03-14 04:30
@anonxs
is this grandfather video enough?tell me if you need more.

**Comment by ratkosrb** [comment] 2021-03-14 04:45
If you are running away from a mob and it's chasing you, melee range will be increased because of leeway. That is not a bug, leeway applies when both units are moving. Here is a video from the official blizzard servers, you can see I can hit the mob from far away just like in your video.

https://streamable.com/vq809y

**Comment by BlackBoar101** [comment] 2021-03-14 04:57
@ratkosrb
please take a look at the 2006 warrior video.what leeway in that video?

**Comment by BlackBoar101** [comment] 2021-03-14 05:24
i have checked this bug over and over again.
Hellground ,Elysium,Classic. 
there is no "lets swing our sword happlily toward AIR" gameplay...I SWEAR.

**Comment by ratkosrb** [comment] 2021-03-14 05:52
Yes it always existed, and we know this for a fact because the logic for it is built into the client!

You can test this on any server, to see that the game expects there to be leeway.
1. Start WoW twice and login to separate accounts.
2. Make level 1 rogue since it has an instant melee spell (Sinister Strike).
3. Duel yourself.
4. On the first rogue enable auto running, and run towards the wall.
5. Go just out of range for Sinister Strike, where the spell turns red.
6. Now start moving and see how the spell becomes white, because the game know range is longer when both units are moving.

https://streamable.com/438ooh

This logic is part of the game client which is made by Blizzard, so this proves leeway existed, since the client takes it into account for distance calculations. This is independent from the server. If the server does not have leeway imlemented, you will still see the spell stops being red when moving, since the client does its own distance checks which include leeway and thinks you should be able to cast the spell.

**Comment by BlackBoar101** [comment] 2021-03-14 06:40
@ratkosrb
ok. the leeway exist. then check the value.value.value!
cause I got someone fix this bug in my local CM. but not on offical CM.why am so hard to understand...

https://user-images.githubusercontent.com/77557058/111059776-0b058400-8490-11eb-8131-1e1dc78ca2ea.mp4


https://user-images.githubusercontent.com/77557058/111059786-15278280-8490-11eb-8154-ccfa6ebed6eb.mp4


compare this two videos.please.

**Comment by BlackBoar101** [comment] 2021-03-14 07:56
@ratkosrb
Since you take Sinister Strike as example.please compare Sinister Strike and normal melee attack(white number damage).
you,ll find leeway work on this two with great difference.
the motion range buffer is much bigger on normal attack than on Sinister Strike.
this is what i mean.the value leeway work on normal attack is not right. too big .

**Comment by BlackBoar101** [comment] 2021-03-14 08:58
@anonxs
this is another evidence.
in normal server at max range any time you can do normal attack you can cast hamstring.
but in CM at max range you can only do normal attack, hamstring is always out of range.


https://user-images.githubusercontent.com/77557058/111062837-5ecd9880-84a3-11eb-9818-0ad30cac45e5.mp4


https://user-images.githubusercontent.com/77557058/111062839-642ae300-84a3-11eb-85cd-b0f8d857f7dd.mp4

**Comment by BlackBoar101** [comment] 2021-03-14 09:08
@killerwife
oh god.i feel like im an alien.hope this can make you guys understand.
if you need more info let me know.i will climb the great wall for you.

**Comment by BlackBoar101** [comment] 2021-03-17 03:44
@mantislord
this is a heavy bug affect any unit in any encounter.

**Comment by BlackBoar101** [comment] 2021-03-17 10:06
@insunaa
hey.do you have time to look leeway bug again?i up load enough evidence.

**Comment by insunaa** [comment] 2021-03-17 10:11
Leeway is calculated correctly as far as I can tell. Are you using a tbc db commit newer than? 2c02b193e78dec115b8825d266ad4c9db3639ad4
That has fixed some issues with reach

**Comment by miraco** [comment] 2021-03-17 10:15
Ob which Server you made those videos? 
Afaik the leeway for spells is 10% of spell distance 
And melee attack 2.66 yards

**Comment by BlackBoar101** [comment] 2021-03-17 10:34
@insunaa @miraco
this is a tbc server at date 1.22 .2021
 i reported this bug #2372 that time but you said leeway is right.
im sure leeway on normal attack(white number damage)should be the same as melee spell(hamstring example).
but does leeway value writen in db?a coder fix my local without db change.

**Comment by insunaa** [comment] 2021-03-17 10:37
No, just confirmed on 1.13 servers that hamstring doesn't get leeway, only white hits do.
Use commit hashes to communicate what version you're on. Dates mean almost nothing.
The date you posted is before the Character-Model reach values were updated in DB.

I think for all intents and purposes this issue can be considered fixed.

**Comment by miraco** [comment] 2021-03-17 10:44
If you say this is bugged you need a proof that shows us how it worked on retail TBC
And saying that it works differently on hellground core/other privat servers isn't.

**Comment by BlackBoar101** [comment] 2021-03-17 10:49
@miraco 
![截屏_20210317_184700](https://user-images.githubusercontent.com/77557058/111455851-35647500-870e-11eb-9e62-4a534bab9fee.jpg)
  
this video date back to year 2006. the super original one.i can upload more if you need.

**Comment by ratkosrb** [comment] 2021-03-17 11:00
Why did you film your laptop screen with your phone, instead of just linking us the original video.

**Comment by BlackBoar101** [comment] 2021-03-17 11:08
@ratkosrb  
cause my country got great wall...if this bug cant be killed this way i will climb it.dude.

**Comment by BlackBoar101** [comment] 2021-03-17 11:18
@miraco
melee range is 5yard. leeway is 2.66yard.so7.66yard.
and charge is 8yard.
are you sure?

**Comment by BlackBoar101** [comment] 2021-03-17 12:09
https://user-images.githubusercontent.com/77557058/111465141-a0677900-8719-11eb-8659-0954dbf26a09.mp4

**Comment by BlackBoar101** [comment] 2021-03-17 13:03
@insunaa
if only white hits get leeway.in the video above 
first hit two warrior cast on each other white damage should come out first.

**Comment by BlackBoar101** [comment] 2021-03-17 13:24
drakkus r14warrior(3)

https://user-images.githubusercontent.com/77557058/111474461-022ce080-8724-11eb-8caa-83cbc2b63022.mp4

**Comment by insunaa** [comment] 2021-03-17 13:28
I'm sorry, but it's literally impossible to discern any details from this video of a video that would make your case. I have tested how leeway works in 1.13 and it's the same way it works in 2.4.3 with any recent commits.

**Comment by BlackBoar101** [comment] 2021-03-17 13:35
this is the video on youtube.hope you when you have time take a look.

https://www.youtube.com/watch?v=_1GjhQU1tvc

**Comment by BlackBoar101** [comment] 2021-03-17 13:37
@insunaa 
ok. i see. i will keep watching this bug when i get my git work smooth.
thanks

**Comment by BlackBoar101** [comment] 2021-03-17 13:39
@ratkosrb 
hey.i have got the video link on youtube. when you have time you can take a look.

**Comment by BlackBoar101** [comment] 2021-03-17 13:43
@insunaa 
now .the leeway make the weapon warrior feel sucks. he dont have nuke anymore. (one white hit plus mortal strike at one time)  and it look so weird...

**Comment by BlackBoar101** [comment] 2021-03-17 13:57
if 1.13 server really conflict against the 2006 classic. what can be done?

**Comment by miraco** [comment] 2021-03-17 14:38
I think it hot tested on retail classic
So The guys running 1.13 are blizzard..

And I still fahr find a bug here

**Comment by killerwife** [comment] 2022-02-22 18:30
Closing this. We have adjusted the angle but everything else corresponds to my client reversal.

**Closed by killerwife** 2022-02-22 18:30 UTC
Labels: Info: Needs Replication

**Comment by BlackBoar101** [comment] 2022-03-02 09:27
Im reporting bugs here doesnt mean cm is not good, pal. CMTBC is the best emulator Ive ever played. 
I have played singly for about 1.5 years. and some bug i reported here i found them maybe 3years ago. i watched them for a long time actually.  want to help you guys do some polish work.
