### ISSUE TITLE
🐛 [Bug Report] Segmentation fault after Starting BattleGround System

### ISSUE THREAD

**Issue by zhaoxuan** [cmangos/issues#2097] opened 2020-01-22 03:15 UTC
## 🐛 Bugreport
When I start mangosd with config file, after 'Starting BattleGround System', I got a Segmentation fault.
Tail Server.log

```
2020-01-22 10:50:55 >> Loaded 850 C++ Scripts.
2020-01-22 10:50:55
2020-01-22 10:50:55 Loading spell scripts...
2020-01-22 10:50:55 Initialize game time and timers
2020-01-22 10:50:55 Starting Outdoor PvP System
2020-01-22 10:50:55 >> Loaded 6 Outdoor PvP zones
2020-01-22 10:50:55
2020-01-22 10:50:55 Starting Map System
2020-01-22 10:50:55
2020-01-22 10:50:55 Starting BattleGround System
```

### Version & Environment

Client Version: 2.4.3

CMaNGOS Repo & Commit Hash: https://github.com/cmangos/mangos-tbc/tree/0c6a1abd48f2b5d1a06b4adb764d8e6acec3a523

Database Repo & Commit Hash: https://github.com/cmangos/tbc-db/tree/c98e40dfb0008782490801d927e682347c9b2c86

Operating System: 
Debian 10
### Steps to reproduce
1.
2.
3.
4. ...
5. Profit

### Crashlog

- None

**Comment by Hollands09** [comment] 2020-01-22 03:36
Tried a fresh install after reformatting and I am having the same issue.

**Comment by canidae** [comment] 2020-01-22 06:37
See https://github.com/cmangos/issues/issues/2095

**Comment by jimmybrancaccio** [comment] 2020-01-22 17:11
Closing as a duplicate of #2095.

**Closed by jimmybrancaccio** 2020-01-22 17:11 UTC
Labels: Info: Needs Replication
