### ISSUE TITLE
Enemies Evade After First Attack

### ISSUE THREAD

**Issue by knuxyl** [cmangos/issues#1868] opened 2019-02-06 09:44 UTC
**Current behavior**: 
Enemies start evading after your first hit and can easily get out of combat with them without chase

**Expected behavior**: 
No evasion

**Steps to reproduce**:

1. Clean install
2. Female Tauren Warrior
3. Attack one of the birds nearby

**Client version**: 
1.12.1 clean

**Commit hash**: 
2b108280e0c8c2a2b4da9b5fa279a51a8646b3fd ( I don't know if thats the right one, reported in terminal at top with server version )

**Database version**: 
can't find database version, grabbed from github, last commit was 74235f8

**Operating system**: 
Xubuntu 18.04.1

[//]: # (If this is a crash report, include the crashlog from a debug build with https://gist.github.com/)
Log either didn't work or didn't save, but during uptime the server reported a creature could not cast a spell with an unknown error of 10.

**Comment by AnonXS** [comment] 2019-02-06 09:57
AzerothCore?

**Comment by knuxyl** [comment] 2019-02-06 09:58
Lol ok I posted the wrong versions, looked at the wrong database, this is for CMangos classic

**Comment by knuxyl** [comment] 2019-02-07 06:33
I just recompiled again just in case and double checked the problem. I still have the same problem. I created a female tauren shaman, and the problems exists with the birds. I then created a female orc warrior and attacked a pig, and still the same problem. first attack will work, every attack after gets evaded, and the enemies can still attack. once i try to leave combat by unclicking them combat gets turned off and they stop attacking. And the error I talked about in original post seems to be related to warrior, although the errors this time were different numbers

DoCastSpellIfCan by Creature (Entry: 13118 Guid: 92288) attempt to cast spell 6713 but spell failed due to unknown result 10.

the shaman did not throw any errors in console.

**Comment by Phatcat** [comment] 2019-02-07 10:07
I cannot reproduce the issue, are there any more parameters than simply to make a new char and attack those neutral mobs, like did you edit anything in the configs, if not, how exactly did you set up cmangos?

**Comment by knuxyl** [comment] 2019-02-07 10:38
I have an automated script that will download, compile, install, and update the sql database all automatically, so I'll try to post just the relevant code here. Btw I go through the terminal output once it's done and check for errors and there were none. The only changes I made to the config files were to change the username and passwords for the sql server.

Here's the code

`To simplify, I did a standard cmake with only setting tools and install path, then a make & make install. I then used the .sql for making the schemas, then imported the bases, then imported the dbc/original_data and dbc/cmangos_fixes, then downloaded the github world cmangos database, went in and configured the InstallFullDB.config and ran the .sh file, edited the .conf files (manually) to connect to server, launched the server, and connected. That is literally all I did.


Variables

game="wow"
server="cmangos"
version="World of Warcraft (Drums of War) 1.12.1 [5875]"
source="https://github.com/cmangos/mangos-classic"
database="https://github.com/cmangos/classic-db"
installpath="/opt/${game}"
sourcepath="${installpath}/source/${server}"

Server

git clone --recursive "${source}" "${sourcepath}"
cd "${sourcepath}"
mkdir build
cd build
cmake -DBUILD_EXTRACTORS=1 -DTOOLS=1 -DCMAKE_INSTALL_PREFIX="${installpath}" "${sourcepath}"
make -j4
make install

Database

cd "${sourcepath}/sql/create"
mysql -uroot -proot < db_create_mysql.sql
cd ../base
mysql -uroot -proot classicmangos < mangos.sql
mysql -uroot -proot classiccharacters < characters.sql
mysql -uroot -proot classicrealmd < realmd.sql
cd dbc/original_data
for i in *.sql; do mysql -uroot -proot classicmangos < "${i}"; done;
cd ../cmangos_fixes
for i in *.sql; do mysql -uroot -proot classicmangos < "${i}"; done;

git clone --recursive "${database}" "${installpath}/sql/"
cd "${installpath}/sql/"
./InstallFullDB.sh
sed -i 's/DATABASE=""/DATABASE="classicmangos"/g' InstallFullDB.config
sed -i 's/USERNAME=""/USERNAME="root"/g' InstallFullDB.config
sed -i 's/PASSWORD=""/PASSWORD="root"/g' InstallFullDB.config
sed -i 's/CORE_PATH=""/CORE_PATH="${sourcepath}"/g' InstallFullDB.config
./InstallFullDB.sh`

**Comment by berserkingyadis** [comment] 2019-02-07 12:21
Is the 
`
cd dbc/original_data for i in *.sql; do mysql -uroot -proot classicmangos < "${i}"; done;
cd ../cmangos_fixes for i in *.sql; do mysql -uroot -proot classicmangos < "${i}"; done;`

**Comment by knuxyl** [comment] 2019-02-07 14:09
I'll try without them, ill post back

**Comment by knuxyl** [comment] 2019-02-07 14:22
I looked further down the script (considering the way I'm importing the line number may be off) and found this

(0,     8,  38, 0,  'Rogue: Combat'),
(0,     8, 253, 0,  'Rogue: Assassination'),
(0,     8,  39, 0,  'Rogue: Subtlety'),
(0,     8, 176, 0,  'Weapon: Thrown'),
(0,     8, 173, 0,  'Weapon: Daggers (Rogue)'),
(0,     8, 176, 0,  'Weapon: Thrown (Rogue)'),

Weapon Thrown for Rogues has 2 0-8-176 entries. I don't know what this code is for, if it's a typo, or what. I'm willing to bet my database stops importing at this error, although importing the actual classic database throws no errors.

**Comment by knuxyl** [comment] 2019-02-07 14:31
Not importing the original_data and cmangos_fixes and also deleting the (0, 8, 176, 0, 'Weapon: Thrown'), entry and importing a fresh database still did not fix the problem. I don't have any more errors in console about a spell, so the Weapon: Thrown error needs to be fixed or else entire db cannot be imported, but I still have evade bug.

**Comment by joltcan** [comment] 2019-06-25 19:57
I'm running 
```
commit 0f0bab8aecb18b9780e18d33c278caa363a68994
Author: Warlockbugs <warlockbugs@outlook.com>
Date:   Fri May 3 06:46:59 2019 +0300
```

And I also have the same log lines still:

```
DoCastSpellIfCan by Creature (Entry: 13118 Guid: 92291) attempt to cast spell 6713 but spell failed due to unknown result 10.
DoCastSpellIfCan by Creature (Entry: 13118 Guid: 92290) attempt to cast spell 6713 but spell failed due to unknown result 10.
DoCastSpellIfCan by Creature (Entry: 13118 Guid: 92288) attempt to cast spell 6713 but spell failed due to unknown result 10.
DoCastSpellIfCan by Creature (Entry: 13118 Guid: 92289) attempt to cast spell 6713 but spell failed due to unknown result 10.
```
so it's probably still valid.

**Comment by mrsaleh** [comment] 2020-02-19 22:32
I have the same issue :
DoCastSpellIfCan by Creature (Entry: 13118 Guid: 92288) attempt to cast spell 6713 but spell failed due to unknown result 10.

**Comment by killerwife** [comment] 2020-02-20 00:05
Those errors are a work in progress. Do not pay too much attention to them. Its normal AI behaviour but I need to clamp down on whats an actual error and what isnt.....

**Comment by al3xc1985** [comment] 2020-02-25 19:18
I tested with given parameters... and all is ok... I suggest to close it @killerwife

**Closed** 2020-02-26 11:23 UTC
Labels: Info: Needs Replication, System: NPC, Version: Classic
