### ISSUE TITLE
🐛 [Bug Report] CMangos playerbot having a problem using drinks or foods

### ISSUE THREAD

**Issue by APEX-MQS** [cmangos/issues#3309] opened 2023-02-22 02:47 UTC
### Bug Details

When playerbots mana is low ,CMangos have a code for them to search for drinks and they will do it by themselves.
At the same time ,they will say"I could use a drink".
According to my test ,if they don`t have any drinks ,they will not say that.
So we can assume that if they say that sentence ,they must already have a drink in their bags.

But in my server most of the time ,they just kept repeating that sentence but do nothing.(they are not in battle and very few time they can drink successfully but most of the time they do nothing even I use commands to ask them to)
Also to mention ,when I use command ask them to use consumables ,like potions ,there is no problem.

If they dont have any drinks ,they wouldn`t say that sentence.
So ,the problem maybe in their using drinks procedure ,but not in finding drinks procedure.
But in the code .I also found something that may have to do with drink finding procedure.

Item* PlayerbotAI::FindDrink() const
{
    // list out items in main backpack
    for (uint8 slot = INVENTORY_SLOT_ITEM_START; slot < INVENTORY_SLOT_ITEM_END; slot++)
    {
        Item* const pItem = m_bot->GetItemByPos(INVENTORY_SLOT_BAG_0, slot);
        if (pItem)
        {
            const ItemPrototype* const pItemProto = pItem->GetProto();

            if (!pItemProto || m_bot->CanUseItem(pItemProto) != EQUIP_ERR_OK)
                continue;

            if (pItemProto->Class == ITEM_CLASS_CONSUMABLE && pItemProto->SubClass == ITEM_SUBCLASS_CONSUMABLE)
                // if (pItemProto->Spells[0].SpellCategory == SPELL_CATEGORY_DRINK)

                // this enum is no longer defined in mangos. Is it no longer valid?
                // according to google it was 59
                // if (pItemProto->Spells[0].SpellCategory == 59)
                if (pItemProto->Spells[0].SpellCategory == 59)
                    return pItem;
        }
    }
    // list out items in other removable backpacks
    for (uint8 bag = INVENTORY_SLOT_BAG_START; bag < INVENTORY_SLOT_BAG_END; ++bag)
    {
        const Bag* const pBag = (Bag*) m_bot->GetItemByPos(INVENTORY_SLOT_BAG_0, bag);
        if (pBag)
            for (uint8 slot = 0; slot < pBag->GetBagSize(); ++slot)
            {
                Item* const pItem = m_bot->GetItemByPos(bag, slot);
                if (pItem)
                {
                    const ItemPrototype* const pItemProto = pItem->GetProto();

                    if (!pItemProto || m_bot->CanUseItem(pItemProto) != EQUIP_ERR_OK)
                        continue;

                    if (pItemProto->Class == ITEM_CLASS_CONSUMABLE && pItemProto->SubClass == ITEM_SUBCLASS_CONSUMABLE)
                        // if is WATER
                        // SPELL_CATEGORY_DRINK is no longer defined in an enum in mangos
                        // google says the valus is 59. Is this still valid?
                        // if (pItemProto->Spells[0].SpellCategory == SPELL_CATEGORY_DRINK)
                        if (pItemProto->Spells[0].SpellCategory == 59)
                            return pItem;
                }
            }
    }
    return nullptr;
}

Someone wrote notes about the SpellCategory problems.
And I think there might be association.
By the way ,I`m using Chinese locales and client.

### Steps to Reproduce

1.See if anyone else have this issue.
2.Check why they have drinks but do nothing.
3.Maybe change the way of drink-finding or drink-using.

### Core SHA1 Commit Hash

everyversion since last year

### Database SHA1 Commit Hash

everyversion since last year

### Operating System

Windows 10

### Client Version

1.12.1 (Classic)

**Comment by f0n1x** [comment] 2023-02-26 17:56
I can confirm this behavior on vanilla (1.12.1). Bots will message about needing a drink but not actually attempt to drink anything even though they have mana restoring drinkables.

**Comment by joltcan** [comment] 2023-03-17 19:01
Can also confirm this on vanilla. This has always been the case with playerbot enabled. Doesn't listen to `use [item]` or `use N <item>` at all when it comes to food or drinks. Not sure if other cases, because this is what I use them for.

**Comment by fuccac** [comment] 2023-06-05 08:05
I can confirm this for TBC - but I dont think its a problem with the SPELL_CATEGORY_DRINK because on my build from Apr. 2021 the comment is identical, and the bots are eating and drinking as intended. However, most of the Playerbot code did not change much in years. Must be something different.

**Comment by fuccac** [comment] 2023-06-06 09:00
Another update: Food/Drinks work on latest WOTLK build.

**Comment by killerwife** [comment] 2023-06-06 09:11
As much as this will be unhelpful, playerbot is the only region I do not support and do not help with supporting. Cala was the principal supporter of this feature and even though I am not against it, you guys are on your own (since cala stepped down). No problem merging PRs but I have no intention to work on any issues with playerbot. Writing it here for everyone involved to see.

**Comment by joltcan** [comment] 2023-06-06 11:34
> As much as this will be unhelpful, playerbot is the only region I do not support and do not help with supporting. Cala was the principal supporter of this feature and even though I am not against it, you guys are on your own (since cala stepped down). No problem merging PRs but I have no intention to work on any issues with playerbot. Writing it here for everyone involved to see.

Bummer, thanks for your efforts and support!

**Comment by Scarabol** [comment] 2023-12-08 01:08
Problem: Target your bot with gm account and use ".debug moveflag", which shows that the movement flags are not 0 even when the bot is standing still. Therefore the bot aborts the spell to eat/drink.

Solution: https://github.com/cmangos/mangos-tbc/pull/643

**Comment by insunaa** [comment] 2024-06-16 17:10
Closing due to deprecation of the old bots.

**Closed as not planned by insunaa** 2024-06-16 17:10 UTC
Labels: Expansion: Classic (1.12), Expansion: TBC (2.4.3), Expansion: WotLK (3.3.5), Info: Needs Replication, System: CMaNGOS Extensions
