### ISSUE TITLE
[CLASSIC] Wretched Zombies Stuck Running In Place

### ISSUE THREAD

**Issue by WOW-Reborn** [cmangos/issues#1698] opened 2018-09-07 11:50 UTC
**Current behavior**: 
Currently and randomly the Wreched Zombies in the undead starting zone will randomly stop moving and act like its going crazy stuck in one spot.  

**Expected behavior**: 
The zombies should walk around until attacked.

**Steps to reproduce**:

1. Go to deathknell and where you have all the zombies walking around you will notice randomly wreched zombies stuck in one spot acting like they are trying to run.

**Client version**: 
cMangos-Classic

**Commit hash**: 
01fb7c2b7acddcf6596abb95866c2d8bc774d052

**Database version**: 
Classic DB version 1.9 "The Black Dragonflight"

**Operating system**: 
Windows Server 2016

[//]: # (If this is a crash report, include the crashlog from a debug build with https://gist.github.com/)

**Comment by WOW-Reborn** [comment] 2018-09-07 11:53
DB-SCRIPTS: Process table `dbscripts_on_creature_movement` id 150101, command 26 attacker can not attack (Attacker: Creature (Entry: 1501 Guid: 44961), Target: Creature (Entry: 1736 Guid: 28711))
 DB-SCRIPTS: Process table `dbscripts_on_creature_movement` id 150201, command 26 attacker can not attack (Attacker: Creature (Entry: 1736 Guid: 28711), Target: Creature (Entry: 1502 Guid: 44965))
 DB-SCRIPTS: Process table `dbscripts_on_creature_movement` id 150101, command 26 attacker can not attack (Attacker: Creature (Entry: 1501 Guid: 44961), Target: Creature (Entry: 1736 Guid: 28711))
 DB-SCRIPTS: Process table `dbscripts_on_creature_movement` id 150101, command 26 attacker can not attack (Attacker: Creature (Entry: 1501 Guid: 44961), Target: Creature (Entry: 1736 Guid: 28711))

**Comment by WOW-Reborn** [comment] 2018-09-07 11:56
What makes this situation even more interesting is that if I log out and log back in then the zombies are moving around fine again and will slowly start glitching out.  So I have no idea where to even begin to think where a problem like this would be located.

**Comment by WOW-Reborn** [comment] 2018-09-07 11:58
![untitled](https://user-images.githubusercontent.com/41515945/45217886-5ad5b580-b26b-11e8-865a-e17943071c7c.png)

**Comment by AnonXS** [comment] 2018-09-07 17:41
This is the cause ```
('150201','1502','11','0','100','0','0','0','0','0','11','26047','0','0','0','0','0','0','0','0','0','0','Wretched Ghoul - Cast Birth on Spawn'),
```

**Comment by WOW-Reborn** [comment] 2018-09-07 23:02
@AnonXS This correction doesn't work.  Removing the line from the database has no effect on the issue that I am having.  Once the zombies are killed and they re spawn they re spawn in a frozen like state while looking like they are trying to run but can't move.

**Comment by WOW-Reborn** [comment] 2018-09-07 23:11
It is so hard to explain the situation and pictures dont work because they are limited to one frame, so I have uploaded a video on youtube so you can see exactly how they are working.  Before I deleted the line of database code you suggested they were isolated stuck in one spot, now the problem is still there but they are moving around.

https://youtu.be/4IUA1yktBtQ

**Comment by Grz3s** [comment] 2018-09-08 01:46
(...) Removing the line from the database has no effect on the issue (...)
You should add this line.. ;)
Anyway try this:
```sql
-- delay corrected for Wretched Ghoul Script
UPDATE dbscripts_on_creature_movement SET delay = 0 WHERE id = 150101 AND command = 22;
UPDATE dbscripts_on_creature_movement SET delay = 1 WHERE id = 150101 AND command = 26;

Delete from `creature_ai_scripts` where `id`=150201;
Insert into `creature_ai_scripts` values 
('150201','1502','11','0','100','0','0','0','0','0','11','26047','0','0','0','0','0','0','0','0','0','0','Wretched Ghoul - Cast Birth on Spawn');
UPDATE creature_template SET AIName='EventAI' WHERE `entry` = '1502';
```

**Comment by WOW-Reborn** [comment] 2018-09-08 01:56
Thanks, I could fix some things with TrinityCore but now that I'm using cMangos I'm having to learn all over again lol

**Comment by AnonXS** [comment] 2018-09-08 10:38
Thanks for looking it up, i thought it was related as the Zombies in Duskwood Graveyard seem to have the same Issue and there this seemed to have fixed it for me.

**Comment by jimmybrancaccio** [comment] 2018-11-24 18:54
@Grz3s or @AnonXS Is this something we should get into the database then if it seems to resolve the issue?

**Comment by AnonXS** [comment] 2018-11-24 19:09
https://github.com/cmangos/tbc-db/commit/aa9817454085039486ebe883ffb7c8718404580b

https://github.com/cmangos/wotlk-db/commit/c053fbd22cef451ba51a00f262ac52db9c542d79

**Comment by jimmybrancaccio** [comment] 2018-11-24 23:40
Awesome, thanks @AnonXS. If I understand correctly and am looking at [the Updates directory](https://github.com/cmangos/classic-db/tree/master/Updates) correctly, we still need to add this into classic-db?

**Comment by cala** [comment] 2018-11-25 14:59
Backport is probably still pending for Classic DB. I’ll close this issue once I ported the fix.

**Comment by cala** [comment] 2018-11-28 13:56
Done in https://github.com/cmangos/classic-db/commit/6d6f88d65fcafdeba470446fb27f66603d32d8ac

**Closed by cala** 2018-11-28 13:56 UTC
Labels: System: Database, System: NPC, Version: Classic
