### ISSUE TITLE
some spell effect or checkcast issues

### ISSUE THREAD

**Issue by wowmui** [cmangos/issues#1225] opened 2017-01-14 11:13 UTC
**Current behavior**: 
This is a very strange problem.
When the Warlock has a high enough shadow resistance will resist his own Drain Soul spell effects.
And the target will continue to be affected by Drain Soul (If it did not resist the spell).
![image](https://cloud.githubusercontent.com/assets/12601614/21954370/7c51f342-da89-11e6-824b-ce7fee72d64b.png)

And the hunter's Entrapment can be triggered by the debuff of Wyvern Sting. Is that correct?
![image](https://cloud.githubusercontent.com/assets/12601614/21954434/469599e6-da8b-11e6-8f26-72c83f4c226c.png)

And the most important one:
If the first mage cast a Frostbolt X, another mage can not cast Frostbolt X - 1 or less to same target.
![image](https://cloud.githubusercontent.com/assets/12601614/21954488/ee5cf7fe-da8c-11e6-9582-409d9e210fe9.png)

**Client version**: 
1.12.1
**Commit hash**: 
90389d4cfbce86005122ec809dfaed39dfe86ac6
**Database version**: 
z2693
**Operating system**: 
WIN10

[//]: # (If this is a crash report, include the crashlog from a debug build with https://gist.github.com/)

**Comment by dagochen** [comment] 2017-01-14 11:27
this also happens for ghostly strike by rogues and a lot of other abilities and effects. 
i have also seen npcs resisting their own suicide spells in aq20 when they explode, which should not be possible as well.

**Comment by robinsch** [comment] 2017-01-14 11:30
SPELL_AURA_BOUNCED should not be checked for damage effects at all.

**Comment by wowmui** [comment] 2017-01-14 11:30
![image](https://cloud.githubusercontent.com/assets/12601614/21954570/e2a4e86a-da8f-11e6-880c-342f989d6c79.png)

The same problem exists warrior's Sunder Armor

**Comment by Warlockbugs** [comment] 2017-01-14 18:35
The first problem occurs  due to lack of partial effect application system. When we query for spell positivity towards a unit, we need to know which exactly effect mask it is affected by, because a spell can have both positive and negative effects on different targets, which you observe atm. That requires modifying target mapping procedure, to memorize this mask for every affected unit. I've tried to plug this hole to an extent in positive/negative detection via unit relation calls, but there will be always caveats. I'll see what else can be done within given limitation, but this will not replace lacking functionality entirely.

Second and third issues are a recent regression after aura stacking extension to modifers to cover more spells. I am on it.

**Comment by Warlockbugs** [comment] 2017-01-14 19:53
Fixed 2 and 3 in classic and TBC. Wotlk was not affected, because aura stacking was not ported (WotLK aura system relies heavily on exclusiveness, which is not implemented yet).
Doing additional tests for bounces and Drain Soul.

**Comment by Warlockbugs** [comment] 2017-01-14 21:07
To summarize:
Drain Soul resists on self is not a CheckCast issue, but a known issue, impossible to fix properly without adding a hack at the moment. This will be fixed after spell targeting improvements.
Entrapment is not a CheckCast issue, its a proc issue (assumed wrong spell causes proc), so it doesn't match the subject.
Rest of the CheckCast issues are taken care of.

To keep issue tracker clean, i am closing this as it is mostly related to aura stacking regressions. You are welcome to open new separate issues for Entrapment and Drain Soul. Let's stick to one common subject per issue tracker entry.

**Closed by Warlockbugs** 2017-01-14 21:07 UTC

**Comment by wowmui** [comment] 2017-01-15 00:44
@Warlockbugs  Thank you for your hard work ! I apologize for my non-compliance with the theme.
I will open new separate issues for those two problems.
