### ISSUE TITLE
Chess event Karazhan - TBC

### ISSUE THREAD

**Issue by EGSilver** [cmangos/issues#1632] opened 2018-06-24 23:04 UTC
**Current behavior**: 
When starting the Karazhan Chess event, the piece that you control (Your faction kings) runs up the stairs and stands at the waiting room (DND) unable to do anything then watch the event go down.

**Expected behavior**: 
We should be able to move our controlled piece and participate in the fight.

**Steps to reproduce**:

1. .go creature Echo of Medivh (or enter Karazhan and start the chess event.)
2. Take control of you faction king.
3. Afer dismissing the pawn player is also unable to move.

**Client version**: 
2.4.3

**Commit hash**: 

**Database version**: 
Latest.

**Operating system**: 
W10

**Comment by EGSilver** [comment] 2018-06-26 06:49
If someone could point me in the right direction here, what exactly is going wrong. where is this problem exactly comming from?

**Comment by jimmybrancaccio** [comment] 2018-11-17 08:12
Closing as duplicate of #827.

**Closed by jimmybrancaccio** 2018-11-17 08:12 UTC
