### ISSUE TITLE
🐛 [Bug Report] Death Knight ability Raise Dead does nothing

### ISSUE THREAD

**Issue by canidae** [cmangos/issues#2379] opened 2021-01-24 15:58 UTC
## 🐛 Bugreport
Raise Dead is supposed to raise a ghoul, but nothing happens when ability is used (with Corpse Dust in inventory), and the ability becomes infinitely locked.

### Expected behavior
A ghoul should be raised, and ability should begin a 3 minute cooldown.

### Version & Environment
  - "3.3.5a" (WOTLK)
  - [WOTLK Core](https://github.com/cmangos/mangos-wotlk/tree/09729a5ab3f5ded2a1fd2c9352b50a42d6afb189)
  - [WOTLK DB](https://github.com/cmangos/wotlk-db/tree/3ccbb4341fa1e00f1cd2bc0446f61a05e8fcc136)
  - Ubuntu Focal

### Steps to reproduce
1. Use Death Knight ability Raise Dead.
2. Profit

### Crashlog
- None

**Comment by eric-collins2000** [comment] 2021-12-16 01:40
Altering the database I was able to get this to work, albeit a bad working version. The default spell id for raise dead is 46584. A functional though somewhat different spell (52150) works, but due to not having an entry in the pet_levelstats table it will be "weakified" having just one hp. If you add in rows for the pet "26125" (you can copy the felguard, but there are better ways) this will allow you to at least have that covered.

Change the row "46584" in wotlkmangos`.`spell_template to the below. I am going to see if I can cause it to need a reagent, but I'm not sure what the rest of the fields do without a bit of trial and error.


'46584', '1245', '0', '0', '2181038080', '132096', '1', '262144', '0', '2097152', '32', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '1', '0', '180000', '0', '0', '0', '0', '101', '0', '0', '56', '56', '0', '5', '0', '0', '0', '0', '4', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '-1', '0', '0', '56', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '87', '0', '0', '86', '8', '0', '0', '10', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '9311', '0', '221', '0', '0', 'Raise Dead', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '0', '133', '1500', '0', '15', '4096', '0', '0', '0', '1', '0', '1', '1', '1', '0', '0', '0', '0', '0', '0', '1', '341', '0', '0', '0', '0', '0', '0', '0', '0', '0'

Issues:

No reagent, doesn't check for a corpse. Currently The recharge timer never appears to start, with my edit. 52150 functions correctly, so it should just be a matter of finding the right field. Relogging will reset the timer.

**Comment by killerwife** [comment] 2022-01-28 19:37
Closed by https://github.com/cmangos/mangos-wotlk/commit/0a6a8b01cfd5ab9e5933e4f75bd13be3ae960f84

**Closed by killerwife** 2022-01-28 19:37 UTC
Labels: Info: Needs Replication, Class: Death Knight

**Comment by Eriumango** [comment] 2022-02-15 00:42
doesnt seem to work

**Comment by killerwife** [comment] 2022-02-15 09:55
I did a clean pull with db rebuild and it works perfectly fine.

**Comment by Eriumango** [comment] 2022-02-15 12:56
ok I just built mine last saturday and my dk cant use the class spell 46584.
 I can give myself spell 46585 and i can raise a  lvl1 guy or 52150 which raises a full pet version, but by itself 46584 does nothing

**Comment by Nytanath** [comment] 2022-02-15 13:14
Tested with Corpse Dust: ghoul does not appear, cooldown does not start until you teleport to another map, spell remains unuseable until then.
Tested with a humanoid corpse nearby: works as expected.

**Comment by eric-collins2000** [comment] 2022-02-15 18:06
Functions as intended for me. But only with permeant pet.

Fresh build of DB and binaries.

Method: created lvl 1 character used GM to level character to 55, created
DK used GM to level to 80 in start zone. Gave money bought corpse dust.
Summoned ghoul, ghoul was level 1. After applying points was as intended.
Uses dust, summons an appropriate pet.

Level and stats for pet are a reference to the DB, so an easy fix.

**Comment by killerwife** [comment] 2022-02-15 20:40
Already fixed level in db several hours ago and I also pushed additional core commits for it.

**Comment by Nytanath** [comment] 2022-02-15 21:50
This is the behavior I get on a currently up-to-date DB and core. This is without any talent points spent:

https://mega.nz/file/7yZiHTiL#0b0J4rCSCIQv6wiYCIKj71xBv08e74whcBYLexdTzEE

**Comment by Nytanath** [comment] 2022-02-15 22:01
[Remade the video since I forgot to rerun CMake to get updated hash in .server info]

This is the behavior I get on a currently up-to-date DB and core, without any talent points spent:

https://user-images.githubusercontent.com/99603810/154156738-3212551d-c528-4882-963e-bf64e6f32277.mp4

The spell starts its cooldown one minute after used, even if no Ghoul appears, so that part works correctly.

**Comment by eric-collins2000** [comment] 2022-02-15 22:57
Thanks killer, I had the older DB. Any chance you'll look at
cryptfever/Ebon plaguebringer?

Will test tonight.

**Comment by killerwife** [comment] 2022-02-15 23:26
Those are also working on my end. I will test casting ghoul on lvl 56 tomorrow.

**Comment by Eriumango** [comment] 2022-02-18 23:15
I did some testing on this and for my own server am going with a compromise, 
1. I'm going to forget about the need for corpse dust or a corpse, I just want the dk to  be able to summon a pet if he  has the ghoul master talent or a 1 min guardian if he doesn't.
2. I removed the script entry for the raise dead from spell_scripts
delete from spell_scripts where id = 46584.
This means I  don't use the code in  \src\game\Spells\Scripts\Scripting\ClassScripts\DeathKnight.cpp

I instead added some simple code to \src\game\Spells\SpellEffects.cpp
in the function void Spell::EffectScriptEffect(SpellEffectIndex eff_idx) 
and in the section  case SPELLFAMILY_DEATHKNIGHT: 
I added a new spell handling for 46584 which is the class spell for raise dead
                case 46584:      // raise dead
                {
                    if (!unitTarget || m_caster->GetTypeId() != TYPEID_PLAYER)
                        return;
                    switch (eff_idx)
                    {
                        case EFFECT_INDEX_0:
                            return;
                      
                        //1 min version ghoul
                        case EFFECT_INDEX_1:
                        {
                            if (((Player*)m_caster)->HasSpell(52143))  //if he has master of ghouls 52143
                            {
                                //dont call perm ghoul with eff 1
                            } else {
                                m_caster->CastSpell(m_caster,46585,TRIGGERED_OLD_TRIGGERED); //raise dead, the 1 min kind
                            }
                        }
                        //ghoul master version
                        case EFFECT_INDEX_2:    
                        {
                            if (((Player*)m_caster)->HasSpell(52143))  //if he has master of ghouls 52143
                            {
                                //m_caster->CastSpell(m_caster, 48289, TRIGGERED_IGNORE_GCD);
                                m_caster->CastSpell(m_caster,52150,TRIGGERED_OLD_TRIGGERED); //raise dead the perm pet kind
                            }
                        }
                    }                             
                }
This works ok, I get a spell not ready message after i cast it, but it works I get either a 1 min  ghoul or a pet depending on the skills . for the 1 min the timer starts as soon as its dead.

**Comment by Nytanath** [comment] 2022-02-18 23:18
> I'm going to forget about the need for corpse dust or a corpse, I just want the dk to be able to summon a pet if he has the ghoul master talent or a 1 min guardian if he doesn't.

In that case the ghoul already works fine without changes, if you have a nearby corpse to use. The bug is only with untalented + Corpse Dust (I didn't test talented, actually).

**Comment by Eriumango** [comment] 2022-02-18 23:22
spell 48929 which i eventually dropped, is raise dead, it consumes a corpse dust (but doesnt summon anything)
I played around with it a bit , but would need to do a lot more coding (than i can or want to :))

**Comment by killerwife** [comment] 2022-02-19 09:14
Ok I did the following. I fully setup mangos-wotlk on my laptop, which is a separate computer. I created a completely new Death Knight. I added 20 corpse dust into inventory, leveled up to 56. I first used it with talented, summoned a permanent ghoul. I killed him, started cooldown. Then I waited out cooldown (cos there is a small bug where cooldown clear doesnt work on the ghoul spell clientside), removed all talents, summoned temporary ghoul, who after dying properly started cooldown.

And I did all of it here:

![image](https://user-images.githubusercontent.com/7995382/154794612-9313fdf2-6217-45d6-a492-84644190ab81.png)

So what am I doing wrong, because I cant find anything bugged.

**Comment by Eriumango** [comment] 2022-02-19 10:14
Teleport to somewhere outside of the starting instance e.g stormwind

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Eriumango** [comment] 2022-02-19 10:21
Hi I found that if I levelled to 56 and got corpse dust (untalented ) yes I could summon in the start instance, but if i waited till it reset and the ghoul had died and teleported to somewhere like stormwind , it wouldnt work then 
thats why I made on my server the changes i did as they worked in the start instance and outside

**Comment by killerwife** [comment] 2022-02-19 10:37
I teleported to silvermoon city, did the whole shebang again, still works. Still untalented.

**Comment by Eriumango** [comment] 2022-02-19 10:56
ok thanks for checking on your side. I will try a clean slate and see how it goes later.

**Comment by Nytanath** [comment] 2022-02-19 17:56
I tried in GM Island and it worked. Looks like a vmaps issue on my end, sorry for the bother :P

**Comment by killerwife** [comment] 2022-02-19 18:01
Okay, until further notice I consider this closed then.
