### ISSUE TITLE
Conditioned EventAI on Death

### ISSUE THREAD

**Issue by killerwife** [cmangos/issues#886] opened 2016-03-30 13:19 UTC
Currently we support conditioned RECEIVE_EMOTE in EventAI. 
After quest 11000 Into the Soulgrinder, all ogres in Blade's Edge Mountains are supposed to make an emote on death. Our db system only supports unconditioned DEATH scripts/events. The alternative to that is writing and SD2 AI for about 30 mobs in blade's edge.

Example of such behaviour https://youtu.be/FCZWQ2c2PDQ?t=1m29s

Proposed change: https://gist.github.com/killerwife/0f0aa00e9735afd0bc7df1cea79eb039
Implement the same system used for RECEIVE_EMOTE for DEATH.
Old cold will still function as intended before the change.

@cala @evil-at-wow @Grz3s @xfurry @X-Savior

**Comment by cala** [comment] 2016-03-30 13:24
What do you mean by ''unconditioned DEATH scripts/events"? Currently, you can prevent/stop the execution of a DB scripts with the commands 31 TERMINATE_SCRIPT and 34 TERMINATE_CONDITION which are true when a nearby creature is dead/alive or a condition specified in the `conditions` table is met.
I may not well understand what you want to achieve.

**Comment by killerwife** [comment] 2016-03-30 13:29
TERMINATE_CONDITION makes it so that the script is cancelled, so lets say we will have two scripts, both DELAY 0, one TERMINATE_CONDITION and the other SAY_TEXT, what if the SAY_TEXT gets executed first, or am I thinking about it wrong?

**Comment by cala** [comment] 2016-03-30 14:12
You are right. Is a delay of 1 for the second script totally inacceptable?

**Comment by X-Savior** [comment] 2016-03-30 14:51
there is a few places this would be nice to have. I think it is a good idea.

**Comment by killerwife** [comment] 2016-03-30 14:55
The delay 1 would definitely make it look "laggy".

**Comment by xfurry** [comment] 2016-03-30 15:45
> The delay 1 would definitely make it look "laggy".

What about a delay lower than 1 sec?

**Comment by killerwife** [comment] 2016-03-30 15:49
Delay in dbscripts is integer afaik.

**Comment by xfurry** [comment] 2016-03-30 16:05
> Delay in dbscripts is integer afaik.

I know. But I think that we could change that, if it helps.

**Comment by killerwife** [comment] 2016-03-30 16:08
Yes, that would generally help when scripting some quests where there is critical timing required (I had to use SD2 because of it) but in this case anything greater than 0 will just feel generally clunky and workaroundishly. That is my opinion.

**Comment by xfurry** [comment] 2016-03-30 16:16
Well the problem is that I can't see how can we add more conditions to eventAI death event.
One option would be to add some additional parameter to check for the killer unit entry in case of creatures.
In case of DBscripts it would be pretty complicated to do more related to conditions.

**Comment by killerwife** [comment] 2016-03-30 16:18
The death event has no parameters right now (at least not in TBC), which means all 4 entries for parameters are unused. The event function is already supplied with the killer Unit* so thats not an issue either. If you look inside my gist, you will see the stuff that would change in code.

**Comment by Schmoozerd** [comment] 2016-03-31 18:29
I am not happy about introducing the old-style sort of "static" conditions.
The static considitions is basicly an inferiour system.

The difficulty is to evaluate:
1) Starting using Condition_IDs within eventAI will
* introduce seriously more complexity and coordinative efforts beween DB and EventAI
* provide much more powers and possiblities

2) Adding the static conditions to EventAI, will
* Possible provide features we currently need and might be sufficient for some amount of time
* Prevent adding additional data to the EventType, as three fields are "occupied" with conditioning stuff

On a side note:
If you decide (which is a perfectly valid concept) to go for static conditions to eventAI OnDeath event, then i suggest to not limit it to player, but maybe also other cases - however be sure that playerControlled (i.e. Pets) must be possible to be assigned to players (I think we had this with the targeting flag)

On a second side note:
Usually these on-death hooks are rather static and explicitly non-combat, so eventAi is not the natural position for these hooks - contrary to DBScripts on Death (if the exist already)
However you must be aware that triggering the DBscripts usually is expected on the generic Map timer, so it is naturaly not on death, and i.e. triggering an action on death might result in problems with mobs that are usummoned on death !

Btw. Hope you all found some nice eggs :)

**Comment by killerwife** [comment] 2016-03-31 18:41
Well, the solution to all of this would be if in a given delay TERMINATE/TERMINATE_CONDITION was always executed first. As a result, we would be able to create nicer scripts and we wouldn't need this EventAI change AT ALL.

**Comment by cyberium** [comment] 2017-09-08 20:50
This is not a real issue a PR or a push will be better ;)

**Closed by cyberium** 2017-09-08 20:50 UTC
