### ISSUE TITLE
🚀 [Feature Request] Max Level Auto-Delete Character(s)

### ISSUE THREAD

**Issue by al3xc1985** [cmangos/issues#2202] opened 2020-05-11 15:09 UTC
## 🚀 Feature

it would be nice to have a cleaning of our servers with extending allready have feature...
for example we have:
#    CharDelete.MinLevel
#        Character gets deleted by CharDelete.Method=0 when the character
#        hasn't the specified level yet.
#        Default: 0  - For all characters the specified mode will be used
#                 1+ - Only for players which have reached the specified level
#                      will be deleted by the specified mode.
#                      the rest will be deleted by CharDelete.Method=0

we need a new feature with CharDeleteMaxLevel to clean the db for example for ALL chars that are for example level 1, and left there only to keep the name busy... someone might want that name, but is allready taken by someone that entered the server, created the chars and left them there... and anybody else who is playing the server frequently can not have his disered name because of this type of ppl who just create chars only to have occupied a name

### Benefits & Purpose

Clear char db names

**Comment by evil-at-wow** [comment] 2020-05-11 20:37
And then you delete someone's level 1 banker character. Oops. :smile:

I like that you also describe _why_ you want this feature request, that you mention what problem it would solve for you. However, I think in your use case deleting characters is a so called "global solution for a local problem". The problem is that you want to free the names of characters that haven't been played for a (long) while - and perhaps not just low level characters but also higher level characters if that account has been offline for too long - and not that you really want to delete these characters. 

So I think what should get implemented here is really something to free up character names from accounts that haven't been online since a given date & time. And I don't think we have to do a lot of work for that: for the characters where we free the name, we could simply set the at_login flag 1 (AT_LOGIN_RESETNAME), so they are forced to pick a new name. That of course leaves their name in the database, so creating a new character will that name will fail because ObjectMgr::GetPlayerGuidByName() finds the name in the database. We could adjust the query used there to only select Guids for characters that don't have the at_login flag set; that way characters can be created with a name already taken by characters that have to be renamed. Which is what you want. 

In fact, if we just adjust the query, one could free up names already with an SQL query that sets the at_login flag 1 for characters as admins require (say on accounts that didn't log in since x, perhaps even limited to certain character levels or account levels, etc).

**Comment by al3xc1985** [comment] 2020-05-12 03:06
I like your ideea too

**Comment by killerwife** [comment] 2022-01-31 14:02
I would never recommend this being an automatic feature. This can go wrong too many ways. On vengeance we did this with a two prone attack. We checked all people who were offline beyond a certain threshold, lets say 1 year, and below a certain level and with a certain time played. Those were the only ones then eligible for transfering a character. This can be managed easily by setting account to 0 for a character with an SQL query and server will then do the whooooole cleanup on its own. As such, I am closing this since the server admin needs to know what he is doing when potentially manipulating thousands of characters.

**Closed by killerwife** 2022-01-31 14:02 UTC
Labels: Type: Feature Request
