### ISSUE TITLE
[CLASSIC] Songflower Serenade and Mark of the Wild/Gift of the Wild Exclusive to Each Other

### ISSUE THREAD

**Issue by Ginnerskov** [cmangos/issues#1490] opened 2017-10-17 19:46 UTC
**Current behavior**:  You can't have both SF Serenade buff (Spell ID: 15366) and Gift of the Wild (Spell ID: 21850) at the same time.

**Expected behavior**: 
You're supposed to be able to have both at the same time.

**Steps to reproduce**:

1.  Apply any of the aura and try to apply the other.
2. 
3. 

**Client version**: 
1.12.1

**Commit hash**: 
e276ece8028936771c998786d33fcce6b72a8fc5

**Database version**: 
Classic DB Version 1.8.5

**Operating system**: 
Windows 10

[//]: # (If this is a crash report, include the crashlog from a debug build with https://gist.github.com/)

**Comment by cala** [comment] 2019-05-06 21:42
Thank you. This is a duplicate of https://github.com/cmangos/issues/issues/1280

**Closed by cala** 2019-05-06 21:42 UTC
Labels: System: Spells, Type: Regression, Version: Classic
