### ISSUE TITLE
🐛 [Bug Report] 

### ISSUE THREAD

**Issue by ghost** [cmangos/issues#3576] opened 2023-10-05 21:13 UTC
### Bug Details

When I tried to compile CMaNGOS on my *nix machine i got an
I've gotten a similar error log with the first 3 examples in the "invoke cmake ../mangos" part

This was from the master branch that I downloaded a couple of hours earlier as the same day I submit this.

### Steps to Reproduce

1. cmake with 3 first examples
2.
3.
4.

### Crash Log

[ 91%] Building CXX object src/game/CMakeFiles/game.dir/vmap/ModelInstance.cpp.o
[ 91%] Building CXX object src/game/CMakeFiles/game.dir/vmap/TileAssembler.cpp.o
during GIMPLE pass: vrp
/mnt/[Harddrive Name]/PrivateWoWInstall/cmangos/mangos/src/game/vmap/TileAssembler.cpp: In member function ‘void VMAP::TileAssembler::exportGameobjectModels()’:
/mnt/[Harddrive Name]/PrivateWoWInstall/cmangos/mangos/src/game/vmap/TileAssembler.cpp:332:10: internal compiler error: in compute_live_loop_exits, at tree-ssa-loop-manip.c:247
  332 |     void TileAssembler::exportGameobjectModels()
      |          ^~~~~~~~~~~~~
0x7f1f25e29d8f __libc_start_call_main
	../sysdeps/nptl/libc_start_call_main.h:58
0x7f1f25e29e3f __libc_start_main_impl
	../csu/libc-start.c:392

### Core SHA1 Commit Hash

259e30e471b2f0c85a9e257c61674c2708cd8417

### Database SHA1 Commit Hash

39aa1e218b4bac8c2059ea905463960322a21d09

### Operating System

Ubuntu 22.04.3 LTS

### Client Version

2.4.3 (The Burning Crusade)

**Comment by evil-at-wow** [comment] 2023-10-05 21:23
This is most likely a duplicate of cmangos/issues#3165 and it's a bug in GCC, the compiler on your system. If you check the output when running CMake, it will probably contain a warning about the GCC version you're using - being GCC 11. You need to either upgrade GCC, or use a different compiler.

**Closed as completed by evil-at-wow** 2023-10-05 21:23 UTC
Labels: Info: Needs Replication

**Comment by ghost** [comment] 2023-10-06 17:52
Thanks a lot for the help, updating the GCC got me through that bump!
