### ISSUE TITLE
[CLASSIC]There are a lot of mistakes in spell_template

### ISSUE THREAD

**Issue by yushicsm** [cmangos/issues#1374] opened 2017-06-04 14:00 UTC
when we use spell.dbc，most of spells work well
when we change to use spell_template，lot of spells have mistakes
For example，spell Breath（17086，18351...），Dragon Orb(19869) and many more
i think the problem was in Attributes.

**Comment by cala** [comment] 2017-06-04 19:16
Poke @killerwife who did the switch from DBC to spell template.

**Comment by killerwife** [comment] 2017-06-04 19:20
I am unable to find the aforementioned issues. I just checked against my clean 1.12.1 spell DBC in my SQL and I checked the values against QSW. I am not saying there is not a mistake somewhere, I am just saying I can't find it with your information.

**Comment by yushicsm** [comment] 2017-06-04 21:28
TEST this，we will see
in the Blackwing Lair，first room
if we use  spell.dbc，we can use “Orb of Domination” to control “Razorgore the Untamed”
but when we use spell_template，we cant use that.

And this https://github.com/cmangos/issues/issues/1212
this because the spell Dual Wield（674） miss passive attribute 
and so many spells miss passive attribute

**Comment by yushicsm** [comment] 2017-06-04 21:37
Onyxia's spell Breath（17086，18351...），
if we use spell.dbc，we will see the Damage and the range of Breath is very large
but when we use spell_template，we see the Damage and the range of Breath is very small

**Comment by cala** [comment] 2017-06-05 10:23
@yushicsm I fully agree with you that recently some spells were broken and I saw myself the Dual Wield bug on dead characters or the Orb of Command/Domination bug with Razorgore the Untamed boss. But, looking at the difference between the DBC and the spell_template table, I cannot see where it comes from:

> And this #1212
this because the spell Dual Wield（674） miss passive attribute （0x00800000）
and so many spells miss passive attribute（0x00800000）

In Classic: SPELL_ATTR_PASSIVE is 0x00000040 and is correctly set both in DBC and spell_template for spell 674.
0x00800000 is SPELL_ATTR_CASTABLE_WHILE_DEAD. It would make sense for Dual Wield, indeed but I cannot find it in spell_template nor in DBC.

So, like @killerwife said: yes there is a problem indeed, but we cannot spot it based solely on the DBC/spell_template comparison. It may comes from the changes that occurred to the spell system or also possibly from the way spell_template is loaded into core in regards of how DBC were.

**Comment by killerwife** [comment] 2017-06-05 10:25
Hm, what if the actual issue is not in the export data, but in the data we read :D DBCFmt might be slightly off, causing this.

**Comment by cala** [comment] 2017-06-05 10:28
That's also a possibility. Do you have an idea how we could check this to at least needle the cause of the problem?

**Comment by killerwife** [comment] 2017-06-05 10:37
simple, put breakpoint in Spell::Prepare if m_spellInfo->Id==674 and check the whole m_spellInfo against Database/QSW. If indeed this is not the same, let me know and I will setup my classic branch.

**Comment by cala** [comment] 2017-06-05 11:39
I'll try to test this this week/WE. Thanks

**Comment by cala** [comment] 2017-06-08 22:03
As promised, I tested further this issue.

**Regarding spell 674**
- I found no difference between QSW, spell_template table and m_spellinfo (I only looked at the fields having a value ≠ 0 in the database though)
- I reverted commit https://github.com/cmangos/mangos-classic/commit/e72ad52fc983309be6f726cd094f153456dcc8d3 and it did not fix spell 674
- what happens: spell 674 is passive and allows players to dual wield. If a player dies, the spell is not removed. However, when a player logs in, the spell is only applied if the player is alive. If he/she is dead, the spell is not applied, resulting in a bug: the weapon in offhand is removed. Adding attribute 0x00800000 (SPELL_ATTR_CASTABLE_WHILE_DEAD) indeed fixes the issue, however, I do not see it in the DBC (at least not via QSW).

**Regarding spell 19869**
- I reverted commit https://github.com/cmangos/mangos-classic/commit/e72ad52fc983309be6f726cd094f153456dcc8d3 and it did not fix the spell
- I looked at the way the spell is scripted in the core and found out that the script is wrong as it requires the target to have an aura that is only available to players having successfully be targeted by the spell, hence the condition can never be true. I will push a fix soon but I wonder how the spell may ever have worked at a time, unless someone inadvertently broke the script recently.

**My opinion**
It is extremely likely that the switch from DBC to spell_template is unrelated to the aforementioned issues (at least Dual Wield and Dragon Orb, I did not look at the breaths). Either the mechanics of the spells were broken by some changes that occurred in recent times or recent changes/fixes in the spell/aura systems unveiled the bugs of these specific spells. Maybe @Warlockbugs have an opinion on this matter.

**My suggestions**
- For spell 674: adds the missing attribute in spell_template via SQL core update
- For spell 19869: fix the script in the core

If you are fine with this, I'll push the fixes ASAP.

**Comment by killerwife** [comment] 2017-06-08 22:05
i know fix. will do it in the morning. thx for investigating                                                                                                                                                                                                                                                                                                                                        Sent from my BlackBerry 10 smartphone on the Orange network.

**Comment by yushicsm** [comment] 2017-06-08 23:17
before i update my core to the latest, i use https://github.com/cmangos/mangos-classic/tree/543121485418c551d3513e32b87f002bdce371ee 
in that version ,the spells(674,19869,Breath) work well 
so i think spell 19869 may not need fix the script in the core
@cala

**Comment by killerwife** [comment] 2017-06-09 09:28
https://github.com/cmangos/mangos-tbc/commit/56f09ca4cef73ced1ac37686966057289df21759 Fixes the dual weild issue. I encountered this bug 4 months ago, and I think the fix is one of my unprocessed PRs as well. Oh well, still progress is progress.

**Comment by cala** [comment] 2017-06-09 12:42
The spell for controlling Razorgore is fixed in commit: https://github.com/cmangos/mangos-classic/commit/584693333b65f6e8c4126df7e295f307a16c29d0

I would like more information about the breath issue, so we can investigate it further.

**Comment by cala** [comment] 2017-08-24 08:27
Without more feedback about the breath issue, I will close this soon.

**Closed** 2017-09-10 11:42 UTC
