### ISSUE TITLE
💬 [Support Request] Please Help Me Understand Why My Core Crashes

### ISSUE THREAD

**Issue by Radu1806** [cmangos/issues#2230] opened 2020-07-11 13:59 UTC
## 💬 Support Request

Hi, can anyone help me understand, i would be grateful.
Getting this segfault when trying to enter Tempest Keep (The Eye)
+++++++++++++Attached logs below++++++++++++++++++++++
Initializing Scripting Library...
  _____           _       _   _____ 
 / ____|         (_)     | | |  __ \
| (___   ___ _ __ _ _ __ | |_| |  | | _____   __
 \___ \ / __| '__| | '_ \| __| |  | |/ _ \ \ / /
 ____) | (__| |  | | |_) | |_| |__| |  __/\ V / 
|_____/ \___|_|  |_| .__/ \__|_____/ \___| \_/ 
                   | |
                   |_| http://www.cmangos.net
SD2: Loading Script Texts...
Loading texts from script_texts, with additional data
>> Loaded 3013 text templates from script_texts

SD2: Loading Custom Texts...
Loading texts from custom_texts, with additional data

>> Loaded 0 string templates. DB table `custom_texts` is empty.
SD2: Loading Gossip Texts...
Loading texts from gossip_texts
>> Loaded 76 string templates from gossip_texts

SD2: Loading Script Waypoints for 109 creature(s)...

>> Loaded 3912 Script Waypoint nodes.
SD2: Loading C++ scripts

Script registering but ScriptName npc_gauntlet_of_fire is not assigned in database. Script will not be used.
No script found for ScriptName 'npc_target_trigger'.
>> Loaded 858 C++ Scripts.

Loading spell scripts...
Initialize game time and timers
Starting Outdoor PvP System
>> Loaded 6 Outdoor PvP zones

Starting Map System

Starting BattleGround System
>> Loaded 8 battlegrounds

Loading Transports...
>> Loaded 10 transports

Deleting expired bans...

Calculate next daily quest reset time...

Calculate next weekly quest reset time...

Calculate next monthly quest reset time...

Loading Spam records...

Starting Game Event system...
GameEvent 14 "Elemental Invasion: Air" started.
GameEvent 16 "Gurubashi Arena Booty Run" started.
GameEvent 21 "Call to Arms: Eye of the Storm!" started.
GameEvent 24 "Stormwind City - Stockades Jail Break" started.
GameEvent 29 "Zul'Gurub - Edge of Madness (Gri'lek)" started.
GameEvent 70 "Brew of the Month - July" started.
GameEvent 78 "Darkmoon Faire (Terokkar Forest) - Darkmoon Faire Open" started.
Next game event check in 447 seconds.
Game Event system initialized.

Loading Quest Group chosen quests...
GameEvent 1005 "Random Daily Dungeon - Wanted: Sunseeker Channelers" started.
GameEvent 1010 "Random Daily Heroic - Wanted: A Warp Splinter Clipping" started.
GameEvent 1025 "Random Daily PVP - Call to Arms: Arathi Basin" started.
GameEvent 1130 "Cooking - Random Daily - Soup for the Soul" started.
GameEvent 1132 "Fishing - Random Daily - Bait Bandits" started.

Player::DeleteOldChars: Deleting all characters which have been deleted 30 days before...

Initialize AuctionHouseBot...
AHBOT is Disabled. Unable to open configuration file(../etc/ahbot.conf). 

Loading WorldState

---------------------------------------
      CMANGOS: World initialized       
---------------------------------------

SERVER STARTUP TIME: 0 minutes 4 seconds

mangos>WaypointMovementGenerator::LoadPath: Creature (Entry: 20038 Guid: 5500060) doesn't have waypoint path 0
void WaypointMovementGenerator<Creature>::InitializeWaypointPath> unable to intialize path for Creature (Entry: 20038 Guid: 5500060)
Segmentation fault (core dumped)

### Version & Environment

Client Version: 
2.4.3" (TBC)

CMaNGOS Repo & Commit Hash: 
[TBC](https://github.com/cmangos/mangos-tbc/tree/82e851cfee73fc24f1f4ed2ff5592397c88305b4)

Database Repo & Commit Hash: 
[TBC](https://github.com/cmangos/tbc-db/tree/3ff738d98e479850209d79ffadbb40d2fb9b68de)

Operating System: 
Ubuntu 20.04

### Steps to reproduce
1.Create  level 70 character.
2. .tele theye
3.Enter instance as GM or create another char to join as a raid group, tried both
4. Server crashes with the error posted above or below.
5. SERVER STARTUP TIME: 0 minutes 4 seconds

mangos>WaypointMovementGenerator::LoadPath: Creature (Entry: 20038 Guid: 5500060) doesn't have waypoint path 0
void WaypointMovementGenerator<Creature>::InitializeWaypointPath> unable to intialize path for Creature (Entry: 20038 Guid: 5500060)
Segmentation fault (core dumped)

**Comment by Grz3s** [comment] 2020-07-11 14:26
this will fix it..
```sql
UPDATE creature SET spawndist = 0, MovementType = 0 WHERE guid = 5500060;
```
he is slave for @CGUID+48 and has no waypoints (shouldnt have) ... 

DB DEVS:  fix need to be added in `Instance` file 
550_the_eye.sql
```sql
(@CGUID+60, 20038, 550, 1, 354.06, -39.9079, -2.38663, 3.94531, 10800, 10800, 0, 0, 0, 0), -- Phoenix-Hawk Hatchling
```

**Comment by Radu1806** [comment] 2020-07-11 15:18
Appreciate you help, i'm new to this and i've just installed the database as shown in tutorial and have no tempered with.
Can you please make me understand what updates i'm missing and where to get them?
Thank you.

**Comment by Grz3s** [comment] 2020-07-11 15:22
this issue is in DB... and need to be implemented by devs (poke myself) ... it doesnt mean that you missing smth ;)
btw: if u followed instalation tutorial for core... and then run ./installFULLdb.sh for DB .. you should have everything correct and up to date.

**Comment by Radu1806** [comment] 2020-07-11 15:33
Apparently most of them will do this, this happened after i've applied the line you provided.
mangos>WaypointMovementGenerator::LoadPath: Creature (Entry: 20031 Guid: 5500011) doesn't have waypoint path 0
void WaypointMovementGenerator<Creature>::InitializeWaypointPath> unable to intialize path for Creature (Entry: 20031 Guid: 5500011)
WaypointMovementGenerator::LoadPath: Creature (Entry: 20031 Guid: 5500012) doesn't have waypoint path 0
void WaypointMovementGenerator<Creature>::InitializeWaypointPath> unable to intialize path for Creature (Entry: 20031 Guid: 5500012)
Segmentation fault (core dumped)

**Comment by Grz3s** [comment] 2020-07-11 15:47
hmmm
@AnonXS looks like you guys did smth to this instance,,,

(@CGUID+11, @CGUID+135, 1679), -- Bloodwarder Legionnaire -> Nether Scryer
(@CGUID+12, @CGUID+135, 1679), -- Bloodwarder Legionnaire -> Nether Scryer

so how 5500011 and 5500012 ... and prob .. more .. has movement Template = 2?

Fix will be exact the same as prev:
```sql
UPDATE creature SET spawndist = 0, MovementType = 0 WHERE guid IN (5500011,5500012);
```

**Comment by Radu1806** [comment] 2020-07-11 15:52
Excellent, thank you for the quick feedback and help.

**Comment by AnonXS** [comment] 2020-07-11 16:42
yea prob just an oversight as they are linked for moving in grp

**Comment by Radu1806** [comment] 2020-07-12 17:45
WaypointMovementGenerator::LoadPath: Creature (Entry: 17906 Guid: 9000988) doesn't have waypoint path 0
void WaypointMovementGenerator<Creature>::InitializeWaypointPath> unable to intialize path for Creature (Entry: 17906 Guid: 9000988)
WaypointMovementGenerator::LoadPath: Creature (Entry: 17906 Guid: 9000989) doesn't have waypoint path 0
void WaypointMovementGenerator<Creature>::InitializeWaypointPath> unable to intialize path for Creature (Entry: 17906 Guid: 9000989)
WaypointMovementGenerator::LoadPath: Creature (Entry: 17906 Guid: 9000990) doesn't have waypoint path 0
void WaypointMovementGenerator<Creature>::InitializeWaypointPath> unable to intialize path for Creature (Entry: 17906 Guid: 9000990)
WaypointMovementGenerator::LoadPath: Creature (Entry: 17906 Guid: 9000991) doesn't have waypoint path 0
void WaypointMovementGenerator<Creature>::InitializeWaypointPath> unable to intialize path for Creature (Entry: 17906 Guid: 9000991)
WaypointMovementGenerator::LoadPath: Creature (Entry: 17906 Guid: 9000992) doesn't have waypoint path 0
void WaypointMovementGenerator<Creature>::InitializeWaypointPath> unable to intialize path for Creature (Entry: 17906 Guid: 9000992)
WaypointMovementGenerator::LoadPath: Creature (Entry: 17906 Guid: 9000993) doesn't have waypoint path 0
void WaypointMovementGenerator<Creature>::InitializeWaypointPath> unable to intialize path for Creature (Entry: 17906 Guid: 9000993)
WaypointMovementGenerator::LoadPath: Creature (Entry: 17906 Guid: 9000994) doesn't have waypoint path 0
void WaypointMovementGenerator<Creature>::InitializeWaypointPath> unable to intialize path for Creature (Entry: 17906 Guid: 9000994)
Segmentation fault (core dumped)

**Comment by Radu1806** [comment] 2020-07-12 17:50
This happened after i cleared human camp in Hyjal, just when Jaina casts teleport.

**Comment by Radu1806** [comment] 2020-07-13 20:19
Furthermore after i applied the fix you provided, again another pack probably but i can't seem to fix it with that command anymore.

WaypointMovementGenerator::LoadPath: Creature (Entry: 17906 Guid: 9000534) doesn't have waypoint path 0
void WaypointMovementGenerator<Creature>::InitializeWaypointPath> unable to intialize path for Creature (Entry: 17906 Guid: 9000534)
WaypointMovementGenerator::LoadPath: Creature (Entry: 17906 Guid: 9000535) doesn't have waypoint path 0
void WaypointMovementGenerator<Creature>::InitializeWaypointPath> unable to intialize path for Creature (Entry: 17906 Guid: 9000535)
WaypointMovementGenerator::LoadPath: Creature (Entry: 17906 Guid: 9000536) doesn't have waypoint path 0
void WaypointMovementGenerator<Creature>::InitializeWaypointPath> unable to intialize path for Creature (Entry: 17906 Guid: 9000536)
WaypointMovementGenerator::LoadPath: Creature (Entry: 17906 Guid: 9000537) doesn't have waypoint path 0
void WaypointMovementGenerator<Creature>::InitializeWaypointPath> unable to intialize path for Creature (Entry: 17906 Guid: 9000537)
WaypointMovementGenerator::LoadPath: Creature (Entry: 17906 Guid: 9000538) doesn't have waypoint path 0
void WaypointMovementGenerator<Creature>::InitializeWaypointPath> unable to intialize path for Creature (Entry: 17906 Guid: 9000538)
WaypointMovementGenerator::LoadPath: Creature (Entry: 17906 Guid: 9000539) doesn't have waypoint path 0
void WaypointMovementGenerator<Creature>::InitializeWaypointPath> unable to intialize path for Creature (Entry: 17906 Guid: 9000539)
WaypointMovementGenerator::LoadPath: Creature (Entry: 17906 Guid: 9000540) doesn't have waypoint path 0
void WaypointMovementGenerator<Creature>::InitializeWaypointPath> unable to intialize path for Creature (Entry: 17906 Guid: 9000540)
Segmentation fault (core dumped)

**Comment by Grz3s** [comment] 2020-07-13 21:38
because theyre summoned... guids there are dynamic...

**Comment by Radu1806** [comment] 2020-07-14 11:51
So how would I fix the error in this situation?

**Comment by Lillecarl** [comment] 2020-10-26 14:17
#2244 is a duplicate of this one.

**Comment by Lillecarl** [comment] 2020-11-16 07:26
Fixed in https://github.com/cmangos/mangos-tbc/commit/b373ab9b3848bb832e3eb91d344fa84e3bead906

**Closed** 2020-11-16 11:21 UTC
Labels: Type: Core Crash, Type: Support
