### ISSUE TITLE
Classic - Reflectors

### ISSUE THREAD

**Issue by dazidkk** [cmangos/issues#1015] opened 2016-08-02 12:31 UTC
Reflectors dont work if you activate them mid air, This is caused by hit being calculated before reflecting.

**Comment by evil-at-wow** [comment] 2016-08-02 19:13
Hit seems to be determined too early indeed, so it's a more general problem than just reflectors. For example, I've noticed that mobs already aggro the moment your Frostbolt, Shadow Bolt, Chaos Bolt, etc starts its journey, rather than when it arrives at its destination.

**Comment by dazidkk** [comment] 2016-08-02 20:25
Anyone with knowledge to rewrite the handling :D?

**Comment by Appled** [comment] 2016-08-03 12:15
This issue persists in TBC as well. If you see a spell flying towards you, and you for example use Ice Block as mage, the spell will still damage you. However if you use the Ice Block before the cast has ended, you are immune. The hit effect seems to be calculated when the cast has finished and the spell starts flying towards you, not when the spell actually hits you.

**Comment by SilvioDoMine** [comment] 2016-08-03 19:53
This issue persists in TBC as well.²

**Comment by dazidkk** [comment] 2016-08-03 21:52
Immune effects work on classic. due to it being calculated before hit

**Comment by Appled** [comment] 2016-08-03 22:19
Then my comment about immunity is irrelavant. But iirc the reflection part is also present in TBC.

**Comment by dagochen** [comment] 2016-09-02 13:49
Sorry guys you are wrong. You need to send to the client, if the projectile (fireball, frostbolt, arrow, or whatever it is) hits or misses (resists) or is reflected, to make the client visualize it correctly. By this reason given you need to check for reflect at the moment of the spell starting to fly and engineering reflectors or other spells/items used midflight can not influence the spell anymore. It would technically work but would need complete rewrite of reflect code, because it would need to be at a different place than the hit calculation. And it might still not work to display the firebolt flying back to the original caster (never seen a video of that from vanilla, though I searched for a long time for it).

**Comment by Phatcat** [comment] 2016-09-02 14:11
@dagochen Oh those can be found. Reflectors very much did reflect the spell back. Visually as well.
you possibly mixing up these two kind of items? http://www.wowhead.com/item=4376/flame-deflector http://www.wowhead.com/item=18638/hyper-radiant-flame-reflector

**Comment by dagochen** [comment] 2016-09-02 16:44
I am talking about reflect. Which means A casts Pyro on B and B reflects the spell back to A. Show me proof, I was searching for it so long and did not found anything from classic (since with TBC it was completely changed because of Arena, PvP and Warriors Reflection Spell).

**Comment by Phatcat** [comment] 2016-09-03 00:53
http://wowwiki.wikia.com/wiki/Hyper-Radiant_Flame_Reflector?oldid=330437
the 'use' it says here should be enough proof, and this is back from vanilla, but as you can read here from pre-TBC: http://www.wowhead.com/item=18638/hyper-radiant-flame-reflector#comments:id=7703 and http://www.wowhead.com/item=18638/hyper-radiant-flame-reflector#comments:id=7712

Those two comments would make no sense if what I saying wasn't true, and it doesn't sound like it's something they have just figured out, it sounds like this is 'common knowledge' at the time, which means this applied to late vanilla as well.

This is not directly proof, though, I know, so I will have to get back to you on this one, I am however gonna need a bit of time to look through old videos.

**Comment by Phatcat** [comment] 2016-09-03 07:19
> I was searching for it so long and did not found anything from classic

I have found that it helps very well to simply google `<topic/mechanic> wow 2006` - this has been yielding me with semi-decent results on most given subjects.

**Comment by Phatcat** [comment] 2016-09-03 07:46
> Immune effects work on classic. due to it being calculated before hit

Should they, though? This greatly affects the usefulness of basically all paladin 'saving' spells; all their bubbles and shields they can do. If I bubble/pop a shield while a spell is in mid air it will still connect and damage me? That doesn't sound right to me, but I never played a pala (past any significant level, at least), so I'd have to look into this..

**Comment by dagochen** [comment] 2016-09-03 08:00
Well then we need to rewrite the core.

**Comment by dagochen** [comment] 2016-09-03 08:01
Because with the current system this is not possible I guess...

**Comment by Phatcat** [comment] 2016-09-03 08:12
> Still not seen any video footage of a mages pyro flying to a target with someone USING the trinket while pyro is ONFLIGHT. Until then I dont believe this was possible in classic.

Oh yeah, video proof of this may actually be somewhat harder to find, I was actually just looking for footage to display a spell getting reflected back in vanilla because that's what I thought you said you'd never seen proof of, not that you could do it mid-flight.

I am not at all 100% sure about being able to reflect mid-flight in vanilla... Actually I am leaning against a no such as yourself on that one for several reasons..

Even though I still believe that immune effects would cancel anything, be the spell still channeling/casting or mid-flight.

**Comment by dagochen** [comment] 2016-09-03 08:18
Nah I said that the midflight-thing is something that is impossible with our current classic core (as far as I investigated) and that I found no source from classic which shows 100% sure, that this feature is needed. And therefore this bugreport is obsolete, since without proof/evidence, there is nor bug and bugfix.

**Comment by Phatcat** [comment] 2016-09-03 08:26
See that, I can get behind.

I am gonna have to agree with @dagochen here, you will need to provide us something, basically anything, which can back up your claim. 
It's a bit like that famous legal saying; "It's not about what you know; it's about what you can prove"

I am closing this by the end of the week should there be nothing new to go by, due to lack of evidence/research. Sorry.

**Comment by dagochen** [comment] 2016-09-03 08:53
Just to make the point: I would really like that feature and I think it was possible in classic ;)

**Comment by Phatcat** [comment] 2016-09-03 08:55
If you have the time and a few $$ to spare (to access archived footage) then http://www.warcraftmovies.com may be the solution.

**Comment by Phatcat** [comment] 2016-09-03 15:19
3:39 https://www.youtube.com/watch?v=0rGdz3PYuwo
2:39 https://www.youtube.com/watch?v=c4bgggKMvQU

Set them both to 0.25 speed

I'm still not sure, though..

**Comment by dagochen** [comment] 2016-09-03 15:54
Yeah both very close. But just by being reasonable I would guess it should be possible. Hit/Miss calculation on spell starting and damage + reflect calculation and so on on target hit. Currently we calculate damage on spell start as well right?

**Comment by Phatcat** [comment] 2016-09-03 16:37
Well, if you find proof of it for TBC I would say it's more than reasonable to assume it was the same for classic and move on that, especially given all other factors (no mention of such change on the wiki for reflection, nor in any comment anywhere I have seen..)
That would also make the most sense, allowing us to do immune/resist on hit as well instead, since there also seems to be issues with that.

About the very specifics of the spell system you'll have to get a hold of someone who has/is working on that, and that ain't me.

**Comment by dagochen** [comment] 2016-09-06 00:37
I know this is no source from 2005/2006, but...

Engineering items
Rocket boots are fully functional and fail at the most inappropriate times.
Reflect trinkets work even when activated while a spell is in flight.

http://classicwarcraft.com/showcase.html

**Comment by mityada** [comment] 2016-09-06 13:03
Let's start with the issue that spell reflects (as well as all other miss types) are not shown in the game correctly in mangos-classic. They always hit the target visually. I've made a PR that fixes it: cmangos/mangos-classic#192.

Now, as you can see, miss information is sent to the client in SMSG_SPELL_GO, that is, when spell is starting to fly. And there seems to be no way to tell the client afterwards that spell should behave differently (e.g. be reflected back). So, while it is technically possible to make the core calculate hit result later, it seems to be not possible to correctly show the new result in the game. In my opinion, it is a strong evidence that reflects could not happen in mid-air on retail.

**Comment by Phatcat** [comment] 2016-09-06 14:44
Not only is it not a source from back in the day, it's not really a source at all. It's a link to a private server. That's not gonna fly, I'm afraid.

mityada, are you then saying that other effects such as immune should not be possible to be triggered mid-flight either?

**Comment by dagochen** [comment] 2016-09-06 18:05
>Sorry guys you are wrong. You need to send to the client, if the projectile (fireball, frostbolt, arrow, or whatever it is) hits or misses (resists) or is reflected, to make the client visualize it correctly. By this reason given you need to check for reflect at the moment of the spell starting to fly and engineering reflectors or other spells/items used midflight can not influence the spell anymore. It would technically work but would need complete rewrite of reflect code, because it would need to be at a different place than the hit calculation. And it might still not work to display the firebolt flying back to the original caster (never seen a video of that from vanilla, though I searched for a long time for it).

@mityada So this was correct in every single point? Thx ;)

**Comment by namreeb** [comment] 2016-09-06 19:48
I'm not sure that there is a suitable opcode to use to trigger the reflection animation after the initial projectile launch.

**Comment by dagochen** [comment] 2016-09-06 21:07
Yeah something like SMSG_SPELL_UPDATE which can change the hitresult-flags would be great, but I didn't found something like that... :(

**Comment by killerwife** [comment] 2016-09-06 21:12
Just compute it sooner and it will work with SPELL_GO i think.

**Comment by Warlockbugs** [comment] 2016-09-06 21:25
By the way, from what i know, reflectors are a very specific thing in terms of being able to cause reflect ping-ponging. Usual (Warrior's for example) spell reflection is limited to 1 reflect, if reflected spell hit reflection again, it will register as "immune" and counted as failed.

**Comment by mityada** [comment] 2016-09-06 21:38
@killerwife, the question is whether it's possible to change is _later_, after SMSG_SPELL_GO was sent. So no, it won't work.

**Comment by cyberium** [comment] 2016-09-06 22:07
My 2 cents
Iam on possessing spell.

[![Spell hit problem](https://img.youtube.com/vi/APNFRpRenSo/0.jpg)](https://www.youtube.com/watch?v=APNFRpRenSo)

I have related problem. You can see that the projectile is hitting the npc right after i canceled possess aura. I am waiting for it to launch it then i cancel the aura while in air.

Look the result. So iam almost sure we are missing some check at spell hit.
(The projectile should never cause damage to a same creature faction)

**Comment by Chaosvex** [comment] 2016-09-06 23:37
Trawled some archives and found a relevant clip from "Mage PvP - Love and Bullets 2", patch 1.12 (at the latest), http://www.warcraftmovies.com/movieview.php?id=30837

The Gyrofreeze trinket is activated as the spell is mid-air and is not reflected:
https://www.youtube.com/watch?v=k1MIZfeL1rM

Another clip, this time from "Tosan: Gyrofreak", patch 1.12 again, http://www.warcraftmovies.com/movieview.php?id=27832

Gyrofreeze is activated a few frames after he gets hit by the frostbolt, although it does reflect something but I'm not sure what since neither player seems to be afflicted with the movement impairing debuff. The movement debuff on the rogue is Blast Wave once his Sprint wears off, just to be clear.

**Comment by namreeb** [comment] 2016-09-07 20:34
To me that is good enough proof that it is not supposed to reflect if the reflector is activated once the spell is already flying.

**Closed by namreeb** 2016-09-07 20:34 UTC

**Comment by Phatcat** [comment] 2016-09-07 20:51
@cyberium I think we can still solve that as well as the immune problem, as that is not relating to spell animation, and it is indeed the animation that were the problem here, right? We can change a spell from dealing damage to being resisted mid air with our current core, no?

**Comment by dagochen** [comment] 2016-09-07 21:28
Yes we can.

**Comment by Laizerox** [comment] 2016-09-07 21:52
@Phatcat technically yes, but client doesn't support it. Client expects result on spell cast. There is no way to update hit result of already started spell in client.

So this is not a bug because client expects to know the result of spell cast as soon as it starts (instant) / finishes (delayed).

**Comment by Phatcat** [comment] 2016-09-07 21:57
Ah, so it must be done with unit flags.

If there is no way of updating it server side, that must be because the client can handle it itself, just like it can handle changing the result from whatever to an 'absorped' if the spell hits a target that died while the spell was in mid-air. otherwise I'd like to know how we do that server-side if that is not the client taking care of that.

**Comment by mityada** [comment] 2016-09-07 22:19
I think @cyberium's problem demonstrates a more global issue: if, due to whatever reason, NPC takes damage from a friendly target, it attacks back. This should not happen at all.

**Comment by Laizerox** [comment] 2016-09-08 06:57
@Phatcat There are no special unitFlags or anything. Result is calculated on spell cast, sent to client.

As @Chaosvex shown in videos spells mid-air are not reflected due to fact that when spell was finished client already knows the outcome.

**Comment by Phatcat** [comment] 2016-09-08 12:30
i am no longer talking about reflect.. also we do not have unit flags nailed down, at al, and i would still like for you to answer that question from before

**Comment by Laizerox** [comment] 2016-09-08 13:14
We've got like 7 UNK UnitFlags in TBC which of majority do nothing for player and could be creature related. For example UNIT_FLAG_UNK15 seems to fix jumpy movement while swimming for creature.

UnitFlags do not affect animations pretty much. Especially in spells or in @cyberium case there seems to be wrong order of packets or some sort of.

**Comment by Phatcat** [comment] 2016-09-08 13:21
again, I wasn't even talking about animatios ...

**Comment by dagochen** [comment] 2016-09-08 13:46
I think Phatcat wants to know what shall happen with a frostbolt midflight if a paladin casts his bubble, right?

**Comment by mityada** [comment] 2016-09-08 14:17
Unit flags? Oh, come on... I'm afraid you are going the wrong way. If you just have to prevent spell from dealing damage, it's perfectly possible and there is absolutely nothing to do with the client.

Actually, all necessary code is already in the core. See https://github.com/cmangos/mangos-classic/blob/master/src/game/Spell.cpp#L1099. There are checks for immunity, hostility, etc. The problem is, none of them works, because Spell::DoSpellHitOnUnit immediately returns due to effectMask == 0. As a result, delayed spells can damage immune, non-attackable and friendly targets, it's even possible to kill other player after duel.

After quickly looking through the code, it seems to me that the check for effectMask is redundant and only makes things worse. Without it, all mentioned checks are working as intended. However, we still have to make sure that removing is is safe.

**Comment by Phatcat** [comment] 2016-09-08 14:29
You:
> Now, as you can see, miss information is sent to the client in SMSG_SPELL_GO, that is, when spell is starting to fly. **And there seems to be no way to tell the client afterwards that spell should behave differently**

Laizer:
> Client expects result on spell cast. **There is no way to update hit result of already started spell in client.**
(...)
Result is calculated on spell cast, sent to client.

Seroiusly, YOU guys 'come on'.

**Comment by mityada** [comment] 2016-09-08 15:07
@Phatcat, I was about visual effect for the missile only. There is really no way to update it. In case of reflect, it's really confusing to see spell hitting yourself but damaging attacker. But in case of friendly target, I guess we'll have to accept that visual effect won't match the actual result.

**Comment by dagochen** [comment] 2016-09-08 15:29
I will call this kind of missunderstandings from now and forever a typical "Phatcat" ;)

We really should not mix up things in one issue which has nothing to do with unitflags, spell immunity and so on....

**Comment by mityada** [comment] 2016-09-08 17:18
@Phatcat, lets continue in cmangos/mangos-classic#194. I left a note there about what could be changed and what couldn't.
