### ISSUE TITLE
[CLASSIC] Guardian Pets Are Not Using EventAI

### ISSUE THREAD

**Issue by cala** [cmangos/issues#1544] opened 2018-01-19 22:29 UTC
**Current behavior**: 

When a player or a NPC summons a guardian pet, the pet does not use the events scripted in `creature_ai_scripts`. This is probably a regression as I'm pretty sure that @Phatcat pet rework introduced the expected behaviour. Currently all guardians seems to use a generic "follow and melee" AI whenever they have scripts set in `creature_ai_scripts` or not.

**Expected behavior**: 

When a player or a NPC summons a guardian pet, the pet should use the events scripted in `creature_ai_scripts` if they exist because some guardians are known to have specific spells. Otherwise, guardians should use a generic AI.

**Steps to reproduce**:

1. `.npc add 12459` and engage it in combat
2. wait for it to summon NPC 14081, the guardian does nothing until despawn (it should summon other mobs through spells)
3. kill NPC 12459 and `.npc add 14081` and wait for it to summon demons this time (it is no longer a guardian and now uses its AI

**Client version**: 

1.12.1

**Commit hash**: 

https://github.com/cmangos/mangos-classic/commit/3f7e6c13644686e9d56ccb58401c1f92953229d9

**Database version**: 

Classic DB v1.8.5

**Operating system**: 

Mac OS X 10.6

[//]: # (If this is a crash report, include the crashlog from a debug build with https://gist.github.com/)

**Comment by AnonXS** [comment] 2018-01-20 18:15
They partly execute/use them, but they are very limited.
Example described here: https://github.com/cmangos/tbc-db/pull/417

**Comment by Phatcat** [comment] 2019-01-29 17:30
This should actually be working now, at least as a player summoning the timbermaw ancester, it did use it's lightning thing.

@cala , are you still having trouble with these?

I tried going by your steps to reproduce and got this result;

![image](https://user-images.githubusercontent.com/1907820/51927196-53b66c00-23f3-11e9-90e8-fbcbae78969c.png)

The only thing I could point to being wrong is that the portal is not stationary and it seems to want to have a target which it shouldn't (but that should be solved through acid, no?), it should probably behave much like the portals that got fixed in ZG (I don't know if these portals should be selectable and killable, though)

**Comment by killerwife** [comment] 2021-12-19 17:32
Seems to be working as intended now.

**Closed by killerwife** 2021-12-19 17:32 UTC
Labels: System: Player Controlled (Pet / Vehicles), Version: Classic (1.12), Version: TBC (2.4.3), Version: WotLK (3.3.5), System: Dbscripts / ScriptDev / ACID (AI), Info: Needs Testing, Info: Replicated: Needs Development
