### ISSUE TITLE
🐛 [Bug Report] C'thun fight issues

### ISSUE THREAD

**Issue by TeraFlux** [cmangos/issues#2238] opened 2020-08-02 18:53 UTC
## 🐛 Bugreport

-Black Aura Around C'thun moves around the room instead of fixed position
-C'thun eye will move around the room instead of standing still
-Phase 2 starts immediately (body pops out before eye is dead)
-Infinite amount of giant claw tentacles are spawned (that pull you into stomach)
-Agro Radius on C'thun is far too small

![image](https://user-images.githubusercontent.com/43866684/89129862-acb60300-d4b5-11ea-807e-4a5d9bd8be74.png)

### Expected behavior

The fight just needs some dev attention, basic fixes to things like immediate phase 2, immobile things moving around the room and infinite adds spawning would actually make the encounter playable.

### Version & Environment
Client Version:
"1.12.1" (CLASSIC)

CMaNGOS Repo & Commit Hash: CLASSIC

Database Repo & Commit Hash: CLASSIC

Operating System: 
Windows

### Steps to reproduce
1. Start C'thun encounter
2. Observer the chaos

**Comment by cala** [comment] 2020-08-26 08:07
Thank you for this issue report.

I tested the encounter and it was exceedingly fun to look at ! :laughing: 

C'Thun is without any doubt the most complex encounter in Classic (script wise) and the core changes in the past year probably took their toll on the actual implementation of the fight.

I shall look at this and see if I can quickly fix the biggest issues or if these will need a full rework of the encounter (that will happen at some time anyway).

**Comment by cala** [comment] 2020-09-03 11:30
Most of the errors described here are fixed in https://github.com/cmangos/mangos-classic/commit/2211f76f269ebff6c24a43340793c015fe143c89 and https://github.com/cmangos/classic-db/commit/3aafacc625c30ea0a532fda188dcb7382b230e8c
I was not able to reproduce the issue with the Eye of C'Thun moving around.

A full rework of C'Thun encounter is in progress.

**Comment by cala** [comment] 2021-01-19 10:01
All of these are fixed by the various C'Thun updates I made lately. The encounter is not yet fully redone, but the remaining issues with it are not listed here and are currently being handled by me, so closing this issue.

**Closed by cala** 2021-01-19 10:01 UTC
Labels: Info: Replicated, System: Scripts, Type: Regression, Version: Classic, Version: TBC, Version: WotLK
