### ISSUE TITLE
🐛 [Bug Report] Ghost Health Dropped To 0 and character got bugged completely when added Talent to Combat Expertise

### ISSUE THREAD

**Issue by Szymplo** [cmangos/issues#2622] opened 2022-01-22 16:03 UTC
### Bug Details

Adding talent-point to "Combat Expertise" while player is in ghost-state causes dying as ghost with 0 health.

The character was lying on ground as a ghost and there was no way to resurrect.
Restarting client didn't fix the problem

The character was completely bugged  the only way to fix it was update table characters by setting health to 1. 

### Steps to Reproduce

1. Die as a paladin with enough talent points to increase "Combat Expertise"
2. As a Ghost add +1 to Combat Expertise (I was acctually increasing it from 1 to 2)
3. Notice that your character will die as a ghost and became bugged/stuck as dead-ghost 

### Expected behavior

Character should NEVER die in ghost mode. The health shouldnt drop to "0"

### Suggested Workaround

I'm not programmer but the main problem is that ghost health dropped to 0 which should NEVER happen.

### Core SHA1 Commit Hash

c27ef1c19c75d7545e4259d371e34cb092913640

### Database SHA1 Commit Hash

4e322a61f0a1f4f103a8ca997698715d4b2012c5

### Operating System

Debian 10 (Buster) With MariaDB database

### Client Version(s)

- [ ] 1.1.12 (Classic)
- [X] 2.4.3 (The Burning Crusade)
- [ ] 3.3.5a (Wrath of the Lich King)

**Comment by berserkingyadis** [comment] 2022-01-28 20:56
Can reproduce. core 267d4cc6c420de2d09de8512f15045286956c990 db 47a035a5e80729453ff4aaecdad5c3e8e6cf8599 on tbc

Requirement for this seems to be having already 1 point allocated in Combat Expertise. Going from 1->2 triggers this but not 0 -> 1
(newest commits at this time)

**Comment by killerwife** [comment] 2022-02-13 12:38
Closed by https://github.com/cmangos/mangos-tbc/commit/6b296942bee2b91cdc5ee5c33ddd0592357d4d8e

**Closed by killerwife** 2022-02-13 12:38 UTC
Labels: Version: TBC (2.4.3), Info: Needs Development
