### ISSUE TITLE
🐛 [Bug Report] Mobs Chasing about 5 x farther, Guards don't engage mobs, Combat state dissapear 10 seconds after killing mob.

### ISSUE THREAD

**Issue by Szymplo** [cmangos/issues#3235] opened 2022-11-28 17:53 UTC
### Bug Details

Enemies chasing you like hell for about half of land (about 5x times farther then in earlier versions)
Guards don't engage enemies and you have to fight alone or you're able to bring boars to Skytower in Oggrimar
Combat state vanishes with 10 seconds delay after killing last mob in range

### Steps to Reproduce

1. Pull Boar near Ogrimmar
2. Run to skytower and realize that guards doesn't do anything with animal in city
3. See that boar can run after you even to top of skytower
4. Kill the boar and see and there is 10 second waiting till "in combat" vanish

### Expected behavior

1) Mobs don't chase you half the world
2) Guards are guards and should help you sometimes
3) Combat state should be off after just killing last mob not 10 seconds after killing it

### Core SHA1 Commit Hash

4b41a77e1614f6dfd628b71811ae5aeb441d0094

### Database SHA1 Commit Hash

5ac6ba2443782e85363790ca089e774f595c72e6

### Operating System

Debian 11

### Client Version

2.4.3 (The Burning Crusade)

**Comment by Pnumekin** [comment] 2022-12-01 14:08
Can confirm on classic too, mobs chasing you way too long. 
Tried to pull a mob and run trough all burning steppes, and he never leaved the combat.

**Comment by MilkmanMHOC** [comment] 2022-12-08 19:28
Updated yesterday, having same issue in classic.  Any thoughts on what update may have caused it so i can roll just that back?

**Comment by MilkmanMHOC** [comment] 2022-12-09 22:56
FYI rolling back the update on nov 12th, seemed to fix it for me.  https://github.com/cmangos/mangos-classic/commit/3e25bf3fa78b1aadd39fd6a76e8a689a2ed2597b

**Comment by ssj17vegeta** [comment] 2022-12-12 12:18
Can also reproduce on WoTLK. Just noticed the 10 seconds delay after killing mobs. This delay seems to be bigger in instances though ?

Typing the GM command `.combat stop` effectively stops the combat.

**Comment by Patrick-Barry** [comment] 2022-12-12 14:39
I did some experimentation in Vanilla and found that the combat state bug can be consistently triggered by finishing off a mob with a spell that has a cast time. Using an enhancement shaman combat would drop either instantly with melee attacks or instant spells when killing the mob, but would have a 6 or 7 second delay to drop if I finish them off with lightning bolt.

**Comment by ssj17vegeta** [comment] 2022-12-23 16:42
Can confirm it's fixed on WoTLK (probably by https://github.com/cmangos/mangos-wotlk/commit/f50c34b36a9186756ae5f99ba480e5fc05545e3e ?)

**Closed as completed** 2022-12-23 18:30 UTC
Labels: Expansion: Classic (1.12), Expansion: TBC (2.4.3), Expansion: WotLK (3.3.5), System: PvE, Type: Regression, Info: Needs Replication
