### ISSUE TITLE
Priest - Mind Vision (Rank 1) + (Rank 2)

### ISSUE THREAD

**Issue by Tobschinski** [cmangos/issues#386] opened 2014-02-23 04:20 UTC
Mind Vision 2 [ID=10909] should not have the requirement to be in line of sight with your target. 
The spell's range increases from 100 yards (Rank 1) [ID=2096] to 50,000 yards (Rank 2), so being in line of sight would however not be possible.

I remember that I have used this spell to get vision on Golemagg - the Incinerator, standing in front of the first two Molten Giants in Molten Core.

---

Taken from http://www.wowhead.com/spell=2096/mind-vision#comments 

"Rank 1 of Mind Vision is a handy little spell for seeing things that are far away. You can jump fromt target to target, however, each target must be in your line of site, and within 100 yards of your location.

If there was ever a major upgrade to a spell from a new rank, Mind Vision Rank 2 was it. Firstly, this does not require line of site. If you can target it, you can mind vision it (for the most part) as long as you are in the same instance. (Kalimdor and the Eastern Kingdoms are really big instances) Also, the range has been increased to 50,000 yards. You can hop from target to target, without the limitation of line of site, only range. [...]"

**Comment by cyberium** [comment] 2016-11-28 18:55
Interesting work for @killerwife or @Warlockbugs

**Comment by killerwife** [comment] 2016-11-28 19:22
Recently I made an interesting assumption that turned out to be true. Spells with range 50k ignore LOS :) I did not yet export it because @xfurry thought it to be not true, but since then I have gathered more evidence and subsequently forgotten about it :D

**Comment by cyberium** [comment] 2017-09-08 20:07
Mind vision on classic doesn't have 50k range.
This can be fixed by applying los attribute to this spell. But is it correct?

For the spell changing state in status bar i did not found any evidence. Someone have an hint?

**Comment by killerwife** [comment] 2017-09-08 20:15
Rank 2

SpellRange (Id 13) "Anywhere"
MinRange = 0
MaxRange = 50000

**Comment by BenDol** [comment] 2019-05-31 15:31
was this resolved?

**Comment by al3xc1985** [comment] 2020-03-07 04:40
@killerwife can we close this? On LH It was working. Did exported or tend to export a fix for tgis fromm vegeance?

**Comment by killerwife** [comment] 2022-02-22 13:14
I can confirm ignores LOS and jumping also works.

**Closed by killerwife** 2022-02-22 13:14 UTC
Labels: System: Spells, Version: Classic (1.12), Version: TBC (2.4.3), Version: WotLK (3.3.5), Info: Needs Replication, Class: Priest
