### ISSUE TITLE
🐛 [Bug Report] There seems to be an invisible hole in the ground

### ISSUE THREAD

**Issue by aleigood** [cmangos/issues#2424] opened 2021-03-20 14:52 UTC
## 🐛 Bugreport

![bug0](https://user-images.githubusercontent.com/3367999/111874027-3a574c00-89ce-11eb-94f1-45218d77438b.gif)
![bug1](https://user-images.githubusercontent.com/3367999/111874032-4216f080-89ce-11eb-97f8-bcc211e5e94a.gif)

### Version & Environment

Client Version: 
"2.4.3" (TBC)
"3.3.5a" (WOTLK)

CMaNGOS Repo & Commit Hash: 
a4cab458f1e536aad59f041db3d87a02e7987c05

Database Repo & Commit Hash: 
00f593f7e2fdc9c87f21c94c59042de14bf2536d

Operating System: 
Linux

### Steps to reproduce
1. .go cr 46825

### Crashlog
none

**Comment by killerwife** [comment] 2021-03-20 14:56
Check the XYZ path of the npc. It is frequent that these paths were added by hand from videos and they do not respond well to new iterations of mmaps. It could be that mmaps are picking a point below the deck.

**Comment by Grz3s** [comment] 2021-03-20 15:49
cant reproduce this on `WOTLK`

**Comment by Grz3s** [comment] 2021-03-20 15:50
![xcfw](https://user-images.githubusercontent.com/2374069/111875874-ecbded80-8993-11eb-85b5-c7f1fe406f02.jpg)

**Comment by aleigood** [comment] 2021-03-20 15:56
set PathFinder.NormalizeZ = 1

**Comment by Grz3s** [comment] 2021-03-20 18:50
valid data used ...
However this wont fix issue... for `PathFinder.NormalizeZ = 1` ...  she walks perfectly fine with `=0`

**Comment by AnonXS** [comment] 2021-07-27 19:28
cant reproduce this on `TBC`, with new or old waypoints. though there are holes inbetween the wood so with very precise mmaps she might be able to fall through these holes.

**Closed** 2021-07-27 19:48 UTC
Labels: Info: Needs Replication
