### ISSUE TITLE
🐛 [Bug Report] CONFIRMED: Precompiled binaries are suffering a Visual Studio issue

### ISSUE THREAD

**Issue by wdstudios2** [cmangos/issues#3449] opened 2023-06-04 21:56 UTC
### Bug Details

After spending the past 3 days suffering from Linux and Virtual Machine issues that are not worth discussing, I can confirm that cores built in Win10 with Visual Studio 2022 do not suffer the NPC ability spam bug that is experienced by cores compiled in Win7 with Visual Studio 2019.

This is not a code or database issue, so most of you can't, and shouldn't, do anything about it. HOWEVER, the person who is responsible for releasing the precompiled binaries should be made aware of this, and should take appropriate measures to ensure that the released binaries are compiled with a toolchain that does not suffer this bug. Additionally, the "Detailed installation guide for Microsoft Windows" should include a warning about Visual Studio 2019.

### Steps to Reproduce

1.
2.
3.
4.

### Core SHA1 Commit Hash

aaaa

### Database SHA1 Commit Hash

aaaa

### Operating System

Win7

### Client Version

2.4.3 (The Burning Crusade)

**Comment by al3xc1985** [comment] 2023-06-05 10:19
I told ya. I don't know if our devs can introduce or fix anything in this situation. But as much as my understanding goes, it is not our cores defect, but the pre/compilers fault

**Comment by Niam5** [comment] 2023-06-05 14:49
The precompiled binaries posted on the repositories are built daily automatically by a GitHub action script, there is noone who builds and then uploads them. The action script should be running on Server 2022, at least that's what it was on when I looked last.

As for Windows 7, that OS is end of life so I doubt any "fixes" specifically for it will be done. Windows 8 and 8.1 are also end of life. As Windows 10 is essentially "free" now there really isn't a reason to not use a currently supported OS.

**Comment by evil-at-wow** [comment] 2023-06-05 19:08
It's unlikely that the Windows version (be it 7 or 10, or 8/8.1) is the thing that makes the difference. Most likely it's going to be the compiler, and then I would expect the problem can be reproduced by using Visual Studio 2019 on Windows 10. In which case we might want to have a closer look because there's still going to be a lot of people on Visual studio 2019 I guess, especially given the 16.11 series is still going to be supported by Microsoft for several years if I'm not mistaken...

**Comment by killerwife** [comment] 2023-06-05 19:46
I am likely using some c++17 feature that is having side effects on msvc in vs2019. Only VS 2022 has basically all features from it done fully. The spell lists use IsSpellReady which uses Chrono, and that should not cause any issues. I myself am on vs2022. Can test at some point in vs2019 to see if i can find the issue. No ETA tho, going on vac this week.

**Comment by insunaa** [comment] 2024-06-16 16:57
iirc this has been fixed by now, closing.

**Closed as completed by insunaa** 2024-06-16 16:57 UTC
Labels: Expansion: TBC (2.4.3), Info: Needs Replication
