### ISSUE TITLE
🐛 [Bug Report] Can not summon mount outdoor 

### ISSUE THREAD

**Issue by aleigood** [cmangos/issues#2560] opened 2021-09-16 02:42 UTC
1 .go xyz -11535.648438 -220.642822 29.161745 0
2 summon mount

**Comment by cala** [comment] 2021-11-28 22:04
Confirmed on Classic. May be related to the way maps are extracted there because the "cannot mount zone" is very small : only when standing on the fence around the graveyard.

@aleigood please, the next time do a proper report. Thanks.

**Comment by ratkosrb** [comment] 2021-11-28 22:30
![WoWScrnShot_112921_002848](https://user-images.githubusercontent.com/35845488/143788726-b6c98de6-0da6-4cc1-9e07-1da222befdf5.jpg)

It's not a bug. You can't mount there on the official Classic PTR either.

**Comment by cala** [comment] 2021-11-28 22:38
That means that we correctly extract the incorrect maps/object ! 😂

Closing this then.

**Closed** 2021-11-28 22:39 UTC
Labels: Version: Classic, Info: Replicated
