### ISSUE TITLE
Using the spell Death Gate by a death knight crashes the server🐛 [Bug Report] 

### ISSUE THREAD

**Issue by LeXXyrus** [cmangos/issues#3122] opened 2022-09-01 17:25 UTC
### Bug Details

Using the spell Death Gate by a death knight crashes the server.

### Steps to Reproduce

1.Use the spell Death Gate by a death knight
2.Server is crashing
3.
4.

### Core SHA1 Commit Hash

d1a9ccc96e299f063842183a1ba1b3dbeeed10f6

### Database SHA1 Commit Hash

667167d1ceb50e0864e308029cc48c1e72bf20d3

### Operating System

Ubuntu 18.04 x64

### Client Version

3.3.5a (Wrath of the Lich King)

**Comment by insunaa** [comment] 2022-09-01 20:59
Duplicate of https://github.com/cmangos/issues/issues/3113
Closing

**Closed as completed by insunaa** 2022-09-01 20:59 UTC
Labels: Info: Needs Replication
