### ISSUE TITLE
Secondary tooltips doesnt update correctly

### ISSUE THREAD

**Issue by kokutek** [cmangos/issues#3009] opened 2022-06-17 11:03 UTC
### Bug Details

Battle and Commanding shout behavior, when learning Commanding presence from Fury talents, it correctly updates the tooltip of the battle shout, but when you use battle shout and check the buff tooltip, its still the same (viz youtube video)
Youtube link: https://youtu.be/UGxZiSF4jb4

### Steps to Reproduce

1. Create a Warrior
2. Learn battle shout (spellID 2048)
3. Check Fury talents and click 1 or more points to Commanding Presence
4. Check the secondary buff tooltip of Battle shout

### Expected behavior

I guess it should update both tooltips, not just that one.

### Core SHA1 Commit Hash

876951b832022c7f2eaa4e27ba605bd716962e5f

### Database SHA1 Commit Hash

5f7671a2ed93c6284b99410b0f60671187d94b91

### Operating System

Linux Ubuntu 20.04.4 LTS

### Client Version

2.4.3 (The Burning Crusade)

**Comment by killerwife** [comment] 2022-06-17 11:19
Not a bug. Thats actually how it used to work. Closing this as unfortunately there is no recourse.

**Closed by killerwife** 2022-06-17 11:19 UTC
Labels: Info: Needs Replication
