### ISSUE TITLE
🐛 [Bug Report] Hunter pet follow action problem

### ISSUE THREAD

**Issue by aleigood** [cmangos/issues#2135] opened 2020-02-20 13:18 UTC
## 🐛 Bugreport

In combat mode, the hunter pet clicks "follow", and the pet will attack the monster again when it comes back.
![image](https://user-images.githubusercontent.com/3367999/74937536-394c9780-5427-11ea-8f66-fadcf86f3f21.png)

Video: https://streamable.com/c0v76

### Expected behavior
Pets should stop attacking.

Client version:
2.4.3

Commit hash:
Newest

Database version:
Newest

Operating system:
centos

**Comment by al3xc1985** [comment] 2020-02-21 04:46
I confirm the bug on stormspire

**Comment by killerwife** [comment] 2020-02-21 08:51
@Warlockbugs I know the report is from wrong place but I am sure the bug exists in cmangos as well.

**Comment by Warlockbugs** [comment] 2020-02-29 14:32
Cannot reproduce while in passive mode. Pet does not attempt to engage attackers with or without follow.

The behavior demonstrated on video is correct while in defensive and aggresive modes. Pet should be switched to passive mode to prevent retaliation.

**Comment by jimmybrancaccio** [comment] 2020-11-15 23:43
Closing this out. If there's still issues with this please create a new issue with _all_ information requested by the bug reporting template.

**Closed by jimmybrancaccio** 2020-11-15 23:43 UTC
Labels: Info: Can't Replicate, Info: Incomplete Information, Info: Needs Replication
