### ISSUE TITLE
Player Position asyn on Different Clients When Killed by Mobs While Player is Moving

### ISSUE THREAD

**Issue by darklordsqk** [cmangos/issues#1859] opened 2019-01-31 14:44 UTC
**Current**: 
Player who got killed performed well, but other players will see the player(not corpse spawn yet) go to a direction continuously. 

**Expected**: 
Player who got killed will got SetRoot(). 
But I don't think directly SetRoot() in KillerPlayer() works. It will prevent dead player's falling. 

Because of the Async, the ResSpell of other players won't work until the player release soul(the corpse will spawn then). 

1. open 2 clients and login 2 different characters. 
2. let one of them killed by mobs while on running and jumping. 
3. switch to another client and watch. 

**Client version classic 1.12.1**:

**Comment by jimmybrancaccio** [comment] 2019-02-05 20:40
@darklordsqk Please provide the commit hash for your core and database.

**Comment by darklordsqk** [comment] 2019-02-06 22:34
> @darklordsqk Please provide the commit hash for your core and database.

@jimmybrancaccio
core version was a2ebef85b92f9acb3194d4dcd59c7d55f7634dfd
db version was dea8a314ad60968ab02d6b32fbf6d584c933cb62

**Comment by bdebaere** [comment] 2019-03-10 15:58
Could not reproduce.

CMaNGOS Repo & Commit Hash:  [CLASSIC](https://github.com/cmangos/mangos-classic/commit/7fa4124748e2f378e209c82bd7d0dea448482f02)
Database Repo & Commit Hash: [CLASSIC](https://github.com/cmangos/classic-db/commit/c02a5131930c04e7b0a0fa2fca6ad726c025cac9)

**Comment by jimmybrancaccio** [comment] 2019-06-08 23:53
Closing this issue out. If anyone is still having a problem, please open a new issue with full details.

**Closed by jimmybrancaccio** 2019-06-08 23:53 UTC
Labels: Info: Can't Replicate, System: Miscellaneous, Version: Classic
