### ISSUE TITLE
Flightmaster node prices not reduced by reputation discount

### ISSUE THREAD

**Issue by robinsch** [cmangos/issues#1500] opened 2017-10-25 11:31 UTC
Just passing a quick ref: https://github.com/TrinityCore/TrinityCore/issues/20713

Same issue on cmangos.

**Comment by killerwife** [comment] 2017-10-25 13:42
Thanks, I will look into it. Subsequent ones aren't missing it?

**Comment by robinsch** [comment] 2017-10-25 14:34
In TC they are missing too.

**Comment by killerwife** [comment] 2017-10-25 14:38
if (npc)
    {
        float discount = GetReputationPriceDiscount(npc);
        totalcost = (uint32)ceil(totalcost * discount);
        firstcost = (uint32)ceil(firstcost * discount);
    }

This should fix the issue I reckon.

**Comment by robinsch** [comment] 2017-10-25 14:41
Yeah it does and for subsequents I would suggest to store ObjectGuid from creature and (atleast for TC) calculate node price at ::LoadPath and get creature ptr with guid. (Since it is just called once and I wanted to avoid pass it to million functions)

**Comment by killerwife** [comment] 2017-10-25 15:58
Is cost calculated by current node NPC or for the npc at the node? For me it would make sense that we apply to each same discount (based on first npc) but I am not sure what blizz did there.

**Comment by robinsch** [comment] 2017-10-25 16:09
No idea really, I just did it for the first npc, would be good to find out.

**Comment by killerwife** [comment] 2017-10-25 17:41
@robinsch I encountered one thing though. When you alt+f4 on fly path, ur supposed to fly when u login again. And you should still pay the same price as checked on start. The problem is that we would have to save it in the DB, OR associate each node with a particular NPC and calculate based on that. @Shauren This is something interesting to think about for you as well.

**Comment by robinsch** [comment] 2017-10-25 17:45
Yeah I basicly did that, no idea if thats the best way.

**Comment by Warlockbugs** [comment] 2017-10-25 17:47
In multi-node flight you can see (or, rather, hear) money removal at each flight path change on interconnected waypoints, so the game simulates talking to flight master and taking individual one-way flight to next node.

**Comment by killerwife** [comment] 2017-10-25 17:48
Yes, so likely need to associate each node with an NPC IF such an example exists (not all taxi points are fly paths)

**Comment by robinsch** [comment] 2017-10-25 17:51
Path cost for each node is calculated from starting NPC faction discount (on retail, pretty sure it was the same back in the days)

**Comment by evil-at-wow** [comment] 2017-10-25 19:30
> I would suggest to store ObjectGuid from creature in m_taxi and (atleast for TC) calculate node price at ::LoadPath and get creature ptr with guid. (Since it is just called once and I wanted to avoid pass it to million functions)

I don't know the TC internals, but this might get tricky because some flight paths are across maps (for example Isle of Quel'Danas/Zul'Aman <=> Light's Hope Chapel) and getting the creature from a GUID might not work as intended on a different map.

If the first NPC is what counts for the entire path, keeping the discount around (persistently) as you suggest should work fine without possible headaches.

**Comment by robinsch** [comment] 2017-10-25 19:41
Yeah, but as you said it's calculated for the first npc, tested Sentile Hill to somewhere in EPL and the discount displayed in client is based on Sentile Hill (Stormwind) faction.

**Comment by robinsch** [comment] 2017-10-30 10:42
ref: https://github.com/TrinityCore/TrinityCore/commit/e947fcedee5fcf3983cd4a745eebcb0e05f9d771

**Comment by Warlockbugs** [comment] 2018-05-21 22:40
Fixed in global taxi rewrite.

**Closed by Warlockbugs** 2018-05-21 22:40 UTC
