### ISSUE TITLE
NPC Doesn't Cast Heal Spells on Friendly Missing HP

### ISSUE THREAD

**Issue by datchannin** [cmangos/issues#1894] opened 2019-02-26 18:03 UTC
## 🐛 Bugreport
Npc that should help to friends by casting heal spells, but they don't do it. This is can be ACID issue, but several months ago all was good. And the script has not been changed since that time.

I've tested several npc:
npc = 940, Kurzen Medicine Man.
Kurzen Medicine Man - Cast Heal on Friendly Missing HP
Kurzen Medicine Man - Cast Renew on Friendly Missing HP

npc = 873, Saltscale Oracle.
Saltscale Oracle - Cast Healing Wave on Friendly Missing HP

npc = 780, Skullsplitter Mystic.
Skullsplitter Mystic - Cast Healing Wave on Friendly Missing HP

npc = 2287, Crushridge Warmonger.
Crushridge Warmonger - Cast Frenzy and Text Emote on Friendly Death

May be other npc don't cast too, there are more than 300 strings at result of:
SELECT * FROM tbcmangos.creature_ai_scripts where event_type in (14);

### Expected behavior
npc should cast spells on friends missing HP.

### Version & Environment
Client Version: ["2.4.3" (TBC)]

CMaNGOS Repo & Commit Hash: [TBC](57b3a61bb117365b25c5e8d3f0c1b5c650ff551d)
57b3a61bb117365b25c5e8d3f0c1b5c650ff551d

Database Repo & Commit Hash: [TBC](f9965649e7b5a0b94a3c8f78f1ce15dc9521aa9a)
f9965649e7b5a0b94a3c8f78f1ce15dc9521aa9a

Operating System: [Win 64]

### Steps to reproduce
1. Add npc id (for example 940) twice
2. Start combat
3. Damage one of them for 600 hp
4. ...
5. Profit

### Crashlog
- [X] None

**Comment by Phatcat** [comment] 2019-03-01 10:16
I can confirm this. Tested with Timbermaw Defender. Doesn't heal the player at all.

**Comment by Almightie** [comment] 2019-03-08 15:49
Created  PR #https://github.com/cmangos/mangos-tbc/pull/272 for this issue.

**Comment by Pastew** [comment] 2019-03-10 18:24
I performed some tests and I confirm that @Almightie PR fixes:
npc = 940, Kurzen Medicine Man.
npc = 873, Saltscale Oracle.
npc = 780, Skullsplitter Mystic.
npc = 2287, Crushridge Warmonger, 

but it doesn't fix:
npc = 2287, Crushridge Warmonger.
Crushridge Warmonger - Cast Frenzy and Text Emote on Friendly Death

**Comment by cala** [comment] 2019-03-11 09:39
Closed by https://github.com/cmangos/mangos-tbc/commit/db369c8b3ed6519d4a349de5121c5d0782411bbe

> npc = 2287, Crushridge Warmonger.
Crushridge Warmonger - Cast Frenzy and Text Emote on Friendly Death

I looked at the actual script and it looks like an abuse of the mechanics. So, we can expect it to fail. The script should be rewritten, I think.

**Closed by cala** 2019-03-11 09:39 UTC
Labels: System: NPC, System: Scripts, System: Spells, Version: TBC

**Comment by bdebaere** [comment] 2019-03-11 10:48
@Pastew or @jimmybrancaccio Can you create a separate issue for Crushridge Warmonger please?

**Comment by jimmybrancaccio** [comment] 2019-03-11 15:39
Couldn't you @bdebaere? 🤔

**Comment by Pastew** [comment] 2019-03-11 17:33
Raised [#1902](https://github.com/cmangos/issues/issues/1902)

**Comment by jimmybrancaccio** [comment] 2019-03-11 17:39
Awesome, thanks @Pastew! 👍

**Comment by bdebaere** [comment] 2019-03-11 18:45
@jimmybrancaccio I had to leave for work and didn't want this to be forgotten.
