### ISSUE TITLE
🐛 [Bug Report] [Raid Serpentshrine Cavern] Trashs summoned by Vashj won't despawn after boss evade

### ISSUE THREAD

**Issue by betayi** [cmangos/issues#3589] opened 2023-10-29 02:15 UTC
### Bug Details

 encounter of Vashj at phase 2 ,there are kinds of trashs were summoned , if players failed at this phase, trashes won't despawn with boss evade, so players can not restart fight normally.  

### Steps to Reproduce

1.go Serpentshrine Cavern and fight with Vashj into phase 2 
2.keep alive untill all 3 kind of trash summoned appear
3.die to finish this encounter
4.watch Vashj and these trashes, Vashj Evaded but trashes not

### Expected behavior

creature summoned in encounter should despawn while Vashj evade

### Core SHA1 Commit Hash

b6baf7cee15a80526556b96962881b349298fe83

### Database SHA1 Commit Hash

latest

### Operating System

Ubuntu20.04

### Client Version

2.4.3 (The Burning Crusade)

**Comment by Diabloxx** [comment] 2024-04-29 13:38
I can confirm this is still an issue, to reproduce this. Go to vash start the fight, wait for a bunch of ads to spawn, wipe, walk upto vash and the ads will be there still.

**Comment by cpevors** [comment] 2024-04-29 14:19
Also can confirm.

**Comment by miraco** [comment] 2024-05-13 13:43
Tested on current cmangos TBC:
https://youtu.be/fOs8rfgCuT8 

Despawn looks fine for me. Can you add a video or entrys that didnt despawn?


Edit: I see the Problem, Lady Vashj also gets despawn on Evade and respawns 30 seconds later, but it looks like she dont reset CombatAi properly and just continue being in Phase 2

**Comment by rayonpt** [comment] 2024-05-14 14:15
confirm this issue, pretty annoying

**Comment by insunaa** [comment] 2024-06-16 16:25
fixed in https://github.com/cmangos/mangos-tbc/commit/537d7280736dd19c586327d4aed202da90581b6a

**Closed as completed by insunaa** 2024-06-16 16:25 UTC
Labels: Expansion: TBC (2.4.3), Expansion: WotLK (3.3.5), System: PvE, System: Scripting, Type: Regression, Info: Needs Replication
