### ISSUE TITLE
mangosd Is Crashing With Boost Error

### ISSUE THREAD

**Issue by jimmybrancaccio** [cmangos/issues#1774] opened 2018-11-23 16:17 UTC
**Current behavior**: 

The mangosd binary is crashing with a boost error:

```
terminate called after throwing an instance of 'boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::system::system_error> >'
  what():  remote_endpoint: Transport endpoint is not connected
```

**Expected behavior**: 

mangosd to not crash.

**Steps to reproduce**:

1. Build the latest versions of mangosd.
2. Utilize the information in [this gist](https://gist.githubusercontent.com/Lillecarl/0bba766b9e077cea0c5c52c9e1f91352/raw/a59b264d4f563c2c23d8c7ca4e937c8de82abbaf/debug) to run mangosd with GDB.
3. Wait until it crashes.

Of note, I had no one connected/connecting to realmd or mangosd during this time. It appears to be receiving a SIGABRT. This appears to be a new issues within the last 1-2 weeks. Previous to then no issues. I thought it might be related to #1359.

**Client version**: 

3.3.5a

**Commit hash**: 

0592a0505513cdc327d2945283aa3f428bdf8754

**Database version**: 

a67bd4b13f28bcc041c8d23da196d07ad3be5638

**Operating system**: 

Ubuntu 14.04

Here's my crash dump - [mangosd-11232018-crashdump.txt](https://github.com/cmangos/issues/files/2611280/mangosd-11232018-crashdump.txt)

**Comment by jimmybrancaccio** [comment] 2018-11-23 22:45
As per discussion with @cyberium in Discord, I am running mangosd again with level 3 logging as it appears the last stack call was not caught in the crash dump. Will report back with new crash log once it happens again.

**Comment by cyberium** [comment] 2018-11-29 21:39
Should be fixed

**Comment by Muehe** [comment] 2019-04-17 12:59
There have been reports over the past month of this error still happening. It may be related to an async socket closing before all messages have been handled.

**Paste from Discord (2019-04-05):**


[01:03] Ansem: terminate called after throwing an instance of 
```
'boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::system::system_error> >'
  what():  remote_endpoint: Transport endpoint is not connected
Aborted (core dumped)
```

My console dropped this.
[01:17] Muehe: Do you have any way to reproduce? Which version are you using(classic/tbc/wotlk)?
[01:31] Ansem: Tbc
[01:32] Ansem: And no idea. It just ran. No players active during the last day
[01:32] Ansem: What can i get out of the core dump for details or where can I upload the dump to
[01:34] Muehe: Apparently this happens when a Boost async connection is closed without reading the remaining messages that were sent before the close instruction reached it's target. From what I gathered on a random Github issue[0] we have to add a read-loop in Socket.cpp[1]. Note the comments below the linked one, especially the one by JoelKatz saying TCP connections need to be closed the same way.

[0]: https://github.com/boostorg/beast/issues/297#issuecomment-292286676
[1]: https://github.com/cmangos/mangos-classic/blob/a59f08f855085bd2ac024b404c593f64197df2ff/src/shared/Network/Socket.cpp#L70
[01:35] Ansem: So nothing I can do about it?
[01:35] Ansem: Config or vps wise
[01:35] astuffedtiger: Same thing happens to me on WotLK
[01:36] Muehe: Probably not, except you want to add and refactor this snippet:

```
    // Continue reading because we initiate a close
    try {
        ws.read(op, sb);
    } catch(const boost::system::system_error& e) {
        std::cout << e.what() << std::endl;
    }
```

[01:36] Muehe: From what I understood you just have to read from the TCP connection until there is an error.
[01:37] Muehe: This snippet is for some Websocket stuff, so it has to be refactored to match with the socket code.
[01:37] Ansem: Ill justvgit pull and compile next week xD
[01:37] astuffedtiger: I don't think that will fix it?
[01:38] astuffedtiger: It sounds like an actual code change needs to be made.
[01:39] Ansem: So ill see that happen eventually as i cant do c++
[01:39] Ansem: XD leeching ftw
[01:39] Muehe: Yeah like I said, it has to be rewritten a bit, let me see if I can coble something together that compiles.
[01:40] Ansem: At least I report bugs #doingmypart
[01:47] Muehe: @astuffedtiger By the way, any idea how to reproduce?
[01:47] astuffedtiger: @Muehe No, unfortunately. I can't figure it out. It just randomly happens. And on servers with no players.
[01:59] Muehe: This patch compiles and the server starts, but no idea if it really fixes the issue:

```diff
diff --git a/src/shared/Network/Socket.cpp b/src/shared/Network/Socket.cpp
index d35d532b6..46ddcb764 100644
--- a/src/shared/Network/Socket.cpp
+++ b/src/shared/Network/Socket.cpp
@@ -64,10 +64,14 @@ namespace MaNGOS
         if (IsClosed())
             return;
 
-        boost::system::error_code ec;
-        m_socket.shutdown(boost::asio::ip::tcp::socket::shutdown_both, ec);
         m_socket.close();
 
+        try {
+            StartAsyncRead();
+        } catch(const boost::system::error_code& e) {
+            sLog.outBasic("Socket::Close. %s. Connection closed.", e.message().c_str());
+        }
+
         if (m_closeHandler)
             m_closeHandler(this);
     }
```

**Comment by killerwife** [comment] 2020-12-18 08:55
@Muehe is this still an issue.

**Comment by Muehe** [comment] 2020-12-18 12:35
Haven't heard anything since that report on Discord, probably solved.

**Closed by Muehe** 2020-12-18 12:35 UTC
Labels: Info: Needs Development, Info: Needs Testing, Type: Core Crash, Version: WotLK
