### ISSUE TITLE
[CLASSIC] Hunter Shooting Range Issues

### ISSUE THREAD

**Issue by kuramajssken001** [cmangos/issues#1052] opened 2016-08-19 06:55 UTC
**Current behavior**: 
Hunter shoot >= 8 dy range, But now need >= 11 dy range.
**Expected behavior**: 

**Steps to reproduce**:
1. shooting distance need >= 11 dyrange
2. 
3. 

**Client version**: 
1.12
**Commit hash**: 
Last
**Database version**: 
Last
**Operating system**: 

Win7 x64

**Comment by Phatcat** [comment] 2016-08-19 09:08
http://wowwiki.wikia.com/wiki/Auto_Shot?oldid=262262

**Comment by Phatcat** [comment] 2016-09-07 21:40
Why didn't I ever close this when I linked to and showed it was indeed 8 yards in late vanilla.

**Comment by Phatcat** [comment] 2016-09-07 21:42
... gotta learn to read

also sorry for the spam, that was unintended...

**Comment by Phatcat** [comment] 2019-02-08 00:55
This is still an issue, distance on the min range of where you can no longer shoot a target is well above 8 meassured with .dist , looks more like it expects us to get 10 yards or more away from the target
![image](https://user-images.githubusercontent.com/1907820/52452700-73146e00-2b44-11e9-915e-fc4e3ecdb143.png)

**Comment by al3xc1985** [comment] 2020-03-19 19:31
@killerwife confirmed..still a but... the distance is >=5 and not 8 minimum

**Comment by killerwife** [comment] 2021-12-18 14:42
After rework of range function and reversing vanilla client it is actually 11 for basic creature and player. 
![image](https://user-images.githubusercontent.com/7995382/146644962-69fa7b3a-3a8f-4f3c-8301-115a0e7f0744.png)

Notice on image how bow is red at 10.62 distance up until 11 raw distance. All working as intended

**Closed by killerwife** 2021-12-18 14:42 UTC
Labels: System: Spell, Version: Classic (1.12), Info: Needs Replication / Information / Feedback, Class.Hunter
