### ISSUE TITLE
🐛 [Bug Report] Warlock (Bot) Dies instantly from Casting "Death Touch" at himself during combat

### ISSUE THREAD

**Issue by Mr-Deadbeat** [cmangos/issues#2144] opened 2020-03-08 15:39 UTC
`## 🐛 Bugreport Warlock (Bot) Dies instantly from casting "Death Touch" on himself during combat

Gates outside of Uldum in Tanaris while doing quest "See what happens"

Combat log says Warlock cast Death Touch on himself and then instantly dies
feels more like a bloody cruel joke after looking up "Death Touch" with Gm commands
is it some kind of anti bot measure ?

currently i'm not so sure it is a bug more like a anti bot measure

at this point in time the bots are totally unplayable way too much bugs and glitches

### Expected behavior
Warlock Not Die ?

### Version & Environment
OS Ubuntu 18.04.4 64bit Server

Client Version: 
 "2.4.3" (TBC)

CMaNGOS Repo & Commit Hash: 

[TBC](https://github.com/cmangos/mangos-tbc/tree/cb5409afabd1ed521e8b1419a8fee643900ee3be)

Database Repo & Commit Hash: 

[TBC](https://github.com/cmangos/tbc-db/tree/3e4b2c0d3469649013b3f070b53cc8c4fe242d94)

Operating System: 

Linux Flavor

### Steps to reproduce

Initiate combat with Elite Stone Golems outside Uldum and Profit!!!
it was a bit random so did not happen everytime keep at it and eventually it will happen

### Crashlog`

**Comment by cala** [comment] 2020-04-15 15:35
> Warlock (Bot) Dies instantly from casting "Death Touch" on himself during combat

Seems to be working as intended... :rofl: 

I'll look at this. :wink:

**Comment by cala** [comment] 2020-04-19 19:57
Hmm… Death Touch is not supposed to be a regular spell and surely not in the Warlock spell book (and I don't see it in PlayerBot Warlock AI code). How come is this spell cast by your bot? Do you use a GM command, some edited bot AI ?

**Comment by cala** [comment] 2020-04-20 19:42
@Mr-Deadbeat I cannot reproduce this. Did you use some GM command like .learn all spells or spells for a class?

**Comment by Mr-Deadbeat** [comment] 2020-04-23 14:39
no GM commands used i initiated combat with the Stone Giants outside Uldum and this happened
the moment the Warlock sent in his pet and started casting spells "Death touch" came out of nowhere and just insta killed the warlock Note the warlock was bot controlled have not revisited uldum after that happened so don't know if it might have been solved with updates can do a quick trip there today and check if it still happens

**Comment by cala** [comment] 2020-04-23 15:04
Ok. Just to be clear so I can investigate this more : 
- we are speaking of TBC core
- Uldum is the area south of Tanaris (south west of Un'Goro entrance) that cannot be visited (and was made a new zone/instance in cataclysm)
- what was the level of the warlock bot and which pet did he use?

**Comment by Mr-Deadbeat** [comment] 2020-04-23 19:48
yeah Tbc-Core and the area is the correct one i was fighting the stone giants outside the Uldum gates to reach the quest area for the "Disc" quest small thing on the left side of the gates think the Warlock had felhunter as pet at the time and the characters were 40 to maybe level 50 somewhere around there been a while so not sure about what level i was at that time can't have been over 50 though since warlock didn't have the felguard yet

**Comment by Mr-Deadbeat** [comment] 2020-04-23 20:15
have tried to replicate the issue but have had no success so i my guess is the issue has resolved itself over the time since it happened been lots of updates since then so no idea what else to do now except ask for this to be closed

**Comment by cala** [comment] 2020-04-23 20:19
What is strange is that Death Touch is a spell that is in the DBC (Classic and TBC) but not available in-game. Unless you cast it through `.cast 5` the only other way is to trigger it with spell 12256 (Add Moogly Radius PT) which is also unavailable in-game. So I wonder, which one of the two methods you had to face.

**Comment by Mr-Deadbeat** [comment] 2020-04-23 20:28
no idea just saw it happen since i heard the "ugh!!" and dead warlock fell to the ground thought at first the damn giants had some spell they cast so checked combat log and there it was "Death Touch"
i never use GM commands either unless the game is glitched so a certain event is impossible to complete otherwise like for example the vault event in BRD stone golems aggro stand in place and aggro the group so bots stop in their tracks and do nothing and boss nukes the whole group down in those cases i use GM commands to get past the event i guess you can close this issue down unless you want to investigate further maybe you get lucky and stumble on the root cause but it's been a while since when it first happened so any number of things might have inadvertently solved it
killed a score of those giants a few minutes ago and could not get it to happen again but could replicate it back when it happened the first time it was a bit random though did not happen on every encounter

**Comment by cala** [comment] 2020-04-23 20:45
Cannot reproduce either. I'll close the issue then. Let me know if it happens again.

**Closed by cala** 2020-04-23 20:45 UTC
Labels: Info: Needs Replication, System: PlayerBot, System: Spells, Version: TBC
