### ISSUE TITLE
🐛 [Bug Report] Crash with Playerbot attacking

### ISSUE THREAD

**Issue by D3thw0lf** [cmangos/issues#2261] opened 2020-09-14 14:48 UTC
## 🐛 Bugreport
If you compile with Playerbots enabled and do some escort quests or try to kill random mobs e.g. spawning Totems there is a chance (not happens everytime but often enough) to crash the core.

It is the most reproducable in Winterspring at the Winterfall Furbolgs. Just take a bot with you and attack them. If they spawn totems and you can manage to kill them without a crash you're a lucky you. :)

### Expected behavior
Do not crash.

### Version & Environment
Client: 2.4.3 TBC

[Core](https://github.com/cmangos/mangos-tbc/commit/96dda3c3b43140d690ec10e0dffa402fa22d0037)
[DB](https://github.com/cmangos/tbc-db/commit/c1348c75bc8a213580f1bfaf0daf21e1024f8779)

Operating System: 
Linux

### Steps to reproduce
1. Go to Winterspring
2. Find the Furbolgs
3. Kill some
4. Hope it's not crashing...
5. For me (at least) there's a 99,99% reproducable crash so no profit :C

### Crashlog
```
0x0000555555cff912 in PlayerbotAI::Attack (this=0x7fffa8cb6510, forcedTarget=<optimized out>) at /src/game/Entities/ObjectGuid.h:90
90	        operator uint64() const { return m_guid; }

CRASHLOG BEGIN

Program stopped at 0x555555cff912.
It stopped with signal SIGSEGV, Segmentation fault.

BACKTRACE

#0  0x0000555555cff912 in PlayerbotAI::Attack (this=0x7fffa8cb6510, forcedTarget=<optimized out>) at /src/game/Entities/ObjectGuid.h:90
#1  0x0000555555cffb82 in PlayerbotAI::DoNextCombatManeuver (this=this@entry=0x7fffa8cb6510) at /src/game/PlayerBot/Base/PlayerbotAI.cpp:3330
#2  0x0000555555d0afbb in PlayerbotAI::DoNextCombatManeuver (this=0x7fffa8cb6510) at /src/game/PlayerBot/Base/PlayerbotAI.cpp:3316
#3  PlayerbotAI::UpdateAI(unsigned int) () at /src/game/PlayerBot/Base/PlayerbotAI.cpp:5321
#4  0x0000555555b9d540 in Player::Update (diff=101, this=0x7fffa8de97a0) at /src/game/Entities/Player.cpp:1583
#5  Player::Update (this=0x7fffa8de97a0, diff=101) at /src/game/Entities/Player.cpp:1347
#6  0x0000555555c94740 in Map::Update(unsigned int const&) () at /src/game/Maps/Map.cpp:609
#7  0x0000555555ca41f2 in MapUpdateWorker::execute (this=0x7fffb8c0d1b0) at /src/game/Maps/MapWorkers.h:51
#8  0x0000555555cae2a9 in MapUpdater::WorkerThread (this=0x55555c00b870) at /src/game/Maps/MapUpdater.cpp:96
#9  0x00007ffff6c4a6df in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#10 0x00007ffff7bbd6db in start_thread (arg=0x7fffe4b94700) at pthread_create.c:463
#11 0x00007ffff6307a3f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```

I know there's not that much priority in Playerbots as they're not Blizzlike or a "needed" feature but I hope that maybe someone can help here to find a solution. That would be awsome. ❤️

**Comment by cala** [comment] 2020-09-19 22:06
Greetings and thanks for this report. There was indeed a rare crash when bots tried to "access" a target that was removed from world but I did not had it in a long time since safeguard were added. Unfortunately, I am not able to reproduce what you describe here. Could you provide a more detailed step by step to have this crash or at least provide a video of it?

**Comment by D3thw0lf** [comment] 2020-09-20 14:35
> Greetings and thanks for this report. There was indeed a rare crash when bots tried to "access" a target that was removed from world but I did not had it in a long time since safeguard were added. Unfortunately, I am not able to reproduce what you describe here. Could you provide a more detailed step by step to have this crash or at least provide a video of it?

Sure I'll upload a Video later this day.

For now try this:
- .go 6757.49 -2724.557 563.37
- Call your Bot with .bot add NAME
- Attack the Furbolg Shamans
- Wait for them to spawn totems
- Try to kill them without a crash
- Feel happy If you can complete to this step because I can't :C

**Comment by cala** [comment] 2020-11-28 20:13
After several tries tonight, I'm unable to reproduce this bug. @D3thw0lf could you confirm that this still happens to you (there were some changes in PlayerBot lately that could possibly fix this bug) ?

**Comment by jimmybrancaccio** [comment] 2020-12-07 00:52
@D3thw0lf Are you still experiencing this issue?

**Comment by D3thw0lf** [comment] 2020-12-07 01:19
I haven't had time to re-check that. I'll try the latest changes tomorrow or midweek. Sorry for my late response. :3

**Comment by cala** [comment] 2021-01-19 10:03
I'm currently having a global look at PlayerBot code and I'm still unable to reproduce this, can you confirm this still happens, please ?

**Comment by D3thw0lf** [comment] 2021-01-21 08:32
Can get closed. Seems to work for me now.

**Comment by cala** [comment] 2021-01-27 13:57
Thank you, closing this issue then ! :)

**Closed by cala** 2021-01-27 13:57 UTC
Labels: Info: Can't Replicate, Info: Needs Feedback, System: PlayerBot, Type: Core Crash
