### ISSUE TITLE
[CLASSIC] Natural Armor Rank 1 Says Required Level is 1, But is Actually Level 10

### ISSUE THREAD

**Issue by BareRose** [cmangos/issues#1318] opened 2017-03-02 20:48 UTC
Rank 1 of the Natural Armor pet skill say "Required: Pet Level 1", but while my pet was below level 10 all attempts to teach it to my pet resulted in a message saying the level was too low. It says it requires level 1, but on cMangos it currently requires level 10.

Clearly something is wrong. Seeing as other rank 1 skills seem to require level 1, I would say the requirement check is wrong and should be changed from level 10 to level 1. Further input on the correct level requirement would of course be appreciated!

**Comment by Phatcat** [comment] 2017-06-10 20:55
http://web.archive.org/web/20061109011028/http://tkasomething.com:80/petskills.php

>Natural Armor
Can be learned by all currently tameable species in the game.

>Natural Armor, Rank 1 Requires: Pet Level 1
Cost: 1 Training Points
Armor increased by 50.

**Comment by cala** [comment] 2017-06-14 12:27
👍

**Comment by Phatcat** [comment] 2017-06-17 00:09
![billede](https://user-images.githubusercontent.com/1907820/27248300-dcc4182c-5301-11e7-947a-1b7f353929df.png)

https://youtu.be/FaV6oAteJGI?t=2h20m26s

**Comment by BareRose** [comment] 2017-06-18 11:24
Looks like we've got plenty confirmation that it should indeed be usable on a level 1 pet.

The level requirement thingy should be somewhere in a spells table, right? Been a while since I've messed with cMangos code/db.

**Comment by BareRose** [comment] 2017-07-22 18:29
Anybody know where level requirement data is stored? If it's client-side then we'll need a hack of some sort. I'd expect this stuff to be server-side though, just haven't been able to find it in DB or core source. Not sure what the "correct" way to search for a given spell is.

Also, [vanillagaming's db](http://db.vanillagaming.org/?spell=24547) has a version of the spell with "level 10" attached to it, could be that cmangos has the same error somewhere, as vanillagaming and cmangos might have gotten some of their DBs from the same source.

**Comment by BareRose** [comment] 2017-07-24 19:31
@Phatcat @Warlockbugs @cala 

Any help on where spell level requirements are dealt with? SpellID should be 24547. Ctrl+F on the code doesn't find that number anywhere, same for database tables with "spell" in their name. Am confuse.

**Comment by Saben65** [comment] 2017-07-24 19:56
It is in `spell_template` but I do believe these values come from the Client's spell.dbc, no?

```SQL
SELECT `id`,`spelllevel`,`spellname` FROM `spell_template` WHERE `id`=24547; 
```
```
    id  spelllevel  spellname      
------  ----------  ---------------
 24547          10  Natural Armor  
```

**Comment by BareRose** [comment] 2017-07-25 00:18
Welp, looks like pma's search is just shit.

Even if it's in the client's dbc we have clear confirmation that it was learnable at level 1 in retail, so maybe Blizzard fucked up on the client and then corrected it server-side, in which case we might aswell do the same.

Adding a db patch to change the spelllevel value for the spell to 1 should fix the issue.

**Comment by Warlockbugs** [comment] 2017-07-25 02:55
Likely it is a training limitation for player, not pet itself, since training and taming are available since level 10.

**Comment by bdebaere** [comment] 2018-08-18 05:02
Just like how the learning of a new spell for a player looks at the required level of the learned spell in the SpellLevel column and not the spell cast by the trainer. So too should this be for pet spells.

The actual armor buffs which are taught to the pet (24545, 24549, 24550, 24551, 24552, 24553, 24554, 24555, 24629, 24630) contain the required levels: **1**, 12, 18, 24, 30, 36, 42, 48, 54.
The learn spells which are taught to the player (24547, 24556, 24557, 24558, 24559, 24560, 24561, 24562, 24631, 24632) contain the required levels: 10, 12, 18, 24, 30, 36, 42, 48, 54, 60.
And of course as usual the spells the trainer casts to learn the spell to the player (24633, 24634, 24548, 24563, 24565, 24566, 24567, 24568, 24569, 24570) contain the required levels: 0.

The client reads the values the correct way and that's why it is showing required pet level 1:
![image](https://user-images.githubusercontent.com/1436449/44295983-76751e00-a2b4-11e8-937e-670b3955b55d.png)

**Comment by Phatcat** [comment] 2019-06-15 11:36
There's been a PR up to fix this for months and it's even been referenced here yet you will indiscriminately slap on that 'needs replication' label.

When a Pr was raised in february this year, you can assume this was at least reproduced in february, so this issue was confirmed less than 4 months prior, yet it still 'needs replication'.

Just do it. Just close this issue. Just close the entire issue tracker, that's clearly your goal here. Doesn't matter if the issue still exists or not, as long as the tracker is nice and clean all is good, yea? It's ridiculous.

**Closed** 2019-12-06 13:04 UTC
Labels: Info: Replicated, System: Spells, Version: Classic
