### ISSUE TITLE
🐛 [Bug Report] The mage's cold ice sword can't hold the monster's hatred

### ISSUE THREAD

**Issue by left3721** [cmangos/issues#3164] opened 2022-10-09 00:13 UTC
### Bug Details

 If you stand at the farthest distance and use the Ice Sword, the monster will turn back. 

### Steps to Reproduce

Uploading bb6c452385c51387048c8cb40dc0d55c.mp4…
https://www.youtube.com/watch?v=7p5nFDRpRTk

### Core SHA1 Commit Hash

ef0b0eb97407bc0f857880c8509407cce0d18615

### Database SHA1 Commit Hash

ec06beaf071858822d55dca2a352b98cebd46ff5

### Operating System

ubuntu 20.4

### Client Version

2.4.3 (The Burning Crusade)

**Comment by insunaa** [comment] 2022-10-27 08:47
Duplicate of https://github.com/cmangos/issues/issues/3127

**Closed as completed by insunaa** 2022-10-27 08:47 UTC
Labels: Info: Needs Replication
