### ISSUE TITLE
🐛 [Bug Report]Unnecessary Error makes console unusable

### ISSUE THREAD

**Issue by ghost** [cmangos/issues#2255] opened 2020-09-13 08:16 UTC
## 🐛 Bugreport

There is this error message in the mangosd console which makes it practically unusable.

It is: MoveSpline::init_spline: zero length spline, wrong input data?

### Expected behavior

This error shouldnt be exisiting.

### Version & Environment

Client Version: 
3.3.5a

CMaNGOS Repo & Commit Hash: 
https://github.com/cmangos/mangos-wotlk/commit/95925d05964e5413cd74a0942515e3c27e5b4f0d

Database Repo & Commit Hash: 
https://github.com/cmangos/wotlk-db/commit/b6dfda5d984ce62dbe5a5b99a8a725cea42fc742

Operating System: 
Windows 10
### Steps to reproduce
1. Just start mangosd and wait a bit.
2.
3.
4. ...
5. Profit

### Crashlog

- None

**Comment by craftorix** [comment] 2020-09-17 13:39
Fix here: https://github.com/cmangos/mangos-tbc/pull/404

**Comment by jimmybrancaccio** [comment] 2020-11-16 00:33
This is a duplicate of #2171.

**Closed by jimmybrancaccio** 2020-11-16 00:33 UTC
Labels: Info: Needs Replication
