### ISSUE TITLE
New Hunters

### ISSUE THREAD

**Issue by D33rhunt3r** [cmangos/issues#1775] opened 2018-11-24 13:56 UTC
**Current behavior**: 
Seems to have the same problems as #1174,  and include:
After completing the quest string to get Summon pet.  you finish by seeing the pet trainer in my case "Ganaar" the pet trainer in the Exodar, to receive "Revive pet" and "Feed Pet".  But after talking to the Pet Training you do not get either spell.  

**Expected behavior**: 
When finishing the pet quest and speaking with the "Pet Trainer"  you should receive 2 spells,  Feed Pet and Revive Pet
**Steps to reproduce**:

1. level a new hunter to 10th
2. Start Pet Quest and Finish
3. See Pet Trainer at the final step.  check Beast Master Line of Spells for Revive Pet and Feed Pet

**Client version**: 
3.3.5 WOTLK
**Commit hash**: 
I've updated the server as of 11/23/18  not sure how to get the commit hash

b08fa044ac453c2569668d4b9d2384ea95df4fe1

**Database version**: 
WoTLKDB v1.1 'The Warsong' for CMaNGOS-WOTLK 13965

3c101da2de04ba2975c241f3990c2198cce42fb8

**Operating system**: 
Windows 10, and windows 7 pro.

[//]: # (If this is a crash report, include the crashlog from a debug build with https://gist.github.com/)

**Comment by adellaci** [comment] 2018-11-24 14:02
@D33rhunt3r 
Go to directory that you "git pull" CMaNGOS and type
'git rev-parse HEAD`
and do the same for the database

**Comment by D33rhunt3r** [comment] 2018-11-24 14:19
Server Hash:
b08fa044ac453c2569668d4b9d2384ea95df4fe1
DB Hash:
3c101da2de04ba2975c241f3990c2198cce42fb8

Thanks,  I'll keep this in mind for the next time.

**Comment by adellaci** [comment] 2018-11-25 19:53
Confirmed. Failed to learn spells Revive Pet (id# 982) and Feed Pet (id# 6991) after being trainer to tame pet

Had to issue command ".learn 982" & ".learn 6991" to get the two spells

**Comment by killerwife** [comment] 2018-11-25 19:58
Spell ID 1579 has to be learned upon quest completion. Please check if that is added in DB. Maybe check against other quests and tbc-db.

**Comment by adellaci** [comment] 2018-11-25 22:34
@killerwife 
Spell ID is in the database and listed as "Tame Beast". When we complete the pet quest we get tame beast. call pet, & dismiss pet, but we did not receive Revive Pet & Feed Pet

**Comment by killerwife** [comment] 2018-11-25 22:39
Different spell ID 5300. I believe a different quest awards that.

**Comment by adellaci** [comment] 2018-11-25 22:50
spell ID 5300 is Beast Training according to DB

**Comment by adellaci** [comment] 2018-12-03 19:52
@killerwife 
I researched it out for the Night Elf. 
The quest starts in Shadowglen at the Hunter Trainer, 'The Hunter's Path' quest=6071. Which send you the Dolanaar to see the Hunter Trainer there, who give you 'Taming the Beast' quest=6063. 
Upon completion you get quest 'Taming the Beast' quest=6101, 
Upon completion you get quest 'Taming the Beast' quest=6102. 
Upon completion you get 'Training the Beast' quest=6103
From here you have to go the Darnassus to the Hunter trainer to complete. The hunter trainer says;

 "A fledgling $C. I see. Yes. I can bestow you with the skills you need to train and guide your pet. Not only will you be able to teach your pet new abilities, you will now be able to feed your pet, as well as revive it, should it fall in battle.$B$BRemember, $N, always respect the balance and live in awe of nature around you. Now, go forth. We shall speak again, at a later date."

Upon completion you are given spells 'Revive Pet' id=982 & 'Feed Pet' id 6991

I will check the other races and report those back to you.

**Comment by AnonXS** [comment] 2018-12-03 20:20
![unbenannt](https://user-images.githubusercontent.com/19734826/49399222-02fefb80-f741-11e8-836e-fa9bd6aa7f55.PNG)

![unbenannt](https://user-images.githubusercontent.com/19734826/49399202-f1b5ef00-f740-11e8-90dd-e55fd9434284.PNG)

![unbenannt](https://user-images.githubusercontent.com/19734826/49399280-2c1f8c00-f741-11e8-832d-48ed9d5a541c.PNG)

Looks fine to me, as the spells are learned by spell = 5300.

**Comment by adellaci** [comment] 2018-12-03 20:51
It looks fine but if you do the quest line you do not receive spells 928 & 6991. I also went out and tamed an animal just to see if it is then that you get the spells, still no spells.

Just finished the Dwarf Hunter line, same result

**Comment by AnonXS** [comment] 2018-12-03 21:08
I guess it is "spell targeting" related, so the questgiver is just not able to successfully perform the spell that learns these spells on the player on successull quest turn in.

**Comment by killerwife** [comment] 2018-12-03 22:09
Quest ID? The final one that should give it, but doesn't give it.

**Comment by AnonXS** [comment] 2018-12-03 22:10
6102 and 6103 both grant spells due to questgiver casting a spell on player.

**Comment by adellaci** [comment] 2018-12-04 13:01
@killerwife , @AnonXS 

AnonXS, i should have payed more attention to what you was saying, I understand better now. Quest giver has to cast spell 5300 in order to give you spells 982 & 6991. I don't understand the relationships between the tables very much, but with each problem i am researching a learning.

So the real point. Spell 5300 has 0 in field 'Targets', and i believe it should be 256. If at the end of the quest line for all the races that can be hunters use the same spell then it should fix all of them. Agree?

**Comment by adellaci** [comment] 2018-12-04 13:02
I have tested it on Night Elf Hunter and it works for them

**Comment by adellaci** [comment] 2018-12-04 15:39
@killerwife 

Then changing field 'Tartgets' in spell_template(5300) to 256 will correct it for all races

**Comment by killerwife** [comment] 2018-12-04 16:03
I'm afraid thats not the correct solution here. Need to figure out why it works for them and not the other.

**Comment by adellaci** [comment] 2018-12-04 16:06
Okay I've made this change to the Database "UPDATE `spell_template` SET `Targets`=256 WHERE `Id`=5300 ". I'll go back and verify that is works for all races now.

**Comment by adellaci** [comment] 2018-12-04 17:50
I've tested the following and they now work.
Nigh Elf Hunter 
Dwarf Hunter
Draenei Hunter

Have to got test Horde side

**Comment by adellaci** [comment] 2018-12-04 18:55
@killerwife 

I've tested the following and now they work.
Orc Hunter
Tauren Hunter 
Troll Hunter
That should be all of them.

It appears that because the 'Targets' was set to 0 those spells were not being casted upon the player.
This should go to 'wotlk-db' and a check on Burning Crusades & Classic.

**Comment by Dramacydal** [comment] 2018-12-05 07:47
@adellaci changing spell template is hack. The core issues should be fixed.

**Comment by adellaci** [comment] 2018-12-05 13:06
@Dramacydal @killerwife @AnonXS 
If you look a the previous quest for all the races, the quest giver upon completion casts 1579 which gives you Tame Beast, Call Pet, & Dismiss Pet. that entry has 256 in the 'Targets' field. So if the change will need to be made on the other spell too. 

This example is from the Night Elf Hunter.
[hunter_quest_template.txt](https://github.com/cmangos/issues/files/2648888/hunter_quest_template.txt)
[hunter_spell_template.txt](https://github.com/cmangos/issues/files/2648892/hunter_spell_template.txt)

Guess have to research other quest that cast spells to give a play a spell(s).

**Comment by killerwife** [comment] 2018-12-05 13:08
@Dramacydal is right. This is meant to work without Targets field alteration. There are 48 spells like this in WOTLK, in TBC there are just 10, so I think blizzard did a change here in the background.

I am gonna look at how this works.

**Comment by adellaci** [comment] 2018-12-05 13:22
@killerwife 
That what is the intent on the 'Targets' field. The only information I find in the Database fields description is

> Targets

Determines the default targets for some effects. Seems to be connected to TARGET_NONE.<

**Comment by adellaci** [comment] 2018-12-05 13:35
Thank you for taking the time to explain

**Comment by killerwife** [comment] 2018-12-05 13:39
The bug is here:
`Unit* Spell::GetUnitTarget(SpellEffectIndex effIdx)
{
    Unit* target = m_targets.getUnitTarget();
    if (effIdx != EFFECT_INDEX_0 && !IsUnitTargetTarget(m_spellInfo->EffectImplicitTargetA[EFFECT_INDEX_0])) // eff index 0 always need to supply correct target or from client
        target = m_caster->GetTarget();

    return target;
}`

**Closed** 2018-12-05 13:46 UTC
Labels: Info: Needs Replication, System: Pet, System: Quests, Version: WotLK

**Comment by adellaci** [comment] 2018-12-05 14:30
@killerwife 
Updated and tested, works correctly now. Thank you.
