### ISSUE TITLE
[CLASSIC] Skinning Impossible When Rollable Item Drops

### ISSUE THREAD

**Issue by bdebaere** [cmangos/issues#1377] opened 2017-06-10 20:12 UTC
**Current behavior**: 
When in group and an item drops which you can roll on, the creature can no longer be skinned.
**Expected behavior**: 
The creature should be skinnable no matter what drops.
**Steps to reproduce**:

1. Make a group
2. Kill a beast or other skinnable creature
3. In case of green or higher item dropping, skinning is not possible

**Client version**: 
1.12.1
**Commit hash**: 

**Database version**: 
Classic DB version 1.8.5 "Below Blackrock Mountain". For core Classic z2697.
**Operating system**: 
Windows 10

[//]: # (If this is a crash report, include the crashlog from a debug build with https://gist.github.com/)

**Comment by Razfury** [comment] 2017-06-14 15:14
confirm!

**Comment by berserkingyadis** [comment] 2017-10-22 21:03
Cannot confirm this, neither on the current version of the core/db nor on the version on the day before this issue. I could skin the creature after rolling for the items they dropped.

1) current version of core/db:
core commit: https://github.com/cmangos/mangos-classic/commit/024e9e776b52643590de7cec1df991cc62ef90a9
db commit: https://github.com/cmangos/classic-db/commit/9f39d405984dac8850344488eccd9d1bac8e190e

2) version of core/db on the days before this issue:
core commit:  https://github.com/cmangos/mangos-classic/commit/584693333b65f6e8c4126df7e295f307a16c29d0
db commit: https://github.com/cmangos/classic-db/commit/edad17c927e6e19aa5d847e89ca0a4556cd20671

Looted these mobs: 
- http://db.vanillagaming.org/?npc=11982
- http://db.vanillagaming.org/?npc=4887

What I did:
````
=> create 2 chars and form a group
#learn skinning
.learn all_crafts
#skill skinning
.setskill 393 300
#give skinning knife
.additem 7005
#spawn mob
.npc add 4887
=> kill the mob with .die , roll the items and skin it
````

Seems to be working as intended, maybe somebody else should reproduce this behavoir.

**Comment by berserkingyadis** [comment] 2017-10-23 10:07
I tested this again with giving the items to the character that cannot skin and vice versa and tried all loot types (round robin, group loot, need before greed) and still could skin. 

@bdebaere How did you encounter this issue? I need more information to replicate this.

**Comment by bdebaere** [comment] 2017-10-23 11:38
@berserkingyadis I will update to the latest version soon and will update this ticket accordingly.

**Comment by jimmybrancaccio** [comment] 2018-11-17 22:30
Given the length of time between this and reports of it being non-reproducible I am closing this one out. Please don't hesitate to reopen a new issue with full details if you can replicate the issue. Thanks!

**Closed by jimmybrancaccio** 2018-11-17 22:30 UTC
Labels: Version-Classic
