### ISSUE TITLE
[Classic] The NPC Bowen Brisboise  Journeyman Tailor have no gossip option

### ISSUE THREAD

**Issue by Saugjunkie** [cmangos/issues#1569] opened 2018-02-24 22:10 UTC
**Current behavior**:  
I make a right click on the npc  the windows go open and the text is in english Train me  but i use a German 1.12.1 client and have alle entrys in the locales_gossip_menu_option translate and the text must be Ich benoetige eine Ausbildung.
I found the NPC
creature_template 
entry 3523 
Name Bowen Brisboise 
SubName Journeyman Tailor
**Expected behavior**: 
The cache is delected i have search the npc id in the database table gossip_menu_option i dont found him so i think he have not a database gossip option entry
**Steps to reproduce**:

1.  go outside from brill to the tailor trainer
2.  Make right click on the npc
3. look in the windows the text Train me 

**Client version**: 
German 1.12
**Commit hash**: 

**Database version**: 
the newest
**Operating system**: 
client Windows 8.1 server Debian 9.1

[//]: # (If this is a crash report, include the crashlog from a debug build with https://gist.github.com/)

**Comment by Saugjunkie** [comment] 2018-02-24 23:18
I have talk with AnonXS thank you for help and he have say me we can fix this and here i have the fix 
INSERT INTO `gossip_menu_option` (`menu_id`, `id`, `option_icon`, `option_text`, `option_id`, `npc_option_npcflag`, `action_menu_id`, `action_poi_id`, `action_script_id`, `box_coded`, `box_money`, `box_text`, `condition_id`) VALUES
(4267, 0, 3, 'Train me', 5, 16, 0, 0, 0, 0, 0, '', 0),

**Comment by cala** [comment] 2018-03-12 12:41
Hi. Before pulling this. Can you perform the following tests, please : 
- try with another journeyman taylor if the issue is the same (for example: Snang (with the command `.go creature id 2855`)
- try with a specific NPC : Eldrin <Journeyman Tailor> (with the command `.go creature id 1103`). You will need an Alliance character for that

Tell me what results you have, please. Thank you.

**Comment by cala** [comment] 2018-03-16 10:57
Poke @Saugjunkie

**Comment by cala** [comment] 2018-04-17 07:37
Last poke @Saugjunkie before closing this issue.

**Comment by cala** [comment] 2018-05-28 12:00
No feedback.

**Closed by cala** 2018-05-28 12:00 UTC

**Comment by Tobschinski** [comment] 2018-05-28 12:08
I can tell you a story if you want.
