### ISSUE TITLE
🐛 [Bug Report] [classic] There is no spell animation when casting a ballistic skill for the first time when a legal class enters a battle.

### ISSUE THREAD

**Issue by jilinge2** [cmangos/issues#2774] opened 2022-02-26 12:46 UTC
### Bug Details

There is no spell animation (ballistic skills, such as Frostbolt, Shadowbolt) when the legal profession enters the battle for the first time casting a skill.

### Steps to Reproduce

1.Create gnome mage/human warlock etc.
2.Cast ranged attack skills (Fireball/Shadow Arrow)
3.
4.

### Core SHA1 Commit Hash

02cddcc712816c85b3233ba8a6e392b32cede3fa

### Database SHA1 Commit Hash

d6c6d541efd8e0d63927eacc3bb0d0581820191b

### Operating System

ubuntu 20.04

### Client Version

1.1.12 (Classic)

**Comment by killerwife** [comment] 2022-02-26 13:12
I did the following:

Took a human warlock and undead mage to blasted lands.  
Attacked a redstone basilisk with fireball/shadowbolt.  
All worked as intended.

**Comment by cbcs** [comment] 2022-02-28 03:47
> I did the following:
> 
> Took a human warlock and undead mage to blasted lands. Attacked a redstone basilisk with fireball/shadowbolt. All worked as intended.

I think he made a mistake...It should be a guiding spell...such as Arcane Missiles  Spell ID is 25979..
Casting spells will have a significant delay and will be released after guidance..
sry my bad english .

**Comment by jilinge2** [comment] 2022-02-28 07:32
Thanks, I disabled all plugins and it worked fine. The first time I experimented on the mangos side, the plug-in can be used normally, so in cmangos I ignored the problem of the plug-in and forgot to disable the plug-in test.

**Closed** 2022-02-28 07:57 UTC
Labels: Info: Needs Replication
