### ISSUE TITLE
WotLK+Cata: Command: .gobj tar / .npc info crashing server

### ISSUE THREAD

**Issue by NightSharky** [cmangos/issues#617] opened 2015-02-23 22:37 UTC
When i use .gobj tar on any object which is in game_event_gameobject table. Server crashed.

The same also for .npc info if creature is in event.

**Comment by virusav** [comment] 2015-02-28 11:52
WOTLK, core - 12852, SD2 - 3114: none of the commands has not led to crash the server.

**Comment by VladimirMangos** [comment] 2015-03-01 10:37
In 99% cases command crash server in result wrong/outdated localization strings for specific command output. I suggest check its, or check crash case with english localization.

**Comment by NightSharky** [comment] 2015-03-03 06:40
WotLK: rev. 12846, UDB
Cata: rev. 13062, UDB
Localization strings are ok.

**Comment by evil-at-wow** [comment] 2015-03-04 22:38
I can confirm the crash with my TBC repository, even with the default English strings.

Are you running Linux too by any chance? If so, what compiler (and version) are you using?

**Comment by VladimirMangos** [comment] 2015-03-07 13:45
Hmm... this commands share code at call ChatHandler::ShowNpcOrGoSpawnInformation but i not see possible problem in it or related db strings.

**Comment by xfurry** [comment] 2015-07-27 19:13
@evil-at-wow Does this issue still happen? I can't reproduce it on master.

**Comment by evil-at-wow** [comment] 2015-07-27 19:49
Yes, this still happens, at least on my Linux system. I'll have to do some more serious debugging instead of a quick look, because the passed strings and format specifiers look just fine to me, yet one of those variable argument calls goes into 'bigga badaboom' mode for some reason...

**Comment by xfurry** [comment] 2015-07-27 20:01
Please give me some example on how to crash the server. That would make it easier for me to understand.

**Comment by evil-at-wow** [comment] 2015-07-27 20:25
As GM, just target any NPC that's associated with an event, and run ```.npc info``` on it.

If you want a sequence of commands, then run the following commands as GM after logging in:
```
.event start 1
.go creature id 16781
/tar Midsummer
.npc info
```
After the last, command, my server goes :boom:

**Comment by korhaldragonir** [comment] 2015-08-20 07:48
Tested the above commands on my server. But it does not crash. I am running:

WoTLK
cMaNGOS r12906 with ScriptDev2 r3154 and UDB 408 Pre-Release with the latest version of ACID-WoTLK 
on Ubuntu 14.04.3 LTS x64 compiled with GCC 4.8.4

When I executed the .npc info my server just showed me the information, but nothing else happened.

**Comment by NightSharky** [comment] 2015-11-23 13:31
I have tested a little bit. And if i cmake source with -DDEBUG=0, it will crash on commands (.gobject target, .npc info). But if i use -DDEBUG=1, its ok and working fine.

**Comment by cyberium** [comment] 2017-09-08 13:02
Iam not able to replicate it nor seeing what could cause this.
Iam closing this but feel free to provide more replication way if any and we'll reopen it.

**Closed by cyberium** 2017-09-08 13:02 UTC
Labels: Version-WotLK

**Comment by Warlockbugs** [comment] 2017-09-08 13:04
The vararg types issue i fixed in all pre-cata cores a few months ago. Should be closed.
