### ISSUE TITLE
[CLASSIC] PlayerBot Group AI Issues

### ISSUE THREAD

**Issue by Trystanosaurus** [cmangos/issues#1648] opened 2018-07-11 06:28 UTC
**Current behavior**: 
I've had a few issues with the playerbots attempting a dungeon. I've included them all in this issue, let me know if you'd prefer separate issues for each. All of these were with a Warrior (protection tank), Priest (holy healer), Mage (frost dps), Rogue (combat dps), Druid (balance dps) alliance group at level 13 attempting ragefire chasm.

- Bots seem to attack neutralized enemies. I saw there was an IsNeutralized function (line 5160 PlayerBotAI.cpp) but it's only used when checking if the bot currently has aggro from a non-neutralized target, it doesn't seem to be used to check a target is okay to attack. The result was my mage spent half his time sheeping a target the tank was beating on.

- After using the pull command melee DPS don't seem to want to leave follow range of their master. Test this by first asking the group to attack a target while playing a ranged character (all will run in), then try pull, the tank will run in but the melee will only attack if you also run into melee range.

- Sometimes when zoning into the instance the bots wouldn't zone in correctly. I found the best way to get them all in was to remove them when outside, zone in and then add them fresh. This is less important but can be a bit of a pain.

- This is more of a suggestion rather than an issue but the bots take 2 seconds standing at the corpses of each enemy they can't loot (the ones they can loot they grab the loot instantly and move on), if you've killed a lot of enemies it does cause a bit of slowdown while they run to each corpse and wait for 2 seconds.

**Expected behavior**: 
Bots leave neutralized enemies alone. Melee bots always close to melee range to fight. Bots zone with masters and ideally they could loot a bit faster.

**Steps to reproduce**:

1. Form a group of bots
2. Try entering and exiting any instance a few times
3. Try asking a character to neutralize a target and see if the group avoids attacking it
4. Command the group to attack a target, then on the next enemy try asking them to pull it, melee DPS won't move.

**Client version**: 1.12.1 (5875)

**Commit hash**: 16a2393

**Database version**: 1.9 -  b5e2f39

**Operating system**: Windows 10

**Comment by cala** [comment] 2018-11-15 09:55
Hi,

Thanks for your comments. Here are quick answers/explanations.

> Bots seem to attack neutralized enemies

They do. As you noted, I added support functions for the purpose you describe. However, the target picking system in playerbot is not as good as it could be and currently a bot picking a neutralized enemy as a target will stick to that target and not attack it until the target is no longer neutralized. Hence, I did not yet deploy the `IsNeutralized()` function on AIs.
I intend to rework the target selection system in playerbot at some point but not in a near future. A workaround is to have a macro broadcasting to party/raid channel the command `attack` so that bots will pick and attack your current target instead.

> After using the pull command melee DPS don't seem to want to leave follow range of their master

This is the same underlying issue than above: target selection by bots. If I remember correctly, asking your tank to cast his/her shoot spell instead of using the pull command should result in the correct behaviour.

> Sometimes when zoning into the instance the bots wouldn't zone in correctly.

This issue is known. I never found out the cause of it (never truly looked at it anyway). An easy way to work around this is to have a macro that remove/readd bots after you zoned in.

> This is more of a suggestion rather than an issue but the bots take 2 seconds standing at the corpses of each enemy they can't loot

IIRC, it's because OOC AI for bots is on a 2 secs timer. There are various ways you can change this: via PlayerBot config file, via bot loot orders in-game, via group loot rules... When reworking the target selection system for PlayerBot, I also intend to ensure bots loot they various targets in the same order to reduce the time they take to do it. But I won't probably work on that in a near future.

**Comment by jimmybrancaccio** [comment] 2018-11-24 19:17
@cala Would you like to leave this issue open as a reminder of work that needs to be done?

**Comment by cala** [comment] 2018-11-24 19:55
Yes, for now. I shall reformulate it into something better development-wise later if need be.

**Comment by jimmybrancaccio** [comment] 2018-11-24 23:42
Sounds good, thank you for the update @cala.

**Comment by cala** [comment] 2019-03-15 22:08
The zone in should be improved by https://github.com/cmangos/mangos-classic/commit/fcb206fb5aabb14cd0233fcefbf990d5692aa492
However, it is not as good as WotLK branch because SMSG_TRANSFER_PENDING seems to not be broadcast 100% of the time to bots like it should. This needs to be investigated, but the actual teleport of bots is still improved in Classic nonetheless.

**Comment by cala** [comment] 2019-03-25 22:36
Point 2 (melee bots staying near master when using pull command) should be fixed by https://github.com/cmangos/mangos-classic/commit/e0781f571c61f6480c67bd758b579b6ba4ea1dc2
A tricky one…

Point 4 (bots staying 2 sec on corpse) should be improved by all the recent commits preventing unnecessary looting. Bots will still stay 2 seconds near the corpse when they do need to loot, but going below this timer would be tricky as it would allow bots to have their AI updated faster than the Global Cooldown (1.5 sec) and there is no safeguard about this in PlayerBot. That could result in unexpected behaviour.

Point 1 is still a work in progress, though I have now a better understanding of the way targets are picked in PlayerBot

**Comment by cala** [comment] 2019-03-28 22:59
And... point 1 is fixed here: https://github.com/cmangos/mangos-classic/commit/c1b751d87364d753f096e792bb623347f02177fc
I'm thus closing the issue.

**Closed by cala** 2019-03-28 22:59 UTC
Labels: System: PlayerBot, Version: Classic, Version: TBC, Version: WotLK
