### ISSUE TITLE
[CLASSIC] Hunter Aimed Shot Has No Casting Bar

### ISSUE THREAD

**Issue by MarcoPolo87** [cmangos/issues#691] opened 2015-05-23 21:56 UTC
When using the Hunter ability "Aimed Shot," the Cast Bar does not appear while the ability/spell is "casting."  After checking old youtube videos, Aimed shot did display a cast bar in Vanilla prior to the release of TBC.  I can not confirm if the "Cast Bar" was visible in every patch from Launch.

I am not sure if this would be labeled as a "content error" (classic DB) or a "server error" (mangos core DB). 

Classic DB version 1.5.0 'The Great Swimming Pool'. For core z2656 and SD2 z2734
ACID 1.12.x (Classic) for CMaNGOS-CLASSIC (1.12.X Client)
required_z2621_s2263_12823_04_mangos_creature

**Comment by Phatcat** [comment] 2019-02-08 02:48
Videos from vanilla; 
https://youtu.be/22yjJP3jR78?t=113
https://youtu.be/PdXahbbVoUk?t=150

It is the other way around, aimed shot was added a casting bar after vanilla (during tbc)
https://www.youtube.com/watch?v=N5CX4hS5zmQ

And this works as intended on the tbc core, there is a bar as you'd expect.
![image](https://user-images.githubusercontent.com/1907820/52455964-0ce31780-2b53-11e9-8a9f-eb2f5fa51f66.png)

Everything is working as intended, this issue can be closed as it's a misreport.

**Closed** 2019-02-08 15:03 UTC
Labels: Info: Needs Replication, System: Spells, Version: Classic
