### ISSUE TITLE
🐛 [Bug Report] Core is still casting spells from creature_template_spells when it shouldn't

### ISSUE THREAD

**Issue by wdstudios2** [cmangos/issues#3417] opened 2023-05-21 12:47 UTC
### Bug Details

Vampiric Duskbats in Tirisfal Glades are still spamming Ravage every 2 seconds. This is a sign that the core is still allowing enemy mobs to cast spells from their creature_template_spells list even when they aren't mind-controlled. Sorry, AnonXS, but it looks like your recent AI tweaks were just a band-aid over a bullet wound.

Also, as I've pointed out before, _**Vampiric**_ Duskbats aren't even supposed to have Ravage in the first place. In TBC, the _**Greater**_ Duskbats have Ravage and the _**Vampirics**_ are supposed to have Screech.

### Steps to Reproduce

1. Find vampiric duskbat
2. get knocked down
3. get up again
4. drink a whiskey drink
5. drink a vodka drink
6. drink a lager drnk
7. drink a cider drink
8. sing the songs that remind you of the good times
9. sing the songs that remind you of the best times

### Suggested Workaround

Delete every hostile mob from creature_template_spells, or at least replace their spell ids with 0.

### Core SHA1 Commit Hash

73dd1ae

### Database SHA1 Commit Hash

6cb4346

### Operating System

Win7

### Client Version

2.4.3 (The Burning Crusade)

**Comment by insunaa** [comment] 2023-05-21 13:02
The reason why creature_template_spells are cast is because they're used as a cheap substitute for spell_lists ever since spell_lists were introduced, but they lack the fidelity that spell_lists have with timing, etc. so they can just be executed whenever, however.
The important issue here isn't that mobs cast things from the creature_template_spells table, but that the table contains incorrect data. Eventually things will be moved to spell_lists and the creature_template_spells will be deleted entirely

**Comment by insunaa** [comment] 2023-05-21 15:30
Vampiric Duskbats however are working as intended, as they are correctly implemented with creature_ai_scripts. Closed as not a bug.

**Comment by miraco** [comment] 2023-05-23 15:26
![WowClassicT_65Qb6FM2Dd](https://github.com/cmangos/issues/assets/6261245/0624e8d1-fda5-42d1-8556-dc96fc1fc2bd)

Im sorry but you are wrong, this creatures indeed only use Ravage as main spell, tested on wotlk classic ptr.
And this is whats also happening on newest cmangos-tbc

**Comment by killerwife** [comment] 2023-05-23 19:25
creature_template_spells is entirely superceded by creature_spell_list, and unless creature_template.SpellList is set to correct id, there is no way creature_template_spells is used other than during mind control/charm. If its a problem during mind control/charm, it has to be migrated to creature_spell_list, because thats what this tech was supposed to fix implicitly in the first place

**Comment by wdstudios2** [comment] 2023-06-01 23:56
Deleting abilities from creature_template_spells affects creature behavior regardless of whether those creatures are mind-controlled or not.

Sent with [Proton Mail](https://proton.me/) secure email.

------- Original Message -------

**Closed as completed** 2023-06-10 00:45 UTC
Labels: Info: Needs Replication

**Comment by AnonXS** [comment] 2023-06-10 00:47
Every Issue regarding "unusual npc ability usage" is welcome!

At this point, every npc type should be througly rechecked to confirm/improve their timers.
