### ISSUE TITLE
🐛 [Bug Report] Resources Herbs/Mines containing nothing

### ISSUE THREAD

**Issue by Yatzii93** [cmangos/issues#2086] opened 2020-01-13 11:12 UTC
## 🐛 Bugreport

It seems atm something is causing resoure nodes to on occasion have nothing in them. 
![image](https://user-images.githubusercontent.com/47720837/72253523-a46da780-35f9-11ea-9c33-8e607eeb3b49.png)
![image](https://user-images.githubusercontent.com/47720837/72254306-83a65180-35fb-11ea-85cb-d782ff216b5b.png)

Clicking off a dud mine and then clicking it again prompts the in use error
![image](https://user-images.githubusercontent.com/47720837/72254363-bb14fe00-35fb-11ea-8cba-6416b8cc859b.png)

### Expected behavior

If they are spawned in and ready to be gathered, they should contain the goods.
### Version & Environment

Client Version: 
2.3.4

CMaNGOS Repo & Commit Hash: 
https://github.com/cmangos/mangos-tbc/commit/650e49b91a3428e3923ce034e49900900e6dbc1f

Database Repo & Commit Hash: 
https://github.com/cmangos/tbc-db/commit/78435bb4ebd70902a0fa74c0a4724036eec97f9b

Operating System: 
Win
### Steps to reproduce
1. Not quite sure yet how to reproduce. I guess if I knew I'd have a means to fix it.
(I have a inclination it's if they populate back in to quickly)

### Crashlog

- None

**Comment by Yatzii93** [comment] 2020-01-13 11:18
One thing I guess to note is I did up the amount of nodes each outland zone has at any time by around double. Not sure as of yet whether that would make a difference concerning this issue.

**Comment by Yatzii93** [comment] 2020-01-13 22:10
OK update. I made sure I was fully up to date with the recent object updates and I can't seem to replicate. Will pull to live and see if it disappears for good. Could be a false alarm, just another one of those teething issues during the commit nukes.

**Comment by Yatzii93** [comment] 2020-01-13 22:24
![image](https://user-images.githubusercontent.com/47720837/72297238-64d3a980-3653-11ea-80a0-b8ed222f6fc4.png)
and that didn't last long. Still happening.

**Comment by Yatzii93** [comment] 2020-01-13 22:27
Also now it seems a new issues has been introduced. 
![image](https://user-images.githubusercontent.com/47720837/72297430-d0b61200-3653-11ea-8d89-edfdedd8b706.png)
this node doesnt seem to want to despawn so you can just spam gather until forever.

**Comment by Yatzii93** [comment] 2020-01-14 05:43
Ok I've isolated where it fails to here.

https://github.com/cmangos/mangos-tbc/blob/master/src/game/Loot/LootMgr.cpp#L1715

**Comment by Yatzii93** [comment] 2020-01-14 07:52
Seems to be gameObject->GetOwnerGuid() != player->GetObjectGuid()).

Removing it doesnt seem to have any impact as far as I can see. Oddly setting the object owner on use to the player produces no loot. Can't wrap my head around why it's failing and whys it's needed.

**Comment by Yatzii93** [comment] 2020-01-14 21:33
Ok I've changed my mind, it's to with the distance calculation. 

> &&!gameObject->IsWithinDistInMap(player, INTERACTION_DISTANCE)
> 
> #define INTERACTION_DISTANCE        5.0f
> 

The distance check for on use is 

> 
> if (sGameObjectDisplayInfoStore.LookupEntry(GetGOInfo()->displayId))
>             return IsAtInteractDistance(player->GetPosition(), maxrange);

maxrange can come out as high as 8 yards concerning the allowed client side interact on resource nodes.

One way I'm confirming to resolve it is to change maxrange to GetInteractionDistance() and then add

> float GameObject::GetInteractionDistance() const
> {
>     switch (GetGoType())
>     {
>     case GAMEOBJECT_TYPE_AREADAMAGE:
>         return 0.0f;
>     **case GAMEOBJECT_TYPE_CHEST:
>         return 5.0f;**

**Comment by Yatzii93** [comment] 2020-01-15 03:12
This looks to be apart of a wider issue when it comes to how spell effect distance and range is calculated. It always seem to be off my a small margin which interm will break things that check hard values, such as the interaction_distance.

**Comment by Lymphome** [comment] 2020-07-12 16:55
This seems to be a problem related to pool management/map display/respawn delay

A way to reproduce it : (just after a server start)
1) find a cavern with few gobs in the same pool (mineral gobs, this is a cavern)
2) empty some nodes and keep attention to new spawning nodes
3) at a node spawn, go to this node immediatly, try to farm it and see the empty loot box
4) retry to farm it and see "already beeing used"
also :
3) at node spawn, go to this node, wait more than 90s, the loot box will not be empty
4) you can farm it until it despawns

These nodes have a m_respawnDelay > 0 but spawn immediatly, they should be displayed only when m_respawnDelay reaches 0. With m_respawnDelay != 0, IsSpawned() (in GameObject.h) returns false and Loot::Loot() can't build the loot.

I'm stuck at this point of investigation.

**Comment by Lymphome** [comment] 2020-07-14 07:18
A crappy fix until someone has a better solution :

1) At https://github.com/cmangos/mangos-tbc/blob/master/src/game/Pools/PoolManager.cpp#L500
Replace by "pGameobject->SetRespawnTime(1);" (1 or 2 or 3... but _NOT_ 0)
(ugly, yes, but it avoids the lock of the spot, it would be better to have this spot respawning according to its m_respawnTime)

2) yatzii comment is true but 5.0f in distance is not enought, I saw some mine gobs as far as 8.6f. The client decides if you can farm or not. So put a bigger value (9.0 9.5 10.0...).

Cheers

**Comment by Lymphome** [comment] 2020-11-15 19:11
It seems the problem is fixed.

**Comment by killerwife** [comment] 2020-11-15 19:12
Closing issue then.

**Closed by killerwife** 2020-11-15 19:12 UTC
Labels: Info: Needs Replication, System: GameObject, System: Loot, Version: TBC
