### ISSUE TITLE
[Classic] Error report Get into Blackwing Lair Crash

### ISSUE THREAD

**Issue by 127y** [cmangos/issues#1613] opened 2018-05-19 06:47 UTC
When open .gm on enters Blackwing Lair Crash

The team captain enters also Crash Only players first enter will not Crash

**Comment by cala** [comment] 2018-05-21 08:40
There is no need to open twice the same issue a few days apart as there is already one [here](https://github.com/cmangos/issues/issues/1604) opened by yourself...
If you want it to be dealt with you should follow the advice that was already given to you: do a proper report by following our template and guidelines: https://github.com/cmangos/mangos-wotlk/blob/master/CONTRIBUTING.md#bug-reports

I'm not able to reproduce this issue so without further details, it will be closed.

**Comment by 127y** [comment] 2018-05-25 10:17
@cala 

Current behavior:Get into Blackwing Lair Crash
![tim 20180525174012](https://user-images.githubusercontent.com/36727009/40539455-6470fe36-6047-11e8-9bf9-6cc87c94f4cc.png)

Expected behavior:no Crash

Steps to reproduce:The .Gm on mode enters Blackwing Lair Crash

Client version:[Classic]1.12.1-1.12.3

Commit hash:

Database version: "required_z2716_01_realmd_totp"
Database version: "required_z2719_01_characters_taxi_system_update"
Database version: "required_z2719_01_mangos_taxi_system_update"

Operating system:win2008/win2012/win10

My English is not good and I don't know how to explain it wrong. Please excuse me

**Comment by cala** [comment] 2018-05-29 09:36
Closed by https://github.com/cmangos/mangos-classic/commit/4f8c28d734e97aa866815801b001d346cf797e14
Thanks @Tobschinski

**Closed by cala** 2018-05-29 09:36 UTC
