### ISSUE TITLE
🐛 [Bug Report] NPC in RP-Transition should not give quests

### ISSUE THREAD

**Issue by ulfgebhardt** [cmangos/issues#2332] opened 2020-12-06 22:39 UTC
## 🐛 Bugreport

An NPC enacting some RP-Lines should not give you quests during this RP.

As Example: `Denalan's Earth`. Completing this quest will make the NPC walk over to the flower pot and have some RP lines till he returns  to his post. On Retail-Classic during this transition you cannot take or turn in quests (this ensures everyone has his/her own RP-transition).
In the attached screenshot you can see that between the two RP lines quests have been accepted.

![image](https://user-images.githubusercontent.com/1238238/101294968-e65b9980-381a-11eb-98c1-dacd863b21a6.png)

### Expected behavior

On retail within the transition its not possible to interact with the NPC till its finished. I cannot tell if this behaviour can be generalized or is quest specific

### Version & Environment

Client Version: "2.4.3" (TBC)

CMaNGOS Repo & Commit Hash: [TBC](https://github.com/cmangos/mangos-tbc/tree/daf52413)

Database Repo & Commit Hash: [TBC](https://github.com/cmangos/tbc-db/tree/96d6b19b)

Operating System: Linux Debian

**Comment by killerwife** [comment] 2020-12-06 22:51
Needs to remove questgiver flag for the duration of the script. Note to anyone who wishes to fix it.

**Comment by miraco** [comment] 2020-12-06 23:34
Does this quest have the RP event? Or is all of it missing?

There are rly much quests with RP and questgiver flag remove, this needs to be done and researched for every quest.

**Comment by Grz3s** [comment] 2020-12-06 23:36
https://www.youtube.com/watch?v=4yAs6pZJ77E
just look on final moment...
i would be cautious with that new classic

**Comment by ulfgebhardt** [comment] 2020-12-06 23:41
@Grz3s This footage shows the problem as described - I do not understand what you refer to when you say
```just look on final moment...
i would be cautious with that new classic```

@killerwife Thanks <3

@miraco THe idea of this issue is to investigate if we can find a general solution for every RP-Quests or if that's not applicable.

**Comment by miraco** [comment] 2020-12-06 23:44
I dont think there will be a general solution for this, cause not all RP-Quests gets this flag removed.
Im pretty sure there are some quests with rp event that not remove questgiver flag.

`INSERT INTO `dbscripts_on_quest_end` (`id`, `priority`, `command`, `datalong`, `datalong2`, `datalong3`, `comments`) VALUES ('997', '0', '29', '2', '2', '0', 'Remove questgiver npc flag');
('997', '0', '29', '2', '1', '0', 'Remove questgiver npc flag');`
I think this would fix it for this quest.

**Comment by ulfgebhardt** [comment] 2020-12-06 23:58
Where is that footage from?

**Comment by miraco** [comment] 2020-12-07 00:01
Current classic i guess. Not sure they changed it

**Comment by Grz3s** [comment] 2020-12-07 00:18
@ulfgebhardt i removed that comment... so u refering to smth that doesnt exist
@miraco `I dont think there will be a general solution for this, cause not all RP-Quests gets this flag removed.
Im pretty sure there are some quests with rp event that not remove questgiver flag.` - Yes this is correct

Npc hasnt got NPCFlag = 1 (gossip : he only has `questgiver_greeting`) ... so removing npcflag =2 ... will block access to other quests until flag is readded. -- which is not correct (you could see that on avi i removed..koz wanted to explain it better)

**Comment by jimmybrancaccio** [comment] 2020-12-07 00:38
@ulfgebhardt Please provide _all_ of the information requested by the bug reporting template.

**Comment by evil-at-wow** [comment] 2020-12-07 17:41
And what do you think is missing, @jimmybrancaccio? He explains the issue, what he was expecting, and his environment (core and database and their commits + the system he's on). What more is the bug reporting template asking for?

**Comment by jimmybrancaccio** [comment] 2020-12-07 17:44
@evil-at-wow Please refer to the bug submission template for full details. Thanks!

**Comment by miraco** [comment] 2020-12-07 17:49
> @evil-at-wow Please refer to the bug submission template for full details. Thanks!

The things that are "missing" are not needed here imo.. 
did you even read the bug report?

**Comment by jimmybrancaccio** [comment] 2020-12-07 17:51
@miraco Sure they are. I'll just go ahead and just close this out for it not having all information as required in the bug report. Thanks!

**Comment by AnonXS** [comment] 2020-12-07 17:51
wth

**Comment by evil-at-wow** [comment] 2020-12-07 18:38
Well, obviously I did check the bug template before asking, and I do not see what's missing here? But Ok, let's go over the bug template in detail then.

> Describe your issue in detail. Include screenshots if needed. Give us as much information as possible.

Looks OK to me.

> Expected behavior. How should it work + proof.

That's present.

> Version & Environment
> Client Version - is required
> Database Version - is required

Client Version is listed, commit hash as well.
Database is lised, commit hash as well.

> Operating System - optional

Although optional, it is listed.

> Steps to reproduce

Oh, that is missing, but that is pretty pointless here. He gave an example of a quest, and any developer with more than two brain cells knows how to find that and check that quest ingame, with the core and database he has because he listed them and their commits.

> Crashlog

Not a crash, so not relevant.

So I'll ask again @jimmybrancaccio, what more do you we need? Because I sure am not seeing it. But then again I'm just a developer here...

**Comment by jimmybrancaccio** [comment] 2020-12-07 18:46
> Oh, that is missing, but that is pretty pointless here. He gave an example of a quest, and any developer with more than two brain cells knows how to find that and check that quest ingame, with the core and database he has because he listed them and their commits.

I appreciate your feedback. I'd still like that this be filled out regardless. Thanks.

**Comment by Muehe** [comment] 2020-12-07 19:01
The steps to reproduce are indeed in the issue description and pretty trivial.

1. Hand in `Denalan's Earth` quest
2. Accept another quest while he is still doing the post-quest script

@jimmybrancaccio Don't want to step on your toes here, since you are the only one triaging issues, but when there are already two core maintainers (KW and Grz3s) in the issue discussing possible solutions more info isn't really needed (or they would have asked for it).

**Comment by jimmybrancaccio** [comment] 2020-12-07 21:31
If we don't want to follow or use the bug reporting template anymore please let me know. It was created and designed the way it was for a reason. There's no let's use it on some issues and not others. This is irregardless of there being core devs in the issue. Anyone new or old to this project should be able to see easily each section/block of the report which is done when the template is used properly. Again if we do not wish to utilize the templates we spent time putting together please let me know. Other please follow the templates and fill out the information requested in them.

At this point this issue still needs to be updated. For further discussion I would recommend we move to [GitHub Team Discussions](https://github.com/orgs/cmangos/teams/moderators). Thank you.

**Comment by Grz3s** [comment] 2020-12-07 22:35
Regarding your main question `An NPC enacting some RP-Lines should not give you quests during this RP.`  Theres no 1 rule for all quests ... it alll depends what happens after... sometimes script req. to gossip be removed .. so it wont interupt with it... 

Regarding this small quest: ... ive updated it .. and now its how it should be... (fact that `list` is shown even if quest flag is removed .. its a compl. diff matter (not related to this issue).. and we need to do more research on it.)

And finall thing... We are here to help each other... PLS remember that.

**Closed by Grz3s** 2020-12-07 22:35 UTC
Labels: Info: Incomplete Information, Info: Needs Replication, System: NPC, System: Quests, Version: TBC

**Comment by ulfgebhardt** [comment] 2020-12-07 23:16
@Grz3s Thank you very much for fixing this <3

@jimmybrancaccio I find this discussion a bit pointless - I was the one designing the bugreport template - tho I knew I did not provide proper steps to reproduce the bug I was sure it was easily enough possible to reproduce. Making a GM and finding the proper steps to make a reproduce this just didn't fit my workflow. Your the one maintaining the repository's issues and I understand your point of view - but beeing to literal on it makes no sense in my opinion:
Reference: https://github.com/cmangos/issues/pull/1948
