### ISSUE TITLE
Classic: Cleanse Delay: Paladin (Critical)*

### ISSUE THREAD

**Issue by Kelzior** [cmangos/issues#568] opened 2015-01-26 01:37 UTC
Core: Lastest
Bugged Paladin Spell: Cleanse 
(http://db.valkyrie-wow.org/?spell=4987)

This is essentially game breaking at the moment, making any paladin immune to any number of crowd control abilities. If you cleanse as soon as a polymorph is cast upon you, the dispell will take place and thus cancels the effect. This can be applied to any other magic abilities such as Fear.

Regards
Kelzior

**Comment by Dramacydal** [comment] 2015-01-26 15:25
Isn't that related to crappy emus with CC delays ?

**Comment by cyberium** [comment] 2015-01-27 16:40
@Dramacydal what you mean?

**Comment by Dramacydal** [comment] 2015-01-29 12:47
@cyberium some forks delay DoSpellHitOnUnit to achieve "blizzlike" effect. You know on retail two rogues can sap each other simultaneously, blind, etc. Due to crappy implementation there are problems like @Kelzior described.

**Comment by cyberium** [comment] 2015-01-29 13:08
Thank @Dramacydal, i cannot reproduce it on Wotlk. Will try later on classic.
@Kelzior please confirm you run a clean cmangos core.

**Comment by Tobschinski** [comment] 2015-01-29 15:58
http://web.archive.org/web/20140621023544/http://us.battle.net/wow/en/forum/topic/13087818929?page=6#114

**Comment by Kelzior** [comment] 2015-01-29 16:44
I dont understand why I have to confirm that im running a clean cmangos core and the others don't? 
NVM .. Here you go... 
![28tuseb](https://cloud.githubusercontent.com/assets/9686159/5961628/65bfbacc-a7de-11e4-90eb-a3fceb7307f0.jpg)

**Comment by cyberium** [comment] 2015-02-03 09:49
> I don't understand why I have to confirm and the others don't?
Because
1 - i cannot reproduce it in wotlk nor in classic.
2 - @Dramacydal have encoutered that kind of situation in other core.
3 - because here we try only to improve cmangos code due to lack of time to handle all other cores issues.
4 - all members involved here are supposed to use clean cmangos core before posting any issue.

Thank you for your little screenshot btw.

Can any other classic users can confirm/infirm this? I cannot reproduce it.

**Comment by cyberium** [comment] 2015-02-03 11:23
Ok after other one confirmed me we can't reproduce this issue we can close it.

**Closed by cyberium** 2015-02-03 11:23 UTC
Labels: System-Spells
