### ISSUE TITLE
Eye of Kilrogg

### ISSUE THREAD

**Issue by tallaxx** [cmangos/issues#2032] opened 2019-08-22 09:12 UTC
## 🐛 Bugreport

First I would like to thank the developers very very much for this beautiful piece of software. It works like a charm, even though I have a bug report.

1. The Eye of Kilrogg is spawned at a different location than the caster his position.
2. The Eye of Kilrogg has some huge health regeneration, which makes it impossible to kill.

*I already started looking into the source code to fix this and would like to contribute, please help me* :)

### Expected behavior

1. The Eye of Kilrogg should spawn at the exact position of the caster.
2. The Eye of Kilrogg should have no health generation.

### Version & Environment
Client Version: "1.12.1" (CLASSIC)
Commit Hash: [CLASSIC](https://github.com/cmangos/mangos-classic/tree/8958049f54d4fa1158a6ce8670b61ea1604d8956)
CMaNGOS Repo & Commit Hash: [CLASSIC](https://github.com/cmangos/classic-db/tree/ee9c247bdc1be2767fcd54da90562fea2d9f73d1)
Operating System:  Linux 
### Steps to reproduce
1. Get a Warlock at level 22.
2. Learn the spell "Eye of Kilrogg"
3. Cast the spell "Eye of Kilrogg"
4. See how the summoned pet is below the map.

**Comment by killerwife** [comment] 2019-08-22 09:19
The issue is TARGET_LOCATION_UNIT_MINION_POSITION which seems to somehow bypass requirements for radius. only 10-20% of spells have radius, and this seems to imply that radius should be ignored for this particular target type. Eye of Kilgrogg has 100, which should DEFINITELY be ingored. It's possibly a setting like "don't go further than 100 yards" instead. I will tweak this myself.

I do not know about the health regen, but it can be set for the entry in DB, try tweaking RegenerateStats in creature_template and let us know how that worked.

**Comment by tallaxx** [comment] 2019-08-22 11:08
Thank you for the quick reply. I have start with fixing the health regen as this seems like a more simple thing to fix.

The original `RegenerateStats` value was 3, I have decreased it to 1.Additionally, I have increased the SpeedRun to 2.  After a server restart, the Eye correctly moves more quickly at a speed of 2. However, the health is still regenerated instantly. 

I actually notice the health is add with a _green_ color. Is it healed or something?

**Comment by evil-at-wow** [comment] 2019-08-22 18:53
> It's possibly a setting like "don't go further than 100 yards" instead.

I doubt that's true. I can't comment about the behavior in vanilla times, but at least in TBC times you could fly your Eye of Kilrogg as far as the duration allowed you. I remember casting it once in BRD standing roughly where you enter East Garrison after doing the arena, and I could go as far as Lokhtos Darkbargainer in the bar (that's the furthest I could get considering the timer). I haven't verified ingame, but I'm sure that's a lot more than 100 yards (that's 2.5 times 40 yards, so 2.5 times the range of my spells nowadays).

**Comment by killerwife** [comment] 2019-08-22 18:55
Okay, then this is a good example of bad data in the DBC.

**Comment by al3xc1985** [comment] 2020-03-05 04:52
First part of bug report fixed last night live by @killerwife

**Comment by cala** [comment] 2021-06-04 21:17
Final part fixed by https://github.com/cmangos/classic-db/commit/86934395aa6813716a905dba36cd6a70c54af7f1

**Closed by cala** 2021-06-04 21:17 UTC
Labels: Info: Needs Development, Info: Replicated, System: Spells, Version: Classic
